### ISSUE TITLE
next-urql not respecting `url` config in exported build

### ISSUE THREAD

**Issue by lukasluecke** [FormidableLabs/urql#1002]
urql version & exchanges:
- urql 1.10.1
- next-urql 1.1.0
- @urql/exchange-graphcache 3.1.1
- @urql/exchange-multipart-fetch 0.1.9
- @url/devtools 2.0.2

**Steps to reproduce**
1. Specify a url in the call to `withUrqlClient` (e.g. `/api/graphql`)
2. `next build`
3. Either `next start` or `next export && npx serve -s out`

**Expected behavior**
- urql should use the specified `url` (`/api/graphql`)

**Actual behavior**
- urql just uses `/graphql`

<img width="422" alt="CleanShot 2020-09-25 at 11 32 43@2x" src="https://user-images.githubusercontent.com/6652670/94251480-dffb9800-ff22-11ea-9534-40b7bd8f2022.png">
<img width="667" alt="CleanShot 2020-09-25 at 11 38 28@2x" src="https://user-images.githubusercontent.com/6652670/94252036-ac6d3d80-ff23-11ea-8107-8b62b4c1d5b9.png">
<img width="1576" alt="CleanShot 2020-09-25 at 11 32 03@2x" src="https://user-images.githubusercontent.com/6652670/94251493-e4c04c00-ff22-11ea-8702-f7d394db71be.png">

**Comment by lukasluecke** [comment]
I have wrapped the whole App component in `withUrqlClient`. It also works just fine in development mode (`next dev`).

**Comment by lukasluecke** [comment]
I have the feeling that the whole config is disregarded - I tried fixing the issue with the URL using a server-side proxy / rewrite, but then noticed that my custom auth exchange (JWT refresh token) is not called at all..

**Comment by kitten** [comment]
This sounds like somehow in your setup the provider isn't being used; although we're also missing information whether this is on the server-side, client-side, or both 😅

**Comment by lukasluecke** [comment]
Seems like it's an issue with the NextJS build process, it seems to be pre-generating the context here with the default values, instead of what I provide to the `withUrqlClient` function. I will have to investigate it further later 🙈 

```
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[   =] info  - Generating static pages (0/7)[Function]
[  ==] info  - Generating static pages (0/7){
  key: 4173135880,
  query: {
    kind: 'Document',
    definitions: [ [Object] ],
    loc: { start: 0, end: 144 },
    __key: 4173135880
  },
  variables: {},
  operationName: 'query',
  context: {
    url: '/graphql',
    fetchOptions: undefined,
    fetch: undefined,
    preferGetMethod: false,
    requestPolicy: 'cache-first',
    pollInterval: undefined,
    meta: { cacheOutcome: 'miss' }
  }
}
```

**Comment by lukasluecke** [comment]
I passed `{ssr: true}` as the `withUrqlClient` options, which then disabled the static page generation, but I still get the same behaviour at runtime:

```
❯ yarn next start
yarn run v1.22.4
$ next start
ready - started server on http://localhost:3000
[Function]
{
  key: 4173135880,
  query: {
    kind: 'Document',
    definitions: [ [Object] ],
    loc: { start: 0, end: 144 },
    __key: 4173135880
  },
  variables: {},
  operationName: 'query',
  context: {
    url: '/graphql',
    fetchOptions: undefined,
    fetch: undefined,
    preferGetMethod: false,
    requestPolicy: 'cache-first',
    pollInterval: undefined,
    meta: { cacheOutcome: 'miss' }
  }
}
{
  key: 4173135880,
  query: {
    kind: 'Document',
    definitions: [ [Object] ],
    loc: { start: 0, end: 144 },
    __key: 4173135880
  },
  variables: {},
  operationName: 'query',
  context: {
    url: '/graphql',
    fetchOptions: undefined,
    fetch: undefined,
    preferGetMethod: false,
    requestPolicy: 'cache-first',
    pollInterval: undefined,
    meta: { cacheOutcome: 'miss' }
  }
}
```

And also at the final export step:
```
❯ yarn export
yarn run v1.22.4
$ next export
info  - using build directory: /Volumes/Work/wwd/smartlearn/app/.next
info  - Copying "static build" directory
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
info  - Launching 11 workers
info  - Copying "public" directory
[====] info  - undefined (0/8)[Function]
{
  key: 4173135880,
  query: {
    kind: 'Document',
    definitions: [ [Object] ],
    loc: { start: 0, end: 144 },
    __key: 4173135880
  },
  variables: {},
  operationName: 'query',
  context: {
    url: '/graphql',
    fetchOptions: undefined,
    fetch: undefined,
    preferGetMethod: false,
    requestPolicy: 'cache-first',
    pollInterval: undefined,
    meta: { cacheOutcome: 'miss' }
  }
}
{
  key: 4173135880,
  query: {
    kind: 'Document',
    definitions: [ [Object] ],
    loc: { start: 0, end: 144 },
    __key: 4173135880
  },
  variables: {},
  operationName: 'query',
  context: {
    url: '/graphql',
    fetchOptions: undefined,
    fetch: undefined,
    preferGetMethod: false,
    requestPolicy: 'cache-first',
    pollInterval: undefined,
    meta: { cacheOutcome: 'miss' }
  }
}
```

Any idea on how I can bypass this, and just force these to be ran dynamically (clientside?) instead?

**Comment by lukasluecke** [comment]
Downgrading the dependencies fixes the issue somehow:

Working
```
"@urql/exchange-graphcache": "^3.0.2",
"@urql/exchange-multipart-fetch": "^0.1.8",
"urql": "^1.10.0",
```

Broken
```
"@urql/exchange-graphcache": "^3.1.1",
"@urql/exchange-multipart-fetch": "^0.1.9",
"urql": "^1.10.1",
```

**Comment by kitten** [comment]
@lukasluecke None of these dependencies are affecting how this works though. What does stand out is the export step though, `Generating static pages (0/7)`. So the higher-order component seems to be stripped.

But either way, there's no information here for us to help out, since we don't know what the setup is like, what the configs are like, which conditions apply and so on.

> I passed `{ssr: true}` as the withUrqlClient options, which then disabled the static page generation

So to clarify, this option enables `getInitialProps` being added to your component at which point SSR is forced to be enabled. What Next makes out of this is that static page optimisations are disabled.

I'm not sure what your setup is like though: Are you trying to generate static pages? Are you trying to run queries client-side? At this point you could also just use a normal provider only on the client-side. And what are the methods you're using to generate statically generated pages? The new methods, the configs, etc?

**Comment by lukasluecke** [comment]
@kitten I know that it doesn't make any sense with only these packages changed, but it really is the only difference.. I will try to somehow create a reproduction that exhibits the same symptoms. Appreciate your help so far!

As to why my setup is weird the way it is, there is a plan to have SSR in the future (no static pages though), but for now the NextJS app is just statically exported with all queries being run (or re-run) clientside (because it needs to be embedded this way in an existing project). I'll try and see if just simplifying the setup for now will also help 🙂

**Comment by lukasluecke** [comment]
Seems to be fixed with the latest next-urql version, really weird 🤔
