### ISSUE TITLE
RFC: Deprecate `operationName` in favour of `kind`

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql#1005]
## Summary

Wording is tricky, and there's currently some confusion between the following two

![Screenshot 2020-09-28 at 14 55 32](https://user-images.githubusercontent.com/10779424/94441972-51458000-019b-11eb-814a-7b8a23a83e3d.png)

### A - Operation type/kind

A finite set of operation types (query, mutation, subscription)

Currently this is indicated in `urql` on `Operation.operationName`. It's widely used in the `Client`'a and `Exchange`s' control flows and is confusing since it implies to refer to `OperationDefinitionNode.name.value`, which is ambiguous.

```gql
query GetUser # <- `query` is the kind
```

### B - Operation name

One or more **user provided** names of an operation.

While this is an optional name on the `OperationDefinitionNode` and not actively observed or used in `urql` it is sent sometimes by the `fetchExchange` and `subscriptionExchange` for instance. This is commonly what's also referred to as the "Operation Name."

```gql
query GetUser # <- `GetUser` is the name
```

> Note: A `DocumentNode` on `urql`'s `Operation` may contain multiple `OperationDefinitionNode`s (i.e. multiple queries) with multiple names but that's not supported by convention and it's encouraged, as in other clients, to only pass one, hence an operation will only have one possible name or none.

### Existing naming

Deprecate the [`operationName` property](https://github.com/FormidableLabs/urql/blob/main/packages/core/src/types.ts#L57) and introduce a `kind` property. The deprecated property would be removed in a subsequent major update but should for the time being issue a warning (as a getter) for the next minor bump in development and at most once.

<details>
  <summary>Ruled out</summary>

#### Option 2

Do option 1 and also rename the Operation interfaces ([Operation](https://github.com/FormidableLabs/urql/blob/main/packages/core/src/types.ts#L56), [OperationContext](https://github.com/FormidableLabs/urql/blob/main/packages/core/src/types.ts#L42), [OperationDebugMeta](https://github.com/FormidableLabs/urql/blob/main/packages/core/src/types.ts#L34) to use the term `Request`/`UrqlRequest` to prevent confusion with the Operation node type in GraphQL (of which, an Urql Operation can have multiple).

Re-introduce the legacy naming scheme as a deprecated alias and subsequently remove in a future major release.

```ts
/* @deprecated use `Request` instead */
export type Operation = Request;
/* @deprecated use `RequestContext` instead */
export type OperationContext = RequestContext;
```

> Note: This would take substantially more work including updates to documentation~

</details>

### Adding support for operation name

Expose [the `getOperationName` utility](https://github.com/FormidableLabs/urql/blob/372b0e3fa4da90d4acdfa4e53db068986e36f6af/packages/core/src/internal/fetchOptions.ts#L13) on `@urql/Core` by moving it, to allow users to get the operation name of a GraphQL `DocumentNode` more easily.

<details>
  <summary>Ruled out</summary>

#### Option 2

Add a `operationNames` property to the existing [Operation type](https://github.com/FormidableLabs/urql/blob/main/packages/core/src/types.ts#L58)

</details>

**Comment by kitten** [comment]
I think option 2 isn't too important or possible, as the `Operation` term is very engrained. This would also conflict with our existing usage of the terms "Request" both for HTTP requests and the raw GraphQL Request (`key` + `document` + `variables` without any other metdata)

Overall I'd be happy to keep the `Operation` terminology as it's been very insightful for users and has worked well to describe the inner "primitive to start a GraphQL operation / IO request+response". This also pairs up nicely with an "operation" in common GraphQL terminology matching up nicely with our idea of an Operation (it matches having variables and the document, where the document defines the kind of operation anyway; just with our metadata added to it)
so I think we can remove "option 2" and go for "option 1" completely.

> Adding support for operation name

Totally agreed on "option 1" here as that utility exists and the name is already set and matches up with general "GraphQL AST utility naming", so no new name is needed and this would stop being ambiguous. "option 2" isn't necessary here I think either.
