### ISSUE TITLE
New Urql client per route

### ISSUE THREAD

**Issue by oliverjam** [FormidableLabs/urql#101]
Urql is awesome, thanks for building it 🎉 

This is more of a question about recommended usage: should we create a new Urql client per route?

Currently I'm creating the client in the entrypoint to my SPA, so every component is wrapped in the provider. This makes e.g. authentication difficult, as (if the user isn't already logged in) I don't have the token when I call `new Client()`.

Apollo lets you [dynamically add headers](https://www.apollographql.com/docs/react/recipes/authentication.html) to each request—is there any way to do something similar with Urql?

Would you recommend just having one client for the login route and another for the logged-in route once I have the auth token?

**Comment by kitten** [comment]
> should we create a new Urql client per route?

No, I'd say that's not a good idea as GraphQL data/queries are quite a global matter

> is there any way to do something similar with Urql?

Yes! The client takes the `fetchOptions` property on the params you pass in. This can also be a function that then retrieves the appropriate header for each request. (Don't forget to also set `'Content-Type': 'application/json'` if you're overriding the headers.

This pattern will become similar to Apollo in 0.3 as we'll be adding "exchanges", our version of links.

**Comment by oliverjam** [comment]
Ah thanks for the quick response! So the `fetchOptions` function runs on every request? That's exactly what I wanted, perfect

**Comment by kitten** [comment]
@oliverjam:

> Might be worth highlighting in the docs that the fetchOptions headers will override the default Urql ones?

Luckily this won't be the case anymore soon. We've had an issue on that topic and it's been changed (also going to go into 0.3) :tada: :taco: https://github.com/FormidableLabs/urql/pull/96
