### ISSUE TITLE
Jest tests produce error in current configuration

### ISSUE THREAD

**Issue by JohnAtFenestra** [FormidableLabs/urql#1014]
Ubuntu: 20.04
Node: 12.16.3

I'm investigating URQL for a project currently in development. I cloned the most current code and attempted to run the Jest tests to get a better feel of what's going on. Instead, I get the following types of errors:

<pre><span style="background-color:#CC0000"><font color="#FDF6E3"><b> FAIL </b></font></span> <font color="#435257">packages/react-urql/src/hooks/</font><b>useRequest.test.ts</b>
  <b>● </b>Test suite failed to run

    <font color="#CC0000"><b>Configuration error</b></font><font color="#CC0000">:</font>
    
    <font color="#CC0000">Could not locate module </font><font color="#CC0000"><b>@urql/core</b></font><font color="#CC0000"> mapped as:</font>
    <font color="#CC0000"><b>/home/john/Documents/fenestra/development/urql/node_modules/@urql/$1/src</b></font><font color="#CC0000">.</font>
    
    <font color="#CC0000">Please check your configuration for these entries:</font>
    <font color="#CC0000">{</font>
    <font color="#CC0000">  &quot;moduleNameMapper&quot;: {</font>
    <font color="#CC0000">    &quot;/^@urql\/(.*)$/&quot;: &quot;</font><font color="#CC0000"><b>/home/john/Documents/fenestra/development/urql/node_modules/@urql/$1/src</b></font><font color="#CC0000">&quot;</font>
    <font color="#CC0000">  },</font>
    <font color="#CC0000">  &quot;resolver&quot;: </font><font color="#CC0000"><b>undefined</b></font>
    <font color="#CC0000">}</font>

     <font color="#555753"> 1 | </font><font color="#06989A">import</font> { <font color="#C4A000">DocumentNode</font> } from <font color="#4E9A06">&apos;graphql&apos;</font><font color="#C4A000">;</font>
     <font color="#555753"> 2 | </font><font color="#06989A">import</font> { useRef<font color="#C4A000">,</font> useMemo } from <font color="#4E9A06">&apos;react&apos;</font><font color="#C4A000">;</font>
    <font color="#CC0000"><b>&gt;</b></font><font color="#555753"> 3 | </font><font color="#06989A">import</font> { <font color="#C4A000">GraphQLRequest,</font> createRequest } from <font color="#4E9A06">&apos;@urql/core&apos;</font><font color="#C4A000">;</font>
     <font color="#555753">   | </font><font color="#CC0000"><b>^</b></font>
     <font color="#555753"> 4 | </font>
     <font color="#555753"> 5 | /** Creates a request from a query and variables but preserves reference equality if the key isn&apos;t changing */</font>
     <font color="#555753"> 6 | </font><font color="#06989A">export</font> <font color="#06989A">function</font> useRequest(

      at createNoMappedModuleFoundError (../../node_modules/jest-resolve/build/index.js:552:17)
      at Object.&lt;anonymous&gt; (src/hooks/useRequest.ts:3:1)

</pre>

There is a `moduleNameMapper` entry in `preset.js`

```js
  moduleNameMapper: {
    "^urql$": "<rootDir>/../../node_modules/urql/src",
    "^(.*-urql)$": "<rootDir>/../../node_modules/$1/src",
    "^@urql/(.*)/(.*)$": "<rootDir>/../../node_modules/@urql/$1/src/$2",
    "^@urql/(.*)$": "<rootDir>/../../node_modules/@urql/$1/src",
  },
```
The mapping implies that Jest should expect `urql` to be installed via npm, but that doesn't make sense to me given this is a development environment.

Any suggestions as to how to get the Jest tests to run successfully?

**Comment by kitten** [comment]
> The mapping implies that Jest should expect urql to be installed via npm, but that doesn't make sense to me given this is a development environment.

I'm not quite sure I'm following; Did you follow these steps and you're basically at the point where you're trying to run `yarn run test` in a package? https://github.com/FormidableLabs/urql/blob/main/CONTRIBUTING.md#how-do-i-set-up-the-project

**Comment by JohnAtFenestra** [comment]
User error. I did not read the CONTRIBUTING file because I'm only conducting research. Using yarn install and yarn run test does work.

For the record, I used `npm install` and that produced the issues I described when I ran `npm run test`.
