### ISSUE TITLE
exchange - @urql/exchange-graphcache typings error

### ISSUE THREAD

**Issue by IrvingArmenta** [FormidableLabs/urql#1017]
I'm using Typescript and `nextjs` with `urql`.

I'm using the `@urql/exchange-graphcache` package and adding it to the client configuration, but it seems there is an issue with the typings and is causing an error that comes out in`vscode`, but everything seems to be working fine, just a typing error.

this only happens in the latest version of `@urql/exchange-graphcache` = `"^3.1.2"`, everything it's okay in `"^3.1.1"`

urql version & exchanges:
```
"urql": "^1.10.1"
"@urql/exchange-graphcache": "^3.1.2",
"next-urql": "^1.2.0"
```
**Steps to reproduce**

1. update the packages to the latest versions with `npm run packageName@latest` 

2. check if there is no TS error on vscode. 

**Expected behavior**
- There should not be any typing error. 

**Actual behavior**
- Shows an error with the typings in `exchange-graphcache` package.

Error message in vscode:
```
Type 'import("/Users/...../node_modules/@urql/exchange-graphcache/node_modules/@urql/core/dist/types/types").Exchange' is not assignable to type 'import("/Users/...../node_modules/@urql/core/dist/types/types").Exchange'.
  Types of parameters 'input' and 'input' are incompatible.
    Type 'import("/Users/...../node_modules/@urql/core/dist/types/types").ExchangeInput' is not assignable to type 'import("/Users/...../node_modules/@urql/exchange-graphcache/node_modules/@urql/core/dist/types/types").ExchangeInput'.
      Types of property 'client' are incompatible.
        Type 'import("/Users/...../node_modules/@urql/core/dist/types/client").Client' is not assignable to type 'import("/Users/...../node_modules/@urql/exchange-graphcache/node_modules/@urql/core/dist/types/client").Client'.
          Types have separate declarations of a private property 'createOperationContext'.
```

**Comment by JoviDeCroock** [comment]
This is probably due to duplicate dependencies, you have multiple versions of `@urql/core`. There's a related issue about this here: https://github.com/FormidableLabs/urql/issues/951 we should move the dependency on `@urql/core` within `next-urql` to a peerDependency to resolve this issue

**Comment by JoviDeCroock** [comment]
We removed the `dependency` on `urql` from `next.js` in the next `next-urql` major version, this should prevent bundlers from running into this issue.

I'll close this issue for now the suggested solution should fix the module resolution, feel free to reopen in case there's something more going on.

**Comment by nathanWanderTech** [comment]
Hi, I'm suing React Typescript and faced this issue with Multipart Fetch Exchange. Has that been fixed with @urql/exchange-multipart-fetch? 
Using `urql version 1.11.6`, `@urql/exchange-multipart-fetch version 0.1.11`. 
`@urql/exchange-graphcache version 3.1.11` is working fine but `@urql/exchange-multipart-fetch`



`TypeScript error in C:/admin-app/src/config/urqlClient.ts(11,30):
Type 'import("admin-app/node_modules/@urql/exchange-graphcache/node_modules/@urql/core/dist/types/types").Exchange' is not assignable to type 'import("C:/admin-app/node_modules/@urql/core/dist/types/types").Exchange'.
  Types of parameters 'input' and 'input' are incompatible.
    Type 'import("C:/admin-app/node_modules/@urql/core/dist/types/types").ExchangeInput' is not assignable to type 'import("C:/admin-app/node_modules/@urql/exchange-graphcache/node_modules/@urql/core/dist/types/types").ExchangeInput'.
      Types of property 'client' are incompatible.
        Type 'import("C:/admin-app/node_modules/@urql/core/dist/types/client").Client' is not assignable to type 'import("C:/admin-app/node_modules/@urql/exchange-graphcache/node_modules/@urql/core/dist/types/client").Client'.
          Types have separate declarations of a private property 'onOperationStart'.  TS2322

     9 | const client = createClient({
    10 |   url: endpoint,
  > 11 |   exchanges: [dedupExchange, cache, fetchExchange, multipartFetchExchange],
       |                              ^
    12 |   fetchOptions: () => {
    13 |     const tempToken = JSON.parse(localStorage.getItem(token));
    14 |     return `

**Comment by kitten** [comment]
@nathanWanderTech this problem looks like an upgrade of `@urql/core` has led to it becoming duplicated. When you look at the paths in your output you can spot two of them on different levels.

This is quite common with Yarn and can be fixed with the `yarn-deduplicate` CLI. A quick run of `npx yarn-deduplicate && yarn` will fix this for you ✌️

**Comment by SorenHolstHansen** [comment]
Running `yarn-deduplicate` didn't work for me. I am getting the following error
`
Type 'import("/Users/.../node_modules/@urql/core/dist/types/types").Exchange' is not assignable to type 'import("/Users/.../node_modules/urql/node_modules/@urql/core/dist/types/types").Exchange'.
`

**Comment by kitten** [comment]
@SorenHolstHansen Typically, if you use yarn `npx yarn-deduplicate && yarn` or for npm `npm dedupe` deduplicate dependencies. In this case you can see that `@urql/core` is installed twice, once for `urql` and once independently. However, we've recently released a new major version of `@urql/core` so it's possible that `urql` is installing `^2.0.0` and the rest depend on `>= 1.8.0` or something of the likes. It may help for you to make sure to first upgrade all packages and then to run the deduplication again.

**Comment by SorenHolstHansen** [comment]
@kitten Thanks a lot, was using an old version of urql which was dependent on @urql/core 1.8.something

**Comment by robquinn** [comment]
@kitten I want to also thank you! Upgrading my `urql` and `@urql/exchange-graphcache` packages fixed the typing issue :)
