### ISSUE TITLE
svelte: variables reactivity

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#1036]
urql version & exchanges:

```json
"@urql/exchange-graphcache": "3.1.3",
"@urql/svelte": "https://pkg.csb.dev/FormidableLabs/urql/commit/4550be11/@urql/svelte",
"graphql": "15.3.0",
"graphql-tag": "2.11.0",
"svelte": "3.29.0",
```

**Steps to reproduce**

1. Start the server opening this page: https://codesandbox.io/s/apollo-server-urql-svelte-crud-h1pcl
1. Open Incognito browser session
1. Go to reproduction: https://77lev.csb.app/
1. Click on "Todos list"
1. Change `first` value using the only input available

**Expected behavior**

New API call on each change

**Actual behavior**

No API call at all

---

If you go [here](https://codesandbox.io/s/urql-svelte-100-variables-reactivity-77lev?file=/List.svelte) you can find this:

```js
// THIS DOESN'T WORK
$: {
  console.log("todos.variables BEFORE:", todos.variables);
  todos.variables.input.first = first;
  console.log("todos.variables AFTER:", todos.variables);
}

// THIS WORKS
// $: {
//   console.log("todos.variables BEFORE:", todos.variables);
//   todos.variables = { ...todos.variables, input: { first } };
//   console.log("todos.variables AFTER:", todos.variables);
// }
```

The second works but is too complicated. **You can imagine when there are so many variables to consider.**

Is this the correct way? Am I wrong?

Can you suggest something alternative?

**Additional**

[CodeSandBox client project](https://codesandbox.io/s/urql-svelte-100-variables-reactivity-77lev?file=/List.svelte)
[CodeSandBox server project](https://codesandbox.io/s/apollo-server-urql-svelte-crud-h1pcl)

**Comment by kitten** [comment]
I don't think the docs aren't wrong here. Reactivity blocks are useful for invalidating state and triggering a component update in one grouped block and that's expected. However, that works well for local variables but not stores.

Stores need to reactively be updated, hence the following two aren't the same:

```js
const store = writable({ test: { deep: { deep: 2 } } });
	
const update = () => {
  // DOESNT WORK:
  $: { store.test.deep.deep++; };

  // WORKS:
  $store.test.deep.deep++;
};
```

This transpiles to two distinct implementations:

```js
$: {
  $$invalidate(0, store.test.deep.deep++, store);
}

set_store_value(store, $store.test.deep.deep++, $store);
```

So you can see how the first update doesn't actually update the store but updates the component.
The second statement here however updates the store, which then updates the component.

I can see how this is confusing but as far as I'm aware this is idiomatic and expected in Svelte store implementations. Other frameworks like Vue work around this by supporting deep updates explicitly but Svelte doesn't quite do that and always requires you to prefix stores with `$` even when they're in reactive blocks.

**Comment by frederikhors** [comment]
Thanks for your answer @kitten.

I'm actually using this:

```js
let search

const todos = query(
  operationStore(
    AllTodosQuery,
    { search },
    { requestPolicy: "network-only" }
  )
);

$: todos.variables = {
  search
};
```

**And it it works reactively now.**

If I change `search` the query is correctly re-executed.

---

And if I say there is a typo in the documentation is because it just doesn't work.

I refer to this:

```js
function nextPage() {
  $todos.variables.from += $todos.variables.limit;
}
```

If I use this code the error is:

```
Uncaught TypeError: It is not allowed to update result properties on an OperationStore.
```

Here a simple reproduction: https://codesandbox.io/s/urql-svelte-100-variables-change-function-error-nulpt?file=/List.svelte

I added the button "Update input":

![image](https://user-images.githubusercontent.com/41120635/95231834-f7c8fb00-0803-11eb-9b8d-5c04b41a0192.png)

Screen of the error:

![image](https://user-images.githubusercontent.com/41120635/95231752-d6680f00-0803-11eb-8584-d89a5dc0df5d.png)

**Comment by frederikhors** [comment]
We can also add my reactivity variables block to the docs if you agree.

**Comment by kitten** [comment]
I believe one of our invariants mistriggered in development, which I managed to reliably reproduce. It caused this erroneous error, but as stated above `$store` assignments rather than `$: { store }` assignements are still correct for the above stated reasons.
