### ISSUE TITLE
ClientEvent (or IEventFn) exports do not exist

### ISSUE THREAD

**Issue by kasbah** [FormidableLabs/urql#105]
I am seeing errors when bundling my app that uses urql v3-next1. 

```
urql/es/interfaces/index.js 8:0-56 " './events' does not contain an export named 'ClientEvent'.
```

With urquelle the error is similar except with `IEventFn`. If you look at line 8 in the transpiled `es/interfaces/index.js` it's:

```js
export { ClientEventType, ClientEvent } from "./events";
```

But `events.js` is just:

```js
export var ClientEventType;

(function (ClientEventType) {
  ClientEventType["InvalidateTypenames"] = "InvalidateTypenames";
  ClientEventType["RefreshAll"] = "RefreshAll";
})(ClientEventType || (ClientEventType = {}));
```

It seems `ClientEvent` is completely removed when transpiling but the export in `index.js` is not.

**Comment by kitten** [comment]
The TypeScript expor for it is probably just missing. I haven’t seen this personally before when testing the new versions but it doesn’t hurt to export it 👍

I’ll do so later
