### ISSUE TITLE
(svelte) mutation not working for newer svelte versions

### ISSUE THREAD

**Issue by JustinVoitel** [FormidableLabs/urql#1050]
I tried to use the mutation function from @urql/svelte with the newest version of svelte but somehow there is a problem with the intern context functionality that uses the client! What wonders me is that queries work wonderfully fine and they also use the intern get/setContext functions from svelte. I also found out that it starts working when downgrading svelte to 3.24.1

urql version & exchanges:
"@urql/svelte": "^1.1.0",

**Steps to reproduce**
1. clone example 
2. update svelte to any version above 3.24.1
3. add mutation example from https://formidable.com/open-source/urql/docs/basics/mutations/#svelte
4. execute the mutation

**Expected behavior**
The mutation getting executed

**Actual behavior**
When I call the mutation, the browser console logs an error: `Function called outside component initialization` and the mutation isn´t getting executed!
![grafik](https://user-images.githubusercontent.com/30449535/95493538-e2d39f80-099c-11eb-97ca-5744d4362772.png)

**Comment by kitten** [comment]
Have you accidentally pasted the mutation example code inside a function body outside of your component's `<script>` block? It needs to become part of the component lifecycle, i.e. you need to call the `mutation` helper function itself inside the component body and not delayed inside a nested function.

**Comment by kitten** [comment]
Hiya :wave: Let me know if you've resolved this or still need some help. For now, I'll close this issue since it's gone unreplied for a couple of days, but feel free to keep posting here with any questions you may have!

**Comment by EskelCz** [comment]
@kitten Why can't it be inside a nested function? I'm struggling with the same issue and I think calling the fetch at a later time (on interaction) is a valid use case. Is it not?

Here's a demo: https://stackblitz.com/edit/sveltekit-urql-issue-demo

Thanks for any guidance, I feel completely stuck and I've already read about 20 threads about this error. :-/
