### ISSUE TITLE
(svelte) - Remove use of void type unions which prevent optional chaining

### ISSUE THREAD

**Issue by jamsch0** [FormidableLabs/urql#1051]
The type of the `data`, `error` and `extensions` properties on `OperationStore` use `void` instead of `null` or `undefined`, which prevents using the optional chaining (`?.`) operator on them when using TypeScript.

According to https://github.com/microsoft/TypeScript/issues/35236, this (lack-of) interaction between the `void` type and the optional chaining operator is intended behaviour.

urql version & exchanges:
@urql/svelte 1.1.0

**Steps to reproduce**

```ts
<script lang="ts>
    let todos = operationStore<GetTodosQuery>('...');
    query(todos);

    $: completedTodos = $todos.data?.todos.filter(todo => todo.completed);
</script>
```

**Expected behavior**
To be able to use optional chaining operator on operation result.

**Actual behavior**
The following TypeScript error is received:
> Property 'todos' does not exist on type 'void | GetTodosQuery'.
>  Property 'todos' does not exist on type 'void'.ts(2339)

The type has to be narrowed first using an `if` or ternary:
```ts
<script lang="ts>
    let todos = operationStore<GetTodosQuery>('...');
    query(todos);

    // This doesn't actually work because of https://github.com/sveltejs/language-tools/issues/493 (I think)
    // $: completedTodos = $todos.data ? $todos.data.todos.filter(todo => todo.completed);

    $: todosData = $todos.data;
    $: completedTodos = todosData ? todosData.todos.filter(todo => todo.completed);
</script>
```

**Comment by kitten** [comment]
I wouldn't consider this a bug per se since it's expected behaviour but I suppose we can switch `OperationResult` types to use `T | undefined | null` in all applicable cases.
cc @JoviDeCroock

**Comment by kitten** [comment]
Ok, limiting this, I just tested this in the TS playground and it only applies to `| void` so the fix indeed only needs to be made to Svelte.
