### ISSUE TITLE
RFC: Update refocusExchange to utilize Page Visibility API

### ISSUE THREAD

**Issue by kitten** [FormidableLabs/urql#1063]
See: https://github.com/FormidableLabs/urql/discussions/1055

## Summary

There are known issues that occur with the `focus` event:

- `iframe` can cause the `focus` event to fire numerous times if the user interacts with the `iframe` and then back with the current document
- DevTools can cause the `focus` event to fire numerous times if the user/developer interacts with the DevTools and then back with the document. (A very common case for developers)
- A developer fires a `focus` event (ie. `node.dispatchEvent(new CustomEvent('focus', { bubbles: true}))`). This case seems less likely but still a side-effect of the current implementation.

We may also want to check what other libraries, like `swr`, are doing.

## Proposed Solution

- Check whether the Page Visiblity API can help with this
- Reimplement `refocusExchange` with the new API
- Preserve IE11 support with fallbacks, polyfills, or workarounds (or an alternative approach entirely?)

**Comment by JoviDeCroock** [comment]
I have just verified the `Page visbility API` on IE11 (Windows 10) and it works correctly as mentioned on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)

**Comment by tatchi** [comment]
Hi,

Has anyone started to work on this? If not, I would love to give it a shot :)

**Comment by JoviDeCroock** [comment]
Hey @tatchi,

Noone has picked this up as far as I'm aware, feel free to give it a shot. In case you're not sure or want some guidance you can put it up as draft and I'd be glad ot help out where I can.
