### ISSUE TITLE
useQuery causes double render

### ISSUE THREAD

**Issue by IskanderMustafin** [FormidableLabs/urql#1085]
When using `urql` with `next.js` in SSR more the `useQuery` hook causes double render. 
Problem occures when using `next-urql` package or when manually creating and using `init-urql-client.ts` and `with-urql-client.tsx`.

This problem appeared at 1.9.0 release (no problems with 1.8.0 and lower).

urql version & exchanges: `urql` 1.9.0 and higher

**Steps to reproduce**
1. Go to this example: [https://github.com/FormidableLabs/urql/tree/main/packages/next-urql/examples/2-with-_app.js](https://github.com/FormidableLabs/urql/tree/main/packages/next-urql/examples/2-with-_app.js)
2. Add some logging in `PokemonList` component and you will see log message twice. React profiler also will say that second render was because of hooks were changed.

_Please note_: graphql endpoint used in this example doesn't work for me (`https://graphql-pokemon.now.sh` returns 404), so for testing purposes I used another graphql endpoint.

**Expected behavior**
`useQuery` hook should not cause second render

**Actual behavior**
useQuery causes double render

**Comment by JoviDeCroock** [comment]
This is not a bug, it's actually intended. At first we get a synchronous result out of the SSR-cache, then we subscribe to new results, we could diff these two results but that's a bit expensive and could be influenced by for instance a potential "local-state" exchange. 

Your UI will look at this data and see that it hasn't changed, if you want to catch these cases you could always use `React.memo` or `shouldComponentUpdate`.

**Comment by kitten** [comment]
Closed due to inactivity

**Comment by c0b41** [comment]
why is this behavior happening, what commit introduced this?
