### ISSUE TITLE
Modify data on resolve in Svelte

### ISSUE THREAD

**Issue by Acidic9** [FormidableLabs/urql#1090]
## Summary

Some GraphQL API endpoints return their data in not the cleanest way. For example, API's that follow the [graph structure](https://developers.facebook.com/docs/graph-api/overview/) with `nodes`, `edges` and `fields`.

This results in you needing to do: `$result.data.data.edges` which is ugly and it would be nice to be able to clean the data on resolve before accessing the returned data.

Another benefit is that you could wrap the returned data in a class to have custom methods available.

Eg:
```js
{#if $result.fetching}
  <!-- loading -->
{:else if $result.error}
  <!-- error -->
{:else}
  <p>Price: {$result.data.getPrice('USD')}</p>
{/if}
```

## Proposed Solution

Add an API to "sanitise" the resolved data before inserting into the `operationStore`.

For example:

```js
operationStore(
  QUERY,
  { arg1, arg2 },
  {
    sanitiser: (data) => {
      // Function to clean data
      return data.data.edges.map(edge => new Foo(edge));
    }
  }
);
```

## Requirements

The Client class needs to be updated to include a new optional field `'sanitiser'` (or something similarly named) which is a function which returns the new data.

```ts
sanitiser: <D, T>(data: D) => T
```

**Comment by kitten** [comment]
Hiya 👋

A couple of points here; Most GraphQL APIs that you consume will also be built by you or a team of yours and should always cater to your applications, so this argument doesn't quite apply.
Furthermore the "edges pattern" is part of the Relay pagination spec and not "ugly" or indirection but is there for a purpose. Saving yourself a single property access isn't nicer or stylistically more desirable, and instead will put a layer of indirection in your code.

That being said, your bindings are not a layer of business logic, hence there are instead two other places where you should place this logic:

- In an exchange that transforms your result (which breaks GraphQL's type guarantees though)
- or in Svelte, a derivation store: https://svelte.dev/tutorial/derived-stores

So unfortunately I'll have to close this proposal. Sorry! ❤️

**Comment by Acidic9** [comment]
I wasn't aware of derived stores, thanks!

**Comment by kitten** [comment]
No worries! Hope they do fit the bill!
