### ISSUE TITLE
client-component subscribes repeatedly to client

### ISSUE THREAD

**Issue by willcosgrove** [FormidableLabs/urql#110]
Hi, I wish I had more information to give you in this issue.  I've been trying to debug this issue for a couple of hours now, and I haven't been able to figure out what the root cause is.

I've got a component (I've tried using the ConnectHOC, and the Connect component) which is connected.  It has one query, and two mutations.  Every time I execute a mutation, a new subscription gets created on the client for the query.  The query never changes during this exercise.  Each of these subscriptions executes the same query.  Running a mutation causes all the subscriptions to refetch, which hammers my server with an increasing number of identical GraphQL queries.  I cannot for the life of me figure out what I am doing that would cause this.  Have you seen anything like this before?

**Comment by willcosgrove** [comment]
Thank you for the quick reply!  Sorry mine was a bit slower, I had to run into a meeting. I'm using Urql 0.2.2.  The subscription I'm talking about is what is being created here:

https://github.com/FormidableLabs/urql/blob/dbe4b1bdeaab2abad16b985ce1dd4dd1d3464293/src/components/client.tsx#L110

So I have one component connected with one query, which is fetching a Song of a specific ID.  I have two mutations which change an attribute of the song being referenced by the query, and the mutation returns the song back.

What I'm seeing is that the array of subscriptions on the client is growing every time I do a mutation, and then each subscription gets refetch on each mutation.

This is the list that keeps growing: ![](http://c.willl.me/3u303I2b1k0X/%255B01fef6c8f7fccfe250db7b4718769a94%255D_Image%2525202018-08-09%252520at%2525205.08.59%252520PM.png)

Thank you again for your speedy reply 🙏

**Comment by kitten** [comment]
Oh interesting!

So you just discovered an edge cases here, which might be at play. https://github.com/FormidableLabs/urql/blob/next/src/components/client.tsx#L70-L75

I think this would cause `formatProps` to resubscribe every time a new query is passed in (which can be quite common if you're creating a query inside render with some variables). And this in turn might cause these subscription listeners to be duplicated and hence called multiple times.

Does this make any sense? Have you tried to swap out the `query` prop with a constant value outside of your component (so that its reference stays the same)? If this prevents multiple refetches, and most importantly duplicated subscriptions, then I think I know what to do to fix this :+1:

**Comment by willcosgrove** [comment]
I actually did try that right before I opened the issue, thinking that that could be a problem, but it still exhibited the same behavior 😕

**Comment by kitten** [comment]
@willcosgrove I think even if the subscription is not duplicated you should still see the query being repeated. If it's indeed send multiple times (if you're rendering the client component several times) you might be glad to hear that the `next` version has query deduplication :)

So maybe try to install the `next` tag (`urql@next`) and see if it fixes this behaviour. `v0.3.0-next4` will go out relatively soon and doesn't have any breaking changes.

**Comment by willcosgrove** [comment]
I'll give that a shot tonight and see if that resolves it.  I will report back once I have.  Thanks!

**Comment by willcosgrove** [comment]
Ok, the report:

It did what I thought, it solved the problem of hammering the server, due to the deduplication of requests.  But the subscriber count still grows with every mutation run.  Here's a gif of the react inspector while I hit the favorite/unfavorite button a few times on my phone:

![](http://c.willl.me/2V073Q0q0Y3l/Screen%252520Recording%2525202018-08-09%252520at%25252008.29%252520PM.gif)

I'd be willing to post my component if you think it would help in debugging.

I'm glad that the deduplication will fix this problem as far as my server is concerned.  I would still like to get this subscription leak under control though, if at all possible.

**Comment by willcosgrove** [comment]
Ah, ok I found an issue with my implementation.  I _said_ that I moved the query and migration construction up to the constructor, which kept the referential equality between renders, but I was wrong.  I moved the individual migration constructions up to the constructor, but I was creating a new object in each render method.

```jsx
<Connect
  query={this.query}
  mutation={{
    favorite: this.favoriteMutation,
    unfavorite: this.unfavoriteMutation,
  }}>
```

🤦‍♂️  Sorry about that, totally spaced.

> If this prevents multiple refetches, and most importantly duplicated subscriptions, then I think I know what to do to fix this 👍

It does fix the ballooning subscription count when I keep the referential equality of the query and mutation objects between renders 🙌

**Comment by willcosgrove** [comment]
I don't know what fix you had in mind, but one thing that I think would work would just be to always unsubscribe before creating a subscription on the client if a `subscriptionId` is present.

**Comment by willcosgrove** [comment]
I wanted to tie together a few of my comments from last night into a full post mortem on my problem. I thought it might be helpful to see some of the pitfalls I hit as a new user of Urql (which I am loving 😄). I'll try to be as brief as I can be, but I'm not known for my short explanations 😬

I have a component, a `<FavoriteButton>` which I needed to hook up to retrieve some data from my GraphQL endpoint, and I also needed it to execute some mutations on press. I hooked it up using the `ConnectHOC` and got it all working in about 20 minutes, success! Then when I was demoing it to someone, I happened to look at the server logs, and noticed _tons_ of GraphQL requests were coming in to the server. Like, a lot a lot, probably close to 30 or 50 per button press.

So I started to investigate to see what I was doing wrong. I noticed that every second the `client` prop on the inner component of the HOC was being updated. The every second thing was not completely out of left field, my app is a music player, and there's redux state changing every second corresponding with progress through the track that is being played. I assumed that my issue was how I had configured the Urql Provider. My app is a React Native app, and when it starts up, I don't know the logged in state of the user. The API key gets loaded asynchronously into the redux store sometime (hopefully quickly!) after launch. But it made it not possible for me to give the Urql Provider a constant client that would live over the whole lifetime of the app, because the API key value could change. Usually from `null` to something. So the Urql Provider is actually wrapped in a `react-redux` `connect` call which creates the client in a `mapStateToProps` function. My fear was that every state change, a new client was being created and passed down. I spent about an hour on this dead end. I think I improved the code, but it didn't fix my problem.

I switched the `<FavoriteButton>` to using `Connect` rather than the HOC, but that didn't help. I added a `console.log` to the render function of my `<FavoriteButton>` to see how often it was re-rendering, and it was indeed rerendering every second, even though it had no need to.

The issue ended up being a combination of things. One of the problems was the one that you pointed out here: subscriptions were being added on each render because the query and mutation objects were being created anew during each render, and so were failing the referential equality check done in Urql, which caused a new subscription to be created. I upgraded to `urql@next` and the query count reduced to a normal amount. I fixed the query and mutation object creation so they would be referentially equal between renders, and that fixed the subscription count rising. I switched my component back to the ConnectHOC, because that's how I wanted it written originally. Then I noticed that my `console.log` in the render function of my component was still firing every second. That's not right! I changed my component to inherit from `PureComponent`, but that didn't change anything. It turns out that the reason that didn't help is because the props being passed down from the HOC to my component were changing every render. I didn't do a full audit to see which all props were changing, but at the very least, the `cache` prop gets regenerated every render. So I went back to inheriting from `Component` and wrote a `shouldComponentUpdate` to only update when props that I cared about changed.

But the HOC component was still rerendering every second. That is because its parent component, the music player, rerenders every second. The props to the HOC weren't changing, but because the HOC inherits from `Component` instead of `PureComponent` it was rerendering (#111). The rerendering was causing the function generating the query and mutation props to create new query and mutation objects, which was causing a new subscription on each render. (I realized I failed to mention earlier that the HOC was hooked up using the function form, where the settings are based off of props, rather than the fixed form).

Whew! That was a lot. Thanks for reading all this! I have some ideas for potential fixes, but I'm sure that you probably, having spent more time on Urql than I have, will have a better, fuller understanding of all the use cases, so I'd be interested to hear what some of your solutions are. I'm happy to help work on the PRs for fixes for some of these problems once we've figured out what the right path forward is.

Thanks again for taking the time! Urql is really nice! I still got that button hooked up in 20 minutes as a first time user, which I was really happy with! Thanks for open sourcing it! ❤️

**Comment by kitten** [comment]
Yea, I thought this might fix it. Regarding the duplicated subscriptions, I’ll look into fixing that on the next branch. Should be easy enough :)

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️
