### ISSUE TITLE
next-urql withUrqlClient causing error in v2.1.0

### ISSUE THREAD

**Issue by mosesintech** [FormidableLabs/urql#1101]
urql version & exchanges: 
urql: v1.10.1
next-urql: v2.1.0

**Steps to reproduce**

1. Install urql, next-urql, and peer dependancies.
2. Import withUrqlClient in Next.js page (example: /src/pages/login.js).
3. Error.

**Expected behavior**
Expect to be able to use withUrqlClient without issues.

**Actual behavior**
Import withUrqlClient causes an issue, without even using it.

Failed to Compile:
<img width="977" alt="Screen Shot 2020-10-29 at 9 38 04 AM" src="https://user-images.githubusercontent.com/50815816/97588769-d7d3c400-19ca-11eb-849e-2823df3b108f.png">

Error in Terminal:
<img width="906" alt="Screen Shot 2020-10-29 at 9 41 34 AM" src="https://user-images.githubusercontent.com/50815816/97588920-f639bf80-19ca-11eb-9049-32098238bf8d.png">

**_NOTE: There is no issue with next-urql v2.0.0, but only with v2.1.0._**

My dependencies:

```
"dependencies": {
    "bcryptjs": "^2.4.3",
    "connect-session-knex": "^2.0.0",
    "express": "^4.17.1",
    "express-graphql": "^0.11.0",
    "express-session": "^1.17.1",
    "graphql": "^15.3.0",
    "graphql-iso-date": "^3.6.1",
    "js-cookie": "^2.2.1",
    "knex": "^0.21.6",
    "next": "9.5.5",
    "next-urql": "^2.1.0",
    "pg": "^8.4.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-is": "^17.0.1",
    "sass": "^1.27.0",
    "urql": "^1.10.1"
  }`
``

**Comment by kitten** [comment]
Hiya we've just noticed this issue too. This was related to an invalid build. If you upgrade to `next-urql@2.1.1` you'll find that it has been fixed ✌️

**Comment by mosesintech** [comment]
Thank you! ^-^
