### ISSUE TITLE
Can ConnectHOC be a PureComponent?

### ISSUE THREAD

**Issue by willcosgrove** [FormidableLabs/urql#111]
I was running into an issue earlier today where I noticed that one of my components was rerendering much more frequently than I expected it to.  It was hooked up to the `ConnectHOC`.  I swapped out my component implementation for one that used the `Connect` component, and my rerendering problems went away.  I checked, and `ConnectHOC` is extending `Component` instead of `PureComponent`.

I'm not a React expert, so I could be way wrong.  But I think the `ConnectHOC` _should_ be able to be a `PureComponent`.  But if it can't, it would probably be good to define some kind of `shouldComponentUpdate` definition for it.

I'm happy to submit a PR to add it, but I always like to get feedback to make sure my proposed changes are wanted/make sense before I start working on a PR.

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️
