### ISSUE TITLE
Null value instead of 0 in this situation

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#1122]
I have a schema like this:

```graphql
type Player {
  id: ID!
  firstname: String
  lastname: String
  sex: Int
}
```

I'm using `offlineExchange` with `schema`.

In my List page I'm querying this:

```js
export const PLAYER_FRAGMENT = `
  fragment PLAYER_FRAGMENT on Player {
    id
    firstname
    lastname
  }
`

export const ALL_PLAYERS = `
  query () {
    players() {
      nodes {
        ...PLAYER_FRAGMENT
      }
    }
  }
  ${PLAYER_FRAGMENT}
`
```

In my Detail page I'm querying this:

```js
export const ONE_PLAYER = `
  query ($id: ID!) {
    player(id: $id) {
      ...PLAYER_FRAGMENT
      sex
    }
  }
  ${PLAYER_FRAGMENT}
`
```

with:

```js
const player = query(
  operationStore(
    ONE_PLAYER,
    { id },
    { requestPolicy: "cache-and-network" }
  )
);
```

Steps:

1. Incognito mode
1. List page
1. Click on single player edit link
1. Edit (detail) page shows form
1. Sex is `null` not `0`
1. `0` is the value coming from GraphQL

**Why `null`?**

_I'm very sorry but I don't have time now for reproduction and you know how much I care about accurate reproductions on codesandbox!!! 😄_

**Comment by kitten** [comment]
Unless I'm missing something this looks expected though?

The first query doesn't seem to ask for that field since it's not in the fragment, the details view then requests it but it'll be uncached.

Since you have a schema passed on, it's nullable, and it's uncached it'll be set to `null` while more data is being fetched and your result should be marked as `stale`

**Comment by frederikhors** [comment]
Sorry. I'm sorry. I was wrong. A lot of confusion among the thousand things in my head. Every now and then you have to get up and go get some air.
