### ISSUE TITLE
Connect causes setState warning after unmount

### ISSUE THREAD

**Issue by cangoektas** [FormidableLabs/urql#114]
Hey 👋 

I had a `Connect` component for a mutation inside another `Connect` component which was querying the same type. The mutation caused a cache invalidation and the child `Connect` to unmount. The result is the following React warning in the console:

<img width="661" alt="screen shot 2018-11-11 at 13 33 27" src="https://user-images.githubusercontent.com/1178516/48313143-67062800-e5b8-11e8-810c-f428e24460a1.png">

I checked the source code and I think the `Connect` component calls `setState` regardless of whether or not the component is still mounted:

https://github.com/FormidableLabs/urql/blob/70f2c882948171f9d6acee41e2584622d790e59f/src/components/client.tsx#L259-L261

**Comment by cangoektas** [comment]
Note: As discussed in #115, this is already fixed in the `next` branch and will be resolved in the upcoming release.

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️
