### ISSUE TITLE
Loading a query with empty Todos

### ISSUE THREAD

**Issue by HawiCaesar** [FormidableLabs/urql#116]
What happens in the case when you start off with no `typenames` i.e. a query with empty todo's and there are no typenames at all ? When you have a mutation `urql` seems to not invalidate the cache. We understand why as the typename  must exist for the invalidate to work. [This](https://github.com/FormidableLabs/urql/pull/113) assumes that there is existing data (and typenames). Is there a solution for this ? 

We found a work around to this. We invalidated the entire cache and then did `refreshAllFromCache();`
```javascript
<form
     onSubmit={e => {
          e.preventDefault();
          addStore().then(() => {
             cache.invalidateAll();
             refreshAllFromCache();
          });
}}>
```

We tried to do a `shouldInvalidate` prop but this only works when a component is still mounted. It seemed not to work when we would navigate between components

**Comment by kitten** [comment]
Yep, that's currently the proposed solution. Urql's "cache" if we can even name it such is a simple heuristic and the bare minimum of what a data cache on the web should do.

That being said the next version of urql will have a "centralised cache exchange". Exchanges are basically like Apollo's links and are already described in other issues.

This means that it'll become possible to customise urql's caching behaviour. Optimally the goal will be to provide some richer exchanges that offer normalised caching or at least a caching system that lies somewhere in the middle, in between normalised and being query-only based.

**Comment by HawiCaesar** [comment]
Alright, seems similar to Apollo just as you said. I hope the customization will be richer.
