### ISSUE TITLE
@urql/core error during runtime after installing urql & graphql. I'm using typescript with react 

### ISSUE THREAD

**Issue by heretodesign** [FormidableLabs/urql#1164]
urql version & exchanges:
 @urql/core: "^1.15.1",
  urql: "^1.11.2",

![Screenshot 2020-11-18 at 4 38 36 PM](https://user-images.githubusercontent.com/23472335/99506469-17d00a80-29bd-11eb-9295-12aaddff9c58.png)

**Comment by JoviDeCroock** [comment]
Hey 👋 

Just to assess what the issue is could you try adding:

```
		    test: /\.mjs$/,
		    type: 'javascript/auto',
```

To your loaders.

**Comment by heretodesign** [comment]
@JoviDeCroock thank you. It worked. Everything is up and running
