### ISSUE TITLE
`loaded` is not set for error cases

### ISSUE THREAD

**Issue by cangoektas** [FormidableLabs/urql#118]
Hey! 👋 

I noticed that the `loaded` argument is not set for error cases. I threw me a bit off because I expected it to be `true` once the first response was received, even for an error response.

Because of that, the following code will never get to display an error message since it handles the loading state first. Here's also [a Codesandbox](https://codesandbox.io/s/r0lxnr242p) of this example.

```jsx
function App() {
  return (
    <Connect query={query(repoQuery)}>
      {({ error, loaded, data }) => {
        if (!loaded) {
          return "Loading...";
        }

        if (error) {
          return "Something went wrong!";
        }

        return (
          <span>
            The "{data.repository.name}" repo has{" "}
            {data.repository.stargazers.totalCount} stars!
          </span>
        );
      }}
    </Connect>
  );
}
```

Although handling the error case first would solve the issue, I believe not having to handle the loading and the error states in a specific order would be the better developer experience. Not sure if this is taken care of in the `next` branch but I also wanted to just raise awareness and start a discussion 🙂

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️
