### ISSUE TITLE
RFC: persisted-fetch exchange retries on failure

### ISSUE THREAD

**Issue by kbariotis** [FormidableLabs/urql#1195]
## Summary

The `persisted-fetch` [exchange](https://github.com/FormidableLabs/urql/tree/main/exchanges/persisted-fetch) follows the conventions set by the [Apollo team](https://www.apollographql.com/docs/apollo-server/performance/apq/) as it retries when the server responds with either persisted queries are not supported or that specific query was not found. 

We would like to take a different approach focusing entirely on security and completely dis-allow raw queries being sent from the client.

## Proposed Solution

Add a flag to the config of the `persisted-fetch` [exchange](https://www.apollographql.com/docs/apollo-server/performance/apq/) to ignore the retrying behaviour.

An example,

```TS
import { createClient, dedupExchange, fetchExchange, cacheExchange } from 'urql';
import { persistedFetchExchange } from '@urql/exchange-persisted-fetch';

const client = createClient({
  url: 'http://localhost:1234/graphql',
  exchanges: [
    dedupExchange,
    cacheExchange,
    persistedFetchExchange({
      dontRetryOnFailure: true
    }),
    fetchExchange,
  ],
});
```

and with the above, the client will never retry the request whatever the response from the server was.

## Requirements

N/A

**Comment by kitten** [comment]
That's a good point! For clarification, in this use-case you'd use a tool like [`graphql-persisted-document-loader`](https://github.com/leoasis/graphql-persisted-document-loader) to pregenerate the hashes and register them with your API beforehand or at deployment time to avoid any non-persisted queries to be necessary, right?

**Comment by kbariotis** [comment]
@kitten Thank you, yes the process still stays the same and we actually do use that library to parse all `.graphql` files and generate the hashes beforehand. All it changes is when the client sends a hash and the server denies it, instead of retrying with the raw query, just abort.

BTW, I'm happy to contribute with a PR. Count on me. 👍 :)

**Comment by frederikhors** [comment]
> focusing entirely on security

@kbariotis what do you mean with this? Security? How? When? 😄

Can you please explain it better?

**Comment by kbariotis** [comment]
Ofcourse @frederikhors, persisted queries in GraphQL can be used for two primary benefits. One is reducing bandwidth by transmitting only a fixed about of bytes each time for every query, so a performance benefit, the other is that you obfuscate the query structure so you don't reveal the structure of the graph and also be able to allow-list only the hashes that have been built on build time and is known only to the server, thus a security benefit.

Apollo, out of the box, [provides persisted queries functionality](https://www.apollographql.com/docs/apollo-server/performance/apq/) and focuses primarily on performance by having the client first querying the server using a query hash, and if the server responds that doesn't know that query, then the client retries with the actual raw query.

FBs' relay, on the other hand, focuses on [security by eliminating the retries](https://relay.dev/docs/en/persisted-queries).

> The relay compiler supports persisted queries which is useful because:
> 
> - the client operation text becomes just an md5 hash which is usually shorter than the real query string. This saves upload bytes from the client to the server.
> 
> - the server can now whitelist queries which improves security by restricting the operations that can be executed by a client.

:)

**Comment by frederikhors** [comment]
Ok. Very clear. Thanks.

The only problem is that I don't know how to tell my server what my graphql queries are.

At each change on the client I should regenerate a map table of the queries and their hashes and re-deploy the server.

Am I right?

**Comment by kbariotis** [comment]
The map must be re-generated every time the client changes the way it queries the server. But that map could be stored in a shared storage so the server can pick up the changes without re-deploying.

It depends on the implementation you choose and the requirements (as always :) ).
