### ISSUE TITLE
@urql/introspection v0.1.1 does not work for ESM build tools (Vite, Snowpack)

### ISSUE THREAD

**Issue by juan267** [FormidableLabs/urql#1203]
urql version & exchanges: @urql/vue 0.2.1  / @urql/introspection 0.1.1

**Steps to reproduce**

1. Create a [vite](https://github.com/vitejs/vite) project
2. Install latest @urql/introspection
3. Configure urql client to use introspection
4. Turn on vite server

**Expected behavior**

The server starts without showing any errors

**Actual behavior**

The server crashes with the following error: 

```
[vite] Dep optimization failed with error:
[vite]: Rollup failed to resolve import "graphql.mjs" from "node_modules/.pnpm/@urql/introspection@0.1.1_graphql@15.4.0/node_modules/@urql/introspection/dist/urql-introspection.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`rollupInputOptions.external`
Error: [vite]: Rollup failed to resolve import "graphql.mjs" from "node_modules/.pnpm/@urql/introspection@0.1.1_graphql@15.4.0/node_modules/@urql/introspection/dist/urql-introspection.mjs".
```

### Note 

This error does not occur on @urql/introspection v0.1.0. It was intruduced with the changes done on v0.1.1

**Comment by kitten** [comment]
Thanks for reporting this! This was just a small build issue that we overlooked, so it'll be fixed with the next release
