### ISSUE TITLE
Suspense: Partial delivery loses fields due to race conditions

### ISSUE THREAD

**Issue by arcanis** [FormidableLabs/urql#1249]
urql version & exchanges: Everything up to date, I just updated everything and checked my lockfile for lingering deps

**Steps to reproduce**

https://codesandbox.io/s/trusting-feynman-setop?file=/src/index.js

**Behavior**

I have an application where each component is responsible for fetching the data pieces it needs (and no others). I also have a cache (using Graphcache) that makes sure I don't request the same data multiple times, and that the entities are well synchronized.

In have two components displayed when loading the page. For simplicity, one is a list of Pages (from a Book), queried via:

```
query {
  book {
    __typename
    id
    pages { 
      // ...
    }
  }
}
```

And the other is the Book's cover, queried via:

```
query {
  book {
    __typename
    id
    cover
  }
}
```

My problem is that when refreshing the page, the cover sometimes (25% of the time?) isn't displayed 😐 The request fires, the response is ok (it contains the cover), but it doesn't show up on the screen. The book pages are always displayed, though - only the cover is missing (in the component, the value is `null`).

The problem isn't there when I remove Graphcache, so I assume it has something to do with it, but I'm not sure why, unfortunately. I realize it's probably difficult to fix this problem since you're likely not even sure I'm not messing something up myself 😅, but I figured I should mention it in case it rings a bell ...

Other interesting tidbits:

- If I make a mutation that return my Book entity with completely unrelated data, the cover gets displayed, even if the server doesn't return it. This hints at the field being persisted in the cache, but without being accessible by the component.

- Forcing a rerender doesn't work.

- I tried downgrading up to Graphcache 2.0.x, but all the versions I tried exhibited the same behavior.

- It's somehow related to the schema property from Graphcache. If I remove it, the field doesn't get lost.

**Comment by arcanis** [comment]
Other interesting tidbits:

- If I make a mutation that return my Book entity with completely unrelated data, the cover gets displayed, even if the server doesn't return it. This hints at the field being persisted in the cache, but without being accessible by the component.

- Forcing a rerender doesn't work.

- I tried downgrading up to Graphcache 2.0.x, but all the versions I tried exhibited the same behavior.

**Comment by arcanis** [comment]
Something else interesting (pardon me, I'm throwing everything I can see 😄) - when using the `debugExchange` between Graphcache and the `fetchExchange`, it seems they have different consistent patterns between cases where the cover is available and cases where it isn't:

**Cover isn't visible**
```
...
[Exchange debug]: Completed operation:  {operation: {…}, data: {…}, error: undefined, extensions: undefined}
[Exchange debug]: Incoming operation:  {key: 197899648, query: {…}, variables: {…}, kind: "teardown", context: {…}, …}
[Exchange debug]: Completed operation:  {operation: {…}, data: {…}, error: undefined, extensions: undefined}
[Exchange debug]: Incoming operation:  {key: 197899648, query: {…}, variables: {…}, kind: "teardown", context: {…}, …}
```

**Cover is visible**
```
...
[Exchange debug]: Completed operation:  {operation: {…}, data: {…}, error: undefined, extensions: undefined}
[Exchange debug]: Incoming operation:  {key: 197899648, query: {…}, variables: {…}, kind: "teardown", context: {…}, …}
[Exchange debug]: Incoming operation:  {key: 197899648, query: {…}, variables: {…}, kind: "teardown", context: {…}, …}
[Exchange debug]: Completed operation:  {operation: {…}, data: {…}, error: undefined, extensions: undefined}
```

**Comment by arcanis** [comment]
I still can't reproduce it with a simple schema, but I've been able to find that it's somehow related to the `schema` property from Graphcache. If I remove it, the field doesn't get lost.

**Comment by arcanis** [comment]
I have a reproduction! I've updated my initial post:
https://codesandbox.io/s/trusting-feynman-setop?file=/src/index.js

**Comment by JoviDeCroock** [comment]
Hey @arcanis,

I've looked into both issues and both seem related to a case how Suspense and our streams interact.
