### ISSUE TITLE
(graphcache) - Race condition when network latency

### ISSUE THREAD

**Issue by arcanis** [FormidableLabs/urql#1253]
urql version & exchanges: latest

(edit: I don't think it's the same bug as https://github.com/FormidableLabs/urql/issues/1249, since this one triggers even when partial delivery is disabled)

**Abstract**

I have two components that access the todo list via different queries (because in my real case they need different fields). One of those components (let's call it Primary, and the other will be Secondary) also has an `addTodo` mutation that, when called, trigger an invalidation on all the `todos` results (I know it's not very efficient, I should likely replace that by a proper optimistic insertion, but it's just simpler to do this during prototype).

When the query from Primary is slower than multiple queries from Secondary, it seems to trigger a bug where the Primary query data are unexpectedly returned as either undefined or null, crashing the application (I use the suspense mode precisely to be sure that my components always have the data they need, unless there's a server error).

**Steps to reproduce**

1. Open my server: https://codesandbox.io/s/jovial-beaver-5mdvn?file=/schema.js
2. Open the client: https://codesandbox.io/s/white-browser-qt2lr?file=/src/index.js
3. Click once on "Add" (just to focus it)
4. Press "Enter" and keep it pressed (to trigger a bunch of requests)

Quickly enough (I engineered the server so that the Todos query is slower than the TodoCount query), the bug will trigger:

![image](https://user-images.githubusercontent.com/1037931/103111890-d1239f00-4651-11eb-9298-2c35d3c29f50.png)

**Comment by kitten** [comment]
Hiya 👋

Just more as an FYI (I haven't even looked at this closely yet and whether it's related to #1249, your other issue) we'll likely be looking at this once we're back in the New Year, just to explain the delay on this.

This sounds like something may not properly be invalidated as I'd assume the invalidation of the mutation would indeed trigger a reexecution of both queries which should then trigger a `Suspense` boundary which means that both reexecutions must finish for the app to rerender. I'd assume that maybe only one catches which doesn't explain this behaviour fully.

But with all things suspense-related, this may be a quirk or edge-case behaviour in how this interacts with React

**Comment by kitten** [comment]
We investigated this and it apparently is just a race condition in Graphcache that's pretty specific to this reproduction. This bug was accidentally non-observable in previous versions and harder to hit in non-synthetic apps, where mutations wouldn't share keys.
