### ISSUE TITLE
Using cache.invalidate with cache.inspectFields causes a TS error

### ISSUE THREAD

**Issue by ostrebler** [FormidableLabs/urql#1262]
urql version & exchanges: urql 1.11.4, exchange-graphcache 3.3.3

**Steps to reproduce**

I was looking for how to invalidate queries based on partial variable match (to ignore pagination variables), and [found this trick from Jovi on Spectrum](https://spectrum.chat/urql/help/is-there-a-way-to-invalidate-queries-with-variables-without-using-variables~5e4fc1b8-849e-46e9-a9ca-72698a8433d0).

However, his last line of code actually throws a TypeScript error : 

```ts
tagQueries.forEach(x => cache.invalidate('Query', 'tags', x.arguments)
```
```
TS2345: Argument of type 'Variables | null' is not assignable to parameter of type 'Variables | undefined'.
Type 'null' is not assignable to type 'Variables | undefined'.
```

`x.arguments` is `Variables` or `null`, whereas `invalidate`'s last argument doesn't accept `null`.

**Expected behavior**

Shouldn't `invalidate` accept `null` or `x.arguments` be `Variables | undefined` ? One would expect one of the two.

**Comment by kitten** [comment]
That's definitely true! I suppose it should be able to accept both `null` and `undefined`
