### ISSUE TITLE
next-urql - getStaticProps doesn't provide static data to useQuery

### ISSUE THREAD

**Issue by pocorschi** [FormidableLabs/urql#1279]
Following the example from the [documentation](https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#using-getstaticprops-or-getserversideprops) which seems to be wrong (tries using the ssrCache exchange without defining it first and a missing comma) I am able to get the query running server side but the client side does an independent query as it doesn't seem to have access to urqlState.
Am I missing something?

urql version & exchanges:

**Steps to reproduce**

https://gist.github.com/pocorschi/0ba2a6c699df917e8a6120acdfb78c30

**Expected behavior**
The query should be executed with a request on server and it should be read from cache on client.
**Actual behavior**
The query gets executed with a request both on server and client side.

**Comment by JoviDeCroock** [comment]
You are always passing `isClient: false` which means it's never retrieved.... The example from the docs is shown here and works fine for me https://codesandbox.io/s/condescending-kapitsa-9p8y7?file=/pages/index.js

**Comment by pocorschi** [comment]
@JoviDeCroock
The codesandbox works perfectly. But it's different than the one provided in the docs. I could make a PR to correct it if you want to.

**Comment by JoviDeCroock** [comment]
Feel free to send a PR 😄

**Comment by pocorschi** [comment]
👍

**Comment by pocorschi** [comment]
Done #1280 - Closing this.
