### ISSUE TITLE
Enable @urql/exchange-refocus to work with React Native (out of the box?)

### ISSUE THREAD

**Issue by BjoernRave** [FormidableLabs/urql#1284]
**Steps to reproduce**

1. Include exchange-refocus
2. Start React-Native

**Expected behavior**

the app refreshes results when the screen/app re-gains focus.

**Actual behavior**

the app crashes since it can't find the window element

**Comment by kitten** [comment]
I removed the bug label, since this isn't quite a bug but a feature request. The refocus exchange is quite a simple one, so feel free to submit a PR for the event listeners for React Native if it has an appropriate API built-in. If it does not then it's unlikely that we'll support React Native directly with this specific exchange, but I'll take a quick look when I find the time ✌️

**Comment by BjoernRave** [comment]
Thanks, I will take a look if it's possible

**Comment by kitten** [comment]
Just looking into this, it seems like we can pass in an event handler that uses `react-native`'s `AppState`, however it'll likely not be an "automatic" change as we're currently avoiding switching bundles for `react-native` as that always leads to some problems. https://reactnative.dev/docs/appstate

**Comment by alexesDev** [comment]
for 0.63
```
import { pipe, tap } from 'wonka';
import { Exchange, Operation } from '@urql/core';
import { AppState } from 'react-native';

// prettier-ignore
export const refocusExchange = (): Exchange => ({ client, forward }) => (ops$) => {
  const watchedOperations = new Map<number, Operation>();
  const observedOperations = new Map<number, number>();

  let appState = AppState.currentState;

  AppState.addEventListener('change', (nextAppState) => {
    if (appState.match(/inactive|background/) && nextAppState === 'active') {
      watchedOperations.forEach((op) => {
        client.reexecuteOperation(
          client.createRequestOperation('query', op, {
            requestPolicy: 'cache-and-network',
          }),
        );
      });
    }

    appState = nextAppState;
  });

  const processIncomingOperation = (op: Operation) => {
    if (op.kind === 'query' && !observedOperations.has(op.key)) {
      observedOperations.set(op.key, 1);
      watchedOperations.set(op.key, op);
    }

    if (op.kind === 'teardown' && observedOperations.has(op.key)) {
      observedOperations.delete(op.key);
      watchedOperations.delete(op.key);
    }
  };

  return forward(pipe(ops$, tap(processIncomingOperation)));
};
```

**Comment by JoviDeCroock** [comment]
Closing due to stale, but the solution suggested by @alexesDev seems correct!

**Comment by nandorojo** [comment]
It would be useful to follow `react-query`'s option of allowing a custom focus listener: https://react-query.tanstack.com/guides/window-focus-refetching#managing-focus-in-react-native

One question I have about the proposal from [above](https://github.com/FormidableLabs/urql/issues/1284#issuecomment-918175394): it never removes the app state listener. Is there any concern about a memory leak here?

**Comment by jtomaszewski** [comment]
@kitten would you be open to having an additional exchange in this repository, that would be focused on react-native?

E.g. just as we have https://github.com/urql-graphql/urql/tree/main/exchanges/refocus, we could have https://github.com/urql-graphql/urql/tree/main/exchanges/refocus-react-native .

`react-native` would be added as a peer dependency into the `@urql/exchange-refocus-react-native` package.

Then, the final usage could then look like this:

```tsx
import { createClient, cacheExchange, fetchExchange } from 'urql';
import { refocusExchange as webRefocusExchange } from '@urql/exchange-refocus';
import { refocusExchange as nativeRefocusExchange } from '@urql/exchange-refocus-react-native';

const refocusExchange = Platform.select({
  default: nativeRefocusExchange,
  web: webRefocusExchange
});

const client = createClient({
  url: 'http://localhost:3000/graphql',
  exchanges: [refocusExchange(), cacheExchange, fetchExchange],
});
```
