### ISSUE TITLE
cache.readFragment returns null even with correct entity key 

### ISSUE THREAD

**Issue by devavi-labs** [FormidableLabs/urql#1292]
I am building a twitter clone app where a tweet is called a **_quack_**. I am fetching quacks with a query called "**_quacksForMe_**". The query returns a "**PaginatedQuacks**" entity which has the following structure..

```
PaginatedQuack {
    quacks {
      ...RegularQuack
    }
    hasMore
}
```

I have a pagination for it in which the returning object's structure is like this

```
return {
    __typename: "PaginatedQuacks",
    hasMore,
    quacks,
  };
```

In the _cacheExchage_'s updates object I have a method for liking a quack in which I am trying to read fragment for the quack which has to be updated like this

```
const _key = cache.keyOfEntity({
        __typename: "Quack",
        id: quackId,
    });

const _quack = cache.readFragment(
    gql(`
        fragment _ on Quack {
            id
            likes
            likeStatus
        }
    `),
    _key
);
```

The "**\_quack**" is always null even though when I tried to log the whole cache in console I can see the quack object with the exact same key available in the records in cache.

```
records: {
    base: [
        {"Quack:480" => Object}
        {"Quack:479" => Object}
    ]
}
```

I am really confused as why is this not working.

**Comment by devavi-labs** [comment]
![Screenshot from 2021-01-12 13-17-28](https://user-images.githubusercontent.com/62388549/104286549-334a2400-54db-11eb-87df-47f21fd08204.png)

**Comment by kitten** [comment]
Hiya, I don't know what queries you've run, but basically if you've run:

```
const _quack = cache.readFragment(
    gql`
        fragment _ on Quack {
            id
            likes
            likeStatus
        }
    `, {
        __typename: "Quack",
        id: quackId,
    }
);
```

And that's yielding no result it could also very well be that a field in this fragment isn't cached at all, so you're getting a cache mismatch. Have you checked whether `cache.resolve({ __typename: "Quack", id: quackId }, 'id')` is giving you a non-null value? If it isn't then the entire entity key is unknown.

**Comment by devavi-labs** [comment]
Hey I figured out I was making a mistake in the fragment, **likes** is an array of **User** object, that's why the readFragment was returning null.
