### ISSUE TITLE
Some queries failing when using @urql/core version 1.16.1

### ISSUE THREAD

**Issue by jonkoops** [FormidableLabs/urql#1298]
**Steps to reproduce**
- Clone https://github.com/amsterdam/atlas
- Check out `urql-repro` branch
- `npm i`
- `npm run start`
- Open `http://localhost:3000/datasets/zoek/`

**Expected behavior**
All calls to the GraphQL succeed

**Actual behavior**
Not all GraphQL calls succeed

This problem seems to have been introduced in https://github.com/FormidableLabs/urql/pull/1225. We downgraded the dependency in our lockfile [in our project](https://github.com/Amsterdam/atlas/pull/3850/files) and this seemed to resolve the issue.

**Comment by kitten** [comment]
Hiya :wave: Just before we go ahead and try to repro this by cloning the whole repo, can you give us some more information on the GraphQL errors or specific error behaviour you're seeing please? Like, an error message, whether it's the API that returns it, whether it's an error from `graphql.js`, etc.

**Comment by jonkoops** [comment]
Hi @kitten, sure I can provide you with some more information. We are making a GraphQL call which ends up in a server error due to a missing argument:

![image](https://user-images.githubusercontent.com/695720/104452885-e8e0aa00-55a3-11eb-9129-fa1a0ac6255f.png)

When we run this specific query on the older version (like our [production environment](https://data.amsterdam.nl/datasets/zoek/)) it seems to come trough ok. The following request body is sent there:

```json
{
  "query": "query totalCountSearch($q: String!, $limit: Int) {\n  datasetSearch(q: $q, input: {limit: $limit}) {\n    totalCount\n    __typename\n  }\n  dataSearch(q: $q, input: {limit: $limit}) {\n    totalCount\n    __typename\n  }\n  articleSearch(q: $q, input: {limit: $limit}) {\n    totalCount\n    __typename\n  }\n  publicationSearch(q: $q, input: {limit: $limit}) {\n    totalCount\n    __typename\n  }\n  specialSearch(q: $q, input: {limit: $limit}) {\n    totalCount\n    __typename\n  }\n  collectionSearch(q: $q, input: {limit: $limit}) {\n    totalCount\n    __typename\n  }\n  mapSearch(q: $q, input: {limit: $limit}) {\n    totalCount\n    __typename\n  }\n}\n",
  "operationName": "totalCountSearch",
  "variables": {
    "q": ""
  }
}
```

However after upgrading it seems an entirely different query is executed:

```json
{
  "query": "query datasetSearchQuery($q: String, $limit: Int, $page: Int, $filters: [FilterInput!], $withPagination: Boolean!) {\n  datasetSearch(q: $q, input: {limit: $limit, page: $page, filters: $filters}) {\n    ...DatasetFields\n    ...FilterFields\n    ...PageInfoFields\n    __typename\n  }\n}\n\nfragment DatasetFields on DatasetSearchResult {\n  totalCount\n  results {\n    header\n    teaser\n    modified\n    id\n    tags\n    distributionTypes\n    __typename\n  }\n}\n\nfragment FilterFields on SearchResult {\n  filters {\n    type\n    label\n    filterType\n    options {\n      id\n      label\n      count\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment PageInfoFields on SearchResult {\n  pageInfo @include(if: $withPagination) {\n    hasLimitedResults\n    hasNextPage\n    totalPages\n    __typename\n  }\n}\n",
  "operationName": "datasetSearchQuery",
  "variables": {
    "q": ""
  }
}
```

The code that executes this query can be found [here](https://github.com/Amsterdam/atlas/blob/develop/src/app/components/PageFilterBox/PageFilterBox.jsx#L16-L21). The GraphQl queries are loaded through a WebPack loader and can be found [here](https://github.com/Amsterdam/atlas/blob/develop/src/app/pages/SearchPage/documents.graphql).

It looks like somehow the schema that goes in is transformed and a different query comes back than before.

**Comment by JoviDeCroock** [comment]
I tried reproducing it here, the query you see in this file is the one from your build output so I'm not really sure what is happening but for me it dispatches the same query in both versions https://codesandbox.io/s/thirsty-frost-cc9re?file=/src/index.js

**Comment by JoviDeCroock** [comment]
@jonkoops I've tried with the test-build of https://github.com/FormidableLabs/urql/pull/1316 which now seems to dispatch the right query, didn't get a result back due to a CORS issue with the GraphQL server but the issue itself seems resolver. We can publish this next week.

**Comment by jonkoops** [comment]
@JoviDeCroock thanks for giving it a test, I will also take a look and see if this resolves the issue.

**Comment by ibash** [comment]
I hit the same problem (incorrect request being made after using graphql loader) and tested this change locally. The fixed worked on my codebase, any chance it can be published?

**Comment by JoviDeCroock** [comment]
Published on latest

**Comment by jonkoops** [comment]
Nice, I can confirm this indeed fixes the problem for us as well.
