### ISSUE TITLE
When two React components make the same urql query with Suspense, one will not unsuspend when query resolves

### ISSUE THREAD

**Issue by chrisapplegate** [FormidableLabs/urql#1332]
urql version & exchanges: 1.11.x, default exchanges

**Steps to reproduce**

1. Create a `<Provider>` with a client with `suspense` set to `true`.
2. Create two React components, each of which is individually wrapped in a `<React.Suspense>`, and each makes the exact same graphql query with `useQuery`.

**Expected behavior**

Upon loading the page, both components initially show their loading states _(Loading...)_, but should both end up displaying data once the query resolves.

**Actual behavior**

When the query resolves, the second component in the page shows its results, but the first does not, it stays in a permanent loading state.

You can see this for yourself with this demo: https://fpp93.csb.app/

Sandbox code is here: https://codesandbox.io/s/fpp93

Do note that in the sandbox, if the urql version is set to version 1.10.3, then the Sandbox will start to work again (see [here](https://codesandbox.io/s/wvfd1)), so this is a bug that was introduced in 1.11.0 most likely.

**Further notes**

In case you're wondering why I have two components making the same request in different Suspense wrappers – my app is a  UI for navigating a folder system. There are two components making queries to the project folder system - one in the sidebar which shows the top-level folders all the time, one in the main panel which the user can navigate up and down all levels. Both work fine, unless the user is navigating the top level in the main panel, in which case both components are making the same query and the sidebar will not load on page load.

**Comment by kitten** [comment]
We've actually recently started talking to the React team to make our implementation more idiomatic according to the constraints they envision for Suspense in the future.

For the meantime, we have an "in-between" branch that follows the expected structure of a new suspense-supporting hook, but not fully. If you're willing to beta test it the PR is here: https://github.com/FormidableLabs/urql/pull/1335

In there you'll find a CodeSandbox CI check that links pre-built packages. If you create a resolution for `"urql"` in your `package.JSON` set to the linked package from CodeSandbox CI you can already try it out.

I've tested it against your sandbox and it does seem to work fine. I'm still trying to figure out whether it breaks any of the old edge cases and what the breaking changes may be.

**Comment by rmmr** [comment]
@kitten I can confirm this new branch fixes numerous issues I had with suspense (in concurrent mode). Looks great!
