### ISSUE TITLE
(svelte) - process is not defined (Routify dev env)

### ISSUE THREAD

**Issue by armchair-traveller** [FormidableLabs/urql#1333]
```javascript
node_modules/@urql/s…urql-svelte.mjs:223 Uncaught (in promise) ReferenceError: process is not defined
    at eval (node_modules/@urql/s…urql-svelte.mjs:223)
    at Object.__impl (index.js:2028)
    at executeModuleImpl (main.js:184)
    at resolve_module (main.js:231)
    at main.js:225
    at Array.forEach (<anonymous>)
    at resolve_module (main.js:214)
    at _require (main.js:240)
    at cb (main.js:200)
```

I tried using urql with the default Routify starter template (https://github.com/roxiness/routify-starter)

Import setClient in any Svelte file and the error crashes the entire app.

urql versions: "@urql/svelte": "^1.1.4"

I think there were a couple related issues to this one, but following the replace... didn't seem to do anything for me? Is it because Routify has a simulated browser env? Help is appreciated, if it's something already answered please point me in the right direction. Thanks.

**Comment by JoviDeCroock** [comment]
Hey,

Just for clarity, you've tried adding [`rollup-plugin-replace`](https://www.npmjs.com/package/@rollup/plugin-replace) and added this to the rollup config as one of the first items?

```
    replace({
      'process.env.NODE_ENV': JSON.stringify('production')
    })
```

**Comment by armchair-traveller** [comment]
Thanks for the quick response! It turns out I must have been configuring it incorrectly somehow because that solution works on my other machine.
