### ISSUE TITLE
requestPolicyExchange upgrade does not result in network request

### ISSUE THREAD

**Issue by stefanaxelsson** [FormidableLabs/urql#1334]
A query that is upgraded to cache-and-network using requestPolicyExchange does not result in a network request.

urql version & exchanges:
urql: 1.11.5
next-urql: 2.2.0
@urql/exchange-request-policy: 0.1.0

**Steps to reproduce**
Clone: https://github.com/stefanaxelsson/urql/tree/main/packages/next-urql/examples/2-with-_app.js

The pokemon endpoint seems to be down so the endpoint and query have to be updated:
1. Set url in _app.tsx
2. Update query in pokemon_list.tsx

Steps:
1. Start app
2. Click link about. Wait 5+ seconds
3. Click link Start

**Expected behavior**
A new network request to be made since the cache is stale and the request-policy has been upgraded to cache-and-network

**Actual behavior**
No new network request is made.

**Comment by stefanaxelsson** [comment]
**Sidenote**: requestPolicyExchange also upgrades teardowns. Not sure if this is expected or not.

**Comment by brummelte** [comment]
I am now using the following versions:

"urql": "^2.0.3"
"@urql/core": "^2.1.1"
"@urql/exchange-request-policy": "^0.1.2"

I still can't seem to get a new network request to be made.

It seems the `shouldUpgrade` function is being called at the right times. And I return `true` from it. But it still does not result in a new network request.

**Comment by brummelte** [comment]
@kitten can this issue be reopened or am I doing something incorrectly?

**Comment by kitten** [comment]
@brummelte No, since you've already opened a new issue 😅 This is entirely unrelated and as a rule, I'd never open an old issue that's been addressed since the context of an issue always changes after it's closed

**Comment by brummelte** [comment]
I think you've misunderstood me. I did not write about the other issue here on purpose.

I have two issues. One is no network request being made (https://github.com/FormidableLabs/urql/issues/1334#issuecomment-839669958), and one is the cache being based on the wrong timestamp (#1636).

But I think this problem here is still not addressed. But if you want I can also create a third ticket for that.
