### ISSUE TITLE
cacheExchange update Mutation not working

### ISSUE THREAD

**Issue by jdgamble555** [FormidableLabs/urql#1352]
I cannot get the **cacheExchange update Mutation** to trigger.  I can get the **cacheExchange update Subscription** to trigger with no problems:

**urql version & exchanges:**

urlql - 1.11.6
svelte - 3.31.0
slash dgraph - 20.11

**Steps to reproduce:**
___

**querys.ts**
```typescript
export const GET_TASKS = gql`
  subscription GET_TASKS {
    queryTask {
      id
      title
      completed
      user {
        username
      }
    }
  }
`;

export const ADD_TASK = gql`
  mutation addTask($task: AddTaskInput!) {
    addTask(input: [$task]) {
      task {
        id
        title
        completed
        user {
          username
        }
      }
    }
  }
`;
```
**todo.svelte**
```typescript
import { ADD_TASK, GET_TASKS } from "./queries";
...
const getTasks = operationStore(GET_TASKS);
const addTask = mutation(operationStore(ADD_TASK));
subscription(getTasks);
...
function add() {
    try {
      addTask({
        task: {
          title: text,
          completed: false,
          user: { username: user?.email },
        },
      });
    } catch (e: any) {
      console.log(e);
    }
  }
```
**cacheExchange**

```typescript
const cache = cacheExchange({
  updates: {
    Subscription: {
      queryTask: (result, args, cache, info) => {
        console.log("subscription: queryTask");
      }
    },
    Mutation: {
      addTask: (result, args, cache, info) => {
        console.log("mutation: addTask");
      }
    }
  },
});
```
The actual **add** mutation function and the **query** subscription work fine as expected.  No problem with regular functionality.  

However, the **subscription** prints ```"subscription: queryTask"``` to the console every time there is a subscription update query (perfect), but I cannot get **addTask** to print ```"mutation: addTask"``` to the console when there is an add mutation.  It does not seem to run.  This is important for some functions I want to write.  Again, the data is added correctly to the database.

**Expected behavior:**

print ```"mutation: addTask"``` to the console when **addTask** is run.

**Actual behavior:**

**update - Subscription** is printed to the console correctly during a subscription **queryTask** update while **update - Mutation** is not printed correctly to the console when there is an **addTask** mutation from the code in the **cacheExchange** object.

**Comment by kitten** [comment]
Have you checked the following:

- Are there warnings in the console about anything that Graphcache raises?
- Does the network tab send the mutation as expected?
- Is the mutation erroring out or not delivering the results?
- Have you tried adding the `debugExchange` to see whether the mutation is sent?

**Comment by jdgamble555** [comment]
1.) No, there are no warnings in the console, everything works as normal.
2.) Yes, it sends the mutation.  As I said, it **IS** added to the database correctly using the mutation.
3.) The mutation **addTasks** works perfectly fine, but the **cacheExchange** -> **updates** -> **Mutation** -> **addTasks** does not get triggered.
4.) I just added **debugExchange** and as expected, the subscription query is displayed in the console, but the mutation is never  displayed in the console.  Again, the mutation does work correctly and the items are added to the database correctly.

**Comment by jdgamble555** [comment]
Got it working.  I had to get rid of this:

```typescript
exchanges: [
   ...defaultExchanges,  // <-- had to get rid of this line...
   cache,
   ...
]
```

Thank you!

J

**Comment by kitten** [comment]
Ah yea, the `defaultExchanges` include three ones: `dedupExchange`, `cacheExchange` (the default one), and `fetchExchange`, so if you're replacing the document cache with Graphcache then the first and last exchanges will have to be passed manually in that order 👍
