### ISSUE TITLE
Clarify custom updates docs

### ISSUE THREAD

**Issue by earksiinni** [FormidableLabs/urql#1359]
[The page on custom updates](https://formidable.com/open-source/urql/docs/graphcache/custom-updates) cites examples of calling methods on `cache` to perform custom updates. However, the examples are inconsistent.

[Here](https://formidable.com/open-source/urql/docs/graphcache/custom-updates/#cacheupdatequery), there are two `cache`'s, an outer one referring to the exchange and an inner one referring to the exchange's store:

```
const TodosQuery = gql`
  query {
    __typename
    todos {
      __typename
      id
      text
      complete
    }
  }
`;

const cache = cacheExchange({
  updates: {
    Mutation: {
      addTodo: (result, args, cache, info) => {
        cache.updateQuery({ query: TodosQuery }, data => {
          data.todos.push(result.addTodo);
          return data;
        });
      },
    },
  },
});
```

[Here](https://formidable.com/open-source/urql/docs/graphcache/custom-updates/#cachewritefragment), there's just one `cache` provided without context:

```
import { gql } from '@urql/core';

cache.writeFragment(
  gql`
    fragment _ on Todo {
      id
      text
    }
  `,
  {
    id: '1',
    text: 'update',
  }
);
```

I hadn't seen the second "inner" `cache` in the prior example, which is provided by a resolver function, and spent about 3 hours trying to figure out how to call `writeFragment` on the first "outer" `cache` (e.g., the exchange), parsing minified code, attempting to divine urql's build system...☹️ I would change the first `cache` to `exchange` to avoid confusion.

Also, the docs for that page abruptly jump into the nitty gritty details of how Graphcache performs updates without giving enough context about how the general philosophy. For example, the intro states:

> Every time Graphcache sees a result from the API for a subscription or a mutation it will look at the response and traverse it. This process is the same as for queries but instead of starting at the Query root type, it will start searching for keyable entities, where an object's __typename and id or _id fields (or a custom keys config) are provided, so it can write normalized entities to the cache.

This intro (and more generally the entire page) presupposes knowledge of a few basic concepts. I'm not sure that any of these are correct, this is just what I'm able to infer from the current docs:

- Any imperative/custom update to the store _must_ be initiated by a mutation (an explanation of why this design choice was made would be helpful)
- A custom update therefore _must_ be effected through a mutation resolver that prevents the mutation from being sent to the server and allows for a custom local update on the store to be performed instead
- The store, which is a part of the exchange, _can only_ be updated using GraphQL (but in an ad hoc, urql-specific way that should be clarified separately for each update method since the GraphQL bits used in the examples don't look like normal mutations; the nitty gritty details about traversal in the intro could form part--but not all--of this explanation)
- The store _can only_ be accessed through a mutation resolver (an explanation of why this design choice was made would be helpful)

It would be really helpful if these concepts could be explicitly explained on the custom updates page before diving into the API and examples. I think that the second paragraph ("Instead, we may use the updates configuration to set up manual updates that react to mutations or subscriptions") sort of gets at part of what I've written here, it just needs to be expanded upon.

urql version & exchanges: N/A, Graphcache

**Comment by earksiinni** [comment]
Another thing that would be good to clarify is whether it's possible to do any arbitrary update to the cache or whether the custom update absolutely must be a side effect to a mutation already supported by the schema. I have a situation where I'm fetching search results from a third-party service and want to normalize those results into Graphcache, all inside the browser. I don't want to hit the server at all, yet the custom updates section makes it seem like that's what I need to do.

(If someone could help me here, I'd appreciate it. This is the question that started me down this path.)

**Comment by JoviDeCroock** [comment]
Hey,

We aim to have graphCache be a representation of your server-side state, this makes a lot of cases more deterministic, hence why we _don't_ allow cache updates outside of mutations/subscriptions.

My advice most often would be to write this inside these transformations inside of React-land, this way the data will keep representing the query.

If the transformation is just a data-formatter or something you could use the `resolvers` API.

**Comment by earksiinni** [comment]
@JoviDeCroock 

> We aim to have graphCache be a representation of your server-side state, this makes a lot of cases more deterministic, hence why we don't allow cache updates outside of mutations/subscriptions.

This makes sense, thank you. Would be great for that to be included in the docs :+1:. I'm not sure that I agree with it but I appreciate the design choice. Personally, I'd rather have an escape hatch, if it would be simple to build, with some kind of scary name like `unsafeCustomUpdate`.

> My advice most often would be to write this inside these transformations inside of React-land, this way the data will keep representing the query.
>
> If the transformation is just a data-formatter or something you could use the `resolvers` API.

Could you please clarify? I'm not sure what you mean by "transformations," I'm looking to take data coming from an external service and store it in a way that the rest of my app can access it using urql. I assume that transformation would be involved to make it fit a shape that urql can understand, but the confusing part is how to get it into the store, not how to perform the transform. Sounds like from your previous comment that this use case is intentionally unsupported and discouraged.

Also, `resolvers` formats data coming from the GraphQL endpoint on my server, no? But my data is coming from a third-party service.

**Comment by kitten** [comment]
@earksiinni Sorry, I haven't checked in here earlier. How do you find the new intro and cache update pages?

- https://formidable.com/open-source/urql/docs/graphcache/normalized-caching/
- https://formidable.com/open-source/urql/docs/graphcache/cache-updates/
