### ISSUE TITLE
Incorrect package in execute-exchange docs

### ISSUE THREAD

**Issue by earksiinni** [FormidableLabs/urql#1360]
[The docs for the execute exchange](https://formidable.com/open-source/urql/docs/api/execute-exchange/) provide these installation instructions:

```
yarn add @urql/exchange-retry
# or
npm install --save @urql/exchange-retry
```

Naturally, it should be:

```
yarn add @urql/exchange-execute
# or
npm install --save @urql/exchange-execute
```

**Comment by JoviDeCroock** [comment]
Fixed in https://github.com/FormidableLabs/urql/commit/4df11e0ea660eb5762aaf67b5fdc882dad686a3d
