### ISSUE TITLE
`data` empty after reloading a Next.js page with `getStaticProps`

### ISSUE THREAD

**Issue by gopeter** [FormidableLabs/urql#1363]
I'm trying to build a website with Next.js and urql, but got stucked because of a strange SSR issue.
If I start the Next.js dev server the first time or if I make changes to the code and refresh the page, everything is fine. But once I reload the page again, my data, fetched by urql, is lost.

**urql version & exchanges:**

```
  "dependencies": {
    "@urql/exchange-graphcache": "^3.4.0",
    "classnames": "2.2.6",
    "date-fns": "2.14.0",
    "graphql": "^15.5.0",
    "graphql.macro": "^1.4.2",
    "interweave": "^12.7.0",
    "next": "latest",
    "next-urql": "^2.2.0",
    "react": "^17.0.1",
    "react-dom": "^16.13.1",
    "react-is": "^17.0.1",
    "styled-components": "^5.2.1",
    "urql": "^1.11.6"
  },
```

**Example:**

```tsx
// frontend/src/pages/index.tsx
import { GetStaticProps, NextPage } from 'next'
import { useRouter } from 'next/router'
import Head from 'next/head'
import { withUrqlClient } from 'next-urql'

import { Container, Layout, Loading } from '@frontend/components'
import { GetHomepageDocument, useGetHomepageQuery } from '@frontend/queries'
import { createClient, urqlClientConfig } from '@frontend/store'

interface Props {
  preview?: boolean
}

const Homepage: NextPage<Props, Props> = ({ preview }) => {
  const router = useRouter()
  const [{ data }] = useGetHomepageQuery()

  if (router.isFallback) return <Loading />
  const { page, pages } = data

  return (
    <Layout preview={preview ?? false}>
      <Container>
        <article>
          <Head>
            <title>{page.title}</title>
          </Head>

          Title: {page.title}
        </article>
      </Container>
    </Layout>
  )
}

export const getStaticProps: GetStaticProps = async ({ preview = false }) => {
  const { client, ssrCache } = createClient()
  await client.query(GetHomepageDocument).toPromise()

  return {
    props: {
      urqlState: ssrCache.extractData(),
      preview,
    },
  }
}

export default withUrqlClient(() => urqlClientConfig, { ssr: false })(Homepage)

```

When I open the page the first time, I get the right result:

![grafik](https://user-images.githubusercontent.com/1242960/106798927-f0edb000-665e-11eb-9ad9-d034be0efbc6.png)

But reloading the page leads to:

![grafik](https://user-images.githubusercontent.com/1242960/106799019-095dca80-665f-11eb-81ef-10f419f51ee2.png)

That's my client config:

```tsx
export const urqlClientConfig = { url: 'https://project.dev:8843/wp/graphql' }

export function createClient() {
  const ssrCache = ssrExchange({ isClient: false })
  const client = initUrqlClient(
    {
      url: urqlClientConfig.url,
      exchanges: [dedupExchange, cacheExchange({}), ssrCache, fetchExchange],
    },
    false,
  )

  // client won't be null ...
  return { client: client as Client, ssrCache }
}
```

This happens just in Next.js' `dev` mode. Building the page and running it on production works fine.

As far as I understand, `data` in `useQuery` should never be `undefined`, since urql's cache was pre-populated during the server side rendering. I've followed the [official docs](https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#nextjs), but maybe I've overlooked something?

For now I'm just returning an empty div as long as `data` is undefined:

```
...
  const router = useRouter()
  const [{ data }] = useGetHomepageQuery()

  if (router.isFallback) return <Loading />
  if (!data) return <div />

  const { page, pages } = data
...
```

But I would prefer to get it to work as it's meant 😄

**Comment by JoviDeCroock** [comment]
When you do a hard-reload sometimes Next doesn't run `getStaticProps` again, in that case `result.fetching` is true.

**Comment by gopeter** [comment]
Oh ... but I've added a `console.log` to my `getStaticProps`, and it fires every time:

![grafik](https://user-images.githubusercontent.com/1242960/106804310-88560180-6665-11eb-92dc-d81c5c5fffee.png)

![grafik](https://user-images.githubusercontent.com/1242960/106804280-7e340300-6665-11eb-9921-0a842fe90f30.png)

**Comment by JoviDeCroock** [comment]
oh odd, maybe the client in the getStaticProps is different from the one we use in the  render-cycle I guess

**Comment by gopeter** [comment]
Hmmmm. Is there something I can do/test/provide?

**Comment by JoviDeCroock** [comment]
A codesandbox would be neat, can look into it later tonight or tomorrow.

**Comment by gopeter** [comment]
Am I able to run next in dev mode in Codesandboxes?

**Comment by JoviDeCroock** [comment]
It always runs in next dev mode

**Comment by gopeter** [comment]
I've forked a Codesandbox from you and it happend immediatley 😂 🙈 

<img width="1792" alt="grafik" src="https://user-images.githubusercontent.com/1242960/106805905-9016a580-6667-11eb-9d80-ea401e4f163c.png">

https://codesandbox.io/s/relaxed-kirch-oj6xd?file=/pages/index.js

**Comment by JoviDeCroock** [comment]
I never see getStaticProps being called though for me https://codesandbox.io/s/zealous-leaf-6bjj2?file=/pages/index.js

**Comment by JoviDeCroock** [comment]
That's cause the server isn't starting :p https://3k1nq.sse.codesandbox.io/ api sandbox

https://codesandbox.io/s/zealous-leaf-6bjj2?file=/pages/index.js:288-317

**Comment by gopeter** [comment]
Hmmmm I've created a [new example](https://codesandbox.io/s/relaxed-kirch-oj6xd?file=/pages/index.js), but can't reproduce it there.

**Comment by gopeter** [comment]
Oh wow ... here's an example where I was able to reproduce it: https://codesandbox.io/s/broken-fire-hhcvf?file=/pages/index.js

```tsx
export default withUrqlClient(
  (ssr) => (urqlClientConfig),
  { ssr: false }
)(Launches);
```

This one breaks the refresh.

It should be ...

```tsx
export default withUrqlClient(
  (ssr) => ({
    url: urqlClientConfig.url
  }),
  { ssr: false }
)(Launches);
```

**Comment by JoviDeCroock** [comment]
Yeah that makes sense, you need to create a new client for fast-refresh to pick up stuff correctly.

**Comment by gopeter** [comment]
Ok, thanks for your support! 😊

**Comment by midnightgamer** [comment]
Facing same issue
