### ISSUE TITLE
RFC: Stale to be "true" if any background fetching is happening

### ISSUE THREAD

**Issue by kmrachko** [FormidableLabs/urql#1372]
## Summary

Stale to be "true" if any background fetching is happening

## Proposed Solution

Hey!

First of all, thanks for the awesome library. Currently, I lead a team that migrates big application from Apollo to urql, and I have very high hopes that this is a correct decision.

Most of our needs are covered by what urql has to offer at the moment, except for one. Comparing to Apollo, urql provides very limited information about current state of the rendered query (e.g. **networkStatus**). I've carefully read reasoning in this [thread](https://github.com/FormidableLabs/urql/issues/417), and can definitely see the logic in an overall strategy, however few details are messing the whole picture for me right now.

Our app mostly consists of different tables with data. User can view them, and modify / delete any row using dropdown menu. When that happens, we run delete mutation, invalidate deleted entity in the cache using `cache.invalidate` in updater, and wait for query that populates the table to be refetched.

Unfortunately, I have not found a way to us to know if that query is refetched. You may suggest for us to not only invalidate an entity, but also update query result in cache manually, but in our case we can't make that due to side-effects on delete. The easiest & safest way would to just show kind of "Syncing..." status in the table until data is freshly fetched.

Same goes for cases when variables change. Often we have a header in the table with range picker or toggles that modify query variables. Query can take few seconds to resolve after change, and whole this time users has no visual feedback to their actions.

I think it can be handled (probably) by custom hooks, maybe exchanges and stuff like that... But from what I see now, this library aims to become a real competitor for Apollo. However, in my opinion, it will not happen until such fundamental functionality has to be hacked around (sorry if I sound rude).

 
## Requirements

I agree that `fetching` flag should only be responsible for explicitly called action.

So it will be only logical that `stale` flag should indicate _staleness of the data_ - which is by dictionary definition **stale** in case query variables change or data becomes invalidated in the cache manually. That way, it would be explicit & straightforward - you will always know if the query is being refetched if you need that info, if no - you just use `fetching`.

**Comment by kitten** [comment]
I think you're completely right. While there are ways to work around this there are also cases where none of the Client/exchanges pipeline took responsibility for emitting a stale flagged result which leads to inconsistencies.

I've got an initial PR up that aims to get this fixed

**Comment by kmrachko** [comment]
Thanks for such quick response and implementation!

> This will always cause the bindings to set fetching: true.

For some reason I didn't think to check that. You are completely right.

> ... but urql is not copying approaches here from either Relay or Apollo but we approach every problem from first principles.

That's a really good approach, and I think that's exactly what makes you better - an opportunity to see what's working best and what doesn't, and make a right decision.

Wish you best luck.

**Comment by kitten** [comment]
@kmrachko On a side note, this change has been merged and much more trivial than expected. So you'll see it go out today (if all goes well) as part of a much larger release batch.

**Comment by kitten** [comment]
Alright, this has indeed gone out with the release batch today. Let me know if you have any further questions about this! 🙌 I'll leave another note on the other RFC
