### ISSUE TITLE
RFC: Allow root types override without Schema Awareness

### ISSUE THREAD

**Issue by kmrachko** [FormidableLabs/urql#1378]
## Summary

Allow root types override without Schema Awareness

## Proposed Solution

In our GraphQL schema we have a type called Subscription. It is not a gql subscription, but rather a representation of a certain business entity (we work in the e-commerce domain). It was an aware choice of naming, as there is not planned support for gql subscription in the API.

Unfortunately, every time we fetch something of that type we receive `data=null` and this [error](https://formidable.com/open-source/urql/docs/graphcache/errors/#25-invalid-root-traversal).

We were able to fix that by overriding root subscription type in schema and enabling schema awareness. However, it came with a cost of either running introspection query on each app load (~1-2 secs of blocking load time) or baking it into the `json` file as recommended. Unfortunately, in our case API is developed by independent team, so keeping `schema.json` up to date is a bit of a challenge.

Is it possible to provide an easier way for us to override root subscription type? Guess that can be applied to other root types as well. We do not benefit much from Schema Awareness feature (which is nevertheless great), but instead we have to live with a hustle of providing a valid schema only for the subscription type override.

**Comment by kitten** [comment]
Funny thing! I had a change to get this in sitting around in an old branch and I didn't get to finishing that up because I would have had to write up an RFC 😆

**Comment by kitten** [comment]
This has gone out in the release batch today since it was a pretty straightforward change. Let me know how you get on with this or if you run into any issues with it! 🙌💙

**Comment by kmrachko** [comment]
Hey! It seems to be working perfectly. Thank you very much!
