### ISSUE TITLE
Docs links are broken when *open in a new tab*

### ISSUE THREAD

**Issue by renatorib** [FormidableLabs/urql#1380]
It looks like client-routing is working properly but the _passed href_ isn't correct.

Links like `https://formidable.com/open-source/urql/docs/api/retry-exchange/`
are being shown as `https://formidable.com/open-source/api/retry-exchange/` (missing `/urql/docs` part) 

_PS: I deleted issue template since it's not about library itself. To reproduce, just open docs and click open in a new tab_

**Comment by Kingdutch** [comment]
It appears the base URL is not properly configured when building the docs (I don't know where this happens). For example the console shows the following information.

![afbeelding](https://user-images.githubusercontent.com/327697/107966251-de06a400-6fab-11eb-897c-cc7a783e8a0d.png)
