### ISSUE TITLE
ssr with Angular - fetch

### ISSUE THREAD

**Issue by jdgamble555** [FormidableLabs/urql#1403]
I have been struggling trying to get urql working with SSR in Angular.  Everything works fine with the core module in Angular regularly, however I can't get the query to actually load before the server page is rendered.  After doing some research, it seems this is because **urql** uses **fetch** in the background.

I found [this link](https://apollo-angular.com/docs/performance/server-side-rendering#server-side-rendering) about how **apollo angular** is able to do this.  

I believe if you fix this problem, all you would have to do is write up the documentation and **urql** could officially support Angular, hence a whole new group of users.

(And, of course, Angular uses rxjs 6 Observables...)

Thanks,

J

**Comment by JoviDeCroock** [comment]
You should be able to replace the `fetchExchange` with something that works with Angular.

**Comment by jdgamble555** [comment]
I guess it is not a bug since Angular is not officially supported. :)

Isn't the **fetchExchange** the core code?  How would I even go about doing that?  If I am re-writing the **fetchExchange**, wouldn't that be in effect re-writing how the core of **urql** works?

**Comment by JoviDeCroock** [comment]
No, the `fetchExchange` is an exchange like any other, you can do

```js
const client = createClient({ exchanges: [dedup, cache, yourFetch] })
```

But as I've said you can also try tweaking fetch itself by doing:

```js
const client = createClient({ fetch: () => httpClient })
```

**Comment by kitten** [comment]
Yea, this sounds to me like you'd want to pass `fetch` to the `Client` so that it uses the `HttpClient` instead; it seems that the API is rather compatible? https://angular.io/api/common/http/HttpClient

Apart from this SSR will most likely be identical to React / Preact / Vue in that you'd add an `ssrExchange` to extract data on the server-side and reinject it on the client-side, as detailed here: https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#the-ssr-exchange

**Comment by jdgamble555** [comment]
@kitten - I am not sure what you mean about the timing.  Does it not delay the request in React / Preact / Vue?  
I am an Angular / [Svelte developer](https://github.com/FormidableLabs/urql/discussions/1405) so I am trying to see if I can use this package instead of Apollo for either / or?

Obviously I need SSR because my meta tags, bread crumbs, etc would be generated based on the generated page from the database. I am not sure how this could be accomplished without a Promise.

@JoviDeCroock I see that it is an exchange, but I have no idea how to write an exchange to fetch something.

As for the second part, I am getting this in Visual Code;

So I have this after importing the **HttpClient** module:
```typescript
fetch: async (): Promise<any> => httpclient,
```
and I get this message
```typescript
Type '() => Promise<HttpClient>' is not assignable to type 
'(input: RequestInfo, init?: RequestInit | undefined) => Promise<Response>'.
Type 'Promise<HttpClient>' is not assignable to type 'Promise<Response>'.
Type 'HttpClient' is missing the following properties from type 'Response': 
headers, ok, redirected, status, and 12 more.ts(2322) client.d.ts(12, 5): 
The expected type comes from property 'fetch' which is declared 
here on type 'ClientOptions'
```
So I am thinking I need to obviously input the request, but I am not sure what that is on the **urql** end...

```typescript
fetch: async (some, variables, here?): Promise<any> => httpclient
```
Do I need to input something?  It looks like **httpclient** takes **RequestInfo** which is:

```
Alternatively you can pass an HTTP method as the first parameter, 
a URL string as the second, and an options hash containing the request body as the third...
```

**Comment by kitten** [comment]
What we're saying about `HttpClient` is that you'd have to write a wrapper around it that has the same API as `fetch`; a shim layer basically that just replaces the `fetch` call. Basically the option itself is used for polyfills usually.

**Comment by jdgamble555** [comment]
This seemed to do the trick so far:

```typescript
  constructor(
    @Inject(PLATFORM_ID) platformId: Object,
    private http: HttpClient
  ) {
...

this.client = createClient({
fetch: async (url: any, q: any): Promise<any> => {
  const data = await this.http
    .post(url, { ...JSON.parse(q.body), ...q })
    .toPromise();
  return {
    json: () => data
  };
},

```
@kitten Does `fetchExchange` not delay the request in React / Preact / Vue as well by a micro-tick?

**Comment by kitten** [comment]
Exchanges aren't bindings-specific. So I'm not sure what the question is. My concern here is that clearly Angular attempts to collect pending requests for SSR. However, these requests are started on a delay so I'm not sure how it constructs the time window that it waits for
