### ISSUE TITLE
Session missing from ctx

### ISSUE THREAD

**Issue by trompx** [FormidableLabs/urql#1409]
I'm migrating from react query to urql so I have a working setup.
I'm trying to convert a withAuth hoc, thus using urql directly server side.

```ts
import { ssrExchange } from "urql";

const withAuth = (getServerSidePropsFunc?: Function) => {
  return async (ctx: any) => {
    const redirectUrl = ctx.resolvedUrl;
    const ssrCache = ssrExchange({ isClient: false });
    const urqlClient = getUrqlClientSS(ssrCache, ctx);
    // The request executed here doesn't have access to session, while when doing the request in react-query it does
    const data = await urqlClient?.query(UserDocument).toPromise();

    if (!data?.user) {
        redirect...
    }

    return {
      props: {
        urqlState: ssrCache.extractData(),
      },
    };
  };
};

export default withAuth;
```

```ts
import {
  NextUrqlClientConfig,
  NextUrqlContext,
  NextUrqlPageContext,
  NextUrqlAppContext,
  initUrqlClient,
} from "next-urql";

export const createUrqlClient: NextUrqlClientConfig = (
  ssrExchange: any,
  ctx?: NextUrqlContext
) => {
  return {
    url: "http://localhost:4000/graphql",
    exchanges: [dedupExchange, errorExchange, ssrExchange, fetchExchange]
  }
};

export const getUrqlClientSS = (
  ssrExchange: any,
  ctx?: NextUrqlContext
) => {
  const canEnableSuspense = false;
  return initUrqlClient(createUrqlClient(ssrExchange, ctx), canEnableSuspense);
};
```

```ts
  const apolloServer = new ApolloServer({
    schema,
    context: ({ req, res }: { req: Request; res: Response }) => {
      return {
        req,
        res,
        redis,
      };
    },
  });
```

In apollo server, I set a redis session with express-session. When the request from the hoc with react query is executed, the userId in the `ctx.req.session.userId` is available, with the code above with urql, it is not.

urql version & exchanges:
```
    "@urql/core": "^2.0.0",
    "@urql/devtools": "^2.0.3",
    "@urql/exchange-auth": "^0.1.2",
    "@urql/exchange-graphcache": "^4.0.0",
    "@urql/exchange-multipart-fetch": "^0.1.11",
    "@urql/exchange-persisted-fetch": "^1.3.0",
    "urql": "^2.0.1",
```

**Expected behavior**
Log with react-query:
```
[Node] Session {
[Node]   cookie: {
[Node]     path: '/',
[Node]     _expires: 2031-01-24T20:31:28.765Z,
[Node]     originalMaxAge: 315360000000,
[Node]     httpOnly: true,
[Node]     secure: false,
[Node]     sameSite: 'lax'
[Node]   },
[Node]   userId: 1
[Node] }
```

**Actual behavior**
Log with urql:
```
[Node] Session {
[Node]   cookie: {
[Node]     path: '/',
[Node]     _expires: 2031-02-20T16:38:09.492Z,
[Node]     originalMaxAge: 315360000000,
[Node]     httpOnly: true,
[Node]     sameSite: 'lax',
[Node]     secure: false,
[Node]     domain: undefined
[Node]   }
[Node] }
```
Any idea why the session userId is missing?

**Comment by kitten** [comment]
I'm not sure where you add `userId` but it'll fully depend on where you do that on why it'd show up in certain places and others not. I can't really piece together the entire setup, but I'd suspect you're adding it in some kind of function, e.g. `getInitialProps` which hasn't run by the point you're checking it maybe?

**Comment by trompx** [comment]
Once again thanks for the fast answer, and sorry to have made you spend time on this.
I found the issue, I totally forgot to pass the cookies to the fetchOptions headers when doing multiple config tests.

Just one question, when declaring a getServerSideProps method in a page, do I have to force ssr: false so it does not wrap it with getInitialProps or it is set to false as default?
Because [on your doc](https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#nextjs), it is written:

> This can be explicitly enabled by passing the { ssr: true } option as a second argument to withUrqlClient

which suggests that it is set to false as default, and just a little bit after :

> { ssr: false } // Important so we don't wrap our component in getInitialProps

whch suggests the opposite and leads to confusion. What is the default?

So with a hoc, should it be `withUrqlClient(createUrqlClient, { ssr: false })(withAuth(Index))`?

**Comment by JoviDeCroock** [comment]
Hey,

We've changed the default to be `{ ssr: false }` if you want to use `getInitialProps` and by extension `react-ssr-prepass` to resolve `useQuery` calls on the server you need `{ ssr: true }`, if you want to utilize the `getXProps` methods then you can leave it as is.

**Comment by trompx** [comment]
Thanks for the clarification @JoviDeCroock!
I was wondering how without declaring getServerSideProps and just setting ssr: true, it was possible to execute the query server side.
So ssr: true -> activate react-ssr-prepass which detects all promises and resolve them on the server.
So it means I could protect a route with a simple useIsAuth hook on the client side + withUrqlClient ssr true === getting the auth user in getXProps with ssr false? If that so, it's awesome

**Comment by JoviDeCroock** [comment]
Exactly yes, if `ssr: true` is on then it will resolve promises on the server and you can use these on the client. _do note_ that effects aren't ran on the server so you can't react to this unauthed within an effect.

**Comment by trompx** [comment]
You mean useEffect? I still can do something like:
```
const [{data}] = useUserQuery()
if(!data.user) {
   redirect(...)
}
```
If yes that's fine, otherwise I'll just redirect directly server side.
