### ISSUE TITLE
pollInterval replacement means fetching=true for refetches.

### ISSUE THREAD

**Issue by bobbyrenwick** [FormidableLabs/urql#1410]
urql version & exchanges: 2.0.1

**Steps to reproduce**

1.

Implement a polling query as per https://github.com/FormidableLabs/urql/pull/1374

```tsx
const [result, executeQuery] = useQuery(...);

useEffect(() => {
  if (!result.fetching) {
    const id = setTimeout(() => executeQuery({ requestPolicy: 'network-only' }), 5000);
    return () => clearTimeout(id);
  }
}, [result.fetching, executeQuery]);
```

**Expected behavior**
`result.fetching` should be true only when the `query` or `variables` change, not during a refetch.

**Actual behavior**
Because of `requestPolicy: "network-only"` it means that refetches will have `fetching: true`. Previously the idea was that any refetches would be "internal" behaviour and most use cases only want to know about the state of the first poll for that query/variable combo.

Is this the new intended behaviour? If so how do I now accurately identify the state where it's fetching for the first time for a query/variable combination?

**Comment by kitten** [comment]
I know this is a bit different from before but it's intentional. When you trigger a refetch then you actively set `fetching`. However, you shouldn't lose access to the previous state, so as long as you have `data` you can keep rendering it. Alternatively, it's also possible to invoke a hook with `cache-only` and then pair that with `client.query(...)` for manual fetches which then only manipulates `stale`.

**Comment by bobbyrenwick** [comment]
I'd like to lose the previous state in the case that the variables change. Before I was using `fetching` as a way to show a loading screen only when variables change, as the view no longer makes sense if you show the stale data. I guess I can have a `key` on the component but then that seems a little leaky as you'll have to know the variables the component is going to use, above the component.

**Comment by kitten** [comment]
That's a solution but as said, you can also use a hook that doesn't fetch with an imperative call to the client.

I'll close this for now, but in general the imperative calls are often what can help in this case

**Comment by bobbyrenwick** [comment]
Thanks for the pointers @kitten, I'll try an imperative approach and see where I get to!

**Comment by bobbyrenwick** [comment]
I had a look at the size of `useQuery`'s internals and got a little spooked, so I've ended up with the following approach instead.

```tsx
const usePollingQuery = (args) {
    const [result, executeQuery] = useQuery(...);

    useEffect(() => {
    if (!result.fetching) {
        const id = setTimeout(() => executeQuery({ requestPolicy: 'network-only', isPolling: true  }), 5000);
        return () => clearTimeout(id);
    }
    }, [result.fetching, executeQuery]);

    return [
        {
            ...result,
            fetching: result.fetching && (!result.operation || !result.operation.context.isPolling),
        },
        executeQuery
    ]
}
```

This seems to work for my use case. Maybe something along these lines could be in the upgrade guide for v2?

**Comment by frederikhors** [comment]
@kitten, @JoviDeCroock can we please add a recipes section? Or maybe increase the docs with these examples? What do you think?

**Comment by bobbyrenwick** [comment]
Actually, the code above has issues where it does't quite work because there's a second render where `fetching=true` but the `isPolling` context isn't there.

During the first `fetching`, `context.operation=undefined`, then during the second `fetching` the `context.operation=cache-and-network without isPolling` and during the third it's then got the `isPolling` context. 

Is there an off by one on the `context.operation`, or is that behaving as expeected?

**Comment by frederikhors** [comment]
@bobbyrenwick, urql is a fantastic product. But these little everyday things (used in so many components) drive me crazy! Hence the request for a cheatsheet like https://sveltesociety.dev/cheatsheet or recipes section like https://sveltesociety.dev/recipes.

**Comment by bobbyrenwick** [comment]
@frederikhors, I'm all for the idea of recipes in the docs, especially as this will help with the upgrade from v1 -> v2 for anyone using polling queries that relied on the old loading format. 

I'm guessing it could be additions to the [Common Questions](https://formidable.com/open-source/urql/docs/common-questions/).

**Comment by ethanjweiner** [comment]
For anyone looking for a basic recipe for polling where `fetching == false` for refetches, something like the following should work:

```ts
export const usePollingQuery = <T extends AnyVariables, V>(
  args: UseQueryArgs<T, V>,
  pollInterval: number = 5000,
) => {
  const [result, executeQuery] = useQuery(args);

  // Sets a timeout to poll the query and recreates the timeout after each fetch
  useEffect(() => {
    if (!result.fetching) {
      const timeoutId = setTimeout(() => {
        executeQuery({ requestPolicy: 'network-only' });
      }, pollInterval);
      return () => clearTimeout(timeoutId);
    }
  }, [result.fetching, executeQuery, pollInterval]);

  // If the query already has data, we don't want to show the fetching state
  return [{ ...result, fetching: !result.data && result.fetching }];
};

```
