### ISSUE TITLE
Next js : query executed on server still executes on client despite passing the query results via urqlState 

### ISSUE THREAD

**Issue by trompx** [FormidableLabs/urql#1411]
Not sure if this is a bug, but I could not find the information in the docs.
I have a similar setup to [the one in the doc](https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#using-getstaticprops-or-getserversideprops).

The hoc that queries data in getServerSideProps then passes it as props.
```ts
import { ssrExchange } from "urql";

const withAuth = (getServerSidePropsFunc?: Function) => {
  return async (ctx: any) => {
    const ssrCache = ssrExchange({ isClient: false });
    const urqlClient = getUrqlClientSS(ssrCache, ctx);
    const data = await urqlClient?.query(UserDocument).toPromise();

    if (!data?.user) {
        redirect...
    }

    return {
      props: {
        urqlState: ssrCache.extractData(),
      },
    };
  };
};
```

The page wrapped with the hoc + urql:
```ts
const Index = (props: any) => {
  // urqlState does have all the data from the server query
  console.log(props);
  
  // Querying the same user query still triggers a new graphql request (the urqlState is not used)
  const [{ data, fetching }] = useUserQuery();
  // Querying like that (using the same UserDocument as in the server) triggers a new graphql request too
  // const [{ data, fetching }] = useQuery({ query: MeDocument });

  return (<>Hello world</>);
};

export const getServerSideProps = withAuth();
// withAuthComponent just pass the props from withAuth to Index
export default withUrqlClient(urqlClientConfig, { ssr: false })(withAuthComponent(Index));
```

urql version & exchanges:
```
    "@urql/core": "^2.0.0",
    "@urql/devtools": "^2.0.3",
    "@urql/exchange-auth": "^0.1.2",
    "@urql/exchange-graphcache": "^4.0.0",
    "@urql/exchange-multipart-fetch": "^0.1.11",
    "@urql/exchange-persisted-fetch": "^1.3.0",
    "urql": "^2.0.1",
```

**Expected behavior**
I'd expect the data passed from the server to hydrate the client and that the client side useMeQuery gets its data from the cache.

**Actual behavior**
A new query is executed on the client to get the same data.

Do you have a working example how to pass that initial data with next js?
Are the steps described in [this section of the docs](https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#the-ssr-exchange) also relevant when it comes to next js? It is the only place where it references **initialState** so I'm not sure.

**Comment by JoviDeCroock** [comment]
Hey,

Could you make a reproduction, issues are meant for bugs/discussions for usage issues. Generally this could be due the ssrExchange not used in your wrapper config,... just double checked on codesandbox and caching works well

**Comment by trompx** [comment]
Thanks a lot for the code sample @JoviDeCroock, it helped solving the issue.
Apologize for posting here but looking for information on how to implement that kind of stuff (query in getServerSideProps + hocs) are pretty sparse on the whole github for urql, and sometimes the doc leaves me with doubts, not knowing if this is a bug or an implementation problem.

If I may:
- that would be great if the docs were fully searchable, for example searching for *urqlState* doesn't return anything.
- implementation of ssr with urql + next.js were a bit confusing, the examples in the react-urql packages [here](https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/examples/3-ssr-with-nextjs/pages/index.js) and the one in the next-urql packages [here](https://github.com/FormidableLabs/urql/blob/main/packages/next-urql/examples/1-with-urql-client/pages/index.tsx) implement I guess the same pattern (but some using the next-urql package and the other having an hardcoded with-urql-client.js with a different codebase). When starting with urql and looking for best practices, it can be confusing.

Anyway thanks for your work on urql!

**Comment by bobevsky** [comment]
@JoviDeCroock I am experiencing this same issue, NextJS executes the graphql calls on the server and the client as well, making the ajax calls on every page load (instead of on build time). I followed the urql docs and the codesandbox above but no help.
