### ISSUE TITLE
(vue) - Promisified useQuery deadlocks or fails to update fetching

### ISSUE THREAD

**Issue by tjk** [FormidableLabs/urql#1429]
(I will try to put together a repro maybe tomorrow)

- @urql/core@2.0.0
- @urql/vue@0.3.0
- exchanges: dedupExchange, cacheExchange, ssrExchange, fetchExchange
- requestPolicy: tried both default and "cache-and-network"

**Steps to reproduce**

- pass initialState to ssrExchange
- await useQuery in async setup

**Expected behavior**

Expect useQuery to resolve immediately (and then depending on requestPolicy, maybe refreshing)

**Actual behavior**

`await useQuery(...)` hangs forever, async setup never resolves, and the component never hydrates.

**Comment by tjk** [comment]
Not sure I can repro at the moment so just closing. If I notice this again will re-open and add more info. Sorry.

**Comment by kitten** [comment]
@tjk No worries, we're aiming to have more examples ready soon to make sure that we can properly provide resources to reproduce issues across all bindings

**Comment by tjk** [comment]
I think I've been able to reproduce this. Could you please check out my repro and see if I'm doing something wrong? Thanks!

https://github.com/tjk/urql-vue-ssr-issue

**Comment by tjk** [comment]
@kitten friendly bump (don't want to rush you but wanted to make sure you didn't miss this)

**Comment by alaarihan** [comment]
I have the same issue, I tried it in SPA mode ( no SSR ), await hangs forever when I visit the route the second time, it just work fine in the first time.

**Comment by casret** [comment]
I noticed that the promise didn't resolve correctly when the request had finished executing before you `await` it.  (Either because like in @tjk case the data was already in the ssr cache, or if you were doing other work between the useQuery call and the eventual await).  I couldn't quite grok how all the wonka pipelines work, but this patch seemed to help, and maybe can help isolate the issue?

```
diff --git a/packages/vue-urql/src/useQuery.ts b/packages/vue-urql/src/useQuery.ts
index cdf0305f..8d2e266d 100644
--- a/packages/vue-urql/src/useQuery.ts
+++ b/packages/vue-urql/src/useQuery.ts
@@ -223,13 +223,14 @@ export function callUseQuery<T = any, V = object>(
   const response: UseQueryResponse<T, V> = {
     ...state,
     then(onFulfilled, onRejected) {
-      return pipe(
+      const promise = data.value ? Promise.resolve(state) : pipe(
         source.value,
         switchAll,
         map(getState),
         take(1),
         toPromise
-      ).then(onFulfilled, onRejected);
+      )
+      return promise.then(onFulfilled, onRejected);
     },
   };
```

**Comment by tjk** [comment]
Please see https://github.com/tjk/urql/tree/vue-urql-ssr-issue for a repro of the issue -- `onStart` is called after `onPush`:

```
tjk@DESKTOP-MUHHEFH:~/src/github.com/tjk/urql$ yarn jest packages/vue-urql/src/useQuery.test.ts
yarn run v1.22.5
$ /home/tjk/src/github.com/tjk/urql/node_modules/.bin/jest packages/vue-urql/src/useQuery.test.ts
  console.log
    onPush

      at Object.<anonymous> (../../node_modules/jest-mock/build/index.js:845:25)

  console.log
    onStart

      at Object.<anonymous> (../../node_modules/jest-mock/build/index.js:845:25)

  console.log
    result.data.value { user: { name: 'Clive' } }

      at Object.<anonymous> (../../node_modules/jest-mock/build/index.js:845:25)

  console.log
    result.fetching.value true

      at Object.<anonymous> (../../node_modules/jest-mock/build/index.js:845:25)

 FAIL  packages/vue-urql/src/useQuery.test.ts (5.265 s)
  useQuery
    ✕ runs queries as a promise-like that resolves (with ssr initialState) (5012 ms)

  ● useQuery › runs queries as a promise-like that resolves (with ssr initialState)

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      34 |
      35 | describe('useQuery', () => {
    > 36 |   it('runs queries as a promise-like that resolves (with ssr initialState)', async () => {
         |   ^
      37 |     const useQueryInput = {...queryGql}
      38 |     delete useQueryInput.key
      39 |     const result = useQuery(useQueryInput)

      at new Spec (../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/useQuery.test.ts:36:3)
      at Object.<anonymous> (src/useQuery.test.ts:35:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        5.574 s, estimated 6 s
Ran all test suites matching /packages\/vue-urql\/src\/useQuery.test.ts/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by tjk** [comment]
PS: Just forcing the `onStart` callback to run before `onPush` in the `next.value` `query$` does *NOT* solve the issue --

```node
let onStartCalled = false;
const doOnStart = () => {
  if (onStartCalled) return;
  onStartCalled = true;
  fetching.value = true;
  stale.value = false;
}
const query$ = pipe(
  value
    ? pipe(
        value,
        onStart(doOnStart),
        onPush(res => {
          doOnStart()
          data.value = res.data;
          stale.value = !!res.stale;
          fetching.value = false;
          error.value = res.error;
          operation.value = res.operation;
          extensions.value = res.extensions;
        }),
        share
      )
    : fromValue(undefined),
  onEnd(() => {
    fetching.value = false;
    stale.value = false;
  })
);
```

**Comment by viztor** [comment]
Ran into the same issue without SSR when I tried to access the same route the second time. It doesn't resolve, a guess would be that since the data is in cache, a request was never made, hence no return for await.

**Comment by viztor** [comment]
This could be related to and under the hood might be the same issue as #1734

**Comment by kitten** [comment]
It's currently extremely hard to pinpoint this issue as I haven't been able to reproduce it in an artifical unit test of ours, here: https://github.com/FormidableLabs/urql/blob/b5c6166699ed19a31df5ecc164c8d1da2d36b9fc/packages/vue-urql/src/useQuery.test.ts#L60-L74 I tried to remove the delay but that didn't really help.

In the meantime I've started a simplified `useQuery` implementation but I'll have to test this: https://github.com/FormidableLabs/urql/tree/fix/vue-suspense-deadlock

@tjk: I'll follow up on what this does in your repro at https://github.com/tjk/urql-vue-ssr-issue and will report back on that. Haven't really gotten to the testing phase just yet. I do see that you reproduced this with the latest `@urql/core` version which is actually excellent. Mostly this means that we just need to figure out the best implementation for `useQuery`. However, this has gotten much easier in `@urql/core@2.1.0` as we there don't need to worry about the potentially duplicate subscription. Either way, the current implementation on `main` is a little too convoluted.

**Comment by viztor** [comment]
> It's currently extremely hard to pinpoint this issue as I haven't been able to reproduce it in an artifical unit test of ours, [here](https://github.com/FormidableLabs/urql/blob/b5c6166699ed19a31df5ecc164c8d1da2d36b9fc/packages/vue-urql/src/useQuery.test.ts#L60-L74). I tried to remove the delay but that didn't really help and I still don't quite have a minimal reproduction in unit tests.
> 
> In the meantime I've started a simplified `useQuery` implementation but I'll have to test this: https://github.com/FormidableLabs/urql/tree/fix/vue-suspense-deadlock
> 
> @tjk: I'll follow up on what this does in your repro at https://github.com/tjk/urql-vue-ssr-issue and will report back on that. Haven't really gotten to the testing phase just yet. I do see that you reproduced this with the latest `@urql/core` version which is actually excellent. Mostly this means that we just need to figure out the best implementation for `useQuery`. However, this has gotten much easier in `@urql/core@2.1.0` as we there don't need to worry about the potentially duplicate subscription. Either way, the current implementation on `main` is a little too convoluted.
> 
> Edit: @tjk, the good news is, this isn't reproducible with the repo above and the new branch. The bad news is, I also can't reproduce the issue as is with your repo 😕

I don't think the issue is with the useQuery where you mocked executeQuery with
`pipe(fromValue({ data: { test: true } }), delay(1)) as any;`
The problem is there seems to be no event in the stream when useQuery was called the second time or as it seems when there is data in the cache.

**Comment by tjk** [comment]
@kitten have you tried running my (hardcoded) test in https://github.com/tjk/urql/tree/vue-urql-ssr-issue with `yarn jest packages/vue-urql/src/useQuery.test.ts`? And what result do you get when you run my repro repo as is?

**Comment by kitten** [comment]
@tjk it's not a reproduction and not relevant unfortunately if I can't reproduce any issues so far; especially with the new implementation on my branch

**Comment by kitten** [comment]
While we don't have a reproduction to check this, there's a good chance that `@urql/vue@0.4.2` will fix this

**Comment by pantajoe** [comment]
@kitten I encountered the same issue with the following versions:

- `@urql/vue@0.6.3`
- `@urql/core@2.4.4`
- `vue@3.2.33`

I also used the Vue `<suspense>` feature, so I awaited the `useQuery` composable in my `setup` function together with the SSR exchange from urql.
However, as soon as I set `staleWhileRevalidate` to `false` or `undefined`, the awaited `useQuery` was resolved. So, it seems to me as `staleWhileRevalidate: true` causes the `useQuery` composable to not be resolved at all.

To clarify this only occurred on the production build, i.e., I statically generated the production bundle with a Vue SSR app, and then on the client, the statically generated html shows, but then the page goes blank (i.e., when the vue app is hydrated, and the `useQuery` composable is fired).
