### ISSUE TITLE
Support of onCompleted and onDone on mutations

### ISSUE THREAD

**Issue by homoky** [FormidableLabs/urql#1449]
Hey, 

we are in process of testing urql in comparison to apollo and we are trying to migrate codebase to urql due to better handling of the cache.

I would like to propose adding `onError` and `onCompleted` async functions to mutations. It is really helpful to be able to set those functions right on declaring useHookMutation.

```typescript
const [createTagMutation, createTag] = useCreateTagMutation({
   onCompleted: async () => toast.message("Superior"),
   onError: async () => toast.error("Something went wrong")
});
```

Please let me know what do you think of this approach.

**Comment by kitten** [comment]
You can derive these states from `result.fetching` and `result.error` changing on any of the three hooks. We've received this question before and these callbacks are simply unneeded and lead to very sketchy patterns, as they're often used to break out of React's lifecycles in odd ways which can lead to additional edge cases with React Concurrent Mode and React Suspense, hence we haven't added them.

That being said, for global events an exchange (like the `errorExchange`) are a better choice and locally, at least in React (in others the code is just a little different), an effect is most of the time the preferred and more solid choice.

Hope that makes sense ✌️

**Comment by homoky** [comment]
Thanks. It make sense.
