### ISSUE TITLE
RFC: Support REST and RPC easily and well

### ISSUE THREAD

**Issue by bionicles** [FormidableLabs/urql#1454]
## Summary

URQL has a ton of wonderful features for API clients in general. Just imagine it had nice syntactic sugar for REST apis and RPC calls. Then could use URQL beyond graphql (since graphql requires a server setup, this would enable folks to get started with urql even if they dont have a graphql server). These things are basic and easy compared to graphql; the key advantage of doing them through urql is to integrate with exchanges, caching, etc

## Proposed Solution

It would presumably be pretty handy (and potentially trivial to implement) to enable the user to pass in a custom fetcher function to make REST calls or RPC calls. 

syntactic sugar for standard REST apis:
`urql.post urql.get` etc or just a `fetch` function which works

syntactic sugar for standard json-rpc 2.0
`const remote = urql.rpc(host)`
`const response = await remote.subtract([42, 23])` Proxy trap on `urql.rpc` could just send a standard JSON-RPC 2.0 call ( `POST` `{"jsonrpc": "2.0", "method": "subtract", "params": [42, 23], "id": 1}` to `host`

`const {added, subtracted} = remote.batch(remote => ([remote.add([1,1]), remote.subtract([42, 23])]));`

custom fetcher functions for other uses
`urql.fetch(myFetchFunction)` etc etc?

This would dramatically increase the flexibility of the client, since we could pull data from disparate apis and execute remote functions and then store it in the graphcache and extend it with the exchanges. We could integrate legacy APIs without needing a different client alongside URQL (faster load times!), and pull data from various sources, transform it, and push it to the graphql side with mutations, could make it easy to ETL data from rest to graphql with urql API scraper scripting, even.

 If this can be done with exchanges, I would definitely use a well-implemented and documented REST/RPC client

Just suggest this because, this project looks really cool, and I want to use it, but a bunch of APIs I have to integrate with, are REST, and also I really like JSON-RPC proxy for simplicity of implementation and usage

## Requirements

1. a simple way to make rest api calls and cache them
2. a simple way to make a RPC proxy so RPC calls are just async function methods on the client (arbitrary hosts) batch call could return a list or object with promises

Would you be openminded to give it a try?

**Comment by JoviDeCroock** [comment]
Hey,

Currently `urql` is focussed around GraphQL as it allows us to develop these additional functionalities, a lot of our API docs would be void if we'd be getting these responses through REST/RPC. GraphQL allows us to accurately say we've mutated this type so the query for this type is now invalidated. It allows us to update normalized entities, ...

Integrating REST/RPC into our core would by extension need us to think of ways to accurately convey this information for these protocols which would make the core of this library grow a lot.

However something we could likely do is use an exchange to represent a `REST/...` call as a GraphQL query and handle the logic behind it internally.

Something like:

```js
useQuery({ query: query { todos @rest { id } }})
```

Where the exchange would translate this to the appropriate `REST` request and attach a `__typename` to it.

**Comment by frederikhors** [comment]
@bionicles basically what https://react-query.tanstack.com already does today.

**Comment by kitten** [comment]
I'd imagine the right choice here isn't query annotations but rather a more convenient executable schema implementation that's cheap enough to run client-side, but I'd say that's a little out of scope for us.

But wasn't the Guild building GraphQL Mesh for this purpose?

**Comment by frederikhors** [comment]
I think @bionicles is talking about something like urql NOT ONLY for GraphQL. I asked this too some time ago.

**Comment by kitten** [comment]
@frederikhors i know, but GraphQL is evidently also a client-side technology and it's especially fatal in our view to ignore schemas and attempts to skip those when cross-integrating with other APIs. There's also no point to become another React Query when we hence lose all strengths of our implementation and GraphQL itself

**Comment by Urigo** [comment]
thanks for the mention @kitten !
GraphQL Mesh might help here, also @dotansimha and @ardatan are working on a refactor to split the conversion phase and do it at build time, so that could lead to even less overhead of using it on the client

**Comment by kitten** [comment]
I don't know if GraphQL Mesh is usable on the client-side, but if it is, `@urql/exchange-execute` covers this use-case, since it allows for client-side schema execution

**Comment by Urigo** [comment]
@kitten sorry for the late reply - the answer is yes, GraphQL Mesh is usable on the client-side and it is actually a pretty common use case for user of it!
Here is an example: https://github.com/Urigo/graphql-mesh/tree/master/examples/openapi-react-weatherbit

@ardatan @kitten (or anyone else interested in this issue) maybe we can create an example showing GraphQL Mesh integration with `@urql/exchange-execute` ?
