### ISSUE TITLE
RFC: make GraphQLRequest type looser

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#1472]
## Summary

Using this code with `@urql/svelte` [mutations](https://formidable.com/open-source/urql/docs/basics/svelte/#sending-a-mutation):

```ts
const myMutation = `
  mutation ($id: ID!, $input: myInput!) {
    myUpdate(id: $id, input: $input) {
      id
      name
    }
  }
`;

const updateMutation = mutation({ query: myMutation });
```

I get this Typescript error:

![image](https://user-images.githubusercontent.com/41120635/111849301-89897800-890d-11eb-8459-24652f3341c6.png)

Why is it complaining about `OperationStore` if I'm passing a `GraphQLRequest`?

```
Argument of type '{ query: string; }' is not assignable to parameter of type 'GraphQLRequest<any, object> | OperationStore<any, object>'.
  Type '{ query: string; }' is missing the following properties from type 'OperationStore<any, object>': variables, context, stale, fetching, and 6 more.ts(2345)
```

## Proposed Solution

@kitten [answered here](https://github.com/FormidableLabs/urql/discussions/1470#discussioncomment-505359):

> I think we should actually make that type looser

Hence this RFC! 😃

**Comment by kitten** [comment]
Sorry, but an RFC must be a little more exact and this is neither precisely what I meant nor ready to be worked on as per the description 😅

In case you'd like to work on this, it's a really small change to `mutation` in `@urql/vue` where this component is supposed to just accept a partial request that only at least requires `query`
