### ISSUE TITLE
Inconsistent documentation for @urql/exchange-retry

### ISSUE THREAD

**Issue by danbeneventano** [FormidableLabs/urql#1504]
https://formidable.com/open-source/urql/docs/advanced/retry-operations/

This page says:

> We want to place the retryExchange **after** the fetchExchange so that retries are only performed after the operation has passed through the cache and has attempted to fetch.

But the example code directly above it places the retryExchange **before** the fetchExchange:

```
const client = createClient({
  url: 'http://localhost:1234/graphql',
  exchanges: [
    dedupExchange,
    cacheExchange,
    retryExchange(options), // Use the retryExchange factory to add a new exchange
    fetchExchange,
  ],
});
```

Which is correct?

**Comment by danbeneventano** [comment]
Just tried it out, it seems that having the `retryExchange` **before** the `fetchExchange` is correct. If the `retryExchange` is after the `fetchExchange`, the operations are never retried. This directly conflicts with what is written on the documentation page. Can you explain this behavior?

**Comment by kitten** [comment]
That's indeed simply a mistake and it's meant to say "directly before the fetchExchange" 😅

**Comment by danbeneventano** [comment]
#1505
