### ISSUE TITLE
Query causing infinite loop 

### ISSUE THREAD

**Issue by Utkarshbhimte** [FormidableLabs/urql#1563]
I have two models `User` and `Course`, and both are linked via `Subscription`. This is my Prisma schema

```
model User {
  id             String         @id @default(cuid())
  createdAt      DateTime       @default(now())
  modifiedAt     DateTime       @default(now())
  email          String         @unique
  courses        Course[]
  subscriptions  Subscription[]
}

model Course {
  id                     String         @id @default(cuid())
  createdAt              DateTime       @default(now())
  modifiedAt             DateTime       @default(now())
  title                  String
  users                  User[]
  subscribers            Subscription[]
}

model Subscription {
  id         String   @id @default(cuid())
  createdAt  DateTime @default(now())
  modifiedAt DateTime @default(now())
  course     Course?  @relation(fields: [courseId], references: [id])
  courseId   String?
  user       User?    @relation(fields: [userId], references: [id])
  userId     String?
  data   Json 
}

```

I have a parent component just querying for user data and then I have a child component querying for all the subscription for the currentUser
```
query GetAllSubscribedCourses {
  currentUser {
    subscriptions {
      id
      course {
        title
      }
    }
  }
}
```

The hook generated from this graphql query is causing an infinite loop where both the APIs are being called simultaneously. 
![image](https://user-images.githubusercontent.com/13379773/115986110-687f0b80-a5cc-11eb-9e19-d0163bc0e15b.png)

urql version & exchanges: `2.0.1`

**Comment by kitten** [comment]
This is probably more something for a discussions thread but without a reproduction or code snippets we're unfortunately not able to tell you what's going on 😅

Most likely this will come down to the inputs you've passed to `useQuery`, like for instance an unmemoised and always changing `context`.

Please also don't forget to utilise GH discussions thread for debugging and questions, when it's about an issue that's usage-related and unlikely to be caused by a library bug ✌️

**Comment by Utkarshbhimte** [comment]
> Most likely this will come down to the inputs you've passed to useQuery, like for instance an unmemoised and always changing context.

The hook is [nexus](https://www.npmjs.com/package/nexus) generated. So I am not sure what I can do there. 

> Please also don't forget to utilise GH discussions thread for debugging and questions

Surely @kitten, I understand, moving the conversation to https://github.com/FormidableLabs/urql/discussions/1565
