### ISSUE TITLE
Documentation on next.js usage refers to deprecated module

### ISSUE THREAD

**Issue by oldo** [FormidableLabs/urql#1579]
Hi there, loving getting to know the urql ecosystem.

I'm playing around with a Next.js project and notice that the documentation refers to the `next-urql` package, however the repo for this package indicates that it is deprecated and included as part of urql-core.

https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#nextjs

**Comment by JoviDeCroock** [comment]
The package has been moved [here](https://github.com/FormidableLabs/urql/tree/main/packages/next-urql) the repo is deprecated not the package.
