### ISSUE TITLE
Mutation typescript error

### ISSUE THREAD

**Issue by reverie** [FormidableLabs/urql#159]
I'm following the example from the README and getting a typescript error. Here is the sample code:

```
const Home = () => (
  <Connect
    query={query(TodoQuery)}
    mutation={{
      addTodo: mutation(AddTodo),
    }}
  >
    {({ loaded, fetching, refetch, data, error, addTodo }) => {
      //...Your Component
    }}
  </Connect>
);
```

And the error is that Property `addTodo` does not exist on type '{ cache: ICache; data: {} | null; error: any; fetching: boolean; loaded: boolean; refetch: (options: { skipFetch?: boolean | undefined; }, initial?: boolean | undefined) => void; refreshAllFromCache: () => void; }'.

A workaround is to accept the parameters as a single value cast to `any` instead of destructuring them. But that seems hacky.

Am I doing something wrong? It would be nice to have a full example of a mutation somewhere, where the mutation gets called, what it returns. The linked examples are all only using queries.

**Comment by andyrichardson** [comment]
Hi @reverie, thanks for submitting this issue. 

We're currently working towards our V1 release which aims to have much stronger type coverage and also addresses this particular issue. 

I'll keep this issue open for now and close once V1 is released with type fixes.

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️
