### ISSUE TITLE
useMutation data not updated on graphcache change

### ISSUE THREAD

**Issue by ostrebler** [FormidableLabs/urql#1609]
urql version & exchanges: 2.0.1 (graphcache 4.0.0)

**Steps to reproduce**

1. Access result data from a mutation :
```typescript
const [{ data }, doStuff] = useMutation(...);
```

**Expected behavior**

When using graphcache, I was expecting `data` to update and the `useMutation` hook to trigger a rerender when the normalized data changes, for example as a result of another mutation.

**Actual behavior**

It does not.

This is a problem in my case, because I have a mutation `parsePatents` that returns a list of `Patent`. Then each patent can be selected via another mutation `selectPatent`, which returns an updated patent with a field `selected` set to `true`. Because of the limitation / bug I mention here, selected patents from the list are never shown to be selected.

**Comment by JoviDeCroock** [comment]
That's not really a bug, a mutation is not showing normalized data, a query is. A mutation will show the result of executing that mutation, if you need data that is subject to change a subscription or query is your better choice.

**Comment by ostrebler** [comment]
@JoviDeCroock Okay, thank you for the explanation. But then there is another issue in my specific case : I need to invalidate a query (`selectedPatentList`) right after my mutation `parsePatents`. But graphcache doesn't accept `Query` entries in `update`. How should I proceed ?

**Comment by JoviDeCroock** [comment]
I mean, it feels like you are mixing a few concerns here. A Query should not induce a side-effect, so unless you want to do `Mutation: { parsePatents: cache.invalidate('Query.selectedPatentList') }`  there seems something wrong in the schema.

**Comment by ostrebler** [comment]
@JoviDeCroock You're right, I'm mixing queries and mutations but it's on purpose, let me explain : `parsePatents` has an argument `autoSelect`, which automatically "selects" every patent after being parsed from files. The selection operation has a mutation semantic, but I've added it to `parsePatents` as a shortcut. So, when `autoSelect` is `true`, `parsePatents` should trigger a refresh of `selectedPatentList`.

Because of that, it needs to be a mutation because of the limitations of `update`. But then, it's `data` should also listen to changes from the cache, so it needs to be a query.

How would you do it ?

**Comment by JoviDeCroock** [comment]
The answer here is kinda two-fold, you answered your own question, you took a shortcut. Semantically GraphQL is set up to work this way, if we bypass it we subject ourself to undesired interactions.

That being said `selected` sounds like a very front-end-y paradigm, but don't really know your data model 😅

**Comment by kitten** [comment]
@ostrebler I really am having a hard time understanding although I'm following along every step here, but if I understand correctly you've got mutations that are queries and queries that are mutations? or rather, you knowingly are using mutations for data that is queried? I'm struggling to understand the reasoning here unfortunately 😅  Feel free to ask more questions or elaborate more and we'll try to help, but I think this is more of a discussion thread asking a question rather than a bug/issue, so I'll close it for now.
