### ISSUE TITLE
GraphCacheConfig not compatible with custom Scalars

### ISSUE THREAD

**Issue by lukasluecke** [FormidableLabs/urql#1647]
Using a custom Date scalar seems to be incompatible with the current type definitions, since it's neither a Primitive nor a ScalarObject.

```ts
export declare type Primitive = null | number | boolean | string;
export interface ScalarObject {
    [key: string]: unknown;
}
export declare type Scalar = Primitive | ScalarObject;
```

urql version & exchanges:
```json
    "@graphql-codegen/typescript-urql-graphcache": "^1.0.1",
    "@urql/core": "^2.1.1",
    "@urql/exchange-graphcache": "^4.1.0"
```
Also using a custom scalar exchange, similar to https://github.com/clentfort/urql-custom-scalars-exchange to actually convert the scalar values to the correct types.

**Steps to reproduce**

```yml
config:
  scalars:
    DateTime: Date
```

**Expected behavior**

Should accept custom scalars

**Actual behavior**

```sh
error TS2344: Type 'GraphCacheConfig' does not satisfy the constraint 'Partial<CacheExchangeOpts>'.
  Types of property 'resolvers' are incompatible.
    Type 'GraphCacheResolvers' is not assignable to type 'ResolverConfig'.
      Property 'Exam' is incompatible with index signature.
        Type '{ id?: Resolver<WithTypename<Foo>, null, string>; name?: Resolver<WithTypename<Foo>, null, string>; description?: Resolver<...>; ... 25 more ...; canUpdate?: Resolver<...>; }' is not assignable to type '{ [fieldName: string]: Resolver<DataFields, Variables, ResolverResult>; }'.
          Property 'id' is incompatible with index signature.
            Type 'Resolver<WithTypename<Foo>, null, string>' is not assignable to type 'Resolver<DataFields, Variables, ResolverResult>'.
              Type 'WithTypename<Foo>' is not assignable to type 'DataFields'.
                Property 'createdAt' is incompatible with index signature.
                  Type 'Date' is not assignable to type 'DataField'. <<<<<<
                    Type 'Date' is not assignable to type 'ScalarObject'.
                      Index signature is missing in type 'Date'.
```

**Comment by JoviDeCroock** [comment]
Hey,

How does your `codegen.yaml` look? Are you defining these `scalars`?

```
scalars
type: ScalarsMap

Extends or overrides the built-in scalars and custom GraphQL scalars to a custom type.
```

You can enable `strictScalars` if you want `codegen` to throw for unknown scalars

**Comment by lukasluecke** [comment]
@JoviDeCroock I put my `codegen.yml` in "Steps to reproduce", and they work fine for other purposes. The generated types are just not compatible with the new Graphcache generic type.

**Comment by kitten** [comment]
I would actually say this isn't _quite_ supported, since Graphcache (and all other parts in `urql`) assume the regular JSON serialisation as layed out by the specification: https://spec.graphql.org/June2018/#sec-JSON-Serialization

However, in this case there's an easy fix for this particular problem. But we can't guarantee anything related to this technically, because you're explicitly deserializing the result and mapping it to a different deserialized JS object. So, there be dragons

**Comment by lukasluecke** [comment]
Graphcache should be unaffected by this, as it would still store the original raw result, if I understand the exchange ordering correctly (custom scalar "before" graphcache, meaning it runs after graphcache for operation results).

The problem is that the only way to communicate the changed scalar mapping to result consumers (e.g. after `useQuery`) is to define that scalar mapping in codegen - which now clashes with the graphcache definitions 🙈

**Comment by JoviDeCroock** [comment]
I'd think that in graphCache the date will be a string though 😅 as you'll only convert it to a date after the cache returns a result to the custom-scalars-exchange

**Comment by lukasluecke** [comment]
That should be right. I could try and split the codegen outputs, so it generates a separate file just for the graphcache, and then not include the scalar mapping there - maybe that works 🤞🏻

**Comment by lukasluecke** [comment]
Seems to work with the following additional codegen config (at least it accepts the generic, and internally represents the DateTime instances as strings - still have some cleanup left to do before I can tell if it's actually 100% correct 😅).

```yml
  app/types/graphql-graphcache.ts:
    plugins:
      - typescript
      - typescript-urql-graphcache
    config:
      scalars:
        DateTime: string
```

Thanks for the help, as always! Hopefully I'll be able to polish my custom scalar exchange enough for release sometime, and then I can add this in the docs 😁
