### ISSUE TITLE
(vue) - useMutation should use executeMutation

### ISSUE THREAD

**Issue by Sytten** [FormidableLabs/urql#1658]
urql version & exchanges: latest

**Steps to reproduce**
When I was following the [testing documentation](https://formidable.com/open-source/urql/docs/advanced/testing/), it says to mock the `executeMutation` function. But it failed when I tried, I looked up the code and it seems to use `mutation` instead. But query uses `executeQuery` and subscription uses `executeSubscription`, so I think it's just some legacy code that that got forgotten. https://github.com/FormidableLabs/urql/blob/720f60c6b118b80dc2bef2fc0a0b22aab23e5415/packages/vue-urql/src/useMutation.ts#L62

**Expected behavior**
Testing should work when mocking `executeMutation`

**Actual behavior**
Testing fails, need to mock ``mutation`

**Comment by kitten** [comment]
Good point! That's an easy win

**Comment by apricote** [comment]
The same issue happened for us with svelte: https://github.com/FormidableLabs/urql/blob/main/packages/svelte-urql/src/operations.ts#L187

Should I open another ticket for this?
