### ISSUE TITLE
__URQL_DATA__

### ISSUE THREAD

**Issue by kamalkech** [FormidableLabs/urql#1666]
urql version : `"^2.0.3"`

```typescript
const isServerSide = typeof window === 'undefined';
const ssrCache = ssrExchange({ isClient: !isServerSide });
const ssr = ssrExchange({
  isClient: !isServerSide,
  initialState: !isServerSide ? window.__URQL_DATA__ : undefined,
});
```

i get this warning !!

`Property '__URQL_DATA__' does not exist on type 'Window & typeof globalThis'`

**Comment by kitten** [comment]
This is just a TypeScript warning. Either you need to declare that this global exists or cast `window` to any.
