### ISSUE TITLE
@urql/vue: useClient no longer exported

### ISSUE THREAD

**Issue by bartenra** [FormidableLabs/urql#1673]
With a recent version of urql, `useClient` is no longer exported:

https://github.com/FormidableLabs/urql/commit/e51daa5da82d54e54d66adefec063f3cd82f613e#diff-88a2d3e73ee7f60fa765e5715890696dd928437c109048a9d26da8120d72a47c

Was this intentional? If not, could you reverse it? :pray:

**Comment by kitten** [comment]
We're still experimenting as we're in the `0.x` releases for `@urql/vue`, but we'd like to encourage the use of `useClientHandle()` (on which you can get the client directly) as it makes the use of the `use*` methods safer: https://github.com/FormidableLabs/urql/blob/main/packages/vue-urql/src/useClientHandle.ts

We've obvserved that people tend to think that imperative calls (as described [in the docs](https://formidable.com/open-source/urql/docs/basics/core/#one-off-queries-and-mutations)) are a sufficient workaround to make queries work in any context, which is _false_, as they'll never update or behave reactively, and hence don't get caching updates or any other client-managed benefits.

The `useClientHandle` access to the `Client` helps with that by encouraging the use of the `use*` functions in more cases.

**Comment by bartenra** [comment]
@kitten I understand, makes sense. :-)

What if you want to fire a one-off mutation from a template though? For my use-case I had both a `SetNewPassword.vue` and `Login.vue` template that both needed to log the user in (a mutation and setting some local state). I refactored the logic into a function that accepts a for that `Urql.Client`.

I guess I could just do, 

```js
const handle = useClientHandle();
const client = handle.client;
```

but personally I'd like to have access to the client directly as well (just like `vue-router` has `useRouter().currentRoute` and `useRoute()`).

**Comment by kitten** [comment]
You can still fire one-off mutations as usual, either with `handle.useMutation` or `client.mutation`. no problem with that 👍

I don't think it's a huge inconvenience to access `const { client }` or `.client` to be completely honest  😅
