### ISSUE TITLE
(svelte) - assigning context only retriggers execution once

### ISSUE THREAD

**Issue by mattfysh** [FormidableLabs/urql#1678]
urql version & exchanges:

Using `@urql/svelte` v1.2.2

**Steps to reproduce**

Attempt to use the following method to refresh/refetch/reexecute a query **more than once:** https://formidable.com/open-source/urql/docs/basics/svelte/#reexecuting-queries

**Expected behavior**

The query is re-executed each time `refresh` is called

**Actual behavior**

The query is only executed the first time, and subsequent calls to `refresh` fail to trigger a backend request

**Comment by mattfysh** [comment]
I've traced it down to this line of code: https://github.com/FormidableLabs/urql/blob/main/packages/svelte-urql/src/operations.ts#L60

**Comment by mattfysh** [comment]
Current workaround is to replace this:

```
function refresh() {
  $todos.context = { requestPolicy: 'network-only' };
}
```

with:

```
function refresh() {
  $todos.context = {
    requestPolicy: 'network-only',
    force: Date.now()
  };
}
```

**Comment by kitten** [comment]
Sorry for the late response. Currently, this is actually expected behaviour due to an explicit change that we just didn't document. The Svelte bindings are the only bindings where we serialise and compare `context` to ensure that we don't double-trigger reexecutions. We did that since it wasn't seemingly possible for us to add an idiomatic `executeQuery` function instead that triggers an effect that's also observed by the store. It may be possible, but not quite idiomatic in Svelte.

We definitely don't want to recommend an assignment (like the one to `context`) triggering a side-effect going (reexecution) going forward, but I believe we just never figured out an alternative.

**Comment by mattfysh** [comment]
One possible way forward is to add a "refresh API" that hides implementation - allowing you to change best practice later on once you've decided the best approach, without having to change the external API, e.g.

```js
// ...
const todos = operationStore(...)

function refresh() {
  todos.refresh()
}
</script>

<Button on:click={refresh}>Refresh</Button>
```

Note that we don't use `$todos.refresh`, therefore refresh would be a method implemented on the store itself, and not a function that lives on the store's held value.

**Comment by mattfysh** [comment]
@kitten I think this may have broken something... because this code no longer works.

```js
const results = operationStore(suggestWidgets, {}, { pause: true })

  const runWidgetSearch = e => {
    const searchterm = e.target.value
    $results.context.pause = !searchterm
    if (searchterm) {
      $results.variables.searchterm = searchterm
    }
  }
```

For now I'll drop back to version 1.2.3 and investigate tomorrow. I've also been meaning to read through the Svelte wrapper code and see if I can help in any way, will reach out later this week!

**Comment by kitten** [comment]
We've arrived at a slight compromise here, especially for paused queries; The context reassignment is now reference-equality-based, which means that it's still a good idea to reassign the context value. However, our shortcut for that is now the new `operationStore(...).reexecute()` method, hence you can do the following:

```js
const runWidgetSearch = e => {
  const searchterm = e.target.value
  if (searchterm) {
    $results.variables.searchterm = searchterm;
    $pokemons.reexecute({ pause: false });
  }
}
```
