### ISSUE TITLE
Refetch causes "Too many re-renders" when context is set in query with suspense enabled

### ISSUE THREAD

**Issue by jtc3161** [FormidableLabs/urql#1679]
So it took a while to build a minimal reproduction, but I think I locked it down. Sandbox: https://codesandbox.io/s/intelligent-voice-3kr0c

I just recently turned on the suspense feature for my react app, but one of my `useQuery` instances in the app changes the operation context consistently fails on refetch.

urql version & exchanges:
- urql: 2.0.3
- default exchanges

**Steps to reproduce**

1. Enable suspense
2. Add a suspense wrapper for the app
3. add a context argument to `useQuery`, can be as simple as an empty object `{}`
4. Load the page and trigger a refetch

I am consistently getting a "Too many re-renders" error both on my app and the provided codesandbox link in the description

**Comment by JoviDeCroock** [comment]
We have opted to make `context` not memoized within `useQuery` as we can't assume when you want to refetch it, hence why we require you doing:

```js
  const [res, executeQuery] = useQuery({
    query: TodoQuery,
    context: React.useMemo(function () {
      return {};
    }, [])
  });
```

**Comment by jtc3161** [comment]
Perfect thanks! hopefully this issue adds to one more set of search terms to make it easier to find then.
