### ISSUE TITLE
responding to mutation error

### ISSUE THREAD

**Issue by badderstuber** [FormidableLabs/urql#169]
I hope this is the best place to ask this. 

I am struggling to work out how to respond to mutation errors returned by my graphql server (apollo-server). 

For example, when registering a new user if the email has been registered before I return an error which looks like this in the graphql response:

```
{
	"errors":
        [
		{
			"message":"A user with that email already exists"
		}
	],
	"data":
	{
		"registerUser":null
	}
}
```

It doesn't appear the error is returned in the `<Connect>` error property (is this for query errors only?), and I have tried catching the error in the returned promise. Is there a way to do this?

Thanks

**Comment by kitten** [comment]
Yep, this is a known issue. We've been working hard on v1 and I'm happy to say that it's almost there :) this is one of the numerous things that we'll be fixing.

Apart from the the goal of v1 is stability and flexibility / extensibility. We'll be closing off some of the current issues you see in this repo once we release v1

**Comment by badderstuber** [comment]
Hey Kitten, thanks for the reponse and I look forward to v1... good luck with the rest of the dev. I think for now i'll hack the 'data' response to include any errors and check for them client side. I know it's impossible to say for sure but are you looking at weeks or months till v1 is released? Also, do you need any beta testers?

**Comment by kitten** [comment]
We're aiming for end of next week with most of the API remaining the same and backwards compatible for now

**Comment by badderstuber** [comment]
Ok thanks kitten

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️
