### ISSUE TITLE
Upgrading to 2.* introduces `pause: true` / executeQuery Bug

### ISSUE THREAD

**Issue by bastianwegge** [FormidableLabs/urql#1698]
Hey @ the urql-Team!
I've been using `urql` for 3 weeks in production and I totally love it. I migrated a large project of mine to `urql` and have had some funny reports from users recently. As I did the `howtographql` on `urql` initially some time ago, I was really flashed and wanted to get my hands on `urql` as soon as possible. So today I thought "maybe I misunderstood something, lets do the howtographql on urql again". So much for my motivation.

Doing the course on howtographql `react-urql` (final results can be seen here: https://github.com/howtographql/react-urql) I noticed a strange behavior which explains some of my recent reports. In the course there's a page which explains how to use `pause: true` and `executeQuery`. Sadly this functionality (paired with `useCallback`) seems to work only 50% of the time. I tried to get an idea of what's going on and figured that upgrading to `urql@^2.*` introduces this behavior.

Maybe I'm completely off track here and somebody will tell me "You just have to pull the nipple through the tab", but I feel quite curious about what's going on.

urql version & exchanges:
- prior to `2.0.0`: Expected Behavior @ `urql@1.5.0` & `urql@1.11.6`
- after `2.0.0`: Actual Behavior @ `urql@2.0.0`

**Steps to reproduce**

1. clone `https://github.com/howtographql/react-urql`
2. initialize the prisma test-db in `server` (authentication with GitHub works fast & easy)
2. change the version of `urql` to `^2.0.3` (latest version as of now)
3. in the root directry run `yarn install` and then `yarn start`
4. create some Links and try to search for the links using the `Search` component
5. `executeQuery` in `src/components/Search.js` only fires every second call

**Expected behavior**

`executeQuery` should always fetch new data

**Actual behavior**

`executeQuery` only works every second call

<img width="594" alt="screenshot-console" src="https://user-images.githubusercontent.com/1541474/120892220-7ed9a780-c60d-11eb-9575-6bf8e18a609b.png">

**Comment by kitten** [comment]
I believe we may have been able to isolate it. We had a check on `executeQuery` that takes a quick peek at the query result, which is used to already set the next result 

This isn't actually necessary as we update it during render, but we had an erroneous check attached to it that cancels the state update if the state isn't going to change.

The problem is that for a paused query the state won't change unless execute is called, which leads to the behaviour you're describing 😅

I already have a PR ready with a fix however

**Comment by bastianwegge** [comment]
Thank you very much for the quick response! 👍
