### ISSUE TITLE
Using urql/core in NodeJS environment raised 'ReferenceError: fetch is not defined'

### ISSUE THREAD

**Issue by Owpac** [FormidableLabs/urql#1700]
Hello !

First of all, thank you for your work.
I'm trying to use urql/core in my backend server developed in KoaJS (equivalent of NodeJS server).
I'm also using codegen to generate types from a schema.graphql file. Here are my files:

urql.ts
```ts
import { createClient } from '@urql/core'

const client = createClient({
  url: ENDPOINT,
  fetchOptions: () => ({
    headers: {
      'Content-Type': 'application/json',
    },
  }),
})

export default client
```

codegen.yml
```yaml
overwrite: true
schema: "schema.graphql"
documents: "src/graphql/**/*.graphql"
generates:
  src/graphql/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-urql"
    config:
      withHooks: false
```

test.ts
```ts
const { data, error } = await client
    .query<UserQuery, UserQueryVariables>(UserDocument, { id: '123' })
    .toPromise()

  console.log(data)
  console.log(error)
```

When I'm running the code I have an error ```ReferenceError: fetch is not defined``` around this kind of line ```return (e.context.fetch || fetch)(r, t).then((function(e) {``` but I have 'node-fetch' installed.

It seem to happen in this file 
```urql/packages/core/src/internal/fetchSource.ts```:

```ts
import { Operation, OperationResult } from '../types';
import { makeResult, makeErrorResult } from '../utils';
import { make } from 'wonka';

const executeFetch = (
  operation: Operation,
  url: string,
  fetchOptions: RequestInit
): Promise<OperationResult> => {
  const fetcher = operation.context.fetch;

  let statusNotOk = false;
  let response: Response;

  return (fetcher || fetch)(url, fetchOptions)
    .then((res: Response) => {
      response = res;
      statusNotOk =
        res.status < 200 ||
        res.status >= (fetchOptions.redirect === 'manual' ? 400 : 300);
      return res.json();
    })
    .then((result: any) => {
      if (!('data' in result) && !('errors' in result)) {
        throw new Error('No Content');
      }

      return makeResult(operation, result, response);
    })
    .catch((error: Error) => {
      if (error.name !== 'AbortError') {
        return makeErrorResult(
          operation,
          statusNotOk ? new Error(response.statusText) : error,
          response
        );
      }
    }) as Promise<OperationResult>;
};
```

Am I doing something wrong?

urql version & exchanges:
- "@graphql-codegen/cli": "^1.21.4",
- "@graphql-codegen/typescript": "^1.22.0",
- "@graphql-codegen/typescript-operations": "^1.17.16",
- "@graphql-codegen/typescript-urql": "^2.0.6",
- "@urql/core": "^2.1.3",
- "graphql": "^15.5.0",
- "node-fetch": "^2.6.1",

**Steps to reproduce**

1. Set up a little NodeJS server
2. Config codegen with a schema.graphql file
3. Config @urql/core client
4. Try to query something 

**Expected behavior**
Successfully executing my query ! :)

**Actual behavior**
```
/node_modules/@urql/core/dist/b4631212.js:266
        return (e.context.fetch || fetch)(r, t).then((function(e) {
                                   ^

ReferenceError: fetch is not defined
    at executeFetch (/node_modules/@urql/core/dist/b4631212.js:266:36)
    at /node_modules/@urql/core/dist/b4631212.js:280:8
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

**Comment by JoviDeCroock** [comment]
Fetch is not defined in node, you can polyfill or pass it in options.fetch for the client https://formidable.com/open-source/urql/docs/api/core/#client

**Comment by Owpac** [comment]
I missed this option ! Sorry for the inconvenience and thank you !

**Comment by crwebb85** [comment]
> Is there a way to get this to work with typescript? I'm getting a typescript error.
> 
> ```
> import fetch from "node-fetch";
> const client = createClient({
>   url: process.env.GRAPHQL_URI || "",
>   fetch,
> });
> 
> #ERROR
>     12     fetch?: typeof fetch;
>            ~~~~~
>     The expected type comes from property 'fetch' which is declared here on type 'ClientOptions'
> ```
It seems the type definitions are not the same for node-fetch. I was able to get it to work by using cross fetch instead. 

```
import fetch from "cross-fetch";
const client = createClient({
  url: process.env.GRAPHQL_URI || "",
  fetch: fetch,
});
```
