### ISSUE TITLE
RFC: add support for mutation queries in exchange-persisted-fetch

### ISSUE THREAD

**Issue by stalniy** [FormidableLabs/urql#1701]
## Summary

I propose to add support for mutations in @urql/exchange-persisted-fetch

## Proposed Solution

I suggest to add an option `operationTypes` (which is enum: "query" | "mutation") that will tell this exchange whether to forward operation further or hash it and send query

## Motivation

I extract all my queries and mutations from js bundle in json file and use that as a whitelist on server to prevent unexpected queries to be executed by someone else

**Comment by kitten** [comment]
I'll mark this as a duplicate for now, as we have an identical RFC here: https://github.com/FormidableLabs/urql/issues/1287

However, we didn't receive enough information about this to decide on what to do about it, as well as not having seen this be used in a lot of APIs that do primarily use persisted queries. Generally, I think some of the trouble comes from this not being a proposed specification for "GraphQL over HTTP" just yet: https://github.com/graphql/graphql-over-http

Instead, it's not a specification but a loose document (that isn't precise enough to go into the details of what this would benefit or enable) here: https://github.com/apollographql/apollo-link-persisted-queries#apollo-engine

We can revive the other thread, but currently we consider this incomplete as of now. We're open to implementing it, but we'd need more guarantees that other implementations will respect this pattern as is, for mutations and including `POST`.
