### ISSUE TITLE
RFC: Swap Positions of Return Values

### ISSUE THREAD

**Issue by iamclaytonray** [FormidableLabs/urql#1704]
## Proposed Solution
To change the positions of the return values from mutations. Currently, there are some instances where I have to do something like:

```tsx
const [, favoriteItem] = useMutation();
```

This feels counter-intuitive to me. There are times where the first object's values aren't relevant to me but I have to stub it out with a comma. Instead, I'm proposing we reverse this. For example:

```tsx
const [favoriteItem] = useMutation();
const [favoriteItem, { fetching, error, data }] = useMutation();
```

I don't see a case where `favoriteItem` would be a "throw-away" or not used. I do see (and encounter) cases where `{ fetching, error, data }` is not used.

## Requirements
Implementation would be relatively simple. We just swap the positions of the return values.

**Comment by kitten** [comment]
We keep this for consistency with `useQuery` and `useSubscription`, and it's structured so that state comes before the action, like the built-in `useState` and `useReducer`. So, although we're aware that often you'd want to ignore the stateful in-hook result, we prefer to keep this predictably in the same order.

**Comment by iamclaytonray** [comment]
The return values make sense for the things you listed. You almost always use `state`. Sometimes you don't need to use `setState` (using the following example: `const [state, setState] = useState();`)

I think a more consistent API is `[whatsAlmostAlwaysUsed, whatsPossiblyUsed]`, which I don't think breaks from the consistency of React's APIs

**Comment by kitten** [comment]
Right, and I see why you'd propose this, however, I personally see discussions along these lines as bikeshedding, as either option fulfils a different set of expectations, but lead to the same outcome and the same overall ergonomics of the API.

> This feels counter-intuitive to me. There are times where the first object's values aren't relevant to me but I have to stub it out with a comma.

Re. this; I don't believe it's "mostly" irrelevant as the most common use, as far as our observed usage of `urql` goes, shows that `mutationResult.fetching` is extremely frequently used for in progress changes to the UI.
