### ISSUE TITLE
[@urql/vue] useQuery, fetching field remains true after loading data from cache

### ISSUE THREAD

**Issue by ec-smyer** [FormidableLabs/urql#1734]
On a basic usage of ``useQuery`` as found in the documentation, ``fetching`` field remains ``true`` after loading from cache. If loading from network, ``fetching`` does update to ``false`` as intended.

https://formidable.com/open-source/urql/docs/basics/vue/#run-a-first-query

urql version & exchanges:

@urql/core: 2.1.3
@urql/vue: 0.4.0

**Steps to reproduce**

Trigger ``useQuery`` from network, navigate away then back to re-trigger ``useQuery`` from cache. Watch ``fetching`` field.

```
<template>
    <p>Fetching: {{ fetching }}</p>
</template>

<script>
import { useQuery } from '@urql/vue'

export default {
    setup () {
        const { fetching } = useQuery({ query: ' ... ', requestPolicy: 'cache-first' })
        return { fetching }
    }
}
</script>
```

**Expected behavior**

After loading from cache, ``fetching`` field should update to ``false``.

**Actual behavior**

After loading from cache, ``fetching`` field remains ``true``.

**Comment by kitten** [comment]
I'm going to mege this into #1429 for now until we can find out more about both issues, so I don't have to paste the same responses in two places :v: Let's follow up there and reopen this if it's necessary
