### ISSUE TITLE
(core) - Stale isn't true for refetch when using cache.invalidate in Graphcache

### ISSUE THREAD

**Issue by kmrachko** [FormidableLabs/urql#1754]
The problem appeared after upgrading to latest urql from 2.0.0.

urql version & exchanges:
"@urql/core": "^2.1.4",
"@urql/devtools": "^2.0.3",
"@urql/exchange-auth": "^0.1.3",
"@urql/exchange-graphcache": "^4.1.4",
"urql": "^2.0.4",

**Steps to reproduce**

1. Query some data with "useQuery" hook
2. Invalidate that data in the cache using "cache.invalidate" or any other method (we do it in updater function)

**Expected behavior**
Stale is "true" while data is being refetched

**Actual behavior**
Stale is "false" while data is being refetched

**Comment by kitten** [comment]
This fix has now been released in `@urql/core@2.1.5`
