### ISSUE TITLE
Move away from yarn

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql#176]
Currently experiencing the following issues with yarn:
 * E2E in CI fails when using yarn ([fix commit](https://github.com/FormidableLabs/urql/pull/175/commits/24f82298676289d0489c6f19ac8f5aa973816a1c))
 * `yarn install` takes over 10 minutes when run in the `examples/2-using-subscriptions` directory (barely 20 seconds with `npm i`)
 * Limited support for lock files. Yarn lock files are only supported by by _yarn_ while `package-lock.json` files are supported by _yarn_ and _npm_.

**Comment by Daniel15** [comment]
Have you filed any bugs for Yarn for the issues you encountered?
