### ISSUE TITLE
Resolvers & WebSockets ETA Timeline

### ISSUE THREAD

**Issue by quadsurf** [FormidableLabs/urql#18]
Just curious when Resolvers and hopefully support for Web Sockets is set to release (a soft roadmap to hope for, no hard dates needed of course). Apollo is already using resolvers to manage local application state, and also allows you to query/mutate your local store in the same fashion you would with a remote data store. What will be different or perhaps better?

**Comment by kenwheeler** [comment]
Roughly a week or two. Im still working out the client side API. Similar client directive type stuff, but maybe different resolver definition style. No ETA on sockets, need to investigate.

**Comment by quadsurf** [comment]
awesome! many many thanks @kenwheeler to you and that innovative spirit... can't wait to try it out!
