### ISSUE TITLE
Typings multipartFetchExchange

### ISSUE THREAD

**Issue by Manubi** [FormidableLabs/urql#1801]
Hi,
since I updated to the latest urql version, `multipartFetchExchange` is giving me type errors. 
` "@urql/exchange-auth": "^0.1.3",
   "@urql/exchange-multipart-fetch": "^0.1.12",
    "urql": "^2.0.4",
`

<img width="1279" alt="CleanShot 2021-07-15 at 11 58 41@2x" src="https://user-images.githubusercontent.com/20935138/125769447-5629a34a-5cad-43c7-b222-d4fc390dd627.png">

**Comment by JoviDeCroock** [comment]
This is not a bug and has frequently been addressed, this is due to having multiple copies of `@urql/core` in your deps, this can be resolved with for instance `yarn-deduplicate`

**Comment by Manubi** [comment]
Thanks! `yarn-deduplicate` did the trick.
