### ISSUE TITLE
executeQuery() is not triggering

### ISSUE THREAD

**Issue by Manubi** [FormidableLabs/urql#1802]
Hi,
I need to refetch a query but both,  `client.query(Document)` and `executeQuery()` is not getting called.

"@urql/exchange-auth": "^0.1.3", "@urql/exchange-multipart-fetch": "^0.1.12", "urql": "^2.0.4",

<img width="707" alt="CleanShot 2021-07-15 at 12 03 14@2x" src="https://user-images.githubusercontent.com/20935138/125770038-77a93fd4-14c3-4103-829a-182026eeedd3.png">

**Comment by JoviDeCroock** [comment]
Our issue-template asks for a reproduction, it's hard for us to just help without having a proper way to look at this issue ourselves.

**Comment by Manubi** [comment]
I did the yarn-deduplicate and now it works. Thanks!
