### ISSUE TITLE
Updating @urql/svelte from 1.2.2 to 1.3.0 issues with operationStore variable updates

### ISSUE THREAD

**Issue by Orion90** [FormidableLabs/urql#1805]
Hi! I noticed that after running `npm update`, `@urql/svelte` was updated from 1.2.2 to 1.3.0 which caused the filtering in the system I'm building stopped working. 

urql version & exchanges: @urql/svelte 1.3.0

**Steps to reproduce**

To exclude any changes I might have done I created a new project and followed the steps here: https://formidable.com/open-source/urql/docs/basics/svelte/

1. Setup a client and query
```javascript
  let id = 1;
  const client = createClient({
    url: "https://beta.pokeapi.co/graphql/v1beta",
    fetch,
  });
  setClient(client);
  const pokemonByID = operationStore(
    `
        query($id: Int!) {
    		pokemon: pokemon_v2_pokemonspecies(where: {id:{_eq:$id}}, order_by: {id: asc}) {
       			name
        		id
      		}
        }
      `,
    { id }
  );
  query(pokemonByID);
```
2. Parse the data from the query + add a next button
```javascript
  let pokemon = {};
  $: pokemon = pokemonByID.fetching ? pokemon : $pokemonByID.data.pokemon[0];
  const handleClick = (e) => {
    e.preventDefault();
    $pokemonByID.variables.id += 1;
  };
```  
3. Render
```svelte
<span>#{pokemon.id} {pokemon.name}</span>
<a href="/next" on:click={handleClick}>Next</a>
```

**Expected behavior**
When clicking on the link I expect id to increment by one (which it does) and a new query to run with the updated state.
**Actual behavior**
No new query is executed, even though the variable is updated.

**Comment by JoviDeCroock** [comment]
I'll look into what causes this regression, was first looking into why it did work for me but it seems like doing `$pokemonByID.variables = { id: $pokemonByID.variables.id + 1 }` works correctly. 😅

**Comment by kitten** [comment]
This is intended behaviour now 😅 Svelte is... questionable at times in terms of setters/getters and effects. The prohlem with them is that any of them could cause an update, but that that can often be excessive. If we then deeply compare changed, then people get confused why sometimes things don't update.

Hence, you can now either update the reference of `variables` entirely or use the `reexecute` method: https://formidable.com/open-source/urql/docs/api/svelte/#operationstore

**Comment by Orion90** [comment]
Thanks for the swift response.

@kitten One question comes to mind; if svelte is questionable at times when it comes to this, wouldn't the svelte developer be aware of those things and able to work around them in their client code? :) 
I haven't ran into a situation where the behaviour seems weird from the svelte knowledge I have, so maybe an example could help here so I can decide on whether to update my code to this new behaviour or stay on `1.2.2` :)

If this is now the intended behaviour I think it should be clearly mentioned in the release notes since code that worked on a previous _minor_ release doesn't anymore? Also [the next page example](https://formidable.com/open-source/urql/docs/basics/svelte/#variables) in the documentation would need an update?

**Comment by kitten** [comment]
@Orion90 It's a difficult situation. We decided to use the `operationStore` as a workaround to separate the reactive updates/client-bindings from the result and input updates. We didn't see it as optimal to have two stores, one for the inputs and one for the results and separate them. Hence, there are some complications that we ran into.

When the reactive statements in Svelte update store, they send the update as an identity call, i.e. they send the store itself. That means that we can't really tell what has changed until we do a deep comparison. Alternatively, we'd otherwise not be able to tell whether result values or input values have changed. We also optimally don't want the inputs to be used immediately when `variables` or `query` don't actually change. That all then ends up causing some edge cases when `variables` are mutated rather than swapped out.

**Comment by Orion90** [comment]
@kitten Thank you for taking time to elaborate, I think I see the issue you were trying to solve a bit clearer now. Like I mentioned it would be cool to have this documented for clarity that code might break and how to migrate to 1.3.0 :) It doesn't seem to be too much hassle changing the client code (at least for me). 

And as a final note I really like this library, it feels very natural to work with!
