### ISSUE TITLE
RFC: add 'requestPolicy' to client.query arguments

### ISSUE THREAD

**Issue by kmrachko** [FormidableLabs/urql#1818]
## Summary

Add 'requestPolicy' as an optional argument to `client.query` method.

## Proposed Solution

'requestPolicy' argument in `client.query` method will specify request policy used for this query, same as it is in the `useQuery` hook.

## Description

My case is following - I have a query to validate credentials (form with 2 inputs + "test" button). `client.query` method works perfectly for this case (useQuery is not really fitting here as I would like to only send request after button was pressed), except when credentials weren't changed but user pressed the "Test" button 2nd, 3rd and so on time. Each time I want to show an error notification. But due to caching, I don't receive an error if credentials were invalid - therefore can't show an error message.

I think it would be solved if I could specify **network-only** request policy to bypass cache, so I guess error should be present on each query attempt. I have also tried using `useQuery` with `pause: true` and manually calling `executeQuery`, but it just doesn't work properly (might create a separate bug report for that).

**Comment by JoviDeCroock** [comment]
The third argument to `query` already allows you to do that through the [`context`](https://github.com/FormidableLabs/urql/blob/main/packages/core/src/client.ts#L108) argument.  https://formidable.com/open-source/urql/docs/api/core/#operationcontext

**Comment by kmrachko** [comment]
Thank you for the tip! Guess issue can be closed. However, I haven't found any mention of the third argument to a query method in the documention - neither [here](https://formidable.com/open-source/urql/docs/basics/core/#one-off-queries-and-mutations) nor [here](https://formidable.com/open-source/urql/docs/api/core/#clientquery).

So I would recommend adding that to the documentation, when you have time.
