### ISSUE TITLE
willAuthError query executes twice

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#1825]
When a willAuthError is present in auth-exchange it results to queries being executed twice.

I saw that there was a PR that fixed the same issue but even that does not seem to fix the error.

If willAuthError is removed and we rely only on didAuthError then everything is working as expected.

Sorry that i am not provided a reproducible case but i think the issue is present in also a very simple auth-exchange scenarios

**Comment by kitten** [comment]
The only way this can be caused, as far as I can tell is when a duplicate operation already reached the exchange.

The `authExchange` prevents `willAuthError` (and `didAuthError`) from being run again when they trigger a refresh, i.e. a call to `getAuth`.

The first failing operation is then queued up for a retry while a subsequent duplicate would simply wait for the promise. However, this would imply that a duplicate has reached the exchange in the first place, which shouldn't be possible as long as you've got a `dedupExchange` in place, as we'd typically expect.

**Comment by zenios** [comment]
Here you are

https://codesandbox.io/s/funny-https-rj8jb

I modified the exchange to return willAuthError after 5 seconds from initialisation. This replicates an expiring jwt token

In order to test
login 
wait 5 seconds
press toggle
The query will execute 2-3 times
