### ISSUE TITLE
Suspend Network Only = Duplicate Requests

### ISSUE THREAD

**Issue by parisholley** [FormidableLabs/urql#1875]
https://codesandbox.io/s/quirky-firefly-nr474

small reproduction, if you look at the console, two http requests are hitting the server for the same todos query, and component is rendered more than it should be. i see this behavior with or without a cache exchange

it also happens on cache-and-network when there is no data in the cache

**Comment by kitten** [comment]
You're using `network-only` here (and no cache). Suspense discards the current render, and clients / observers outside can't tell whether the suspended component will or will not be remounted, meaning that there's no way to have correct behaviour here, except for `cache-first` (the default) or `cache-and-network`. Generally, we have an internal cache for some guarantees, but `network-only` and no cache is not a deterministic/supported one, since we don't deem it to ... make a lot of sense 😅 

We also in general do not recommend `network-only` in declarative framework bindings (or using `cache-and-network` by default in all cases for that matter). So this is expected behaviour for both aspects of this unfortunately.

**Comment by parisholley** [comment]
you see my edit, this behavior is the same with a cache exchange?

**Comment by kitten** [comment]
I've just explained this (coincidentally?) in another thread on discussions, so maybe that fills more gaps :v: https://github.com/FormidableLabs/urql/discussions/1874#discussioncomment-1208738

**Comment by parisholley** [comment]
hmm.. is there any practical reason why network-only should even be allowed when suspense = true? feels like this should be a thrown exception.

also, double requesting still happens, on cache-and-network w/ exchange and nothing in the cache

**Comment by parisholley** [comment]
i've been working on implementing my own hook with a few extra features, and i've been able to get the behavior i expect to work running, but it depends a lot on assumed behavior within urql and took some of your advice from #1874. things to note:

* `network-only` bypasses the existing client instance and creates a new instance with `cache-first` as the request policy, allowing us to always get a fresh copy and not write anything to global cache.
* `cache-and-network` ends up running a `cache-only` request first, then on component mount, running another query using `cache-first` to get the latest version (since `toPromise` will never return a stale result from what I can tell). my approach fixes the cache miss scenario i've noted above.
* `network-first` is a new concept where we run the same `cache-and-network` behavior as above, but do not run an additional query on mount.
* i implemented a simple diffing algorithm to only re-render if the data returned from the server has changed, may or may not be expensive at scale but isn't an issue for me
* you'll notice I have a global invocation cache to store promises, this design approach assumes I am ok with multiple mounted components "seeing" the same state, regardless of what is in the urql cache. for my purposes, this is preferred behavior, vs having a lot of resolved queries presenting different data sets to the user. i'm sure it is possible some type of race condition could exist in my approach.

```
const pending: Record<
  string,
  {
    error?: Error;
    promise: Promise<unknown>;
    data?: unknown;
    listeners: number;
    complete: boolean;
    stale: boolean;
  }
> = {};

export function useQuerySuspense<D, V extends Record<string, unknown>>(
  query: TypedDocumentNode<D, V>,
  variables?: V,
  policy: RequestPolicy | 'network-first' = 'network-only',
  refresh = false
): D {
  const ref = useRef<D>();

  // eslint-disable-next-line react-hooks/rules-of-hooks
  const client = policy === 'network-only' ? useGraphClient() : useClient();

  if (policy === 'network-only' && refresh) {
    throw new Error('Cannot refresh with network-only, use network-first instead.');
  }

  // loc && __key are appended to query object after first execution
  const cacheKey = JSON.stringify({ kind: query.kind, definitions: query.definitions, variables });

  const requestPolicy =
    policy === 'network-first'
      ? 'cache-and-network'
      : policy === 'network-only'
      ? 'cache-first'
      : policy === 'cache-and-network'
      ? 'cache-only'
      : policy;

  if (!ref.current) {
    if (!pending[cacheKey]) {
      const execute = client.query(query, variables, { requestPolicy });

      pending[cacheKey] = {
        listeners: 0,
        stale: false,
        complete: false,
        promise: pipe(execute, take(1), toPromise).then(async (r) => {
          if (!pending[cacheKey]) {
            return;
          }

          if (r.stale !== undefined) {
            r.error = 'Did not expect stale to be set';
          }

          if (!r.error) {
            if (policy === 'cache-and-network') {
              if (r.data === null) {
                r = await client.query(query, variables, { requestPolicy: 'cache-and-network' }).toPromise();
              } else {
                pending[cacheKey].stale = true;
              }
            }
          }

          if (r.error) {
            pending[cacheKey].error = r.error;
          } else {
            pending[cacheKey].data = r.data;
          }

          pending[cacheKey].complete = true;
        }),
      };
    }

    if (pending[cacheKey].error) {
      throw pending[cacheKey].error;
    }

    if (!pending[cacheKey].complete) {
      throw pending[cacheKey].promise;
    }

    ref.current = pending[cacheKey].data as D;
  }

  const [result, setResult] = useState<D | Error>(ref.current);

  if (result instanceof Error) {
    throw result;
  }

  useEffect(() => {
    if (!pending[cacheKey]?.stale && !refresh) {
      return;
    }

    const requestPolicy =
      pending[cacheKey]?.stale && policy === 'cache-and-network' ? 'cache-and-network' : 'cache-first';

    if (pending[cacheKey]) {
      pending[cacheKey].stale = false;
    }

    const execute = client.query(query, variables, { requestPolicy });

    const subscription = pipe(
      execute,
      subscribe((r) => {
        if (r.error) {
          setResult(r.error);

          return;
        }

        // __typenames are appended after server response and "look" like a new object in cache
        if (JSON.stringify(removeTypename(result)) !== JSON.stringify(removeTypename(r.result))) {
          // prevent unnecessary renders
          if (pending[cacheKey]) {
            pending[cacheKey].data = r.data;
          }

          setResult(r.data);
        }
      })
    );

    return () => {
      subscription.unsubscribe();
    };
  }, [result]);

  useEffect(() => {
    if (!pending[cacheKey]) {
      return;
    }

    pending[cacheKey].listeners += 1;

    return () => {
      pending[cacheKey].listeners -= 1;

      if (pending[cacheKey].listeners == 0) {
        delete pending[cacheKey];
      }
    };
  }, []);

  return result;
}

export function removeTypename(obj: any) {
  for (const prop in obj) {
    if (prop === '__typename') {
      delete obj[prop];
    } else if (typeof obj[prop] === 'object') {
      removeTypename(obj[prop] as any); // eslint-disable-line @typescript-eslint/no-explicit-any
    }
  }

  return obj;
}
```
