### ISSUE TITLE
Better TS typing for useMutation

### ISSUE THREAD

**Issue by scyclow** [FormidableLabs/urql#188]
It would be nice if there was some way to type the input on a mutation. Currently, `useMutation` only accepts a type for the response. As far as I can tell, there's no way to type the input to the mutation: https://github.com/FormidableLabs/urql/blob/master/src/hooks/useMutation.ts#L26

For example:
```
interfact MutationOutput {
  someMutation {
    someProp: string
  }
}
...
const [response, execute] = useMutation<MutationOutput>(mutationString)
```
Here, I can pretty much pass any object into `execute`, and it won't throw a type error.

Maybe the useMutation definition could accept an input type:
```
export const useMutation = <T = any, V = object | void>(query: string): UseMutationResponse<T> => {
```
and then
```
const executeMutation = (variables: V) => {
```
or something along these lines?

**Comment by kitten** [comment]
Good point! We totally forgot to generics for variables across the board. We'll fix that ASAP

**Comment by scyclow** [comment]
Awesome! One more note on this. In this example:
```ts
const [response, executeMutation] = useMutation<Response, Input>(mutation)
```
it looks like the type of `executeMutation` is `(args: Input) => Promise<OperationResult>`, which types its `data` property as `any`. Is it possible/desirable to give `OperationResult` a type for its `data`, and then type `executeMutation` is `(args: Input) => Promise<OperationResult<Response>>`?
