### ISSUE TITLE
Calling one-off Queries

### ISSUE THREAD

**Issue by quadsurf** [FormidableLabs/urql#19]
For most queries, the received data is bound to the component's props, so in essence, the app makes the data request, not the user. However, there are times when the user needs to manually make the data request, long after the component has been mounted (i.e. a user performs an inline search request that is not meant to be tied to or handled by, another child component). While for the most part I LOVE Apollo and am very appreciative of their OSS contribution, this is actually one area where they added too many extra steps for the developer... instead of directly supporting this, they came up with a very clunky "workaround" that requires a separate import:
```import { withApollo } from 'react-apollo'```

So since you're soliciting feedback  :-)  ...  please directly support this instead of creating a clunky work-around for calling one-off/adhoc queries.

**Comment by jmeas** [comment]
@quadsurf would [`client.executeQuery()`](https://github.com/FormidableLabs/urql/blob/55de396e3797f8c68aef968334dd0405dbb1c866/src/modules/client.ts#L109) / [`client.executeMutation()`](https://github.com/FormidableLabs/urql/blob/55de396e3797f8c68aef968334dd0405dbb1c866/src/modules/client.ts#L166) work for your use case?

**Comment by kenwheeler** [comment]
I could expose those as wrapped props, I'm assuming you'd be expecting a promise to be returned with the result of the query?

**Comment by quadsurf** [comment]
Yes... it would be a lot more convenient that way, thank you... love what you're doing here! I've used your Victory charts before too, great OSS!

**Comment by kenwheeler** [comment]
Thanks! I'll make it so.

**Comment by kitten** [comment]
@kenwheeler I have some concerns around exposing these methods. It'll make the public API on the render props even larger than it already is, and might get us into a situation where we lose some "manoeuvrability" if we change how urql executes queries. In such a case we'd have to reimplement `executeQuery` just for this API to continue working.

So overall I'd suggest against this and rely on the user being able to call `client.executeQuery`. Afterall that's just 7 characters more and we won't have to guarantee it :wink:

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️
