### ISSUE TITLE
svelte: exchange-graphcache@^4.3: cache-and-network doesn't work for cached data

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#1904]
I think I found a bug.

### REPL
https://github.com/frederikhors/issue-urql-graphcache-4.3-cache-and-network-doesnt

I cannot reproduce it on codesandbox (I'm using SvelteKit locally). But I can reproduce it with few lines of code in that dedicated repo.

### Steps to reproduce:

1. `git clone https://github.com/frederikhors/issue-urql-graphcache-4.3-cache-and-network-doesnt`
1. `npm install`
1. `npm run dev`
1. open browser incognito mode at http://localhost:3000
1. the first time it fetch and cache correctly in indexeddb
1. if you reload the page it doesn't fetch anymore! And it should because of `cache-and-network`

### Code

- package.json:

```json
"@urql/exchange-graphcache": "4.3.2",
"@urql/svelte": "1.3.0",
```

- urql.ts:

```ts
const storage = makeDefaultStorage({
  idbName: "myCache",
  maxAge: 2,
});

const exchanges = [
  dedupExchange,
  offlineExchange({
    storage
  }),
  fetchExchange,
];
```

A simple query like this:

```ts
const USER_QUERY = `
{
  user {
    id
  }
}
`;

const user = query(
  operationStore(
    USER_QUERY,
    {},
    { requestPolicy: "cache-and-network" }
  )
);
```

**doesn't get "revalidate"**, `user` has `stale: true` and **the `cache-and-network` call never starts** (the user is cached in IndexedDB correctly).

The same code **works well with: `"@urql/exchange-graphcache": "4.2.1"`**.

I'm not crazy and I remove node_modules and use incognito mode every time.

**Comment by frederikhors** [comment]
I cannot reproduce it on codesandbox (I'm using SvelteKit locally). But I can reproduce it with few lines of code in a dedicated repo I'll push in a moment.

**Comment by frederikhors** [comment]
REPL added in the first post.

**Comment by frederikhors** [comment]
REPL and steps added in the first post.

**Comment by kitten** [comment]
Thanks for providing the reproduction! It's been pretty simple to pin this one down as I saw that we forgot to remove the `hasNext` flag from stale responses, generated by Graphcache, after shipping an update to the `dedupExchange` for the `@defer` & `@stream` support.
