### ISSUE TITLE
Infinite loop with `useQuery` variables

### ISSUE THREAD

**Issue by scyclow** [FormidableLabs/urql#192]
Something weird is going on when I pass variables into a `useQuery` hook, which is causing my component to rerender in an infinite loop. I've replicated a couple of times, and it seems to only occur when I pass it a `variables` object.

Here is an example of a component:
```ts
type PostQuery = {
  postById?: { id: number }
}
const postQuery = `
query postById ($id: Int!) {
  postById (id: $id) {
    id
}`

const Post: React.SFC<{ id: number }> = ({ id }) => {
  const [{ error, fetching, data }] = useQuery<PostQuery>({ 
    query: postQuery, 
    variables: { id } 
  })

  return (
    <section>
        {error && <DisplayError error={error} />}
        {fetching && <Loading />}
        {data && <Post post={data} />}
    </section>
  )
}
```

I looked at the source, and I think this might be the issue: https://github.com/FormidableLabs/urql/blob/master/src/hooks/useQuery.ts#L54

I think `useEffect` does a `===` comparison on everything passed into that array. So in my case, I think it's running the check `{ id: 5 } === { id: 5 }`, which continuously evaluates to `false` and leads to another call on `executeQuery`.

**Comment by kitten** [comment]
Ah, damn! Sorry, I've just taken a look and we've indeed messed that up. I must have missed it in code review since we wanted to have v1 ready to go. Thanks for giving it a test round! :heart:

I've got a branch with a fix and I'm just updating some docs and will get that ready in a minute

**Comment by kitten** [comment]
Published a hotfix for this issue along with one for #188. Thanks again for having a look at urql v1 🙌

**Comment by scyclow** [comment]
Awesome, thanks for the quick turnaround! Just gave it a test run, and everything looks good. Really liking the v1 interface so far!

**Comment by Elijen** [comment]
Is there possibly a regression? I have just noticed this behavior after `yarn install`
