### ISSUE TITLE
Is `pause` type missing in `context` using Svelte?

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#1924]
Is `pause` type missing in `context` using Svelte?

**urql version & exchanges:**

```json
"@urql/exchange-graphcache": "4.3.3",
"@urql/svelte": "1.3.0",
```

**Steps to reproduce**

```ts
const players = operationStore<PlayersQuery, PlayersQueryVariables>(
  PlayersDocument,
  { condition },
  { requestPolicy: "cache-and-network", pause: !search }
);

query(players);

$: players.variables = { condition };

$: players.context. ???
```

![image](https://user-images.githubusercontent.com/41120635/132107538-7a579574-9115-46b4-9f3a-58844834b66f.png)

![image](https://user-images.githubusercontent.com/41120635/132107595-bb407ad9-2e7e-458f-91cd-08b3e496657e.png)

**Comment by kitten** [comment]
This is probably our bad for not highlighting it in the docs, but `pause` (in none of the bindings) is a context-specific option. It's always a local property of telling your binding that you're not interested in data right now. In other words, it's a way of specifying that you're not using any operation reactively but rather imperatively, hence it's not a built-in option but common yet isolated to bindings' implementations

**Comment by frederikhors** [comment]
Ok. I'm scratching my head.

`pause` is working good for me. What I need is to see it in VSCode when I type the dot after `context`.

Right now `pause` is `any` for VSCode.

This is my issue.
