### ISSUE TITLE
[Graphcache] null vs undefined for nested arguments

### ISSUE THREAD

**Issue by steinroe** [FormidableLabs/urql#1964]
Hi,

awesome work!

I am trying to implement a relay pagination resolver that works with nested pagination variables, e.g. 
```
{
  flows(paging:{before:"1", last: 100}) {
    edges {
      node {
        id
      }
    }
  }
}
```

I simply copied the default one and changed a few lines of code to access the nested object. Here is the full implementation: https://gist.github.com/steinroe/62f9766c1e03e8bca78cd5ce2314f7e5

Now, all tests where null is written to the store as an argument fail, e.g.
`write(store, { query: Pagination, variables: { cursor: null } }, pageOne);`

This is because
```typescript
const hasCurrentPage = !!ensureKey(
      cache.resolve(entityKey, fieldName, fieldArgs)
    );
```
returns false.

With some debugging I found out that if undefined is written instead, e.g.
```typescript
write(store, { query: Pagination }, pageOne);
```
it works fine. The issue seems to be that `write` removes all undefined and null values when writing to the cache, but not for nested arguments. When writing with `cursor: null`, the fields are
```
[
      {
        fieldKey: 'items({"paging":{"after":null,"first":1}})',
        fieldName: 'items',
        arguments: { paging: [Object] }
      },
      {
        fieldKey: 'items({"paging":{"after":"1","first":1}})',
        fieldName: 'items',
        arguments: { paging: [Object] }
      }
    ]
```
and since the field args are `{ paging: [Object: null prototype] { first: 1, after: undefined } }`, it cannot find the field. When writing with cursor undefined, the fields are
```
[
      {
        fieldKey: 'items({"paging":{"first":1}})',
        fieldName: 'items',
        arguments: { paging: [Object] }
      },
      {
        fieldKey: 'items({"paging":{"after":"1","first":1}})',
        fieldName: 'items',
        arguments: { paging: [Object] }
      }
    ]
```
and when resolving with `{ paging: [Object: null prototype] { first: 1, after: undefined } }` the page is found as expected.

I am not sure whether this is a bug or intended, since `write` is expected to `skip undefined values that are expected` https://github.com/FormidableLabs/urql/blob/c9a5ef1fe769c6600054ff385c7d0743474127b0/exchanges/graphcache/src/operations/write.test.ts#L157

urql version & exchanges:
```
"urql": "^2.0.4",
"@urql/exchange-auth": "^0.1.6",
"@urql/exchange-graphcache": "^4.3.1",
```

Happy to provide a reproduction if required!

**Comment by kitten** [comment]
This basically isn't a bug and you can often see me talk about how `undefined` is a _useful_ distinction when handling JSON data or GraphQL 😆 But that's a little besides the point.

When you have a variables definition like:

```graphql
query ($test: Int) {}
```

Then `{ test: null }` is a valid and acceptable way to resolve this, but `{ test: undefined }` is not. However, when the input is [an "input object" value](https://spec.graphql.org/June2018/#sec-Input-Object-Values) then the actual structure is unknown. In other words, `input Paging` could contain any fields which aren't known to Graphcache or any other traversal by looking at the document only. Hence, the technically incorrect input of `undefined` can't be safely coerced to `null`. Any input object is simply passed on as it's received.

**Comment by steinroe** [comment]
Makes sense, thanks for the clarification!
