### ISSUE TITLE
RFC: Having similar behaviour for useQuery and useMutation (react)

### ISSUE THREAD

**Issue by Miraj98** [FormidableLabs/urql#1974]
## Summary

`useQuery` and `useMutation` have very different behaviours specifically w.r.t the tuples they return. I like the way `useMutation` works. It returns `[result, executeMutation]` when called. `useMutation` does not automatically make an initial request unlike `useQuery` which makes an api call automatically unless specified otherwise using the `pause` option. The other thing is `executeQuery` returned from `useQuery` does not return a promise which makes it difficult to work with especially when queries need to be executed when say a button is pressed and things need to be handled from there on based on the response from that query.

## Proposed Solution

`executeQuery` should work exactly like `executeMutation`, meaning it should return a promise which resolves to the response of that query. Also, I would personally prefer `useQuery` to not execute automatically because that seems more logical to me and there should be an option to execute automatically. Basically the default behaviour should be opposite of what it is right now because the current behaviour is not at all intuitive.

**Comment by kitten** [comment]
In the past we'd actually recommend `client.query`, i.e. "manual client usage" for these cases. The reason being that it can be extremely quick to fire off a single request, when it's imperative as you say, and for the other cases `pause: true` is more suitable 

We also haven't encountered a majority of cases where pausing `useQuery` or using imperative queries makes sense, hence it's more of a secondary role, since firing off one off requests isn't too hard based on the core logic in the Client ✌️

**Comment by Miraj98** [comment]
@kitten 
I actually use some graphql codegen which internally seems to be using `useQuery`. And hence you can see why it might be frustrating to use `client.query` separately especially given the fact I am using typescript and the codegen simply handles the types for me.

Also playing around with `useQuery` revealed some buggy behaviour. I have `pause: true` and I tried calling `executeQuery` "manually". It does not seem to work the first time, but calling it again seems to work. Any idea about this or should I open a separate issue for this?

**Comment by kitten** [comment]
Are you using GraphQL Code Generator? Because if so you could switch to generating `TypedDocumentNode`s which work with any of our APIs where you pass queries. https://www.graphql-code-generator.com/docs/plugins/typed-document-node

**Comment by kitten** [comment]
> I have pause: true and I tried calling executeQuery "manually". It does not seem to work the first time, but calling it again seems to work. Any idea about this or should I open a separate issue for this?

It's possible that something isn't quite right there; either in usage or something else, so feel free ❤️

**Comment by frederikhors** [comment]
Hi guys! Is there any docs on how to use https://www.graphql-code-generator.com/docs/plugins/typed-document-node with https://www.graphql-code-generator.com/docs/plugins/typescript-urql?

**Comment by taneba** [comment]
@frederikhors 
If you'd like to use typed-document-node, you don't need to use typescript-urql plugin.
All you need to do is just passing generated TypedDocumentNode to useQuery:

```ts
import { useQuery } from 'urql'
import { GetPostDocument } from './generated/graphql'

const [res, executeQuery] = useQuery({
  query: GetPostDocument,
  variables: { id: "1" },
})
```

**Comment by taneba** [comment]
@kitten 
Sorry for cutting in, but what is the desired behavior of pause: true and calling executeQuery situation?
It doesn't seem to be "executed" in that situation unless set pause: false manually as it uses the same context.

**Comment by kitten** [comment]
Copying this over from #1982, since it belongs here:

> @Miraj98: "Urql really needs to have a separate `useLazyQuery` hook. I know `pause: true` achieves that but it's not good api design and is frustrating to use. The perfect solution is having a separate hook for this which returns `executeLazyQuery`. We can have this function accept the query variables directly instead of passing them through the hook. This will also be more efficient because `useQuery` runs a few checks every time the inputs to the hook change. Hence a separate lazy hook will have a simpler implementation and will be more performant.
> 
> @Miraj98: "I know there have been previous discussions around adding `useLazyQuery` but there seems to be a lack of intent to add that api. Mostly the reason given is `pause: true` works just fine. But honestly it's not a great way to implement it given a better approach is possible."

And my reply:

> I honestly don't think that's accurate, sorry 😅 In any case, what it's always been is a one-switch solution to toggle between the two modes. That's an important distinction, since it also enables you to pause any ongoing changes as you see fit, meaning that the hook enables a lot more use cases than two separate ones.
>
> You can feed it changing inputs and it will reactively change what query it actively provides results for. When you combine that with `pause` you can declaratively ignore certain inputs, e.g. for a search form with a minimum length inputs, or form validation.
>
> You can enable pause and imperatively feed it inputs and trigger the hook with `executeQuery`.
>
> You can defer the query either by setting `pause` to false later on or calling the `executeQuery` function as a one-off.
>
> I could go on, but basically, it enables all use-cases that you could throw at it, while remaining a declarative and reactive hook. For all imperative-only patterns (if I press a button, _then_ something happens, and only then) we'd always recommend the client methods. That's what a lazy hook would otherwise often be used for, which would be redundant 😅
> 
> Anyway, I can hope you come around to this API design, however, a note on the bug is, just because we regressed on a feature or API — while it obviously alters trust and perception to it temporarily — doesn't make it redundant in my opinion

**Comment by JoviDeCroock** [comment]
Closing it as `pause` delivers the functionality of `useLazyQuery`

**Comment by villesau** [comment]
@kitten I think it is fairly common to load data based on user action. In that case generated `client.query(GetSomeDocument, { data: here }).toPromise();` would make to improve the type safety. e.g in my case I'm loading upload url when user selects file. I don't want to tie it to component lifecycle since that would be unnecessary and increase complexity. It is cleaner and easier to understand to do it directly in a callback.

I don't think that hook is needed for that kind of case, instead it could be totally react agnostic.

**Comment by andvalsol** [comment]
Adding a bit more on what @villesau  has mentioned, here's some example of what `useLazyQuery` can be:
`import { TypedDocumentNode } from '@graphql-typed-document-node/core';
import { CombinedError, OperationContext, RequestPolicy } from '@urql/core';
import { DocumentNode } from 'graphql';
import { useClient } from 'urql';

export interface UseLazyQueryState<Data = any> {
  data?: Data;
  error?: CombinedError;
}

export interface UseLazyQueryArgs<Variables = object, Data = any> {
  query: string | DocumentNode | TypedDocumentNode<Data, Variables>;
  variables?: Variables;
  requestPolicy?: RequestPolicy;
  context?: Partial<OperationContext>;
}

const useLazyQuery = <Data = any, Variables = object>(
  args: UseLazyQueryArgs<Variables, Data>,
) => {
  const client = useClient();

  return async (): Promise<UseLazyQueryState<Data>> => {
    const query = args.query;
    const variables = args.variables ?? {};
    const { data, error } = await client.query(query, variables).toPromise();
    return { data, error };
  };
};

export default useLazyQuery;
`
