### ISSUE TITLE
[debug exchange] Expose callbacks to allow users to decide how to log

### ISSUE THREAD

**Issue by Undistraction** [FormidableLabs/urql#1976]
## Summary

Currently logging from the [debug exchange](https://github.com/FormidableLabs/urql/blob/ef4b5b002d31e17d84fb41e5feb24d2200c9656f/packages/core/src/exchanges/debug.ts) is not configurable. By exposing callbacks users can decide what mechanism to use for logging. 

## Proposed Solution

Expose callbacks that allows somebody using the exchange to define how they would like to log operations. Currently this is hardcoded to `console.log`, and happens on Incoming and Completed operations. Being able to log out using a logger would allow better integration with logging used elsewhere in a client. `console.log` could remain the default behaviour, allowing backwards compatibility.

## Requirements

Allow handlers to be passed in to the exchange at initialisation:

```
debugExchange({
  onIncoming: ({operation}) => {
    exchangeLogger.info(`Incoming`, {body: operation})
  },
 onComplete: ({operation}) => {
    exchangeLogger.info(`Complete`, {body: result})
  }
})
```

**Comment by JoviDeCroock** [comment]
I think the work in https://github.com/FormidableLabs/urql/pull/1743 should cover this, but as it stands that's a breaking change and lined up for the next major of core.
