### ISSUE TITLE
Next, SSR, authExchange and cookie auth

### ISSUE THREAD

**Issue by saevarb** [FormidableLabs/urql#1986]
### Discussed in https://github.com/FormidableLabs/urql/discussions/1973

<div type='discussions-op-text'>

<sup>Originally posted by **saevarb** September 20, 2021</sup>
Hello.

I have built a nextjs application, and that same server hosts a GQL API which I am querying with urql. Authentication is done via an HTTP-only cookie, and I'm using next-urql.

I also want to use `getServerSideProps` to authenticate my pages, in case that is relevant.

My question is: How do I properly configure `authExchange` (and I guess any other relevant part of urql) so that urql can run during SSR when using cookie auth? It seems to me that on the server, I need to be able to access the next context's request and grab the cookie, so we can use it on the user's behalf. When on the client, nothing special needs to be done because the cookie is send automatically.

I thought I might be able to do this using the `context` parameter given by `withUrqlClient`, but it seems that this is always undefined on the server.
</div>

The documentation seems to state that we should be able to make use of the next context, but given that it is `undefined` every time on the server, this seems like a bug.

**Comment by JoviDeCroock** [comment]
`context` is injected when using the `ssr: true` option which utilizes `react-ssr-prepass` and `getInitialProps` to aggregate data upfront, if you need the context in `getServerSideProps` you'll have to incorporate the passing of said context in the server-side function like this:

```js
export async function getStaticProps(ctx) {
  const ssrCache = ssrExchange({ isClient: false });
  const client = initUrqlClient({
    url: 'your-url',
    // pass in the ctx from the upper function in here
    exchanges: [dedupExchange, cacheExchange, ssrCache, fetchExchange],
  });

  await client.query(TODOS_QUERY).toPromise();

  return {
    props: {
      urqlState: ssrCache.extractData(),
    },
    revalidate: 600,
  };
}
```
