### ISSUE TITLE
Documentation misspelling "interally"

### ISSUE THREAD

**Issue by app** [FormidableLabs/urql#1990]
At https://formidable.com/open-source/urql/docs/architecture/  
You can find this  
![image](https://user-images.githubusercontent.com/9341/134797162-267e0d26-8513-4e8b-bf50-b706aa5e52e6.png)

**Comment by kitten** [comment]
Hiya 👋 We happily accept PRs fixing typos or mistakes in the docs, however we can't accept _bug_ tickets for them. Typos are common and if we had an issue per typo we'd have to read 100 issues to fix just 100 missing/added letters in the docs 😅 But I know it's well intentioned, so thank you!
