### ISSUE TITLE
3-Way Data Binding

### ISSUE THREAD

**Issue by quadsurf** [FormidableLabs/urql#20]
For this to work, it can't just be the client listening for changes on the server, but the server has to also be listening for changes in the local store, in order for this to work.

I know this feature suggestion sounds a bit premature/ridiculous, but it's only a matter of time before someone comes out with it, so why not Formidable haha?! I know this is done via web sockets between Angular and Firebase, but here's what that might look like in the React/GraphQL world:

https://docs.google.com/presentation/d/1NjjbYW-TaAdxyydwcGx9BoP2eSVp2Sh6hMzmxrOstDU/edit?usp=sharing

**Comment by kitten** [comment]
In `next` this can be addressed by a custom `exchange` (Our version of Apollo Link but farther-reaching). The library might need further changes though.

I was planning to make Query components _reactive_ to cache changes and remove their own cache logic. This would make this 100% possible via a custom `exchange`.

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️
