### ISSUE TITLE
(next-urql) Query doesn't fetch from network and show stale results after resetUrqlClient but results show stale:false

### ISSUE THREAD

**Issue by Biboswan** [FormidableLabs/urql#2031]
We discovered this more than a month ago. But this bug exists till now. Once the client is reset using `resetUrqlClient`, the query doesn't return new results even when using` { requestPolicy: 'network-only' }`. It just returns old results
Checking the network tab I couldn't trace corresponding graphQL call but interestingly results.state shows `false` value
  
**urql version**
next-urql: 3.2.1
urql: 2.0.5

**exchanges**:
[devtoolsExchange,dedupExchange, cacheExchange, _ssrExchange, fetchExchange]

**Comment by Biboswan** [comment]
I didn't get time to show a minimal reproducible yet. I will be on away for few weeks. But the issue remains. So will get back asap.

**Comment by JoviDeCroock** [comment]
Closing due to stale, feel free to open with a reproduction when possible
