### ISSUE TITLE
(svelte) - nested queries are blocked

### ISSUE THREAD

**Issue by jney** [FormidableLabs/urql#2042]
I try to run queries in store instead of in `.svelte` components, probably because of [this](https://github.com/svelte-society/recipes-mvp/issues/6).
Anyway, running a query inside `subscribe` function another one is blocking.
Not sure if it is the expected behavior.

urql version & exchanges:

`"@urql/svelte": "^1.3.1"`

**Steps to reproduce**

```js
  // 1st query
  query(operationStore(query, vars)).subscribe((res) => {
    if (res.fetching) {
      return;
    }
    // nested query
    query(operationStore(query, vars)); // blocked there
    doSomething() // never reached
  })
```

**Comment by kitten** [comment]
Obsolete and potentially resolved by: https://github.com/FormidableLabs/urql/pull/2370
The API basically now just exposes store factories that are a transparent conversion from sources to a readable store.
