### ISSUE TITLE
GET method: strip whitespaces

### ISSUE THREAD

**Issue by emateu** [FormidableLabs/urql#2051]
For GET requests, `urql` was stripping whitespaces correctly: https://github.com/FormidableLabs/urql/pull/908/files

I believe after this https://github.com/FormidableLabs/urql/pull/1851 it stopped removing the whitespaces.

If the GET query has white spaces, it will go thru in this way....
<img width="451" alt="Screen Shot 2021-10-28 at 23 51 07" src="https://user-images.githubusercontent.com/629964/139365775-68a6f2ef-4ee4-4288-8eb3-1c184d33db66.png">

And we might end up getting unexpected `414` errors.

**Steps to reproduce**
Perform a GET query with redundant whitespaces.

**Expected behavior**
Redundant whitespaces get stripped.

**Actual behavior**
Redundant whitespaces are not stripped.

**Comment by JoviDeCroock** [comment]
We won't fix this as part of core due to the reasoning of @kitten but this can be done in an exchange.
