### ISSUE TITLE
(next-urql) - staleWhileRevalidate flag doesn't trigger a network request

### ISSUE THREAD

**Issue by yoshiwarab** [FormidableLabs/urql#2059]
urql version & exchanges:

urql@2.0.5
next-urql@3.2.1
next@11.1.0

dedupExchange, cacheExchange, ssrExchange, fetchExchange

**Steps to reproduce**
You can view the issue by visiting this [codesandbox](https://codesandbox.io/s/urql-stale-while-revalidate-bug-lziis).  I'm console logging the stale flag returned by the useQuery hook, and it's being set as expected while using the staleWhileRevalidate flag (i.e. stale on first render and then not stale after a new request should have been made). However, while watching the network tab in devtools, you can see that no actual network request is being made.  I would expect that the query results should only be marked as not stale after a new request has been made. 

Thanks for the awesome library, and please let me know if I can do anything else to help get this resolved or if I've done something wrong in my setup!

**Comment by reza-akbari** [comment]
I see the same issue with urql v2.2.2 and next-urql v3.3.3
when setting `staleWhileRevalidate` to true the `stale` flag remains true without any network requests
