### ISSUE TITLE
@urql/exchange-auth has no types

### ISSUE THREAD

**Issue by ollydixon** [FormidableLabs/urql#2066]
Standard Svelte typescript project created with Vite.

`Cannot find module '@urql/exchange-auth' or its corresponding type declarations.`

**Comment by JoviDeCroock** [comment]
It does and points correctly at the file https://www.runpkg.com/?@urql/exchange-auth@0.1.6/package.json#24

**Comment by ollydixon** [comment]
@JoviDeCroock thanks for the speedy reply.

Not sure where I'm going wrong here, other packages seem to work just fine :-/

<img width="443" alt="Screenshot 2021-11-08 at 18 11 57" src="https://user-images.githubusercontent.com/6940726/140787189-7573e8c9-1e76-404d-a669-dc860f2dad57.png">

**Comment by ollydixon** [comment]
After ```npm install --save @urql/exchange-auth```

**Comment by JoviDeCroock** [comment]
What do you see when you click into the `node_modules`? Do you see the `types` entry for `package.json` and can you follow it to the types file? Maybe there's something wrong in TypeScript or the way we do the pathing

**Comment by ollydixon** [comment]
Indeed it looks correct. Hmm.

<img width="772" alt="Screenshot 2021-11-08 at 18 15 04" src="https://user-images.githubusercontent.com/6940726/140787634-b07d8c3c-45b8-4190-9bba-b0d9e6bf6ab2.png">

Perhaps try with Svelte TS; ```npx degit user/project my-project``` ?

**Comment by ollydixon** [comment]
@JoviDeCroock do you know if there's an easier way to just set the headers? 

The ```exchange-auth``` looks over-engineered, like with other libraries you just called .setHeaders({})

Even with a custom type (to override this error), we still can't get it working properly. :-/

**Comment by JoviDeCroock** [comment]
You can leverage `context.fetchOptions` https://formidable.com/open-source/urql/docs/basics/svelte/#context-options

**Comment by ollydixon** [comment]
@JoviDeCroock yeah we tried that, doesn't work, this is a test project, all one file.

I get that, but most of the time we have our own ways to deal with auth; and keeping it simple is best!

```
  function onJwtChange() {
    /// This is fired but the token doesn't change.
    graphQLClient.fetchOptions = {
      headers: {
        authorization: currentJwt ? `Bearer ${currentJwt}` : "", //
        "Access-Control-Allow-Origin": "*",
      },
    };
    console.log("JWT changed: " + currentJwt);
  }
```

**Comment by JoviDeCroock** [comment]
Those fetchOptions are part of a `query` there
