### ISSUE TITLE
Cannot read property 'redirect' of undefined

### ISSUE THREAD

**Issue by jdgamble555** [FormidableLabs/urql#2071]
I am using @urql/core with sveltekit.  I imagine this is an easy fix.

urql version & exchanges:

    dedupExchange,
    cacheExchange,
    fetchExchange,
    subscriptionExchange,

Latest Version

**Steps to reproduce**

Ran url/core with sveltekit

**Expected behavior**

No Error Message

**Actual behavior**

![Errors](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8l2u6dugdcl24fma4qzy.png)

**Comment by kitten** [comment]
This sounds like you have a `fetchOptions` option set to a function on your `Client` that is returning `undefined`

Please note that without a reproduction or code, we can't look into this further 😅 https://raw.githubusercontent.com/FormidableLabs/urql/main/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by jdgamble555** [comment]
Okay, so I simplified my code and I have this:

**urql.ts**
```typescript
import { createClient } from "@urql/core";

const client = createClient({ url: `https://my dgraph url` });

export default client;
```

**index.svelte**
```typescript
<script context="module" type="ts">
  import client from '../modules/urql';

  const r1 = `
    query {
      queryResource {
        content
        title
        id
      }
    }
  `;

  export async function load() {
    const r = await client.query(r1).toPromise();
    console.log(r);
    return { props: { resources: r.data?.queryResource } };
  }
</script>

<script type="ts">
  export let resources: any[];
</script>

<h1>Welcome</h1>

<ul>
  {#if resources}
    {#each resources as resource (resource.id)}
      <li>{resource.title}</li>
    {/each}
  {/if}
</ul>
```

I want it to load on the backend for ssr (I had no problems in a previous project).

**package.json**
```typescript
  "devDependencies": {
    "@sveltejs/adapter-vercel": "next",
    "@sveltejs/kit": "next",
    "@typescript-eslint/eslint-plugin": "^4.31.1",
    "@typescript-eslint/parser": "^4.31.1",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-svelte3": "^3.2.1",
    "node-sass": "^6.0.1",
    "prettier": "^2.4.1",
    "prettier-plugin-svelte": "^2.4.0",
    "svelte": "^3.42.6",
    "svelte-check": "^2.2.6",
    "svelte-preprocess": "^4.9.4",
    "tslib": "^2.3.1",
    "typescript": "^4.4.3"
  },
  "type": "module",
  "dependencies": {
    "@urql/svelte": "^1.3.2",
    "firebase": "^9.4.0",
    "graphql": "^16.0.1",
    "subscriptions-transport-ws": "^0.11.0",
    "urql": "^2.0.5",
    "ws": "^8.2.3"
  },
```
Thanks,

J

**Comment by JoviDeCroock** [comment]
That would mean that we somehow have an `undefined` `fetchOptions` being passed into `makeFetchSource` which seems impossible judging from the `fetchExchange` code 😅 maybe vite/svelte is doing some magic
