### ISSUE TITLE
(core) - maskTypename option mangles nested lists in JSON result

### ISSUE THREAD

**Issue by rifton007** [FormidableLabs/urql#2072]
I want to fix this strange behavior, Urql converts some array to object.
The property `nodes` is an array wich contains tuples of arrays, for example : 

```javascript
nodes : [[0,5],[10,12],[14,18]]
```

> But after retrive data of Urql query, Urql returns objects
![image](https://user-images.githubusercontent.com/2601347/140918933-29eef163-d472-454a-a4c9-90b572b9d0c7.png)
![image](https://user-images.githubusercontent.com/2601347/140919001-6e9340a9-7e8a-4aaa-a792-cb15d1f77d13.png)

> But, like you can see, the response of graphql and database is arrays, not objects.
![image](https://user-images.githubusercontent.com/2601347/140919409-19cc56bf-d0e1-4139-9c29-f729b9037cd4.png)

> To be sure, same verification with GraphQLi
![image](https://user-images.githubusercontent.com/2601347/140921022-bb83ec85-9615-496d-8403-e40c64ff9257.png)

My opinion is that Urql converts the array to object, is it possible ?

urql version & exchanges: @urql/core@2.3.4

**Steps to reproduce**
The Urql query retrives objects instead arrays.

**Expected behavior**
Urql query returns arrays
**Actual behavior**
Urql query returns objects

**Comment by kitten** [comment]
Can you post a reproduction here, like queries, data samples, or a minimal reproduction sandbox? That'll really help speed up how long it'll take for us to look into this, since otherwise we'll have to start from scratch. Screenshots are fine for illustration purposes, but they're static and it's easier for us to have the queries on hand ❤️ 

Also, we'll need steps to reproduce this and information about your environment. For instance, I'm assuming you must be using `@urql/exchange-graphcache`?

**Comment by rifton007** [comment]
When you have spoken about `@urql/exchange-graphcache`, I have commented it and that resolves the problem.

```javascript
  const urql = createClient({
    url: url,
    fetchOptions: {credentials: 'include'},
    exchanges: [
      dedupExchange,
      // cacheExchange, => disabled this resolve the problem.
      authExchange({//...}),
      ssr,
      fetchExchange
    ],
    requestPolicy: 'network-only',
    maskTypename : true
  });
```

Same `console.log()`
![image](https://user-images.githubusercontent.com/2601347/140962054-4cdab873-1174-49e4-864e-47e56442f690.png)




If you need yet more information , I'll add it later.
Thanks

**Comment by kitten** [comment]
Do you have any configuration on the `cacheExchange` from `@urql/exchange-graphcache`?

**Comment by rifton007** [comment]
I don't have installed `@urql/exchange-graphcache`
I only activate the `cacheExchange` like in documentaiton, no particular configuration.

**Comment by JoviDeCroock** [comment]
All right, that's a good detail to have that means it's in our document-cache we have this bug

**Comment by rifton007** [comment]
If it can help, here is my package.json

```json
{
  "name": "app",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@ciruxx/joi-extension-objectid": "^1.0.2",
    "@nuxtjs/axios": "^5.12.5",
    "@nuxtjs/proxy": "^2.1.0",
    "@riophae/vue-treeselect": "^0.4.0",
    "@shopify/draggable": "^1.0.0-beta.12",
    "@urql/core": "^2.1.4",
    "@urql/exchange-auth": "^0.1.3",
    "@urql/introspection": "^0.2.0",
    "bootstrap": "^5.0.2",
    "bricks.js": "^1.8.0",
    "column-resizer": "^1.3.6",
    "cookie-universal-nuxt": "^2.1.5",
    "core-js": "^3.15.1",
    "dayjs": "^1.10.4",
    "element-ui": "^2.15.6",
    "express": "^4.17.1",
    "graphql": "^15.5.1",
    "graphql-combine-query": "^1.2.3",
    "graphql-tag": "^2.12.5",
    "http-proxy-middleware": "^2.0.0",
    "interactjs": "^1.10.2",
    "isomorphic-unfetch": "^3.1.0",
    "joi": "^17.4.2",
    "json-to-graphql-query": "^2.0.0",
    "lodash": "^4.17.20",
    "masonry-layout": "^4.2.2",
    "nuxt": "^2.13.3",
    "pluralize": "^8.0.0",
    "v-calendar": "^2.1.1",
    "vue-material-design-icons": "^4.12.1",
    "vue-tippy": "^4.10.2",
    "vuex-map-fields": "^1.4.1"
  },
  "devDependencies": {
    "@nuxtjs/router-extras": "^1.1.1",
    "babel-plugin-component": "^1.1.1",
    "fibers": "^5.0.0",
    "sass": "^1.35.1",
    "sass-loader": "^10.1.0"
  }
}
```
