### ISSUE TITLE
 Cannot read property 'operation' of undefined in `afterMutation`

### ISSUE THREAD

**Issue by reverie** [FormidableLabs/urql#210]
Just before the error:
<img width="973" alt="Screen Shot 2019-03-17 at 1 48 40 PM" src="https://user-images.githubusercontent.com/73446/54495608-6d384800-48bb-11e9-8b55-f5f4ca1d1ec8.png">

(Note the key value and the comment.)

Traceback:
<img width="1064" alt="Screen Shot 2019-03-17 at 1 47 23 PM" src="https://user-images.githubusercontent.com/73446/54495609-6f9aa200-48bb-11e9-900f-3fdeb525965a.png">

There's nothing unusual about the mutation itself. The only thing that's weird is that this error only happens if I first create the 'event' then send the 'invitation' without refreshing. (I'm creating an event-planning app.) If I create the event, then refresh, then send the invitation, it works without error.

**Comment by kitten** [comment]
@andyrichardson Mind taking a look here? seems to be sth with the invalidation logic going wrong.

@reverie like as I've requested in the other issue, can you attach some code snippets please? The description is quite vague, so it's tough for us to imagine which order things are actually being done in to reproduce this bug :)

**Comment by reverie** [comment]
@kitten Not sure what snippet would be interesting, I feel like I’m just using it normally. What if I gave you or @andyrichardson repo access and repro instructions?

**Comment by federicobadini** [comment]
I have experienced this problem too and I think it can be quite easily reproduced. I have attached a picture describing a typical scenario that would lead to the problem depicted above.
[
<img width="993" alt="Screenshot 2019-03-23 at 16 57 33" src="https://user-images.githubusercontent.com/7805759/54868626-b0e4f300-4d8e-11e9-949f-20084bbb9854.png">
](url)
Here we have two different subsequent mutations which impact on the same data, causing a refetch query being triggered twice.

In this scenario, if the query pointed by the arrow takes longer than the subsequent mutation, `resultCache.get(key)` (on the third last line of the attached code) will be undefined for the second query triggering an error.

``` js
// Invalidates the cache given a mutation's response
export const afterMutation = (
  resultCache: ResultCache,
  operationCache: OperationCache,
  client: Client
) => (response: OperationResult) => {
  const pendingOperations = new Set<number>();

  collectTypesFromResponse(response.data).forEach(typeName => {
    const operations =
      operationCache[typeName] || (operationCache[typeName] = new Set());
    operations.forEach(key => pendingOperations.add(key));
    operations.clear();
  });

  pendingOperations.forEach(key => {
    const operation = (resultCache.get(key) as OperationResult).operation; // Result is guaranteed
    resultCache.delete(key);
    reexecuteOperation(client, operation);
  });
};
```

**Comment by federicobadini** [comment]
I have seen the PR, however I am not really convinced it completely solves the problem.
In a scenario like the one depicted above, with two mutations impacting on overlapping data, if the query marked with the arrow takes longer than the second mutation to complete, the final result produced by the two subsequent mutations will not be fetched.
The first query finds and removes the operation key from the map and basically prevents the second query to even execute.
