### ISSUE TITLE
`const [state, createSomething] = useMutation(your_mutation)`; `state` is not updated after the mutation is executed

### ISSUE THREAD

**Issue by futurechallenger** [FormidableLabs/urql#2109]
**urql version & exchanges**:

urql@2.0.5 with default exchanged:

```js
import { Client, defaultExchanges } from 'urql';

export const createClient = () =>
  new Client({
    url: 'http://localhost:9090/graphql',
    exchanges: defaultExchanges,
  });

```

**Steps to reproduce**

1. 2.

**Expected behavior**
Here's the code:
```js
const [state, executeMutation] = useMutation(mutation);
```

Expect the `state.fetching` becomes `false` or equivalent value from `true`, after the api request has response.

**Actual behavior**

The `state` is not updated, but the value in the promise has updated values, which `refresh` is undefined then.

**NOTE**
I'm using react@18

**Comment by kitten** [comment]
The `useMutation` hook is pretty simple, so I can't imagine the state to get lost unless the component holding it remounts, so I'll have to ask for a minimal reproduction here; for reference, here you can see that `useMutation` doesn't really do much beyond setting some local state: https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/src/hooks/useMutation.ts

**Comment by futurechallenger** [comment]
Code is:
```javascript
import React, { useState } from 'react';
import {
  Box,
  InputLabel,
  MenuItem,
  FormControl,
  Select,
  TextField,
  Button,
  CircularProgress,
} from '@mui/material';
import { useMutation } from 'urql';

import { mutation } from '../services/post.js';

/**
 * TODO: make add field more flexible like request tools
 */
function Post() {
  const [method, setMethod] = useState('');
  const [state, executeMutation] = useMutation(mutation);

  const handleChange = event => {
    setMethod(event.target.value);
  };

  const handleSubmit = async event => {
    console.log('handle submit> ', event);
    const fieldsValue = {
      title: event?.target?.[0]?.value,
      desc: event?.target?.[2]?.value,
      requestPath: event?.target?.[4]?.value,
      method: event?.target?.[6]?.value,
      requestParams: event?.target?.[8]?.value,
      published: event?.target?.[10]?.value,
    };

    executeMutation({ postInput: { ...fieldsValue } }).then(result =>
      console.log(':mutation result>', result),
    );
  };

  console.log(':>mutation state>', state);

  return (
    <Box sx={{ minWidth: 120 }} autoComplete="off">
      <form onSubmit={handleSubmit}>
        <FormControl fullWidth required>
          <TextField required id="title" label="Title" />
        </FormControl>
        <FormControl style={styles.formItem} fullWidth>
          <TextField required id="desc" label="Description" />
        </FormControl>
        <FormControl style={styles.formItem} fullWidth required>
          <TextField required id="requestPath" label="Request Path" />
        </FormControl>
        <FormControl style={styles.formItem} fullWidth required>
          <InputLabel id="requestMethod">Request Method</InputLabel>
          <Select
            labelId="requestMethod"
            id="requestMethod"
            label="Request Method"
            value={method}
            onChange={handleChange}>
            <MenuItem value="get">GET</MenuItem>
            <MenuItem value="post">POST</MenuItem>
          </Select>
        </FormControl>
        <FormControl style={styles.formItem} fullWidth>
          <TextField
            multiline
            id="requestParams"
            label="Request Params"
            fullWidth
            rows={3}
          />
        </FormControl>
        <FormControl style={styles.formSubmit}>
          {state.fetching && <CircularProgress />}
          {state.error && <div>{state.error?.message}</div>}
          {state.data && <div>{`Success: ${state.data}`}</div>}
          <Button variant="contained" disabled={state.fetching} type="submit">
            Submit
          </Button>
        </FormControl>
      </form>
    </Box>
  );
}

const styles = {
  formItem: {
    marginTop: '20px',
  },
  formSubmit: {
    marginTop: '50px',
  },
};

export { Post };
```

The log is
![image](https://user-images.githubusercontent.com/383584/143732971-0b87da0f-074f-4520-9bf6-04ee40333599.png)


From the code here: https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/src/hooks/useMutation.ts
When the `executeMutation` is called, the `isMounted.current` is already false, so the `setState` with `fetching: false` is not called. 
![image](https://user-images.githubusercontent.com/383584/143732988-098a9655-f9c5-4897-977c-ff267c6116ca.png)

**Comment by Dremora** [comment]
I can confirm the issue. Also I've noticed mutations break with React 17 in the same manner when the page gets refreshed via Fast Refresh.
There's something both share in common: effects get executed more than once (React 18 in dev mode executes all effects twice). Perhaps there's something inside `useMutation`'s logic that depends on its own effects being only executed once?

**Comment by Dremora** [comment]
Something [like this](https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/src/hooks/useMutation.ts#L72-L76). I think a fix would be rather trivial: set `isMounted.current = true` in the beginning of the effect.
