### ISSUE TITLE
RFC: Suspense option per-query

### ISSUE THREAD

**Issue by MasonD** [FormidableLabs/urql#2111]
## Summary
Currently suspense is an all-or-nothing thing enabled or disabled on the client for every useQuery. I'd like to see the option to overwrite the global setting on a per-call basis of useQuery.

## Proposed Solution
Add a `suspense` option to `UseQueryArgs` and use that over the global setting if present.

**Comment by JoviDeCroock** [comment]
This is already possible by leveraging the context.suspense option on useQuery https://formidable.com/open-source/urql/docs/api/core/#operationcontext

**Comment by MasonD** [comment]
Oh. Thanks. Sorry for missing that in the documentation.
