### ISSUE TITLE
RFC: Vue 2 support with vue-demi inclusion

### ISSUE THREAD

**Issue by dargmuesli** [FormidableLabs/urql#2118]
## Summary

I'm coming from Vue 2 with no realistic way to upgrade to Vue 3 just yet. I still want to start using urql, but urql-vue is currently only supported for Vue 3.

## Proposed Solution

By using [vue-demi](https://github.com/vueuse/vue-demi) it seems to be possible to make urql support Vue 2 too fairly simple.

Is that an option to you? I'd be highly pleased!

**Comment by kitten** [comment]
Closing this for now ✌️
Bot because vue-demi wasn't quite a good fit and this is the second attempt 😅 And, we're probably better off focusing on Vue 3 fixes and features
