### ISSUE TITLE
Generics support for Component

### ISSUE THREAD

**Issue by dotansimha** [FormidableLabs/urql#213]
Hi! 

I'm the maintainer of https://github.com/dotansimha/graphql-code-generator . 
[One of our community members suggested we should add a plugin](https://github.com/dotansimha/graphql-code-generator/issues/1575) that generates ready-to-use type-safe Components and hooks using your library. 
It sounds like a cool idea, but we currently not able to implement it because your implementation does not allow to override the type of `data` (https://github.com/FormidableLabs/urql/blob/master/src/components/Query.tsx#L16) or `variables`.

In the hooks implementation, we can pass the type using generics and override the `data` and `variables` types, which is great, because we can generate ready-to-use wrappers for it. 

It would be great to have support for generics, and then we'll implement the plugin for the codegen :)

**Comment by kitten** [comment]
Yes, we weren't quite sure how to implement the generics on the component so that inference works correctly in all edge cases, and since put more focus on our hooks now we haven't quite been spending time on that 😅

Open to suggestions on what's the norm though 👍

**Comment by dotansimha** [comment]
@kitten because React Components are just classes, you should easily add generics and then pass it to the props type, something like that:

```typescript

type QueryProps<T> = {
   variables: T;
}

type QueryState<T> = {
   data: T;
}

export class Query<TData = any, TVariables = any> extends React.Component<QueryProps<TVariables>, QueryState<TData>> {
  render() {
     // ...
  }
}
```

Then, to override it (we'll generate a similar output with the codegen):

```typescript
type MyCustomQueryData = {

};

type MyCustomQueryVariables = {

};

export class MyCustomQuery extends Query<MyCustomQueryData, MyCustomQueryVariables> { ... }
```

**Comment by kitten** [comment]
@dotansimha yep, that so far is clear, but when I've implemented generics on components in the past that'd mean that when inference breaks on JSX one would have to manually assign generics to the component which is troublesome in a `tsx` file.

**Comment by dotansimha** [comment]
@kitten any chance you can provide an example? I never noticed this issue before...

**Comment by kitten** [comment]
@dotansimha I don't have any TS codebase readily available, but I did hit this issue a long time ago, so I'm wondering whether it's simply been fixed.

**Comment by kitten** [comment]
Ok, seems like this is a non-issue now, since JSX+Generics will explicitly become easier in TS https://mariusschulz.com/blog/typescript-2-9-passing-generics-to-jsx-elements

**Comment by parkerziegler** [comment]
PR up for this in #249. @dotansimha please take a look and let me know if you think this would solve your use case. If so, I'll continue down this path to type `Mutation` and `Subscription`.

**Comment by dotansimha** [comment]
@parkerziegler looks great! Thank you!
