### ISSUE TITLE
Urql/core query/mutation typings is loosing the generic type information

### ISSUE THREAD

**Issue by marcinkoziej** [FormidableLabs/urql#2152]
Hi!

After upgrading @urql/core from 2.1.6 to 2.3.6 I started having problems with typing of the return value.

I have a query document generated by `@graphq-codegen/typescript-operations`, for example:

```
import { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";

GenerateKeyDocument : DocumentNode<GenerateKey, GenerateKeyVariables>;
```

Before, where I passed this to `Client.query(GenerateKeyDocument, { vars...} )`, I would get a result like this:
```
{
  data: GenerateKey;
  error: CombinedError;
}
```
Now, the generics seem to be lost somewhere and I get:
```
{
  data?: unknown;
  error: CombinedError;
}
```

I believe this is because the `Client.query` has a type:

```
  query<Data = any, Variables extends object = {}>(
    query: DocumentNode | TypedDocumentNode<Data, Variables> | string,
    variables?: Variables,
    context?: Partial<OperationContext>
  ): PromisifiedSource<OperationResult<Data, Variables>>;
```
 the query has an union type `DocumentNode` OR `TypedDocumentNode<Data, Variables>`, and it seems the GenerateKeyDocument matches DocumentNode first. This makes the TS inference not match it with `TypedDocumentNode<Data, Variables>`, and it just ignores the Data and Variables.

I managed to work around the problem by monkey patching Client.query. I  narrowed the type of query argument to only be of TypedDocumentNode<D,V>
```
type UrqlMethod = <Data = any, Variables extends object = {}>(
  query: TypedDocumentNode<Data, Variables>,
  variables?: Variables,
  context?: Partial<OperationContext>
) => PromisifiedSource<OperationResult<Data, Variables>>;
(...)

const method : UrqlMethod = link.query;
const result = await method(GenerateKeyDocument, { ... }).toPromise();
```

Please take a look at this, perhaps the order of types in the union should be swapped?
So the type of query is: 
```
    query:  TypedDocumentNode<Data, Variables> | DocumentNode | string,
```

I'm not a TS expert so not sending a PR (It took me hours of hair pulling to locate the problem and I need a break from this)

**Comment by kitten** [comment]
Can you provide a reproduction here please? It seems much more likely to me that you may have duplicate dependencies or that TypeScript has several definitions of `TypedDocumentNode` available that will never match.

However, if this doesn't occur in `graphql@<16` then maybe there's a change in GraphQL Code Generator that's also relevant. So testing `@urql/core@2.3.5` should  be tested here. https://github.com/FormidableLabs/urql/blob/main/packages/core/CHANGELOG.md

Generally, we're dealing with a version upgrade from January here and without some information on GraphQL Code Generator upgrades, GraphQL upgrades, and other factors, and without a reproduction, we can only say... well, that this hasn't broken for us 😅

**Comment by marcinkoziej** [comment]
@kitten sure I understand!! I also get lost in this ecosystem tbh. The upgrades were from the dependabot :0, minor version changes. Will try to produce a small example (the one I have is a bit bigger and convoluted)

**Comment by JoviDeCroock** [comment]
What version of `@graphql-typed-document-node/core` do you have when you type `yarn list @graphql-typed-document-node/core` if it's not 3.1.1 that might be the issue https://github.com/dotansimha/graphql-typed-document-node/releases/tag/core%40v3.1.1

**Comment by marcinkoziej** [comment]
it is `@graphql-typed-document-node/core@3.1.1`

**Comment by marcinkoziej** [comment]
Correction: one of the dependencies used `3.1.0`, :crying_cat_face: my heart breaks when I realize how instable is @graphql ecosystem .... 
Thanks for a great tip, I would have never found that!
Closing the issue.
