### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by shashkovdanil** [FormidableLabs/urql#218]
Do you plan to support server rendering?

**Comment by kitten** [comment]
Yep, that's connected to this issue: #208

Since we were using hooks we needed another major building block for SSR which is now done: https://github.com/FormidableLabs/react-ssr-prepass

It's definitely one of the reasons why we haven't announced urql v1 publicly yet

**Comment by ivan-kleshnin** [comment]
@kitten would be great if you guys add a NextJS integration example once SSR is finished.

**Comment by BjoernRave** [comment]
any updates on this. I would love to try out urql, but this is keeping me from doing so :/

**Comment by kitten** [comment]
@BjoernRave yea, This issue is at the top of my todo list so I'm expecting to get this done quite soon :)

**Comment by helloguille** [comment]
Let us know if there's an alpha we could try. I'd be happy to help testing or help debugging.

**Comment by kitten** [comment]
#250 and #256 introduce the groundwork for this to be completed. I'll write the API for getting the cache's state and rehydrating it soon, so this should be resolved shortly and we'll publish SSR support as part of v1.1
