### ISSUE TITLE
RFC: Separate repeated mutations using reference equality rather than Operation Key

### ISSUE THREAD

**Issue by kitten** [FormidableLabs/urql#2184]
## Summary

Currently, if a mutation is triggered twice then it's sent twice, as expected. This is because we consider each mutation an intent to trigger a side-effect on the GraphQL schema. However, we compare all results of operations using `operation.key`, which would remain the same across repeated mutations; Hence, it's not possible to trigger two mutations concurrently, and see both results for them.

## Proposed Solution

When a mutation is triggered, use reference equality of `operation` instead and only return results for equal operations.
This change may have to be balanced however with cases where we potentially create new references (as copies) of mutation operations while not re-sending them, i.e. on the return in the exchange pipeline. We could for instance be stricter about "what a mutation is", by enforcing `makeOperation`. Alternatively, we could only use reference equality if we know that two operations are currently running simultaneously.

In essence however, the change is as simple as checking `res.operation === operation` in `makeResultSource` rather than comparing keys.

## Requirements

- Allow concurrent mutations to deliver distinct results in the `Client`, when triggered
- Check for bindings to create distinct operations on each call of `executeMutation` (local state will still always be overwritten of course)

**Comment by villesau** [comment]
Wow, what a resolution time @kitten and @JoviDeCroock! Thanks a lot! :)
