### ISSUE TITLE
Query component requires client and key in props

### ISSUE THREAD

**Issue by capaj** [FormidableLabs/urql#219]
I am using uql with typescript and I have a problem with 

![image](https://user-images.githubusercontent.com/1305378/55499151-9ab81c00-5645-11e9-904c-462e4e5f0611.png)

none of the examples show the `<Query />` component with these two props yet they are required.
Either the typing is wrong or all the examples need amending. I am thinking the former.

**Comment by andyrichardson** [comment]
Your code looks about right. Can you confirm which version you are currently using?

**Comment by capaj** [comment]
Using latest 1.0.4

**Comment by andyrichardson** [comment]
Looks like there were a couple of things that caused this. There's a PR to fix the issue. 

Would strongly recommend that you look into upgrading react and using the hooks implementation if possible.

**Comment by capaj** [comment]
Very fast response! This is exactly the patch I had in mind.Hope it get's merged soon.

**Comment by andyrichardson** [comment]
I'll pressure @kitten to approve 👿
