### ISSUE TITLE
Cache update errors are caught

### ISSUE THREAD

**Issue by bkiac** [FormidableLabs/urql#2191]
I had an error in my update resolver logic which was really hard to find because the error was caught by the cache exchange like nothing happened. I'm not sure if this is intentional or not.

urql version & exchanges: 

<table>
<tr>
	<td> urql
	<td> 2.0.6
<tr>
	<td> @urql/exchange-graphcache
	<td> 4.3.6
</table>

**Steps to reproduce**

```ts
const cache: GraphCacheConfig = cacheExchange({
	schema,
	updates: {
		Mutation: {
			doSomething: () => {
				throw new Error("this is caught")
			},
		},
	},
})
```

**Expected behavior**
Errors are propagated/re-thrown

**Actual behavior**
Errors are caught inside the cache exchange

**Comment by JoviDeCroock** [comment]
Nothing in urql is catching these we are throwing them for the user, here is a [simple reproduction](https://codesandbox.io/s/interesting-wing-kduoz?file=/src/index.js) highlighting this case. When you press a todo it will throw an error.
