### ISSUE TITLE
Potential performance gain in a babel-transform

### ISSUE THREAD

**Issue by blainekasten** [FormidableLabs/urql#22]
This is specifically addressing the way urql injects `__typename` into queries at runtime. These transformations can be done statically at build time, rather than at runtime through a custom babel-transform.

What the babel transform would do is translate:

```js
const TodoQuery = `
query {
  todos {
    id
    text
  }
}
`;
```

into 

```js
const TodoQuery = `
query {
  __typename
  todos {
    id
    text
  }
}
`;
```

(or whatever it needs to do, haven't traced the code entirely).

At that point, most of [this file](https://github.com/FormidableLabs/urql/blob/master/src/modules/typenames.ts#L32) can go away.

My proposal is to do the following:
1. Don't change the runtime code.
2. Create a babel-transform that injects `__typenames` and _shakes away_ the `typenames.ts` file so it doesn't even try to do any runtime transformations.

This approach gives a very lazy buy in where consumers don't _have_ to use our babel-transform, but can use it to get a very specific optimization.

**Comment by kenwheeler** [comment]
I like it. Wanna PR or do you wanna give it a spin?

**Comment by jaydenseric** [comment]
Might be a good idea to give the transform a generic name and not tie it directly to `urql`; other libs might make use of it. Pretty sure [Apollo inserts `__typename`](https://github.com/apollographql/apollo-client/issues/1913#issuecomment-315756883).

**Comment by iansu** [comment]
I'm interested in giving this a shot if no one else is. I have written babel plugins before but I've never used it with GraphQL. Anything I should check out for reference/inspiration? `babel-plugin-relay` or `babel-plugin-graphql-js-client-transform`? Something else?

**Comment by iansu** [comment]
I spent a bit of time looking into this and, while it should be relatively easy to create a babel transform to add `__typename`, the fact that urql uses regular template literals for queries (as opposed to tagged template literals like `graphql-tag`) seems like a problem. There's no easy way for a babel transform to know if a template literal is a GraphQL query or something else.

**Comment by blainekasten** [comment]
I like the idea of just injecting `__typename` into every string and let everyone struggle with debugging it.

**Comment by iansu** [comment]
I agree that the performance gain is probably not worth the effort in this case, not to mention the additional code complexity, etc. Although I do like the idea of throwing `__typename` into everything just for fun. 😂

**Comment by kenwheeler** [comment]
I think the biggest gain here would be removing the graph-ql dep. Is there any way I can use a wrapper function or something to signal that the string is eligible for injection?

**Comment by iansu** [comment]
A tagged template literal is probably the best option. That's what Apollo does with `graphql-tag`: https://github.com/apollographql/graphql-tag. You could provide your own, lighter-weight version of that that doesn't use `graphql-js`, or use it as a way to flag strings for a babel transform.

**Comment by kitten** [comment]
I think in combination with #90 and exchanges in `next` there's potential here for this stuff to be in userland, as we basically just pass queries through. We just need to be able to accept gql asts instead of just strings and add an option (separate exchange?) for the typename transpilation

**Comment by iansu** [comment]
Let me know if that's something I can help out with.

**Comment by kasbah** [comment]
Hello, I just found [babel-plugin-graphql-tag](https://www.npmjs.com/package/babel-plugin-graphql-tag) which seems similar to what you want. graphql-tag would need to gain support for adding typenames as well and it looks like there is an [issue open for that](https://github.com/apollographql/graphql-tag/issues/71). 

I think an upside of changing the urql API to accept the parsed AST would be that you could determine whether it's a query or mutation from the AST rather than making the user effectively specify it twice with use of the existing functions.

**Comment by kitten** [comment]
Lets replace this with #50 to reduce duplication and keep things simple
