### ISSUE TITLE
RFC: Graphql-codegen: Generate exchange TS types from graphql files

### ISSUE THREAD

**Issue by villesau** [FormidableLabs/urql#2216]
## Summary

I see that the types for exchanges & cache are incomplete. In my case, all my mutations and queries are defined using graphql files, and graphql-codegen generates urql hooks out of them. However, when working with exchanges (like cacheExchange), the cache is not well typed, even though all the graphql queries are well defined.

## Proposed Solution

Would be awesome, if graphql-codegen for Urql would also be able to define cahce & exhange types, maybe even whole exchanges like cacheExchange. In optimal case I could just import the exchange and it would be fully typed based on the graphql-files I use for queries & mutations, in a similar manner like the Prisma client is typed or generated based on Prisma schema. This way the whole urql would remain fully typed as long as you would follow this rule: Never create adhoc graphql queries that would not be handled by graphql-codegen.

**Comment by JoviDeCroock** [comment]
This already exists with [their graphcache package](https://www.npmjs.com/package/@graphql-codegen/typescript-urql-graphcache)

**Comment by villesau** [comment]
Oh, looks like everything with the Urql is already thought out! :D
