### ISSUE TITLE
[urql@2.1.0] reintroduces error: ReactDOMServer does not yet support Suspense

### ISSUE THREAD

**Issue by Swiftwork** [FormidableLabs/urql#2239]
Package `urql@2.1.0` reintroduces the previous suspense error when paired with `next` and `next-urql`:
```
Error: ReactDOMServer does not yet support Suspense
```
urql version & exchanges:
```json
"dependencies": {
  "graphql": "16.3.0",
  "next": "12.0.10",
  "next-urql": "3.3.2",
  "react": "17.0.2",
  "react-dom": "17.0.2",
  "react-is": "17.0.2",
  "urql": "2.1.0"
},
```

**Steps to reproduce**

1. Setup a new next project from scratch with `yarn create next-app`
2. Add urql and dependencies `yarn add next-urql react-is urql graphql`
3. Create a page using `withUrqlClient(...)` and `ssr: true`
4. `useQuery(...)` to fetch data from a GraphQL endpoint
5. Run the project with `yarn dev` and observe the error

**Expected behavior**

Continue working the same as version `2.0.6` and not cause the error above.

**Actual behavior**

[Repository with reproduction of error](https://github.com/Swiftwork/reproduce-next-urql-pnp-suspense)

**Comment by JoviDeCroock** [comment]
This should be fixed in `2.1.3`, feel free to reopen if the issue persists, the linked PR's contain the reproduction used

**Comment by Swiftwork** [comment]
Great work @JoviDeCroock I'll check it out tomorrow!

**Comment by Swiftwork** [comment]
I can confirm that the changes have resolved this issue :)
