### ISSUE TITLE
(introspection) - Passing SDL to getIntrospectedSchema errors with "Cannot use GraphQLSchema (...) from another module or realm."

### ISSUE THREAD

**Issue by CherryDT** [FormidableLabs/urql#2250]
urql version & exchanges: `@urql/core@2.4.1`, `@urql/introspection@0.3.1`

**Steps to reproduce**

You can reproduce it with this example project I uploaded: https://codesandbox.io/s/github/CherryDT/urql-issue-repro

If the sandbox is already running, you won't see the error, so you have to fork it to see it failing. You can also just install the repository manually:

```bash
git clone https://github.com/CherryDT/urql-issue-repro
cd urql-issue-repro
npm install
npm start
```

The relevant code is:

```javascript
import { createClient, dedupExchange, cacheExchange, fetchExchange } from '@urql/core'
import { readFile } from 'fs/promises'
import { getIntrospectedSchema } from '@urql/introspection'

// ...

const sdl = await readFile(new URL('./schema.graphql', import.meta.url), 'utf8')
const schema = await getIntrospectedSchema(sdl)

const client = createClient({
  url: 'http://localhost:8080/graphql',
  exchanges: [
    dedupExchange,
    cacheExchange({ schema }),
    fetchExchange
  ]
})
```

**Expected behavior**

No error.

**Actual behavior**

Error:

```
Error: Cannot use GraphQLSchema "{ __validationErrors: undefined, description: undefined, extensions: {}, astNode: undefined, extensionASTNodes: [], _queryType: Query, _mutationType: Mutation, _subscriptionType: undefined, _directives: [@include, @skip, @deprecated, @specifiedBy], _typeMap: { Tweet: Tweet, ID: ID, String: String, User: User, Stat: Stat, Int: Int, Notification: Notification, Meta: Meta, Url: Url, Date: Date, Query: Query, Mutation: Mutation, Boolean: Boolean, __Schema: __Schema, __Type: __Type, __TypeKind: __TypeKind, __Field: __Field, __InputValue: __InputValue, __EnumValue: __EnumValue, __Directive: __Directive, __DirectiveLocation: __DirectiveLocation }, _subTypeMap: {}, _implementationsMap: {} }" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/mnt/c/Users/david/Temp/urql-test/node_modules/graphql/jsutils/instanceOf.js:43:19)
    at isSchema (/mnt/c/Users/david/Temp/urql-test/node_modules/graphql/type/schema.js:32:37)
    at assertSchema (/mnt/c/Users/david/Temp/urql-test/node_modules/graphql/type/schema.js:36:8)
    at validateSchema (/mnt/c/Users/david/Temp/urql-test/node_modules/graphql/type/validate.js:34:28)
    at assertValidSchema (/mnt/c/Users/david/Temp/urql-test/node_modules/graphql/type/validate.js:56:18)
    at assertValidExecutionArguments (/mnt/c/Users/david/Temp/urql-test/node_modules/graphql/execution/execute.js:194:35)
    at execute (/mnt/c/Users/david/Temp/urql-test/node_modules/graphql/execution/execute.js:113:3)
    at executeSync (/mnt/c/Users/david/Temp/urql-test/node_modules/graphql/execution/execute.js:161:18)
    at getIntrospectedSchema (file:///mnt/c/Users/david/Temp/urql-test/node_modules/@urql/introspection/dist/urql-introspection.mjs:20:11)
    at main (file:///mnt/c/Users/david/Temp/urql-test/index.js:7:24)
```

I tried `npm ls graphql` but there is only one instance of the package installed.

**Comment by kitten** [comment]
Hm, looks like this is related to Node.js resolution where `import { executeSync } from 'graphql'` isn't resolved as the `.mjs` versions (i.e. exports) however, the other files, e.g. `import { getIntrospectionQuery as t } from "graphql/utilities/getIntrospectionQuery.mjs";` are, since they're linked directly.

So, this is likely Node.js version dependent, but since we've got a new version of `babel-plugin-modular-graphql` that should resolve this, I can probably republish the package to fix this

**Comment by CherryDT** [comment]
I see. Thanks.

In the meantime, I implemented this very ugly hack:

```javascript
import { createRequire } from 'module'
const require = createRequire(import.meta.url)

const instanceOfModule = require('graphql/jsutils/instanceOf.js')
instanceOfModule.instanceOf = (value, constructor) => {
  if (value instanceof constructor) return true

  if (typeof value === 'object' && value !== null) {
    const className = constructor.prototype[Symbol.toStringTag]
    const valueClassName = value[Symbol.toStringTag]
    // Do allow this case to work around https://github.com/FormidableLabs/urql/issues/2250
    if (className === valueClassName) return true
  }

  return false
}
```

~~But this now showed me a new problem with my code, maybe you can give me a hint of what could be wrong (I guess I'm doing something wrong in this case so I'm not sure it warrants its own issue): I'm getting `r is not a function` which comes from ~~ Yeah thanks for your edit, I was just typing a question about that. That would explain it! I thought those two things are the same. Thank you!

**Comment by CherryDT** [comment]
Question - Now I instead have the issue that [the generated schema has tons of empty objects](https://gist.github.com/CherryDT/3a16704e931fafe95e7fe749a00391d6) instead of real data, which then leads to a crash when accessing `e.types[e.mutation]` since `e.types` is an empty object as well. Could this be related to my workaround (so I should just wait for the release instead) or would that be something else entirely?

**Comment by kitten** [comment]
I took a look and that isn't reproduceable to me. Not sure if something went wrong when you stringified it, but it does look to be behaving fine for me now when I'm testing out the fixed build

**Comment by CherryDT** [comment]
I couldn't get it to work, now I used [this](https://stackoverflow.com/a/70836752/1871033) method instead and it works fine now.
