### ISSUE TITLE
(refocus) - refocusExchange not refetching on window focus, only on tab change

### ISSUE THREAD

**Issue by longfellowone** [FormidableLabs/urql#2268]
refocusExchange is not refetching on window focus, only on tab change

urql version & exchanges:
`"@urql/exchange-refocus": "^0.2.5"`
`"urql": "^2.1.3"`

Windows 10 / Latest edge browser

**Steps to reproduce**

https://codesandbox.io/s/peaceful-pare-o1nxf?file=/src/index.js
https://o1nxf.csb.app/

**Expected behavior**

Query should refetch on window focus in addition to tab change (similar to react-query)

**Actual behavior**

Query only refetches on tab change

**Comment by JoviDeCroock** [comment]
We are currently using [this event](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event) which is a lot less aggressive compared to just focussing as focussing fires _a lot_ 😅 the exchange is fairly small so maybe vendoring it is the best option here.
