### ISSUE TITLE
This entity is reset when I search something in the select

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#2293]
urql version & exchanges:

```
"@urql/core": "2.4.2",
"@urql/devtools": "2.0.3",
"@urql/exchange-graphcache": "4.3.6",
"@urql/exchange-persisted-fetch": "1.3.4",
"@urql/exchange-retry": "0.3.2",
"@urql/svelte": "1.3.3",
```

**Steps to reproduce**

1. Go to https://codesandbox.io/s/iss-urql-select-6731ue?file=/schema.js to start the server
1. go to https://stackblitz.com/edit/sveltejs-kit-template-default-9hxszm?file=src%2Froutes%2FForm.svelte&terminal=dev for the client
1. delete all the text in textarea
1. choose "Category 1" from select
1. it works (the category is changed in todo)
1. write something in select (for example "cat")
1. the todo is reset!

**Expected behavior**

The todo is not reset! And the category I choose is the new Todo's category.

**Actual behavior**

The todo is reset.

This doesn't happen if you remove `offlineExchange` from exchanges in `__layout.svelte` file, line 31.

I totally reproduced my local app issue except for the schema that I don't know how to reproduce here. But in my local app everything is correct (schema too).

![issue](https://user-images.githubusercontent.com/41120635/154999776-9f1fc9d0-c1d8-496c-8477-935bc78c5199.gif)

**Comment by JoviDeCroock** [comment]
As alluded to in #2294 this is the cache  and network result coming in and you resetting the value because of it

**Comment by frederikhors** [comment]
@JoviDeCroock I’m sorry. I spent a lot of time creating that reproduction because the issue is not simple as you said.

If you see the gif I’m not retrieving the todo. I’m retrieving the categories. And this happens only when I search. If I chose one category before the search it works.

Can you please re-open until we better understand this behavior? Please. I’m really loosing my mind here.

Thanks.

**Comment by JoviDeCroock** [comment]
I mean, to reiterate you are straight up reusing data that is refetched

```js
  <Form
    todo={$todo.data.todo}
    {submit}
  />
```

This part gets refetched because you are updating its category as typing `C` in the category-field will make you refetch categories, this category is a sub-field of the `todo` you are observing. This makes it so that the query on your layout fires again and you send a new todo to your Form. Generally in front-end it's a best practice to work with a copy of your entity when manipulating a form. This because data can change and that should not interrupt someone's workflow

**Comment by frederikhors** [comment]
@JoviDeCroock thank you for the answer.

Is a simple reload of the categories enough to make the todo reload even if neither the category nor the todo has changed?
