### ISSUE TITLE
Memory leak in urql@^2.1.0

### ISSUE THREAD

**Issue by nickrttn** [FormidableLabs/urql#2298]
Hello folks,

We've recently narrowed a memory leak in our Next.js application, on the server side, down to urql versions 2.1.0 and up. Downgrading to `2.0.6` resolves the memory leak. I haven't been able to reproduce the bug in a reproduction application with a similar configuration for next-urql's `withUrqlClient` so I suspect a potential interaction with a different package or something else in our setup.

Our application uses next-urql wrapped around App and is fairly complex. I would like to further narrow down the cause of the issue, but I'm not entirely sure how to proceed. The Node.js debugger isn't helpful as the snapshot very quickly grow beyond the point of it being able to parse them. I'm curious if you have any suggestions that might help me find the cause of the issue or that would help to pinpoint the exact circumstance that causes the memory leak.

urql version & exchanges:

`urql@^2.1.0`, `next-urql@3.3.2`, `@urql/devtools@2.0.3`, with a custom error exchange that reports errors to Sentry in the `onError` event handler.

**Steps to reproduce**

No reproduction possible at this time.

**Expected behavior**

Memory garbage collection to work.

**Actual behavior**

In a built version of the application, memory usage is quickly increasing when doing requests to any page that includes GraphQL queries (in our case, all of them), up to a memory overflow that causes Node.js to crash.

**Comment by kitten** [comment]
Hm, the only thing that comes to mind here is the `useSyncExternalStore` refactor, so that may be a place to start at 🤔 But without a comprehensive look at whether it's down to `@urql/core` or `urql` (react-bindings) it's hard to find a place to start here, I guess 😅

**Comment by nickrttn** [comment]
Alright, here goes:

We wrap our Next.js App in the `_app` file with the following configured withUrqlClient HoC:

```js
export default withUrqlClient((ssrExchange, ctx) => {
  const fetchOptions = {
    headers: {},
  };

  if (ctx?.req) {
    // forward the client request cookies to the GraphQL middleware on the server
    fetchOptions.headers.cookie = ctx.req.headers.cookie;
  }

  const opts = {
    fetch,
    fetchOptions,
    exchanges: [
      devtoolsExchange,
      errorExchange({
        onError: (error, operation) => {
          // log users out when their token has expired
          if (error.message.includes('401')) {
            logout(ctx);
          }

          Sentry.captureException(error, { errorInfo: operation });
        },
      }),
      dedupExchange,
      cacheExchange,
      ssrExchange,
      fetchExchange,
    ],
    maskTypename: true,
  };

  opts.url = ctx ? `${getHost(ctx?.req)}/api/graphql` : '/api/graphql';

  return opts;
});
```

That same app is wrapped by three other HoCs that instantiate various parts of our global state in the following manner:

```js
export default compose(
  withUrql,
  withUserData,
  withSomeMoreData
)(CustomApp);
```

Each of these HoCs wraps `App.getInitialProps` with their own `.getInitialProps` and wraps the passed App component with a React.Context that does all of the work of instantiating the global state. They both include a `useQuery` hook that fetches part of the global state.

We fetch our data from a local GraphQL API endpoint (which is made with `apollo-server-micro`) that sits as a proxy between our application and a REST API. 

In production, our application runs as a persistent process in a Docker container, based on `node:16-alpine`. We're seeing memory usage build up over the course of a couple of hours to around 17Gb, then Node.js crashes. The application is non-responsive during that time. I can reproduce memory buildup locally outside of Docker by building and running the application and hitting some random page with `siege`. Memory usage will quickly build up to multiple Gbs.

Then each separate page in our application includes a multitude `useQuery` calls at the component level. We rely fairly heavily on query deduplication to keep data fetching running optimal.

Is this enough info? Is there some more context I can give?
