### ISSUE TITLE
(react) - Fetching state is not turning to 'true' while reexecuting a query

### ISSUE THREAD

**Issue by lajosVlasics** [FormidableLabs/urql#2299]
In our react app we updated urql to 2.0.10. We found out that the fetching state is not turning to true while reexecuting a query.

urql version & exchanges:
higher than 2.0.6

**Steps to reproduce**

1. Create a React useQuery hook (doesn't matter if it is paused or not).
2. Call the reexecuteQuery function (in 'network-only' mode) returned from the useQuery hook.

**Expected behavior**
The fetching state (in the result from the useQuery ) turns to true while calling the reexecuteQuery, than to false after the query is finished.

**Actual behavior**
The fetching state filps to true only the first time we calling the query, but never again, it remains false. 

https://codesandbox.io/s/urql-reexecute-query-fetching-state-issue-egw2et?file=/src/Foo.jsx

**Comment by gus-t27** [comment]
I am still getting this exact problem on urql version: 3.0.3..

I am re executing a query with 'network-only' and fetching does not flip to 'true'..

I have been following the docs [here](https://commerce.nearform.com/open-source/urql/docs/basics/react-preact/#reexecuting-queries) and [here](https://commerce.nearform.com/open-source/urql/docs/api/urql/#usequery) which suggests that fetching should become true whilst the reexecution is happening.

However, I noticed that these docs are now deprecated but I cannot for the life of me find the suggested TSDocs in my editor! 

@JoviDeCroock Please could you let me know exactly what I am missing? Thanks
