### ISSUE TITLE
Nested object fields don't get optimistically updated

### ISSUE THREAD

**Issue by alexkirsz** [FormidableLabs/urql#2321]
urql version & exchanges:

```
    "@urql/core": "^2.4.2",
    "@urql/exchange-auth": "^0.1.7",
    "@urql/exchange-graphcache": "^4.3.6",
```

**Steps to reproduce**

1. Have a mutation that returns an object (e.g. a `Post`) with nested fields that are non-keyable (e.g. a `PostMetadata`).

```gql
type PostMetadata {
  title: String!
}

type Post {
  id: ID!
  metadata: PostMetadata!
}

input InputPost {
  id: ID!
  metadata: PostMetadata!
}

type Mutation {
  createPost($post: InputPost): Post!
}
```

By non-keyable, I mean that the graphcache's exchange `keys` map is as follows (as prescribed [here](https://formidable.com/open-source/urql/docs/graphcache/errors/#15-invalid-key)):

```ts
cacheExchange({
  // ...
  keys: {
    PostMetadata: () => null
  },
})
```

2. Have an optimistic mutation for that mutation that also tries to update the nested `Post.metadata`:

```ts
cacheExchange({
  // ...
  createPost: (args: CreatePostMutationVariables) => {
    return {
        __typename: "Post",
        ...args.post,
      },
    };
  },
})
```

**Expected behavior**

The `PostMetadata` associated with the `Post` is updated locally.

Option 3. is unnecessary, option 2. works out of the box.

**Actual behavior**

Only the direct fields of the `Post` are updated.

If you explicitly specify `__typename` for the `PostMetadata`, things work as expected:

```ts
cacheExchange({
  // ...
  createPost: (args: CreatePostMutationVariables) => {
    return {
        __typename: "Post",
        ...args.post,
        metadata: {
          __typename: "PostMetadata",
          ...args.post.metadata,
        }
      },
    };
  },
})
```

However, this seems like a footgun.

**Comment by JoviDeCroock** [comment]
That is expected behavior, we have no way to predict what the sub-types will be for a given entity

**Comment by alexkirsz** [comment]
@JoviDeCroock If I have an introspected schema available on the client-side, is there a way for me to do this "filling in __typename" automatically?

**Comment by JoviDeCroock** [comment]
That makes it hard to predict for unions/... so not really

**Comment by alexkirsz** [comment]
For others that might encounter this problem and are using TypeScript, this utility type can ensure you are properly setting typenames on all of your sub-fields:

```ts
export type WithExplicitTypename<T> = T extends { __typename?: string }
  ? {
      __typename: NonNullable<T["__typename"]>;
    } & {
      [Properties in keyof Omit<T, "__typename">]: WithExplicitTypename<
        T[Properties]
      >;
    }
  : T extends { [key: string]: any }
  ? {
      [Properties in keyof T]: WithExplicitTypename<T[Properties]>;
    }
  : T;
```

I will still be looking for a way to do this automatically in the absence of unions.
