### ISSUE TITLE
Query does not refetch when variables change with custom graphcache resolver

### ISSUE THREAD

**Issue by alexkirsz** [FormidableLabs/urql#2340]
This bug appears to be very similar to https://github.com/FormidableLabs/urql/issues/668, but I cannot reproduce the issue with the provided sandbox and latest urql, so I made my own sandbox.

**urql version & exchanges:**

```
    "urql": "2.2.0",
    "@urql/exchange-graphcache": "4.3.6",
```

**Steps to reproduce**

Client: https://codesandbox.io/s/charming-butterfly-tuz71q
Server: https://codesandbox.io/s/sharp-lovelace-jhm3u7?file=/schema.js

The sandbox is setup with the graphcache exchange and a custom resolver on `Query.todos`. The role of this custom resolver is to append new results at the end of the result list instead of replacing the list itself. It's like a simpler simple pagination resolver.

1. Create a new `Todo`
2. Click "Increment after"

**Expected behavior**

The query is refetched with `variables: { after: 1 }` and the new `Todo` appears at the end of the list.

**Actual behavior**

The query is not refetched and the new `Todo` does not appear.

**Notes**

If you comment out the custom resolver in `src/index.js`, you will see the new `Todo` appear (but the pagination will no longer work).

**Comment by JoviDeCroock** [comment]
The issue is that you are returning data for the new variables rather than telling it to fetch new data 😅 graphCache can't really assume that you intend something else as you are returning all entities that it already has so that's a cache-hit.
<img width="704" alt="Screenshot 2022-03-11 at 11 34 08" src="https://user-images.githubusercontent.com/17125876/157850850-edb1275c-330e-480c-b743-7d1b77d1b287.png">

**Comment by alexkirsz** [comment]
@JoviDeCroock First off, thanks for the lightning speed answer!

I see! I've added the following to the end of my resolver and it seems to have fixed the issue indeed:

```ts
    const hasCurrentResult = cache.resolve(entityKey, fieldName, fieldArgs);
    if (hasCurrentResult) {
      return result;
    } else {
      info.partial = true;
      return result;
    }
```

Let me know if you believe this to be incorrect, but in the meantime I'll close this issue.
