### ISSUE TITLE
Intermediate results from subscriptions or queries overwrite optimistic updates

### ISSUE THREAD

**Issue by alexkirsz** [FormidableLabs/urql#2352]
This is related to https://github.com/FormidableLabs/urql/discussions/2349, but I'm posting this here as a bug since it's surprising behavior, and I've created a small repro case to illustrate the effect.

**urql version & exchanges:**

```
"@urql/core": "^2.4.3",
"@urql/exchange-graphcache": "^4.3.6",
```

**Steps to reproduce**

* I have a mutation that updates a `Todo`.
* I have a subscription that listens for `Todo` updates.
* I have an optimistic update setup on a `completeTodo` mutation.

Consider the following sequence of events:
1. I execute a `completeTodo` mutation. The todo is optimistically mutated according to my arguments and the request is sent to the server.
2. I receive an answer from the server with the updated `Todo`: my todo is now perfectly synced between client and server.
3. I mutate the same `Todo` again.
4. I receive a subscription event with the `Todo` from (1.). The optimistically updated `Todo` is rolled back from its state at (3.) to its state at (2.).
5. I receive an answer from the server  with the updated `Todo`. The todo is rolled back from its state at (4.) to its state at (3.).

**Expected behavior**

The `Post` should not be rolled back to its state at (2.) but instead roll back the optimistic update, apply the update from the subscription, then replay the optimistic update while we have yet to receive word from the server. Hence, the order of states should always be (2.) -> (3.) and not the current (2.) -> (3.) -> (2.) -> (3.).

**Actual behavior**

The `Post` is rolled back.

**Reproduction**
Client: https://codesandbox.io/s/elastic-yalow-x9hctp?file=/src/index.js
Server: https://codesandbox.io/s/beautiful-worker-k7xhgq?file=/schema.js

Demonstration of the effect, which you can observe by toggling a todo in quick successions:

https://user-images.githubusercontent.com/1621758/158698143-3fbd5582-ad35-46c2-b6d0-a886fd022886.mov

The effect is even more pronounced on slow networks and when optimistic updates stack.

**Comment by JoviDeCroock** [comment]
Conceptually a subscription reflects an accurate state of the server hence we have opted to not include subscription responses into our layering logic. This because you can't assume ordering mutation --> sub trigger --> query --> ... and other relevant combinations would not be deterministic if subscription responses would be layered.

Hence this isn't really a bug to me but more a server sending an invalid state from another user updating so could this be more of a UI state issue. A user updates a similar entity while also having an update present 😅

**Comment by alexkirsz** [comment]
We ended up switching to apollo-client because this particular behavior was a deal-breaker for our application. Closing this since it's expected behavior.
