### ISSUE TITLE
[Nuxt3] Error when using "useQuery" on serverside

### ISSUE THREAD

**Issue by oysandvik94** [FormidableLabs/urql#2360]
When calling useQuery in Vue/Nuxt3 I get this error on the serverside:
"Error: use* functions may only be called during the `setup()` or other lifecycle hooks."
This happens on a completely minimal project, and it only happens when running the node server (production mode, not the dev server).

My vue file looks like this:
```
<template>
  <div>
    <NuxtWelcome />
  </div>
</template>
<script setup lang="ts">
import { useQuery } from '@urql/vue';
const { data, fetching } = await useQuery({
  query: `query {
  Page {
    users {
      id
    }
  }
}`
})
</script>
```

I have created the SSR client in a nuxt plugin like this:
```

import { defineNuxtPlugin, NuxtApp } from "#app";
import { createClient, ssrExchange, dedupExchange, fetchExchange } from "@urql/vue";
import { ref } from "vue";


export default defineNuxtPlugin(nuxt => {
    const { vueApp } = nuxt;
const isServerSide = typeof window === 'undefined';

    // SSR exchange
  const ssr = ssrExchange({
    isClient: process.client,
  });

// Extract SSR payload once app is rendered
if (process.server) {
    nuxt.hook("app:rendered", () => {
      nuxt.payload.data["urql"] = ssr.extractData();
    });
  }

  // Restore SSR payload once app is created
  if (process.client) {
    nuxt.hook("app:created", () => {
      ssr.restoreData(nuxt.payload.data["urql"]);
    });
  }

  const client = ref(createClient({
   url: "https://graphql.anilist.co",
   exchanges: [
       dedupExchange,
       ssr,
       fetchExchange
   ]
  }));

  nuxt.provide('urql', client)
  vueApp.provide('$urql', client)

})


```

This is a completely fresh scaffolded Nuxt 3 project.

I dont get an error if I put my useQuery in an `onMounted` hook. 

urql version & exchanges:
"graphql": "^16.3.0",
 "@urql/vue": "^0.6.1"

Exhanges are in the code example

**Steps to reproduce**
See above.

**Expected behavior**
No exceptions

**Actual behavior**
I get an exception. Full trace:
> Error: use* functions may only be called during the `setup()` or other lifecycle hooks.
>     at useClient (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:46:11)
>     at callUseQuery (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:69:9)
>     at useQuery (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:64:10)
>     at setup (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/app/server.mjs:3789:5)
>     at _sfc_main.setup (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/app/server.mjs:3810:23)
>     at callWithErrorHandling (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/index.mjs:1957:22)
>     at setupStatefulComponent (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/index.mjs:7517:29)
>     at setupComponent (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/index.mjs:7498:11)
>     at renderComponentVNode (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/index.mjs:9853:17)
>     at Object.ssrRenderComponent (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/index.mjs:10284:12)
> [Vue warn]: Component  is missing template or render function.
> use* functions may only be called during the `setup()` or other lifecycle hooks.
>   at useClient (file://./.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:46:11)  
>   at callUseQuery (file://./.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:69:9)  
>   at useQuery (file://./.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:64:10)  
>   at setup (file://./.output/server/chunks/app/server.mjs:3789:5)  
>   at _sfc_main.setup (file://./.output/server/chunks/app/server.mjs:3810:23)  
>   at callWithErrorHandling (file://./.output/server/chunks/index.mjs:1957:22)  
>   at setupStatefulComponent (file://./.output/server/chunks/index.mjs:7517:29)  
>   at setupComponent (file://./.output/server/chunks/index.mjs:7498:11)  
>   at renderComponentVNode (file://./.output/server/chunks/index.mjs:9853:17)  
>   at Object.ssrRenderComponent (file://./.output/server/chunks/index.mjs:10284:12)
> Error: use* functions may only be called during the `setup()` or other lifecycle hooks.
>     at useClient (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:46:11)
>     at callUseQuery (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:69:9)
>     at useQuery (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:64:10)
>     at setup (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/app/server.mjs:3789:5)
>     at _sfc_main.setup (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/app/server.mjs:3810:23)
>     at callWithErrorHandling (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/index.mjs:1957:22)
>     at setupStatefulComponent (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/index.mjs:7517:29)
>     at setupComponent (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/index.mjs:7498:11)
>     at renderComponentVNode (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/index.mjs:9853:17)
>     at Object.ssrRenderComponent (file:///home/langeoys/dev/nuxtbug/nuxt3-app/.output/server/chunks/index.mjs:10284:12)
> [Vue warn]: Component  is missing template or render function.
> use* functions may only be called during the `setup()` or other lifecycle hooks.
>   at useClient (file://./.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:46:11)  
>   at callUseQuery (file://./.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:69:9)  
>   at useQuery (file://./.output/server/node_modules/@urql/vue/dist/urql-vue.mjs:64:10)  
>   at setup (file://./.output/server/chunks/app/server.mjs:3789:5)  
>   at _sfc_main.setup (file://./.output/server/chunks/app/server.mjs:3810:23)  
>   at callWithErrorHandling (file://./.output/server/chunks/index.mjs:1957:22)  
>   at setupStatefulComponent (file://./.output/server/chunks/index.mjs:7517:29)  
>   at setupComponent (file://./.output/server/chunks/index.mjs:7498:11)  
>   at renderComponentVNode (file://./.output/server/chunks/index.mjs:9853:17)  
>   at Object.ssrRenderComponent (file://./.output/server/chunks/index.mjs:10284:12)
>

**Comment by idflood** [comment]
@oysandvik94 I had the same issue and found the [solution here](https://github.com/FormidableLabs/urql/issues/1596#issuecomment-955773985).

In your `nuxt.config.js` you can add `@urql/vue` in `nuxt.options.build.transpile` and the error should go away 🤞

```javascript
export default defineNuxtConfig({
    …
    build: {
        transpile: [
            "@urql/vue"
        ]
    },
    …
}
```

**Comment by oysandvik94** [comment]
@idflood You're a legend! Can't believe I didnt find that thread myself. This worked like a charm for me.

**Comment by kitten** [comment]
As stated above, I assume there are some issues with the build environment which puts this out of our control 👀 Also, we've got discussions in case you'd want to ask a question first. When you see an explicit error message we've written, most of the time it'll not be related to our code but to your setup ✌️

**Comment by genu** [comment]
I'm facing this issue as well. I'm not sure if its related to the transpile.

To reproduce, try to use `urql` query inside of a nuxt middlware. It will throw the same error.
