### ISSUE TITLE
@urql/core requestPolicyExchange upgrade does not result in network request

### ISSUE THREAD

**Issue by szv** [FormidableLabs/urql#2364]
**urql version & exchanges**
- @urql/core - 2.4.3
- @urql/exchange-request-policy - 0.1.5
- graphql - 16.3.0

**Steps to reproduce**

I configured the client like this:
```Typescript
import { createClient, dedupExchange, fetchExchange, cacheExchange } from '@urql/core';
import { requestPolicyExchange } from '@urql/exchange-request-policy';

const client = createClient({
    url: "myGraphQLUrl",
    exchanges: [
        dedupExchange,
        requestPolicyExchange({ ttl: 1, shouldUpgrade: op => true }),
        cacheExchange,
        fetchExchange
    ]
});
```

**Expected behavior**

I expect that every ```cache-first```-query gets upgraded to ```cache-and-network```.

**Actual behavior**

The same behaviour as described in #1640 and #1334

---

For testing I replaced the request-policy-exchange with the following:
```Typescript
import { pipe, tap } from 'wonka';
import { Exchange, Operation } from '@urql/core';

export const requestPolicyExchange = (): Exchange => {
    return ({ client, forward }) => ops$ => {

        const processIncomingOperation = (op: Operation) => {
            if (op.kind !== 'query' && op.context.requestPolicy !== "cache-first") {
                return op;
            }

            op.context.requestPolicy = "cache-and-network";
            return op
        };

        return forward(pipe(ops$, tap(processIncomingOperation)));
    };
};
```
But this does not lead to the desired behavior either.

**Comment by JoviDeCroock** [comment]
Tried reproducing it and it does do it correctly for me [here](https://codesandbox.io/s/late-leftpad-1ems7m?file=/src/index.js) just press refetch and observe the transformation in your console, as shown in the next screenshot

![transformation from cache-first to cache-and-network](https://user-images.githubusercontent.com/17125876/161782175-c3513c1b-db77-4b2e-9fd4-b94af80aa0dd.png)

And observe the network request

![graphql request on the network](https://user-images.githubusercontent.com/17125876/161782293-c3fe04eb-3d54-4cf6-a471-4597a2b55191.png)

**Comment by Torsten85** [comment]
Because of this issue, we can't use urql in our company.
Somewhere the cache exchange prevents all other exchanges to run again after a "cache-first" operation is cached.

**Comment by JoviDeCroock** [comment]
@Torsten85 this is a off-topic but that's how cache-first is supposed to work, you can change requestPolicies however you like, if you are having an issue with this exchange a reproduction would be awesome in helping y'all out. If you are having an issue with cache-updates/... a lot of it is in our documentation how caches work and when data is refetched.

**Comment by JoviDeCroock** [comment]
Well that assumption is a bit wrong, the initialization of the exchange-chain only happens once.

[here](https://codesandbox.io/s/confident-sound-muolcc?file=/src/index.js) is a corrected example so as long as the requestPolicyExchange lives in front of the cache you are good as documented

**Comment by JoviDeCroock** [comment]
This was an actual bug with the promises and we fixed it in #2386 which will be available in the new core-version, thank you so much for the information that lead us to finding this

**Comment by szv** [comment]
Thank you very much 😇
Now it's working 🥳🥳🥳🥳🥳

**Comment by Torsten85** [comment]
Yes! Solved my problem. Now we'll replace Apollo with Urql 😉
