### ISSUE TITLE
RFC: add AnnotatedOperationResult interface

### ISSUE THREAD

**Issue by jonathanstanley** [FormidableLabs/urql#2371]
## Summary

React, Vue, and Svelte bindings all use `{fetching:boolean}`
- https://formidable.com/open-source/urql/docs/basics/svelte/#run-a-first-query
- https://formidable.com/open-source/urql/docs/basics/vue/#run-a-first-query
- https://formidable.com/open-source/urql/docs/basics/react-preact/#run-a-first-query

however `@urql/core` doesn't appear to define the interface.

## Proposed Solution

@urql/core can include the interface.  I also had this in my [recent PR](https://github.com/FormidableLabs/urql/blob/6240f48c6315a1f94e2bc6ffff4fe4a437cd4643/packages/svelte-urql/src/common.ts#L24)

```ts
/**
 * An OperationResult annotated with convenience properties
 */
export interface AnnotatedOperationResult<Data, Variables>
  extends OperationResult<Data, Variables> {
  /** `true`: awaiting fetch response (no error, no data), otherwise `false` */
  fetching: boolean;
}
```

## Requirements

IMO, there should be a few status properties for convenience:
- `isIdle`: !fetching && !data
- `isFetching`: !!fetching && !data 
- `isSuccess`: !error && !!data
- `isError`: !!error

Since these all have `is` prefix, `fetching` and `isFetching` is redundant.  deprecate or drop `fetching`

**Comment by JoviDeCroock** [comment]
I personally don't really see a lot of merit in incorporating this in client as the state of fetching in core could both be the promise resolving when the consumer uses `.toPromise()` which could lead to confusion and resolve to a `cache-only` stream being open. hence the `fetching` concern is moved to the implementing client instead.

We have always attempted keeping urql as lightweight as possible, hence giving the consumer the power over creating these conveniences with wrappers,.... and enabling others to benefit from a minimal API-surface (not a lot of bits and bops) to get acquinted with.

**Comment by JoviDeCroock** [comment]
> is fetching:true during local cache: indexed-db lookup (async)?

Graphcache never does a lookup in indexed-db it is only used for data-hydration, hence using offline-storage isn't impacting the sync nature of our exchange chain

> is there a retry on network failure and does fetching change during retry?

This is the retry-exchange and it does, fetching is a binding specific thing hence us not moving it in core, as long as the exchange chain is busy we are in theory fetching and that is the only thing a binding should care about. When core does something special like returning an old result the bindings can choose to set fetching to false and indicate the result as stale because core will tell you.

**Comment by JoviDeCroock** [comment]
Closing as stale and due to the given answers giving a good indication why we aren't adding fetching etc to the client (promisified, ...)
