### ISSUE TITLE
reexecute in svelte doesn't work

### ISSUE THREAD

**Issue by isaacfink** [FormidableLabs/urql#2378]
I have this simple function to reexecute a query
```
function reexecute(){
      console.log('reexecuting')
      $category.reexecute()
    }
```

urql version & exchanges:
`"@urql/svelte": "^1.3.3"`

**Expected behavior**
new query should be triggered

**Actual behavior**
nothing shows up in network tab, and nothing gets updated in the ui

**Comment by JoviDeCroock** [comment]
Have you tried doing `$category.reexecute({ requestPolicy: 'network-only' })` as without it you'll be using the default from your client which is probably `cache-first`

**Comment by isaacfink** [comment]
@JoviDeCroock thank you so much, I couldn't find it in the documentation guess I had a brain freeze, sorry for waisting your time
