### ISSUE TITLE
Cause error when specifying context of `useQuery`

### ISSUE THREAD

**Issue by dqn** [FormidableLabs/urql#2379]
urql version & exchanges:

- v2.2.0 & no exchanges
- v2.0.4 & no exchanges

**Steps to reproduce**

Add `context` option (empty or not, it shouldn't matter) for `useQuery`.

```js
const [res] = useQuery({
  query: TodoQuery,
  context: {},
});
```

**Expected behavior**

Works without errors.

**Actual behavior**

Cause following error.

```
Too many re-renders. React limits the number of renders to prevent an infinite loop.
```

I want to use `suspense` option like this issue #2111.

```js
const [res] = useQuery({
  query: TodoQuery,
  context: {
    suspense: true,
  },
});
```

CodeSandBox:
https://codesandbox.io/s/determined-meadow-47yow6?file=/src/components/Todos.js

**Comment by JoviDeCroock** [comment]
You have to memoize the context object this is in the docs. We can't assume when you want to refetch due to a ctx change

**Comment by dqn** [comment]
Thank you! I wish there was a way to make it easier to realize that memoization is a must...
