### ISSUE TITLE
Just for React?

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#238]
Just for React?

Angular, Vue, Svelte?

**Comment by kitten** [comment]
Yes, currently this library is mainly geared towards React. That wouldn't stop anyone from writing a new wrapper around it though! In fact, we have a small section in the docs on that https://github.com/FormidableLabs/urql/blob/master/docs/extending-and-experimenting.md#writing-new-apis-for-the-client

For now, this is not something we'd like to take on just yet. Sorry!

**Comment by parkerziegler** [comment]
For what it's worth, we do have bindings to use `urql` with ReasonML / ReasonReact, with a version to support `urql@1.x.x` going out later today / tomorrow. https://github.com/FormidableLabs/reason-urql

**Comment by milahu** [comment]
> Svelte

yes yes yes!

sounds like a perfect match, in terms of performance

* [Computer, build me an app - Rich Harris - JSConf EU 2018](https://youtu.be/qqt6YxAZoOc)
* [Shift Dev 2019: "Rethinking Reactivity" - Rich Harris (New York Times)](https://youtu.be/gJ2P6hGwcgo)
* [The Return of 'Write Less, Do More' by Rich Harris | JSCAMP 2019](https://youtu.be/BzX4aTRPzno)

cos react's "virtual dom" is a bug, not a feature
cos compilers are always better than runtimes

[svelte-apollo](https://github.com/timhall/svelte-apollo) is there already
but we all know, apollo is too heavy
client side validation? waste of time

so urql-svelte is on my todo list ....
but [dont expect anything](https://youtu.be/m7P7fPSGXpg?t=3) : P

**Comment by frederikhors** [comment]
@milahu any news?

**Comment by JoviDeCroock** [comment]
@frederikhors urql is usable outside of React, if you are querying specifically about svelte, I've started working on it [here](https://github.com/JoviDeCroock/svelte-urql) if you have more svelte experience it's more than welcome. This is a spare-time project so I haven't dedicated that much time to it yet.
