### ISSUE TITLE
Next-urql: SSR not working

### ISSUE THREAD

**Issue by AvKat** [FormidableLabs/urql#2396]
This single file is basically a copy of what is said in the next-urql docs but with does not work when `ssr: true`.  Next.Js crashes saying `ReactDOMServer does not yet support Suspense.`. I have no idea what do do now.
```
import { withUrqlClient } from "next-urql";
import Link from "next/link";
import { cacheExchange, dedupExchange, fetchExchange, useQuery } from "urql";

const pokemonQuery = `
  query firstTwentyPokemons {
    pokemons(first: 200) {
      name
      image
    }
  }
`;
const createUrqlClient = (ssr) => ({
  url: "https://graphql-pokemon2.vercel.app/",
  exchanges: [dedupExchange, cacheExchange, ssr, fetchExchange]
});

function Home() {
  const [{ data: pokemons }] = useQuery({ query: pokemonQuery });
  console.log(pokemons);
  return (
    <ul>
      {pokemons?.pokemons.map((pokemon) => (
        <li key={pokemon.name}>
          <Link as={`/pokemon/${pokemon.name}`} href="/pokemon/[name]">
            <a>
              <h2 style={{ textTransform: "capitalize" }}>{pokemon.name}</h2>
              <img src={pokemon.image} alt={`${pokemon.name} pic`} />
            </a>
          </Link>
        </li>
      ))}
    </ul>
  );
}

export default withUrqlClient(createUrqlClient, { ssr: true })(Home);

```

Package versions:
```
"graphql": "^15.0.0",
"next": "latest",
"next-urql": "^3.3.2",
"react": "^17.0.2",
"react-dom": "^17.0.2",
"urql": "^2.2.0"
```

(I was not able to reproduce this on codesandbox but just using this as the `pages/index.tsx` can help reproduce)

**Comment by JoviDeCroock** [comment]
Have you tried our example? Maybe it's the new next/react version. Typically this error would imply that your query failed to resolve during react-ssr-prepass which runs in getInitialProps.

**Comment by AvKat** [comment]
Okay so I tried your example, which has `"next": "10.1.2"`, but when I upgraded that to the latest (`12.1.5`), I got the same error. I suspect its because next 12 also experimentally supports the React 18 Suspense data fetching and that is what's crashing. Do you think there's any way around that?

Also, I went through the example and found a page with `ssr: true` and another with `getServerSideProps`. I was wondering if there's any difference between them.

**Comment by pdong** [comment]
@AvKat Does your example work with 12.1.4? I noticed an issue the same issue with my custom `_app.js` on 12.1.5

**Comment by AvKat** [comment]
@pdong Yeah I think only the latest one has the issue. Thank you for your help!
