### ISSUE TITLE
RFC: Mutable graphcache configuration at runtime

### ISSUE THREAD

**Issue by CreativeTechGuy** [FormidableLabs/urql#2397]
## Summary

In the process of rewriting a large app to urql, I see a problem where there are queries located across many files but all of the resolvers/keys/updates/etc need to be in-line in the cacheExchange setup. It'd make sense to co-locate the appropriate graphcache configuration with the queries that need it.

## Proposed Solution

Two easy options:

* An API which acts like a reducer, you pass a function to it, it receives the current config object, then you can mutate that object to add/remove/change anything and then return the updated object. This function could then be called prior to calling a query to setup the appropriate configuration needed for that query.
* Make the object which is passed to `cacheExchange` safely mutable. This would allow consumers to pass in a reference to an object in the client setup and then hold a reference to that configuration so they can mutate it however they see fit. This may already be possible depending on how the internals of cacheExchange work today, but it'd be nice to have this be a documented use-case so we can depend on it.

Both of these would lead to better code splitting since the graphcache configuration would be located with the queries that need it and only "registered" if they are used.

## Requirements

* N/A

**Comment by kitten** [comment]
This is by design, we have a centralised configuration because it's not safe to split up the config without knowing where parts are used. The exception is at most the `updates` config option. However, all other configuration options must be available when any type globally is available and could occur in any query.

The important note here from a prior discussion is that the configuration is already mutable. In other words, while we don't recommend this, you can split it up: https://github.com/FormidableLabs/urql/discussions/1868

**Comment by CreativeTechGuy** [comment]
Can you elaborate on why this isn't safe? It's strange that it is something which can work and is supported but not documented and "not safe". I'd like to understand what problems I may run into if I do this.

**Comment by kitten** [comment]
Say you have a `keys` or `resolvers` configuration that's only defined in part of your application. It's pretty likely that eventually you'll run into cases where the types or fields that depend on these parts of the configuration won't be accessible yet. In other words, we simply don't guarantee any defined behaviour when this configuration changes on the fly.

This is basically effort that we don't find worth the cost of having to manage this configuration separately. Typically, these updaters are designed to stay manageably small, so it's not too unlikely that splitting them up will ultimately not save as much later on as the effort it costs upfront. Meaning, it's not impossible, but also not advisable as long as tooling doesn't support it.

There's also a certain philosophy behind it. It's tempting to say that updaters and optimistic results may be grouped with where mutations are used, and resolvers and keys should occur where they're used in queries, but as apps grown, from our observation, it's unavoidable that these are two distinct parts. In other words, adding them to UI code ultimately makes GraphQL front end code more unmanageable as applications grow.
Updaters having to be reused when mutations that depend on them are used, adding resolvers as their fields are used in queries (or mutations), and the likes is error prone, and ultimately your UI code shouldn't have to care about this.

Personally, I see GraphQL as the best data dependencies abstraction when it comes to using it in code. When mutations and queries are written it's a decent language to say what you want to do or what data you need. From that principle you can also derive a lot of the recommendations that some GraphQL tooling makes. For instance, fragments are great tools to compose data dependencies. That said, the normalised cache is usually something that adapts to data as it's thrown at it. Hence, the need for some customisations in a central place. However, when those data dependencies are defined where they're needed that usually is, at least to me, just a place of "data binding" but not the primary place of business logic or data logic in general.

Hope that clarifies it a bit :v: but I'm very aware this is more of a collection of thoughts, so not the best explanation 😅
