### ISSUE TITLE
Avoid stale state updates

### ISSUE THREAD

**Issue by jackfranklin** [FormidableLabs/urql#240]
I think that `useQuery` needs to track if it's been unmounted to avoid stale updates.

We're seeing:

```
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all sub
```

And I think it's coming from `useQuery`. I think the `setState` calls need to be conditional based on some variable that we toggle from `true` to `false` when the component gets updated.

Much like this `usePromise` example: https://gist.github.com/mjackson/05c7749430d0ec87b66612733805bad6.

Happy to make the PR if you're happy with this proposal?

**Comment by andyrichardson** [comment]
This should be easily doable using a ref on mount/unmount.

**Comment by kitten** [comment]
#256 will additionally ensure that we don't regress on this
