### ISSUE TITLE
Codegen uses `DOM Event` type for my custom `Event` object in schema

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#2403]
urql version & exchanges: `"@graphql-codegen/typescript-urql-graphcache": "2.2.10"`

**Steps to reproduce**

1. If I use the name `event` for an object codegen generates it but using `DOM Event` type :smile:

**Expected behavior**

It generates my own `Event` type.

**Actual behavior**

![image](https://user-images.githubusercontent.com/41120635/163705999-5a2424bc-01bd-45f9-ab67-68c305fca2d3.png)

**Comment by frederikhors** [comment]
I opened https://github.com/dotansimha/graphql-code-generator/issues/7775.

**Comment by JoviDeCroock** [comment]
That sounds like a more suitable place for the issue yea 😅

**Comment by frederikhors** [comment]
I thought that you are managing those packages anyway.
