### ISSUE TITLE
executeQuery returns old data and ignores fetched data

### ISSUE THREAD

**Issue by chojnicki** [FormidableLabs/urql#2409]
For some reason when I'm executing query that was already called before in other part of app, it returns previous data instead. It behaves like cache (that I disabled by network policy in client) but it's not because fetch is actually executed in devtools network tab. I'm receiving fresh data, but `executeQuery` returns old one anyway o.O If I reexecute it again and again it always returns data from previous one.

In real world scenario I'm fetching user data on init. If api does not return data (token expired) user need's to log in. After that I'm fetching user again on same query by using `executeQuery` again. Now API returns correct user, but urql still sees that response as null even that it's not. I'm debugging this now by returning random number in endpoint.

I noticed also:
- In real app I have this query extracted in composable, but it does not matter. Same behavior if I just duplicate queries in two components.
- If I change ANYTHING in one of queries like field or name - it works fine.

urql version & exchanges: @urql/core@2.4.4 @urql/vue@0.6.1

**Steps to reproduce**

1. App.vue

```
<template>
  <router-view />
</template>

<script setup lang="ts">
import { gql, useQuery } from '@urql/vue'

useQuery({
  query: gql`
    query GetLoggedUser {
      me {
        id
        randomNumber
      }
    }
  `,
}).then(({ data }) => {
  console.log(data.value.me)
})
</script>
```
2. SomePage.vue

```
<template>
  <button @click="demo">
    Demo
  </button>
</template>

<script setup lang="ts">
import { gql, useQuery } from '@urql/vue'

const getLoggedUserQuery = useQuery({
  query: gql`
    query GetLoggedUser {
      me {
        id
        randomNumber
      }
    }
  `,
  pause: true,
})

const demo = () => {
  getLoggedUserQuery.executeQuery()
    .then(({ data }) => {
      console.log(data.value.me)
    })
}
</script>
```

**Expected behavior**

In console I should have two random numbers fetched from API.

**Actual behavior**

In console I have two same numbers (from first execution of query).

![Screenshot from 2022-04-19 21-39-55](https://user-images.githubusercontent.com/34774522/164088683-95a37d02-a5be-4b80-a0fb-c2e21d77169b.png)

![Screenshot from 2022-04-19 21-40-37](https://user-images.githubusercontent.com/34774522/164088692-7dce1325-edda-4a7e-8993-6134429b7b37.png)

**Comment by JoviDeCroock** [comment]
Is it right to assume you are dealing with a cached result being returned and another fetch happening in the background? If so that is expected behavior you can remedy this with

```js
    return new Promise(resolve => {
      const subscription = pipe(
        client.executeQuery(),
        subscribe(result => {
          if (!result.stale && !result.hasNext) {
            Promise.resolve().then(() => {
              subscription.unsubscribe();
              resolve(result);
            });
          }
        })
      );
    });
```

**Comment by chojnicki** [comment]
> TIL we have an async execute in the vue bidnings, do you have a reproduction for this?

Can you elaborate? If I use async and wait, it's same thing.

**Comment by JoviDeCroock** [comment]
No I mean, can you provide a sandbox reproducing the issue. I'm assuming it's a bug in the vue bindings but yeah 😅 can't tell atm

**Comment by chojnicki** [comment]
I tried but I cannot find any public graphql example api that provides random numbers or timestamps in response so it could show issue on codesandbox :/ Will try again later or just create my own..

**Comment by chojnicki** [comment]
@JoviDeCroock https://codesandbox.io/s/eloquent-clarke-nmi52t

After start in console you should see random number received from query executed inside App.vue. 
After clicking button in component (Query.vue) it executes same query defined in that component (duplicated query code for testing purposes). Problem is that it logs same number from first query, even that it received different random number. After clicking again it will show that second number. So I'm always one result behind. If that is expected behavior then I'm confused ;)

**Comment by chojnicki** [comment]
I can confirm that on v0.6.2 everything works fine now! :tada: 

Too bad I lost 2 days trying to figure this out thinking that it had to be something wrong with my code and not urql... 

Thanks for instant reply and fix! :pray:
