### ISSUE TITLE
cache.updateQuery returns always null

### ISSUE THREAD

**Issue by ronaldruzicka** [FormidableLabs/urql#2423]
### Discussed in https://github.com/FormidableLabs/urql/discussions/2181

<div type='discussions-op-text'>

<sup>Originally posted by **jdinartejesus** January  8, 2022</sup>
Hi everyone, I'm having issues with `updateQuery` on graphcache and I don't understand your examples. I'm not using `offlineExchange` since I don't need it, I'm using instead `cacheExchange` from `"@urql/exchange-graphcache"`. I'm trying to update my cache with `cache.updateQuery` but always returns null. Reading the docs, says it's normal because isn't cached before? But isn't all the queries being cached automatically? 

I'm added a new note, but the query `getPlayerProfileActivities` was already run before and should have been cache, I believe.

```
TabActivities.Vue
 ...
 const { data, fetching } = useQuery({
    query: getPlayerProfileActivities,
    variables: {
      playerId: computed(() => props.player?.id),
      workspaceId: computed(() => workspaceId.value),
    },
  });
...

graphql-cache.js
...
 updates: {
      Mutation: {
        insert_player_note_one: (result, { player_id, workspace_id }, cache) => {
          if (!result?.insert_player_note_one) return;

          const variables = { playerId: player_id, workspaceId: workspace_id };
          cache.updateQuery({ query: getPlayerProfileActivities, variables }, (data) => {
            console.log("data ==>", data);
            if (data) data.player_by_pk.notes.push(result.insert_player_note_one);
            return data;
          });
        },
     }
     ...
```

We have the same issue. We have a list of items and when we use any dynamic `variables` on that query, e.g. `limit` or `where` condition with an `id` field we get `data: null` from `cache.updateQuery` callback. But when we don't use dynamic `variables`, we normally get data from that callback.

We are trying to implement infinite scroll pagination with `simplePagination` resolver using `limit` and `offset` variables to our query. But when we have to update that query due to changes to one item, e.g. delete (we have soft delete, that we just update field `deletedAt` and query only items where is it `null`), we don't get any `data` from the `cache.updateQuery` callback, so we cannot update the cache and the deleted item stays rendered.

```js
const cacheConfig = {
  updates: {
    Mutation: {
      updateCase: (result, _args, cache, info) => {
        cache.updateQuery(
          { query: CASES_QUERY, variables: { id: info?.variables?.pkColumns?.id } },
          (data) => {
            if (result.updateCase?.deletedAt) {
              if (data) {
                //  "data" here is null, when using dynamic variables with limit, offset or id, so the "filter" never runs
                const changedData = data.cases.filter(
                  (caseData) => caseData.id !== result.updateCase.id,
                );

                return { cases: changedData };
              }
            }

            return data;
          },
        );
      },
    },
  },
};
```
Please what are we doing wrong?

**Comment by ronaldruzicka** [comment]
So I found out, why the `data` is `null` when using dynamic variables. It looks like the query is different when using `offset: 10` and when `offset: 20`. Moreover we didn't even pass the `offset` to the `variables` in the `cache.updateQuery`. If I hardcoded the variables it was returning data, that was in `cache` for that particular `offset`. Now the problem is, that I cannot, or don't know, how to pass the dynamic `offset` that is in `query: CASES_QUERY` when using the `mutation UpdateCase`, since the `offset` lives only in the component and unlike Apollo or React Query, we cannot update cache in a component, but it the static object when using `cacheExchange`. I can only read from the `mutation`s variables, but there is no information about the current `offset`. 

Is there a way to pass the `offset` variable to the `cache.updateQuery` when using `updates.Mutation`?

**Comment by kitten** [comment]
This is a question not an issue or a report of a bug. Please stick to the discussion you've already mentioned 😅

We also got this question a lot of times before in different forms — browsing the past discussions is super worth it 👀

Also, you can pass variables outside of the mutations' defined variables to your updaters. It isn't 100% safe to be fair, but in some cases it's possible. However, we'd recommend using `cache.inspectFields` as documented and commented in the discussion
