### ISSUE TITLE
RFC: preserving startCursor / endCursor in cases of empty pagination results

### ISSUE THREAD

**Issue by tgriesser** [FormidableLabs/urql#2430]
## Summary

When using relay style cursor pagination to fetch the latest result

```
connectionField(first: 10)
```

We get a result that looks like this:

```
pageInfo: { startCursor: 'ABC', endCursor: 'DEF' }
nodes: [{ ... }, { ... }, { ... }, ...]
```

If we want to poll for items earlier newer than `startCursor`, we might want to query for something like:

```
connectionField(last: 10, before $startCursor)
```

The issue is that when there is an empty result set: 

```
pageInfo: { startCursor: null, endCursor: null }
nodes: []
```

The `relayPagination` will then merge in & return the `null` cursor values for this latest result set. Ideally we'd like to keep the latest known `startCursor` so we can continue to re-issue the query for items before the `startCursor`.

## Proposed Solution

Add a new option, maybe named something like `skipEmpty` or `excludeEmpty`, which would skip over results that don't have any nodes/edges while [looping through the pages](https://github.com/FormidableLabs/urql/blob/e1278c91b8bb601e57835179c202ac4526c6f1bf/exchanges/graphcache/src/extras/relayPagination.ts#L207-L217) in the `relayPagination` helper, so as to not clobber the cursors for the existing paginated list.

```ts
if (params.excludeEmpty && (page.edges.length === 0 && page.nodes.length === 0 && typename)) {
  continue
}
```

**Comment by kitten** [comment]
Hm, I'd go as far as to say this is a bug since it's unexpected behaviour as per the intention of the relay spec 🤔
