### ISSUE TITLE
Issue Invalidating Storage

### ISSUE THREAD

**Issue by leggomuhgreggo** [FormidableLabs/urql#2443]
## Overview

Trying to validate the [Cache Invalidation on Logout](https://formidable.com/open-source/urql/docs/advanced/authentication/) functionality, extended with `storage.clear()` using graphcache + offlineExchange.

Doesn't seem to want to clear as expected.

Repro: [codesandbox](https://codesandbox.io/s/urql-graphcache-storage-h48h7c?file=/src/index.tsx:200-210)

`urql@2.2.0`
`@urql/exchange-graphcache@4.4.0`

## Things I've Tried So Far

I reviewed these related issues [#1684, #297] and looked over the relevant [code](https://github.com/FormidableLabs/urql/blob/3eaed7ea172e7f7b2cf91ee12af239806e9f8cc2/exchanges/graphcache/src/default-storage/index.ts#L100-L110) but nothing jumped out at me. 

My IndexedDB chops aren't very sophisticated but I took a swing at manually deleting the db with `indexedDB.deleteDatabase(dbName)` but no luck (blocked transaction I think, may revisit)

Quite possible I've overlooked something simple. 

## Additional Context

In case it's useful, my goal is to make sure there's no chance of user PII sticking around in the browser, in case someone is using my app from a public computer, for example. 

Thanks!

**Comment by JoviDeCroock** [comment]
This looks to be a change in chrome/Firefox, are you seeing the following error message aswell?

```
DOMException: The user denied permission to access the database.
```

**Comment by nightgrey** [comment]
I have the same issue as you; the DB is just.. not cleared. :+1:

**Comment by nightgrey** [comment]
@leggomuhgreggo 

I had success in clearing IndexedDB via

```
          const transaction = global.indexedDB.deleteDatabase('graphql-cache');
          await new Promise((resolve, reject) => {
            transaction.addEventListener('success', resolve);
            transaction.addEventListener('error', reject);
          });
```

The database will be deleted. The only issue is that you have to reload the page until the browser does not have access to the data anymore (I guess it is in RAM?). Even though Chrome DevTools doesn't show a DB anymore, the data will still be retrieved from it when `urql` performs requests.

That is the best workaround I have found yet.

**Comment by JoviDeCroock** [comment]
```js
          const transaction = global.indexedDB.deleteDatabase('graphql-cache');
          await new Promise((resolve, reject) => {
            transaction.addEventListener('success', resolve);
            transaction.addEventListener('error', reject);
          });
          setClient(createClientProp());
```

Are you doing the above? In your code example it looks like you first reconstruct the client which would mean that it still has the oppurtunity to read before it gets cleared/destroyed

**Comment by nightgrey** [comment]
> ```js
>           const transaction = global.indexedDB.deleteDatabase('graphql-cache');
>           await new Promise((resolve, reject) => {
>             transaction.addEventListener('success', resolve);
>             transaction.addEventListener('error', reject);
>           });
>           setClient(createClientProp());
> ```
> 
> Are you doing the above? In your code example it looks like you first reconstruct the client which would mean that it still has the oppurtunity to read before it gets cleared/destroyed

Yes, I am - but only because `storage.clear()` doesn't / didn't work.. but now that you say that, you might be right ...

Here's my whole `urql` file:

```jsx
import {
  createClient as urqlCreateClient,
  dedupExchange,
  fetchExchange,
  Provider as UrqlProvider,
} from 'urql';
import { devtoolsExchange } from '@urql/devtools';
import { offlineExchange } from '@urql/exchange-graphcache';
import { makeDefaultStorage } from '@urql/exchange-graphcache/default-storage';
import { refocusExchange } from '@urql/exchange-refocus';
import { requestPolicyExchange } from '@urql/exchange-request-policy';
import schema from '../../../schema.json';

// Create a persistent cache storage
const storage = makeDefaultStorage();

/**
 * Create a `urql` client
 *
 * @param {import('urql').ClientOptions} opts
 * @return {Client}
 */
export const createClient = (opts) =>
  urqlCreateClient({
    url: `${config.api.urls.gateway.http}/graphql`,
    exchanges: [
      devtoolsExchange,
      dedupExchange,
      offlineExchange({
        schema,
        storage,
        keys: {
          LeadPage: () => null,
          PropertyObjectDetails: () => null,
        },
        resolvers: {
          Queries: {
            lead: (data, args) => ({
              __typename: 'Lead',
              id: args.id,
            }),
          },
        },
      }),
      fetchExchange,
      refocusExchange(),
      requestPolicyExchange(),
    ],
    fetchOptions: () => {
      const accessToken = getAccessToken(computeLocalBundle());

      return {
        headers: { authorization: accessToken ? `Bearer ${accessToken}` : '' },
      };
    },
    ...opts,
  });

export const ClientContext = React.createContext({
  resetClient: () => {},
  client: null,
});

/**
 * ClientProvider
 *
 * Provides `urql` client and allows resetting it via `useClient` to clear caches.
 *
 * @see https://github.com/FormidableLabs/urql/issues/297#issuecomment-504782794
 */
export const ClientProvider = ({
  createClient: createClientProp,
  children,
}) => {
  const [client, setClient] = React.useState(createClientProp());

  return (
    <ClientContext.Provider
      value={{
        resetClient: async () => {
          setClient(createClientProp());

          if (!storage) return;

          await storage.clear();

          const transaction = global.indexedDB.deleteDatabase('urql-cache');
          await new Promise((resolve, reject) => {
            transaction.addEventListener('success', resolve);
            transaction.addEventListener('error', reject);
          });
        },
        client,
      }}
    >
      <UrqlProvider value={client}>{children}</UrqlProvider>
    </ClientContext.Provider>
  );
};

ClientProvider.propTypes = {
  createClient: PropTypes.func.isRequired,
  children: PropTypes.element,
};

ClientProvider.defaultProps = {
  children: null,
};

/**
 * UseClient
 *
 * @example
 *   const { resetClient, client } = useClient();
 * @return {{ resetClient, client }}
 */
export const useClient = () => React.useContext(ClientContext);
```

So, basically what I do is before logging in and when logging out, I call...

```jsx
import { useClient } from 'app-lib/urql';

// Hook that runs on every login
export const useLoginFlow = () => {
  const { resetClient } = useClient();

  resetClient();
}

// Hook that runs on every logout
export const useLogoutFlow = () => {
  const { resetClient } = useClient();

  resetClient();
}
```

I'll see if it works without re-creating the client and/or switching the order.

**Comment by nightgrey** [comment]
@JoviDeCroock 

I reduced `resetClient` to `storage.clear()`, but that doesn't clear the storage either. It persists after storage.clear() is executed, which I confirmed by debugging.

![image](https://user-images.githubusercontent.com/6065401/168267125-82191f0b-ff0a-4b95-9764-b9c227b2c58e.png)

It is, as far as I can see, executed properly... it just doesn't clean anything. 

![image](https://user-images.githubusercontent.com/6065401/168267412-920584a9-d5ab-479b-9f2a-47e14f51e0cf.png)

**Comment by JoviDeCroock** [comment]
Have you tried manually clearing, I know they changed something of clearing in a worker but no idea how that affects stuff. Anyhow the deletion should work as long as you create the client after (similar for clear, you would need to listen/wait for the event and after recreate)

**Comment by JoviDeCroock** [comment]
Quickly forked the example to show what I mean, you are dealing with a non-awaited function there because of the iife closure. This means that you will clear when the client is activating or is still active meaning it can still read the store. Here's an example of how this can work [sandbox](https://codesandbox.io/s/urql-graphcache-storage-forked-7e4zz1?file=/src/index.tsx)

You will see that initially the data will output an empty object, when we press login it will still log an empty object, after 1 second it will show you the hydrated state, when we press logout you will see an empty object again.

<img width="738" alt="Log output going in the sequence of: logged out (empty object), logged in (empty object), After completed login (hydrated object with pokemon data) and finally logged out (empty object)" src="https://user-images.githubusercontent.com/17125876/168551028-617feaf9-85a3-462d-b65a-4b953184ca7f.png">

**Comment by JoviDeCroock** [comment]
Are you recreating the cache or are you keeping it in memory?
