### ISSUE TITLE
RFC: Svelte - query anytime anywhere

### ISSUE THREAD

**Issue by EskelCz** [FormidableLabs/urql#2449]
## Summary

If I understand correctly, right now in the svelte bindings it is presumed that a single query will run with the component loading and that's it. When I try to do a query at a later time (in a function triggered by user interaction for example), the library triggers "Error: Function called outside component initialization".
Demo:  [https://stackblitz.com/edit/sveltekit-urql-issue-demo](https://stackblitz.com/edit/sveltekit-urql-issue-demo)
Just to be sure I tried all the usual fixes (turning off SSR, passing down the client with sveltekit fetch, etc)

I feel like this is a valid and frequently needed use case which should be supported.

First I thought it's a bug, but after reading dozens of threads I came to understand it's an unsupported use case of urql/svelte.

## Proposed Solution

It just has to work whenever data querying or mutation is needed.

I became quite desperate, I need this use case to work to move on with my project.
Thanks for your consideration.

**Comment by JoviDeCroock** [comment]
Have you tried using the core urql client? Sounds more appropriate for this case compared to framework bindings as this is a limitation of state in fe frameworks

**Comment by jonathanstanley** [comment]
@EskelCz  Maybe this is duplicate of #2110 which should be resolved with #2369 ?

**Comment by EskelCz** [comment]
@JoviDeCroock It's a bit verbose but it works well, thank you. :)

@jonathanstanley Not sure about the duplicate but I'm hoping the new urql/svelte version will allow this use case. That's why I raised it there as well.

**Comment by EskelCz** [comment]
The urql/svelte 2.0 update didn't help much. It doesn't throw an error, but only says the query is paused. Any way around it?
Demo: [https://stackblitz.com/edit/sveltekit-urql-issue-demo-xl476c?file=src/routes/broken.svelte](https://stackblitz.com/edit/sveltekit-urql-issue-demo-xl476c?file=src/routes/broken.svelte)

**Comment by JoviDeCroock** [comment]
No other way around it afaik this is how Svelte works, just like how other frameworks don't allow you to start state in an event closure, which makes sense as that would make the state short-lived or one-off

**Comment by EskelCz** [comment]
@JoviDeCroock But that's exactly what's needed, a short-lived one-off database request, triggered on user interaction.

Should urql explain people with such need (who use sveltekit) that they need to use urql/core for that? We know it's not that urql in general can't do it.

Even very simple websites and web apps need database interaction based on user actions. Search, subscriptions, discussion, filtering, paging, orders, rating, etc etc.

**Comment by JoviDeCroock** [comment]
Well `@urql/svelte` is an integration with a front-end library, i.e. it adheres to their state-cycle 😅 if you want to perform stuff outside of their state-cycle and scope those down then you will need to do one-off requests which we support _as well_ in the core package. I mean, I am not sure what you expect me to say here 😅 if you can give me an example of how other Svelte libraries bypass this within the Svelte lifecycle I am more than open to it but afaik, not a Svelte expert, this is common amongst all front-end libraries and general how those lifecycles work

**Comment by tmarsik42** [comment]
I don't know if this will help you @EskelCz, but that error `Error: Function called outside component initialization` is coming from svelte. Check this terrible example on [repl](https://svelte.dev/repl/e9ad66846f5d4e468e02b0468272980f?version=3.48.0).

`setContext` or `getContext` must be called during  component initialisation. That means you have to save client from context outside of the function.

Another thing that I noticed in your example is, that you approach store's instance instead of its value with $. I updated your example [here](https://stackblitz.com/edit/sveltekit-urql-issue-demo-pt4nna?file=src/routes/broken.svelte), it works now.

**Comment by EskelCz** [comment]
@tmarsik42 Thank you so much, you saved me. :) Just what I needed to understand what's happening.
