### ISSUE TITLE
Links in Docs go to 404

### ISSUE THREAD

**Issue by ijones16** [FormidableLabs/urql#246]
I noticed some links in the docs navigate to 404's.

It looks like the base url isn't getting set correctly if you navigate through the menu:

![urql_docs](https://user-images.githubusercontent.com/4407263/58726197-1e288c00-83af-11e9-8ee7-e0f5e93d68e0.gif)

The first time I click `API` the link goes to a 404 route: `https://formidable.com/docs/getting-started/#writing-queries`

If you refresh on the page, you will get the desired link: `https://formidable.com/open-source/urql/docs/getting-started/#writing-queries`.

**Comment by kitten** [comment]
cc @VirtualDOMinic @kiraarghy et al

**Comment by VirtualDOMinic** [comment]
At first glance, I'm concerned this could be an issue with how `react-live` builds relative paths... Might need to have a look at this with someone else (and might feed into our doc site strategy @jevakallio ?) but I'll assign @kiraarghy and me for now

**Comment by kitten** [comment]
This should be fixed, but let's open new issues if there's more issues :)
