### ISSUE TITLE
`suspense: true` causes duplicated requests

### ISSUE THREAD

**Issue by fathyb** [FormidableLabs/urql#2465]
urql version & exchanges:
- `@urql/core@2.5.0`
- `@urql/exchange-graphcache@4.4.1`

**Steps to reproduce**

1. Create a client with `suspense: true` and `requestPolicy: cache-and-network`
2. Render the app using the new `createRoot` or `hydrateRoot` React API

**Expected behavior**

Only one request is made.

**Actual behavior**

Two requests are made.

**Reproduction**

Run this sandbox to see two requests being made: https://codesandbox.io/s/vibrant-saha-8bdm4g?file=/src/index.js

---

I have a feeling that's related to React making a separate fiber when suspending, `useQuery` is called again in a different context, which makes it think it's called for the first time. I didn't dig deeper though..

**Workaround**

I'm using this simple exchange to dedupe all requests made within a second:
```js
const operations = new Map<number, number>()
const exchanges = [
    ({ forward }) =>
        (source) =>
            pipe(
                forward(
                    pipe(
                        source,
                        filter(({ key, kind, context }) => {
                            if (
                                kind === 'query' &&
                                context.requestPolicy === 'network-only'
                            ) {
                                const limit = operations.get(key)

                                return !limit || limit < Date.now()
                            }

                            return true
                        }),
                    ),
                ),
                tap(({ operation, hasNext }) => {
                    if (
                        !hasNext &&
                        operation.context.meta?.cacheOutcome !== 'hit'
                    ) {
                        operations.set(operation.key, Date.now() + 1000)
                    }
                }),
            ),
    dedupExchange,
    cacheExchange({ keys }),
    ssrExchange,
    options.fetchExchange ?? fetchExchange,
]
```

**Comment by JoviDeCroock** [comment]
From a React point of view there aren't any ways around this becaue an interrupt isn't observable. This means that when the initial render happens we start the cache-miss fetch, then we get a response, un-suspend and have a cache-hit. Now the request-policy kicks in and refetches the cache-hit in the background. This is intended behaviour 😅

**Comment by fathyb** [comment]
Ah, got it. I think that this behaviour, while intended, is not the one most urql users are expecting. For example, doing SSR with the streaming APIs result in duplicated calls, increasing latency and resources needed to render a page.

Would you be receptive to a tested PR fixing the duplication?

**Comment by kitten** [comment]
Just to clarify, inherently, when you say `cache-and-network` then you're saying "when I ask for cached data, also load data again". So you're explicitly expressing that you want this behaviour. This is why we never recommend or explicitly tell people to change the default request policy for every request. This simply is wasteful.

That said, if you do want this behaviour, two identical requests will never be sent simultaneously. So it doesn't really matter whether it sends one or two requests, since the second one is only sent because it wasn't already being sent.

**Comment by fathyb** [comment]
I think the confusion here is that `suspense: true` is changing the request-policy behaviour, which isn't expected or documented.

I don't expect `suspense: true` to cause some requests to be sent twice in a row because I'm not asking for data twice. React might be, but I'm a user, it's transparent to me. I'm expecting urql to be `suspense` aware, and provide the same caching behaviour whether `suspense` is enabled or not.

For my use-cases, `cache-and-network` provides the best compromise between user experience (display cache data fallback when loading) and consistency (always query data when requested). I want cache data to be invalidated, but I don't want it to be wasteful.

> So it doesn't really matter whether it sends one or two requests, since the second one is only sent because it wasn't already being sent.

My main worry here is a ~1.5x increase of GraphQL-related hosting costs (bandwidth, compute and IOPS).

---

The workaround I mentioned fixes the `suspense` behaviour for me, so I'm closing this issue as you feel this is the desired behaviour. I'm editing the title to make it easier to find in case someone hits the same problem.

**Comment by kitten** [comment]
No, it's not changing the request behaviour. We never recommend using `cache-and-network` on every request by default. An operation is triggered on mount which means it sends off an operation that may then get fulfilled by the cache exchange. Depending on when React decides to unmount and remount or let a component lose its state (and as per Concurrent Mode we always now have to assume that state and effects are repeated or lost) then the operation is re-issued.

This is basically just a React-specific behaviour and working against it introduces other problems. To prevent it the simplest method is to not work against our caches.
We have a TTL-based `requestPolicyExchange` which is a much better compromise if you want to regularly let operations refetch

**Comment by jtomaszewski** [comment]
I find it very hard to comprehend this.

@kitten Are you saying that it is expected for urql with `cache-and-network` to trigger two API requests?

[Docs](https://nearform.com/open-source/urql/docs/basics/document-caching/#request-policies) currently say:

> `cache-and-network` returns cached results but also **always sends an API request**, which is perfect for displaying data quickly while keeping it up-to-date.

It's written "sends an API request", not "sends two API requests".

Thus, am I still misunderstanding something, is urql bugged, or are the docs misleading at the moment?

cc @fathyb
