### ISSUE TITLE
Custom exchange examples

### ISSUE THREAD

**Issue by alexraginskiy** [FormidableLabs/urql#247]
Are custom exchanges dependent on the `wonka` library? I'm having a hard time following that, since there is no documentation for that library.

**Comment by juank11memphis** [comment]
Hi yeah I would love to see some examples on how to create custom exchanges, this feature sounds really interesting but I am still having a hard time thinking what kind of things we can build and how we can build them.

Thanks for all the great work!

**Comment by kitten** [comment]
Hiya, this is definitely one of our high-priority issues that we'll address as part of our ongoing effort to provide more documentation 👍

**Comment by kitten** [comment]
@alexraginskiy @juank11memphis Hiya :wave: We've just started writing guides on how to build custom exchanges! https://github.com/FormidableLabs/urql/blob/master/docs/guides.md

There's currently only one on writing an authentication exchange, but the guide also details on what to keep in mind when writing custom exchanges, which we call "The Rules of Exchanges".

Furthermore the `wonka` library now has its own documentation site, with sections on its architecture and basics and a very detailed API reference document. https://wonka.kitten.sh/

I'll close this for now, but please let me know if you have any more questions :)

**Comment by cadenzah** [comment]
@kitten I can't find the document "The Rules of Exchanges", since the link you embeded is not available for now. Is there any link or alternative for that document?
