### ISSUE TITLE
The requested module does not provide an export named 'initClient'

### ISSUE THREAD

**Issue by beebase** [FormidableLabs/urql#2481]
After default installation of @urql/svelte adding this line to App.svelte results in an error.
Maybe it's related to vitejs
```
 import { initClient } from "@urql/svelte"
 initClient({
    url: "....",
  })
```
error
```
Uncaught SyntaxError: The requested module '/node_modules/@urql/svelte/dist/urql-svelte.mjs?v=c1b8d850' does not provide an export named 'initClient'
```
urql version & exchanges:
  "devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^1.0.0-next.30",
    "svelte": "^3.44.0",
    "vite": "^2.9.9"
  },
  "dependencies": {
    "@urql/svelte": "^2.0.0",
    "graphql": "^16.5.0",
  }

vitejs.config.js
```
  optimizeDeps: {
    exclude: [ '@urql/svelte']
  }
```

**Steps to reproduce**
see above

**Comment by kitten** [comment]
You're using `v2` of the `@urql/svelte` package. While the basics guides haven't been updated yet (see notice at the top of: https://formidable.com/open-source/urql/docs/basics/svelte/) we have already updated the API guide: https://formidable.com/open-source/urql/docs/api/svelte/#context-api

We'll still need more content and examples for this, but basically, the API now has switched over to store factories.
