### ISSUE TITLE
useMutation doesn't work with async/await

### ISSUE THREAD

**Issue by sachbazjan** [FormidableLabs/urql#2490]
urql version & exchanges:
version: 2.2.0
exchanges: [
  dedupExchange,
  cache,
  errorExchange({
    onError: (error: CombinedError) => {
      // eslint-disable-next-line no-console
      console.error('URQL ERROR', error);
    },
  }),
  fetchExchange,
],

**Steps to reproduce**

```
  const onSubmit = async (data: PreregisterInput) => {
    await inviteWorkerToCompany({
      companyId,
      userToInvite: data,
    });

    if (inviteWorkerToCompanyResult.error) {
      toast.error(t('userAccount.inviteFailed'), {
        position: 'bottom-center',
      });
      console.error(inviteWorkerToCompanyResult.error);
    } else {
      toast.success(t('userAccount.inviteSuccess'), {
        position: 'bottom-center',
      });
      refetch?.({ requestPolicy: 'cache-and-network' });
      closeTopModal();
    }
  };
```

In the example above inviteWorkerToCompanyResult.error is undefined even tough in console I'm getting error. Transforming the code above to use promise chain resolves the issue and in 

```
await inviteWorkerToCompany({
      companyId,
      userToInvite: data,
    }).then(result => { console.log(result) })
```

 result.error has the error inside of it

1. 2.

**Expected behavior**

inviteWorkerToCompanyResult should have the same output as result in promise chain

**Actual behavior**

inviteWorkerToCompanyResult has the same result as result in promise chain

**Comment by JoviDeCroock** [comment]
This is expected in React, the outer-closure will still be the one from the previous state, instead doing

```js
    const result = await inviteWorkerToCompany({
      companyId,
      userToInvite: data,
    });

   if (result.error)
```

will work

**Comment by sachbazjan** [comment]
@JoviDeCroock Thank you for your quick reply. One question. What is the purpose of in my case inviteWorkerToCompanyResult ? Seems quite useless

**Comment by JoviDeCroock** [comment]
in your case it's useless yes but you can also handle these cases differently, i.e. use an effect to react to errors, ... in which it becomes part of the reactive cycle which isn't subject to this outer-closure issue as it is part of the render closure.
