### ISSUE TITLE
urql/svelte v2 variables inside queryStore are mandatory.

### ISSUE THREAD

**Issue by mpiorowski** [FormidableLabs/urql#2495]
setContextClient throw "Unsafe call of an `any` typed value."

![image](https://user-images.githubusercontent.com/26543876/173444574-7e6c49d9-fe65-4e7c-b6e1-f11a449c9ed1.png)

Also variables inside queryStore are mandatory, not optional. Is this a correct behavior? Docs says it should be optional.

![image](https://user-images.githubusercontent.com/26543876/173444867-96f555e0-b661-4422-9757-bff312df07f0.png)

urql version & exchanges:
"@urql/svelte": "^2.0.1",

**Comment by JoviDeCroock** [comment]
We'll need some kind off reproduction as this seems an eslint error not JS-throwing 😅 also the value does seem typed [here](https://www.runpkg.com/?@urql/svelte@2.0.1/dist/types/context.d.ts#7)

**Comment by mpiorowski** [comment]
@JoviDeCroock Sorry, the first one was sth wrong with my eslint.

But the second one still exists, its typed, but still mandatory to write, so everywhere i have to write variables: {} if i am not using it.

Here's the newest sveltekit with typescript and error in _layout page:

https://github.com/mpiorowski/test

**Comment by JoviDeCroock** [comment]
Ah yes, we can make variables optional like other bindings

**Comment by mpiorowski** [comment]
@JoviDeCroock Maybe i can make my first public pr :D It's a simple task, so why not start here.
