### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by flexzuu** [FormidableLabs/urql#25]
Hey, can we publish typescript types for this package? 
I saw it is written in Typescript, so this should be easy. Using it in a Typescript code base not having types is a bummer.

Maybe we can just publish the raw `.ts` files but am not to confident about this option.

**Comment by flexzuu** [comment]
I explored a route with using [dts-gen](https://github.com/Microsoft/dts-gen) but it is not that great maybe using `tsc` instead of babel for the compilation would be better but I am not sure why babel was used in the first place.

**Comment by kenwheeler** [comment]
i'm not super familiar with generating or providing types. any tips or pr?

**Comment by dyst5422** [comment]
How do you want it emitted? As commonjs, or es2015 modules?

Also, not sure what benefit you're looking for out of using babel over just tsc as you aren't using the pipeline operator anywhere.

**Comment by dyst5422** [comment]
Basically, if you remove the `"allowJs"` and `"noEmit"` options and specify `"outDir": "./build"` it will emit to `./build` with types and sourcemaps.

**Comment by flexzuu** [comment]
I would second this

> Basically, if you remove the "allowJs", "experimentalPipelineStage1", and "noEmit" options and specify "outDir": "./build" it will emit to ./build with types and sourcemaps when you run tsc.

**Comment by dyst5422** [comment]
There are also a number of other adjustments I would make to the repo, like moving `tests` outside of the `src` directory so they don't get sucked into the distributable that's published to NPM. (You can still type check the test files by having a tsconfig that is for the IDE essentially and another one that extends it for building which excludes the tests)

**Comment by ryan-roemer** [comment]
@dyst5422 -- Tests are already ignored for publishing (modulo a small oversight with one file that I've just put up https://github.com/FormidableLabs/urql/pull/28 to fix). Take a look at https://unpkg.com/urql/ to see what we actually publish (and `lib|es/tests/utils/fetch-mock.js` being there is what I've just fixed).

**Comment by ryan-roemer** [comment]
Also, for anyone discussion CJS vs. ESM, our publishing approach is **both**. See, e.g.:

- ESM: unpkg.com/urql/es/
- CJS: unpkg.com/urql/lib/

Hope that helps!

**Comment by kenwheeler** [comment]
I'm reluctant to publish the actual .ts source, but as far as definitions, should I be publishing to @types, or running tsc and pointing at that from package.json? cc @danielrossenwasser

**Comment by ar1a** [comment]
I can't seem to get type hinting working. I think it's because theyre hidden under a types/ subfolder and not next to the .js or in a @types package.

Would you consider moving them to @types/urql?
