### ISSUE TITLE
@graphql-codegen/typescript-urql-graphcache optimistic update return type expects all the object props

### ISSUE THREAD

**Issue by villesau** [FormidableLabs/urql#2502]
Not sure whether this is supposed to be reported here or in graphql-codegen but I think this repo has more relevant audience.

urql version & exchanges:

**Steps to reproduce**

1. @graphql-codegen/typescript-urql-graphcache version 2.2.16
2. type the cachce exchange: `cacheExchange<GraphCacheConfig>(`
3. have optimistic update ( https://formidable.com/open-source/urql/docs/graphcache/cache-updates/#optimistic-updates )
4. try to return partial result, similar to what the actual mutation would return (only updated fields)
5. typescript complains about missing properties, it expects the whole object with all the properties

**Expected behavior**

To my understanding partial results should be fine. I might not even have the whole type fetched from the API.

**Actual behavior**

typescript complains about missing properties, it expects the whole object with all the properties.

This change happened in 2.2.10 version and is still happening in 2.2.16 version: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/urql-graphcache/CHANGELOG.md#2210

In 2.2.9 it was fine, unless it is intentional for some reason. Based on the documentation I think it should not be.

E: this is likely the problematic PR: https://github.com/dotansimha/graphql-code-generator/pull/7681

**Comment by JoviDeCroock** [comment]
Yes partial should be fine as we only expect the selectionSet to be fulfilled

**Comment by saihaj** [comment]
Released [`@graphql-codegen/typescript-urql-graphcache@2.3.0`](https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen/typescript-urql-graphcache%402.3.0)

**Comment by AndysonDK** [comment]
> To my understanding partial results should be fine. I might not even have the whole type fetched from the API.

What if the return type from the graphql schema and it's properties are non nullable then you would as a client expect a complete type, if not, an error should occur

**Comment by JoviDeCroock** [comment]
The partial nature of the result-type isn't meant to indicate the nullability part of a schema, it aims to indicate how selection-sets work, i.e. we could invoke a mutation selecting all fields which would include the `nullable` schema hint or only ask for one specific field.

**Comment by AndysonDK** [comment]
Ah I see now. Okay but let's say you make an explicit cache update for a specific mutation and that the mutation result type's properties are non-nullable. That means that the data you must pass to the cache update mechanism has to comply with the mutations result type which is, as said, a type with non-nullable properties not optional properties.
