### ISSUE TITLE
bs-platform peer dependency warning

### ISSUE THREAD

**Issue by mjadczak** [FormidableLabs/urql#251]
After installing urql 1.0.5, I get this warning from npm:
```
npm WARN bs-rebel@0.2.3 requires a peer of bs-platform@>=2.2.0 but none is installed. You must install peer dependencies yourself.
```
It seems like this dependency is brought in by wonka, used by urql:
```
$ npm list bs-rebel
<project>@0.1.0 /mnt/c/Users/mjadcza/Projects/<etc>
└─┬ urql@1.0.5
  └─┬ wonka@2.0.2
    └── bs-rebel@0.2.3
```
Do I actually need to install this peer dependency? If this is to do with the internal workings of wonka, I think urql should just explicitly require it, no? And if this is something I should install myself, it should probably be documented.

**Comment by kitten** [comment]
You don't need to install this and I basically forgot to remove this peer dependency from `bs-rebel`. It'll be fixed in the next release but feel free to ignore it for now 👍
