### ISSUE TITLE
Fast Refresh doesn't work with `useQuery`

### ISSUE THREAD

**Issue by nandorojo** [FormidableLabs/urql#2512]
## urql version & exchanges:

`urql@2.0.5`

## **Steps to reproduce**

1. Call `useQuery` in a component
2. Save the file
3. The result of the query will go empty and it will refetch

My hunch is that it may be related to [calling `setState` in render](https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/src/hooks/useQuery.ts#L145-L152)(?)

I haven't seen this kind of React code before so it's hard for me to know how to potentially adjust the `useQuery` internals.

## **Expected behavior**

Fast refresh shouldn't affect the results of `useQuery`. If it's already fetched, then it should maintain the same data without going stale / empty.

## **Actual behavior**

Saving a file when `data != undefined` results in either a) the query losing its data and refetching, or b) the query losing its data and not refetching.

## **Reproduction**

https://codesandbox.io/s/urql-fast-refresh-9te6gq?file=/src/index.js

Save the file here, and you'll see that the query goes away and refetches.

**Comment by JoviDeCroock** [comment]
Hmm, this could be me misunderstanding fast-refresh in React but I mirrored part of their spec for the fast-refresh in Preact and you rerun effects when a fast-refresh occurs which in our case will initiate a new fetch, I do wonder why the state is being reset. Setting state in render is allowed as long as you have a stable way of skipping it, when you setState in render the render will be dirtied and repeated.

The hooks get completely reset when hook-signatures differ which are made by the Babel plugin, will check later what is being reset here but if it's something to do with the effects/memo call being reset this would make sense as then the functional integrity of source would be different.

**Comment by nandorojo** [comment]
The effect re-running would make more sense. Do you think there is a way to fix it?

**Comment by JoviDeCroock** [comment]
![logs indicating that memo is getting recreated and thus the effect rerunning](https://user-images.githubusercontent.com/17125876/174678320-a346531b-d1c4-42f2-a7df-5182f5f58a94.png)

Yes it always seems to invalidate the initial `useMemo` resulting in a new request.

**Comment by nandorojo** [comment]
I’m using React 17 in my app. Your repo upgraded to 17.0.2 also breaks fast refresh for me.

https://codesandbox.io/s/urql-fast-refresh-forked-xc296u?file=/src/index.js

**Comment by nandorojo** [comment]
Ah I see, upgrading React DOM on sandbox fixes it. Hmm I wonder why my app isn’t working then.

**Comment by JoviDeCroock** [comment]
Maybe an unstable context value/... something in the outer closure acting up? 😅 tried a bunch of permutations but all looks good on the urql side
