### ISSUE TITLE
Svelte v2 queryStore not updating after mutation

### ISSUE THREAD

**Issue by freb** [FormidableLabs/urql#2513]
This issue was created from a discussion. Given @JoviDeCroock 's comments there, it seemed like I should create an issue as there are clear bugs in the Svelte v2 implementation.

As the title says, updates to the cache performed through a mutation are not causing the queryStore to update. Here is a reproduction of the issue:

https://stackblitz.com/edit/vitejs-vite-2ssvxj?file=src/routes/index.svelte

See my latest comments here about the current status of things:

https://github.com/FormidableLabs/urql/discussions/2503#discussioncomment-2988351

**Comment by JoviDeCroock** [comment]
Should be fixed in #2514

**Comment by mpiorowski** [comment]
@JoviDeCroock Everythings works perfectlly, thank You :)

**Comment by JoviDeCroock** [comment]
Thank you for the confirmation @mpiorowski, will work on getting the docs out asap as well. Feel free to hit us up if you run into anything else

**Comment by freb** [comment]
> @JoviDeCroock Everything works perfectly, thank You :)

Same here!
