### ISSUE TITLE
@urql/core is being bundled twice when using @urql/exchange-persisted-fetch

### ISSUE THREAD

**Issue by edygar** [FormidableLabs/urql#2518]
urql version & exchanges:
- `@urql/core` `^2.4.4`
- `@urql/exchange-persisted-fetch` `1.3.4`

**Steps to reproduce**

1. Installing both packages. 

**Expected behavior**

A new version for `@urql/exchange-persisted-fetch` that depended on `@urql/core@^2.4.4`.

**Actual behavior**

Installing both packages on their latest versions will cause a nesting of `@urql/core@2.3.6` under `@urql/exchange-persisted-fetch` leading to a bundle containing `@urql/core` twice with different versions.

**Comment by JoviDeCroock** [comment]
You can run `npx yarn-deduplicate` or `npm dedupe` to fix this issue
