### ISSUE TITLE
URQL not compatible with new SvelteKit `fetch` polyfill

### ISSUE THREAD

**Issue by Nickersoft** [FormidableLabs/urql#2533]
Hey folks, from my understanding, SvelteKit has recently adopted [`node-fetch` to use as a fetch polyfill](https://github.com/sveltejs/kit/pull/5292), and with it seems to be breaking SSR rendering attempts using SvelteKit with URQL. Attempting to use the `fetch` polyfill in the URQL from the server now results in:

`Error: [Network] Request with GET/HEAD method cannot have body.`

An example of an offending `load` function can be [found here](https://github.com/Nickersoft/urql-example/blob/169e31bf51f3b24a3e151bc6152e60d6706306d9/src/routes/index.svelte#L7-L42).

urql version & exchanges:

`@urql/core`: 2.5.0
`@urql/exchange-graphcache`: 4.4.3
`@urql/svelte`: 2.0.2

**Steps to reproduce**

I've [updated my `urql-example` repo](https://github.com/Nickersoft/urql-example/blob/master/src/routes/index.svelte) from the last time I posted here to highlight the issue. Just run `yarn dev` and the issue should happen on page load.

**Expected behavior**

The fetch call should function the same as it would in the browser. I'm not 100% this is _entirely_ a URQL repo, as I did some digging and saw some unexpected logic happening inside `node-fetch`, but seeing this is where I saw the issue first, I figured I'd rule it out with you guys before opening any other issues.

**Actual behavior**

Described above.

**Comment by JoviDeCroock** [comment]
I mean, this sounds like a Svelte issue we are explicitly using `POST` as long as you don't activate `useGETMethod` https://github.com/FormidableLabs/urql/blob/main/packages/core/src/internal/fetchOptions.ts#L88
