### ISSUE TITLE
"Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled" when building urql

### ISSUE THREAD

**Issue by Daniel15** [FormidableLabs/urql#254]
When I run `yarn build` on this repo, I get this error:
```
PS C:\src\urql> yarn build
yarn run v1.13.0
$ rimraf dist
$ run-p build:types build:bundle
$ tsc -d --emitDeclarationOnly --outDir dist/types
$ microbundle --format es,cjs --no-compress
(babel plugin) SyntaxError: C:\src\urql\src\client.ts: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (29:8):

  27 | 
  28 | /** Options for configuring the URQL [client]{@link Client}. */
> 29 | export interface ClientOptions {
     |        ^
  30 |   /** Target endpoint URL such as `https://my-target:8080/graphql`. */
  31 |   url: string;
  32 |   /** Any additional options to pass to fetch. */

Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.

at undefined:29:7
SyntaxError: C:\src\urql\src\client.ts: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (29:8):

  27 | 
  28 | /** Options for configuring the URQL [client]{@link Client}. */
> 29 | export interface ClientOptions {
     |        ^
  30 |   /** Target endpoint URL such as `https://my-target:8080/graphql`. */
  31 |   url: string;
  32 |   /** Any additional options to pass to fetch. */

Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.
    at Object.raise (C:\src\urql\node_modules\@babel\parser\lib\index.js:3831:17)
    at Object.expectPlugin (C:\src\urql\node_modules\@babel\parser\lib\index.js:5148:18)
    at Object.maybeParseExportDefaultSpecifier (C:\src\urql\node_modules\@babel\parser\lib\index.js:8315:12)
    at Object.parseExport (C:\src\urql\node_modules\@babel\parser\lib\index.js:8267:29)
    at Object.parseStatementContent (C:\src\urql\node_modules\@babel\parser\lib\index.js:7344:27)
    at Object.parseStatement (C:\src\urql\node_modules\@babel\parser\lib\index.js:7248:17)
    at Object.parseBlockOrModuleBlockBody (C:\src\urql\node_modules\@babel\parser\lib\index.js:7812:25)
    at Object.parseBlockBody (C:\src\urql\node_modules\@babel\parser\lib\index.js:7799:10)
    at Object.parseTopLevel (C:\src\urql\node_modules\@babel\parser\lib\index.js:7181:10)
    at Object.parse (C:\src\urql\node_modules\@babel\parser\lib\index.js:8660:17)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:bundle" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Seems similar to https://github.com/babel/babel/issues/9528, however I can't figure out how to work around the issue.

Windows 10, build 1809
Node 11.10.0

**Comment by Daniel15** [comment]
Just tried building on Linux (Ubuntu 18.04) via Windows Subsystem for Linux, using a different Node.js version (v8.10.0, the version that's bundled with Ubuntu 18.04) and got the same error, so I don't think it's Windows-specific.

```
$ microbundle --format es,cjs --no-compress
(node:511) Warning: N-API is an experimental feature and could change at any time.
(babel plugin) SyntaxError: /mnt/c/Users/danlo/Dropbox (Personal)/src/urql/src/client.ts: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (29:8):

  27 | 
  28 | /** Options for configuring the URQL [client]{@link Client}. */
> 29 | export interface ClientOptions {
     |        ^
  30 |   /** Target endpoint URL such as `https://my-target:8080/graphql`. */
  31 |   url: string;
  32 |   /** Any additional options to pass to fetch. */
```

**Comment by kitten** [comment]
Hm that's odd, since this isn't happening on any of our test environments or other things. Can you give us some more output? Maybe there's something going wrong with your yarn run where the lockfile isn't being respected?

Maybe give this branch a try; just bumped a couple of dependencies, although that's probably not related https://github.com/FormidableLabs/urql/pull/255

**Comment by Daniel15** [comment]
Okay so I tested a bit more - For some reason this is working fine on my desktop PC, but failing on my work laptop. Both are Windows 10. I'll figure it out properly at some point, but for now I'll just use my desktop PC for building urql. As an side, these weird environmental issues are one of the main reasons I don't work on much JS stuff any more 😛 (totally not your fault, it's just a common issue with the ecosystem in general)

**Comment by kitten** [comment]
@Daniel15 totally; when I've used WSL and Windows for a while the amount of issues I got with tooling skyrocketed.

**Comment by Daniel15** [comment]
Seems like it's microbundle being weird, as I hit a similar issue when using microbundle on a very simple file. Reported it at https://github.com/developit/microbundle/issues/409

**Comment by Daniel15** [comment]
Worked it out... How bizarre. Microbundle fails to parse the TypeScript if the directory name contains parenthesis (wut... how does that even happen?). I had the code in Dropbox to share it between multiple PCs. On my personal desktop PC, it was at `C:\Users\Daniel\Dropbox\src\urql`, whereas on my work PC it was at `C:\Users\danlo\Dropbox (Personal)\src\urql`, as my work PC has my business Dropbox account on it too. The `(Personal)` in the directory name was breaking it.
