### ISSUE TITLE
RFC: Add render optimization by tracking values

### ISSUE THREAD

**Issue by nandorojo** [FormidableLabs/urql#2542]
## Summary

I'd like to add simple render optimizations to URQL. Currently, `useQuery` re-renders whenever `fetching`, `stale`, `data`, `error` change.

However, if a component isn't using `fetching` or `stale`, it would ideally not re-render if these are the only values changing. `swr` and `react-query` implement this render optimization, resulting in much less rendering.

Here is a relevant [conversation from Twitter](https://twitter.com/TkDodo/status/1524248682434117632?s=20&t=OegPJG1YnFEZfWO2uUCiLA).

## Proposed Solution

This hook should only re-render when `data` changes:

```ts
const [{ data }] = useQuery()
```

This hook should only re-render when `data` or `stale` change.

```ts
const [query] = useQuery()

if (query.stale) {}

return query.data
```

## Potential Implementation

Add getters to the response of `useQuery` to track which state variables to update. This code is very off-hand to get the idea across, but shouldn't be taken as a true implementation. I haven't built this strategy myself, but I've benefited from it in other libraries.

Here's some pseudocode to illustrate the idea, based on what [SWR does](https://github.com/vercel/swr/blob/main/core/use-swr.ts#L615-L629). I can look more closely into the code for an actual implementation.

```ts
const tracked = useRef({}).current

const shouldUpdate = (prevSnapshot, currentSnapshot) => {
  let update = false
  for (const key in tracked) {
    if (!isEqual(prev[key], current[key])) {
      update = true
    }
  }

  return update
}

const setState = (nextSnapshot) => {
  if (shouldUpdate(snapshot, nextSnapshot)) {
    // I'm not sure how urql implements this exactly
  }
}

return {
  get fetching() {
    tracked.fetching = true

    return snapshot.fetching
  }
  // ...the same for other fields
}
```

In addition to getters, I believe other implementations like valtio achieve this with a `Proxy`. I can't say much about that though, since I don't have experience using proxies.

## Requirements

- Add an option for users to hooks to only re-render when tracked values change. 
  - This is the default behavior for both SWR and React Query. React Query lets you customize it with `notifyOnPropsChange`

Other references: https://github.com/pacocoursey/idyl

**Comment by JoviDeCroock** [comment]
To add on top of this, this could lead to lost updates. Let's look at a scenario:

```
const Component = () => {
  const [result] = useQuery()
  
  if (result.fetching) return <p>loading</p>
  if (result.stale) // do something
  
  return data
}
```

So assume that we check for `fetching` get to see if we have to update that and similarly we check `stale` when it needs updating, now on the first render we never got to asking for `stale` meaning that in some scenario's where a different component resolving data that leads to partial data in this one means we lose an update to stale that we don't want to lose.

There's a lot of edge-cases in here, I don't take the disposal of the switching of a single boolean attribute is worth this hassle.

**Comment by nandorojo** [comment]
All fair points.

Perhaps my perspective is unique, but I'm migrating from SWR to urql and our app is experiencing noticeably more renders when refetching happens across components.

> To also put this differently, do you really want every hook for React out there to do this? Like, every single one? I don't really see to what end that'd help 😅

It's worth mentioning that many of the popular data fetching and state management libraries in the ecosystem have in fact done this. At the end of the day, I just want the easiest way to make the app feel fast. I know that React 18 complicates this approach since everything should be a pure result of props and state.

I've noticed some screens getting choked up when `useUserQuery()` becomes `stale` and it re-renders in every component, since this hook is used everywhere. 

Since I'm coming from SWR, I didn't have to memoize much for network requests, because they 1) deep compare all results from the network and only re-render if they change, and 2) only re-render tracked variables. So adding memoization everywhere it's needed is a challenge for an app with hundreds of screens.

If I were starting a new app, this RFC might be less needed since I could just memoize. But I wanted to see if I could preserve the behavior I've gotten used to from SWR.

> To add on top of this, this could lead to lost updates. Let's look at a scenario:

Hm good point...I'm not sure if there is any way around this 🧐
