### ISSUE TITLE
in 3.0 'createClient' no longer supports relative path URLs (i.e. '/graphql')

### ISSUE THREAD

**Issue by onionhammer** [FormidableLabs/urql#2625]
### Describe the bug

When initializing createClient, if you pass in a relative path, i.e. "/graphql" without the fully qualified name, fetchOptions.ts constructing a new URL() without a `base` argument (https://developer.mozilla.org/en-US/docs/Web/API/URL/URL)

This appears to be an undocumented breaking change, not sure the best way to address it except to just add document.origin.

Passing 'document.location.origin' in the URL constructor's `base` argument would add back support for the previous behavior, where if you specify an ABSOLUTE url it would use that, but if you pass a relative url it would use the base;

i.e.

```ts
const url = new URL(operation.context.url, document.location.origin);
const search = url.searchParams;
```
  

### Reproduction

use '/graphql' as url for createClient

### Urql version

urql v3.0.1

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/FormidableLabs/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/FormidableLabs/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by kitten** [comment]
We indeed forgot to update the documentation, however, it only actually throws when the passed in `url` parameter is used when `preferGetMethod` (or a similar non-body mechanism) is active. We'd always prefer to construct a full URL beforehand (hence the name `url` rather), and hence have assumed that this is a safe change to make.

In some cases, where `preferGetMethod` is enabled, this may now indeed fail.
Since we support SSR (where a full URL is needed anyway), we can't assume `document.location.origin` exists and would like to not fallback to a less strict search parameter concatenation for GET methods when it comes to URLs.

This is also a case where JS engines fail with a very transparent error, "Invalid URL.", which is completely accurate, since a path is strictly speaking not a full URL, but can be resolved to one.

**Comment by shtse8** [comment]
> We indeed forgot to update the documentation, however, it only actually throws when the passed in `url` parameter is used when `preferGetMethod` (or a similar non-body mechanism) is active. We'd always prefer to construct a full URL beforehand (hence the name `url` rather), and hence have assumed that this is a safe change to make.
> 
> In some cases, where `preferGetMethod` is enabled, this may now indeed fail. Since we support SSR (where a full URL is needed anyway), we can't assume `document.location.origin` exists and would like to not fallback to a less strict search parameter concatenation for GET methods when it comes to URLs.
> 
> This is also a case where JS engines fail with a very transparent error, "Invalid URL.", which is completely accurate, since a path is strictly speaking not a full URL, but can be resolved to one.

I don't agree. for example, in nuxt3, plugins are setup in two file `urql.client.ts` and `urql.server.ts`. for each side, we have set up different strategies to resolve the query.

`urql.server.ts`
```ts
install(nuxtApp.vueApp, {
      url: '/api/graphql',
      exchanges: [
        // debugExchange,
        errorExchange({
          onError(e) {
            console.error(e)
          },
        }),
        dedupExchange,
        cacheExchange({
          schema: introspectionQuery,
        }),
        ssr, // Add `ssr` in front of the `fetchExchange`
        executeExchange({
          schema,
          context: () => {
            if (!nuxtApp.ssrContext?.req || !nuxtApp.ssrContext?.res)
              throw new Error('Missing srrContext')
            return context(createEvent(nuxtApp.ssrContext.req, nuxtApp.ssrContext.res))
          },
        }),
      ],
    })
```
`urql.client.ts`
```ts
install(nuxtApp.vueApp, {
      url: '/api/graphql',
      exchanges: [
        // debugExchange,
        errorExchange({
          onError(e) {
            console.error(e)
          },
        }),
        dedupExchange,
        cacheExchange({
          schema: JSON.parse(nuxtApp.payload.data?.__URQL_QUERY__),
        }),
        ssrExchange({
          isClient: true,
          initialState: JSON.parse(nuxtApp.payload.data?.__URQL_DATA__),
        }),
        fetchExchange,
      ],
    })
```

So, we can use `executeExchange` in SSR while use `fetchExchange` in client side. It works perfectly. as you can see, the url in `urql.server.ts` is useless as it is resolving using `executeExchange`. Please don't assume it always using the same code in both SSR and client sides.

Also, relative path is extremely important as we need to serve different domain or origin with the same app. For example, `domain.com` for internation and `domain.cn` for China. So using absolute path is impossible as we don't know where the request comes from or needs tones of work to resolve the origin before creating the client.

**Comment by JoviDeCroock** [comment]
@shtse8 correct me if I'm wrong here but if you are _only_ using the URL on the client side can't you just satisfy that requirement by doing `url: document.location.origin + '/api/graphql'` and an absolute URL only matters when you are using `GET` for your operations so existing searchParams can be maintained.

**Comment by shtse8** [comment]
> @shtse8 correct me if I'm wrong here but if you are _only_ using the URL on the client side can't you just satisfy that requirement by doing `url: document.location.origin + '/api/graphql'` and an absolute URL only matters when you are using `GET` for your operations so existing searchParams can be maintained. The above means that your SSR code does _not_ need to change and that your client can just use the existing window code to get the stuff you need for an absolute URL.

Yes. You are completely right.

**Comment by JoviDeCroock** [comment]
Closed by https://github.com/FormidableLabs/urql/pull/2626
