### ISSUE TITLE
Tree shaking of default exchanges?

### ISSUE THREAD

**Issue by Daniel15** [FormidableLabs/urql#263]
The [1.0 announcement](https://www.formidable.com/blog/2019/urql-2019/) says:

>  Exchanges are also fully tree-shakeable, so any built-in exchanges you don't use don't end up bloating your client bundle!

However to me it seems like this isn't true for the default exchanges, as the reference to `defaultExchanges` always exists at compile-time:
https://github.com/FormidableLabs/urql/blob/d87c4f02363592b91f59cf5ee84f2d0332cb0125/src/client.ts#L68

It's a very minor thing, but if I were to replace `cacheExchange` with my own custom caching mechanism (for example), the default one would still be bundled even though I'm not actually using it.

**Comment by kitten** [comment]
Yes, that's definitely true; _Most_ exchanges are tree-shakeable, but not all of them due to our defaults 😅 Currently due to their small size we don't really see this as a major problem, but if you have a suggestion on how to improve this, we'd be happy to change this!

**Comment by kitten** [comment]
So I think we can tackle this by making `exchanges` a required field, which would then be used like so:

```js
import { createClient, defaultExchanges } from 'urql';

const client = createClient({
  url: '...',
  exchanges: defaultExchanges
});
```

The migration path can probably be made easier by throwing a warning when this is missing, for users who're not using types etc:

```js
if (process.env.NODE_ENV !== 'production' && (!exchanges || !exchanges.length)) {
  throw new TypeError('Missing an exchanges array in the Client options!');
}
```

However, we can probably only ship this in a future major release, which would probably also include #227

**Comment by Daniel15** [comment]
Yeah that sounds reasonable to me.

**Comment by kitten** [comment]
Closing in favour of #253 for now
