### ISSUE TITLE
fetching is not set to true for subscriptions on variable change

### ISSUE THREAD

**Issue by elias-pap** [FormidableLabs/urql#2648]
### Describe the bug

I'm using a subscription which looks like this:

```
const [result] = useExampleSubscription({
  variables: { variableA: valueA, variableB: valueB },
});
```
`useExampleSubscription` is a generated hook by graphql-code-generator, which calls `useSubscription` under the hood:
```
export function useExampleSubscription<TData = ExampleSubscription>(options: Omit<Urql.UseSubscriptionArgs<ExampleSubscriptionVariables>, 'query'> = {}, handler?: Urql.SubscriptionHandler<ExampleSubscription, TData>) {
  return Urql.useSubscription<ExampleSubscription, TData, ExampleSubscriptionVariables>({ query: ExampleDocument, ...options }, handler);
};
```
The graphql server that I'm using is Hasura.

Then I'm changing `valueB` to a new value, the old subscription closes (as expected), a new one opens and I would expect `result.fetching` to be temporarily `true` in the new subscription result until there is new data from the API.
But instead, `result.fetching` of the new subscription result is `false` the first time it is returned (together with the new data). Is this expected ? If yes, how can I know that a subscription is on fetching state after a variable change ?

In the docs it is mentioned: `Whenever the variables (or the query) option on the useQuery hook changes fetching will switch to true, and a new request will be sent to our API, unless a result has already been cached previously.`

I can verify that this works for `useQuery` (using the respective generated hook by graphql-code-generator), but it does not seem to work for `useSubscription`.

I hope I'm not missing something. Thank you.

P.S. Please let me know if I should submit a reproduction url, in case the above description is not sufficient.
P.S.2 This works correctly in case the subscription is first paused, and then resumed at the same time `valueB` is changed. It also works correctly on first render.

### Reproduction

""

### Urql version

urql: 3.0.1
graphql-codegen/typescript-urql: 3.6.4

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/FormidableLabs/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/FormidableLabs/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
We definitely set [fetching to true](https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/src/hooks/useSubscription.ts#L90) maybe when switching a subscription off and on it reuses the connection and hence seems instantaneous 😅

**Comment by elias-pap** [comment]
Thanks for the reply. Switching the subscription off and on using the `pause` argument does return `fetching: true` for ~1sec until the new data comes, as it is expected. But when `valueB` is updated without fiddling with pause, the first result comes after ~1sec with `fetching: false` and the new data. I would expect the first result to come immediately with `fetching: true` instead (maybe together with the old data that correspond to the previous set of variables). Using urql devtools I can see some events that seem expected (old subscription closes - teardown event, new subscription opens - execution event, new data arrives - update event). So after the execution event and before the update event I'd expect to get a result with `fetching: true`, which I don't.

**Comment by JoviDeCroock** [comment]
Just tested in a sandbox and `fetching` correctly flips to `true` for me https://codesandbox.io/s/competent-noether-qn84pb?file=/src/components/Messages.js

**Comment by elias-pap** [comment]
Here's a fork of the previous Sandbox: https://codesandbox.io/s/hidden-waterfall-3hzc1g?file=/src/components/Messages.js

Notice that when `id` is set to `2`, `fetching` is `false` (expected since the subscription is paused). When `id` is set to `3`, `fetching` sticks to `true` *until new data comes* (expected). In all other cases, e.g. when `id` is set to `1`, `4`, `5` etc., `fetching` is initially set to `true` *but then immediately flips back to `false`* before any new data comes. And this is the confusing (unexpected) part, also because the order of events displayed in urql devtools is the same no matter the id value. So I'd expect `fetching` flag behavior to be the same as well.

**Comment by JoviDeCroock** [comment]
I mean, a subscription is distinct from a query right, it should only be `fetching` while it establishes a connection to the server because a subscription is a server-side PUSH to your application. Not a client-side demand for data, i.e. we can reliably tell our application that we are not establishing a connection and are ready to receive messages from the server so we set fetching to false.

**Comment by elias-pap** [comment]
Thank you for the fast responses and tackling of this issue !
