### ISSUE TITLE
Typings are broken after recent changes

### ISSUE THREAD

**Issue by devunt** [FormidableLabs/urql#2662]
### Describe the bug

Some of urql typings are broken after #2607 was introduced.

To be precise, it is broken in next three files.

* https://github.com/FormidableLabs/urql/blob/main/packages/core/src/utils/operation.ts (see line 8 and 14)
* https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/src/components/Query.ts (see line 7 and 19 for mismatch)
* https://github.com/FormidableLabs/urql/blob/main/packages/react-urql/src/components/Mutation.ts (see line 13 and 29 for mismatch)

### Reproduction

It is a typing issue

### Urql version

@urql/core 3.0.2
urql 3.0.1

### Validations

- [x] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/FormidableLabs/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/FormidableLabs/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
Hey,

Mind pointing out what is wrong with it, TypeScript in Strict mode isn't having any issues 😅 we ask for a reproduction or at the very least the error the error in question.

You are pointing at three files and telling us it's a typing issue but I can't really go off that as it's succeeding for me.

**Comment by devunt** [comment]
@JoviDeCroock
Apologize for providing not enough information at the first place 😢 Glad you understood it though.

**Comment by JoviDeCroock** [comment]
No worries we got there 😅
