### ISSUE TITLE
The value of data is undefined on the first render when accessing the cache

### ISSUE THREAD

**Issue by larsbs** [FormidableLabs/urql#267]
When accessing the cache (not firing a `/graphql` request) on the first render, the data  value returned is `undefined`. That creates an annoying flickering effect if you have some kind of loading animation.

Sample code:
https://codesandbox.io/s/nifty-banzai-7q0bz\

You can see how switching between different components, sometimes creates a flash of the red loading background before displaying the data even tho the data is already on the cache.

**Comment by kitten** [comment]
I'll go ahead and close this as per the discussion over in #245 since this is now a duplicate :)
