### ISSUE TITLE
RFC: Configurable url-size limit

### ISSUE THREAD

**Issue by c-schwan** [FormidableLabs/urql#2680]
## Summary

https://github.com/FormidableLabs/urql/pull/2384#issue-1193259509

its a hardcoded limitation

In our case we don't need to limit the url size because its an internal graphql request. 
With the limitation its not possible to force GET requests.

## Proposed Solution

Please accept a new parameter (eg "urlSizeLimit")

**Comment by JoviDeCroock** [comment]
We can do this yeah, we have the hard-coded limitation in-place so people don't run into this issue head-first as browsers have their own limitations and servers do too 😅 

Example

```
Microsoft Internet Explorer: 2,083 characters
Microsoft Edge: 2,083 characters
Google Chrome: 32,779 characters
Mozilla Firefox: more than 64,000 characters
Apple Safari: more than 64,000 characters
Google Android: 8,192 characters
```
