### ISSUE TITLE
useQuery not returning stable references

### ISSUE THREAD

**Issue by sarink** [FormidableLabs/urql#2701]
### Describe the bug

I hope that I'm simply misunderstanding or have misconfigured something, but I can't seem to figure out why objects inside `useQuery().data.MyQuery.someList[index]` are changing references. This means they cannot be memoized, and the application rerenders unnecessarily

* On initial load, the TodosList and every Todo renders three times
* Upon creating or updating a todo, each individual Todo in the list rerenders

Thanks :)

For skimming (if you don't want to pull the repro repo):

![Screen Shot 2022-09-23 at 4 05 03 PM](https://user-images.githubusercontent.com/1881761/192056778-58a3a68a-8e48-4fa5-9b14-6ff924b895c0.png)

![urql-memo](https://user-images.githubusercontent.com/1881761/192056828-fd2592e8-ada1-4f27-b4ff-8f4d7a20ad55.gif)

### Reproduction

https://github.com/sarink/urql-perf/pull/2

### Urql version

^2.2.3

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/FormidableLabs/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/FormidableLabs/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
We have gone over this quite a few times in issues/discussions, we do our best to provide stable references but at the end of the day it isn't the most important thing. i.e. a re-render isn't the expensive thing, memoizing everything and doing deep equality might be a lot more expensive if we'd do that on every query.

The best bet for us is to ensure you have the most up-to-date data and you can optimize the re-render process yourself by means of `memo` and `useMemo`, also a re-render isn't expensive as long as you aren't doing the most expensive operation, which is touching the DOM. 

Other issues https://github.com/FormidableLabs/urql/issues/425#issuecomment-530706043

**Comment by sarink** [comment]
@JoviDeCroock the code _is_ fully memoized -- memoization works by equality comparison, so if the object references keep changing, memoizing has no effect. The above code has exactly the same number of rerenders with or without memoization.

**Comment by sarink** [comment]
I don't really accept that this impossible or that it's it is unimportant. I just rebuilt the same demo with apollo client, and it behaves exactly as you'd expect, the memoization works and rerenders are prevented:

![urql-apollo-memo](https://user-images.githubusercontent.com/1881761/193300889-b18d07bd-32c3-4469-9f94-e68b0b589016.gif)

Getting a bit frustrated here.

**Comment by kitten** [comment]
Just to send an update, this could be an issue with Graphcache losing the reference to the last result, but I haven't looked into this just yet

**Comment by sarink** [comment]
This is destroying our performance, and with memoizations having no effect, I don't think there's anything consumers can do about it? I'm surprised more people haven't noticed/this isn't of high importance

Is this something that could be fixed in v3? Or a regression that could be fixed by downgrading?

**Comment by JoviDeCroock** [comment]
Some initial observations from going through this

- we see three re-renders and the last adds `__typename` to the selection-set
- when we add `__typename` to the query we see two re-renders

so I guess we can boil this down to two distinct issues, one where we aren't removing `__typename` correctly and secondly one where we aren't marking the array as untouched and re-using it for a subsequent result.
