### ISSUE TITLE
RFC: Auth exchange reference implementations for real-world authentication services.

### ISSUE THREAD

**Issue by mrflip** [FormidableLabs/urql#2727]
## Summary

Provide or link to auth exchanges that target popular authentication schemes.

## Proposed Solution

I propose adding copy-pasteable canonical implementations of auth exchanges against certain backend schemes. We would contribute an implementation for targeting Cognito via the AWS Amplify package, as well as an apikey based one that uses a static token suitable for eg targeting Github. I'll post a separate discussion thread to harvest some others such as Auth0 that I'm sure are out there.

This does not have to be runnable importable code provided by the `@urql/exchange-auth` package; it could be a separate `exchange-auth-contrib` repo, blessed links to gists, or the like.

The benefits I see:

1. As it stands, Urql gives you 99% of a production-ready solution but leaves you to write this one essential piece. If you are developing against a service that already requires auth (github, AWS amplify, AWS Api Gateway + serverless, etc) then it is impossible to evaluate urql without this chore.
2. It's straightforward code, but the kind of code that is only straightforward once you've written it one or more times. And even still I somehow we managed to introduce a diabolical bug due to improperly merging the old and new contexts.
3. This is critical security code that deserves community review
4. Better standardization of the auth exchange implementations will lead to better bug reports, as it reduces unknown variables and makes reproducible examples more straightforward. As it stands, to send a repro-repo that includes an auth exchange I would ???. Providing a recommended setup that included e.g. a static-token auth exchange targeting the github api lowers the effort significantly.

Some drawbacks:

1. A single package that provided importable code targeting multiple backend services would have an untenably heavy package.json, most of which would be unused (since you would only want one)
2. Delivering a well-tested solution is not maintainable, even apart from the difficulty of mocking the backend services
3. You likely don't want to be on the hook for people seeking advice on setting up Amplify / Auth0 / etc.

So providing runnable importable code seems untenable

There's surely some middle ground, however, that lets you disclaim direct maintenance responsibility while still improving the safety and implementation burden of URQL.

## Requirements

* an interesting initial set of concrete implementations that you would feel comfortable attaching a "Looks reasonable enough but we don't actually use or maintain that" endorsement to.
* enough signifiers in the README that takes you off the hook for maintaining the code and directs people experiencing issues to the right venue
* standards for contributing new targets

**Comment by kitten** [comment]
We're not interested in maintaining this because this is not something we can sustain at our current breadth of features with few core maintainers.

To suggest an alternative, feel free to publish a package that provides Cognito Authentication via the auth exchange, by wrapping it, or a similar utility package.

Cheers 🙌
