### ISSUE TITLE
errorExchange does not fire when defaultExchanges is used

### ISSUE THREAD

**Issue by princefishthrower** [FormidableLabs/urql#2757]
### Describe the bug

As the title states, if I do something like:

```typescript
const client = createClient({
  url: "abc123obviouslyfakeurltotriggererror",
  requestPolicy: "network-only",
  fetchOptions: {},
  exchanges: [
    ...defaultExchanges,
    errorExchange({
      onError(error) {
        console.log("custom error example #2: hello world");
      }
    })
  ]
});
```

I notice that my `errorExchange` callback does not fire. However, when I explicitly define all exchanges, `errorExchange` works:

```typescript
const client = createClient({
  url: "abc123obviouslyfakeurltotriggererror",
  requestPolicy: "network-only",
  fetchOptions: {},
  exchanges: [
    dedupExchange,
    cacheExchange,
    errorExchange({
      onError(error) {
        console.log("custom error example #1: hello world");
      }
    }),
    fetchExchange
  ]
});
```

Is this a "feature", or a bug 😄 ? I would have expected that when defining `errorExchange` _after_ `defaultExchanges`, that my custom `errorExchange` would be used. Though my guess is with the internals, since it is an array, it is difficult (or maybe even impossible to detect multiple instances of `errorExchange`, and thus when using `defaultExchanges`, the first (i.e. default) `errorExchange` is taken instead of a custom defined one.

Fiddling around with the `urql` version in codesandbox, I can confirm this "bug" affects versions 2.2.2 and up (to the current, 3.0.3) 

### Reproduction

https://codesandbox.io/s/muddy-cloud-ny6oqr?file=/src/client.ts:583-879

### Urql version

2.2.2

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/FormidableLabs/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/FormidableLabs/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by JoviDeCroock** [comment]
This is intended, `fetchExchange` is an ending exchange which is part of the defaultExchange i.e. fetch never forwards to `errorExchange`, instead it returns the data back along the chain.

**Comment by kitten** [comment]
Hiya 👋

There's more in-depth information on exchanges on this docs page and why their order matters: https://formidable.com/open-source/urql/docs/advanced/authoring-exchanges/

In short, since this exchange deals with errors in results, you'll have to put it in front (i.e. before in the array) any exchange that delivers results, which most commonly is just the `fetchExchange`.

You can put it in front of all exchanges, but it's more advisable to replace the `defaultExchanges` list with a manual one and put it directly in front of the `fetchExchange`
