### ISSUE TITLE
[Vue] [Auth Exchange] - "willAuthError" doesn't get called inside App.vue

### ISSUE THREAD

**Issue by darthmeme** [FormidableLabs/urql#2759]
### Describe the bug

Whenever I call a query from `App.vue`, the `wilAuthError` function never gets called before said query gets sent out.

If I do the same query anywhere else, `willAuthError` and subsequent logic will be called correctly.

I've included a reproduction repo - once cloned & `node_modules` installed, steps to reproduce are:
1. Start the dev server (`npm run dev` or `yarn dev`) and open devtools
2. Go to `/about` page - you'll be able to see that `willAuthError called` is logged, and I've made it always 
return true to show that `Fetching new token` is also logged correctly. (urql config is located in `main.ts`)
3. Comment out the request from `AboutView.vue` and uncomment the request from `App.vue`.
4. The same query gets sent out, but nothing gets logged.

### Reproduction

https://github.com/darthmeme/urql-auth-exchange-issue

### Urql version

`@urql/exchange-auth`: `1.0.0`
`@urql/exchange-graphcache`: `5.0.2`
`@urql/vue`: `1.0.2`

### Validations

- [X] I can confirm that this is a bug report, and not a feature request, RFC, question, or discussion, for which [GitHub Discussions](https://github.com/FormidableLabs/urql/discussions) should be used
- [X] Read the [docs](https://formidable.com/open-source/urql/docs/).
- [X] Follow our [Code of Conduct](https://github.com/FormidableLabs/urql/blob/main/CODE_OF_CONDUCT.md)

**Comment by heygambo** [comment]
@darthmeme thanks for putting this together ☺️.
What's the chance this will be look at this week?

**Comment by JoviDeCroock** [comment]
This is most likely related to your `getAuth` being handled in a [microtick](https://github.com/darthmeme/urql-auth-exchange-issue/blob/main/src/main.ts#L22) and when Vue decides to start rendering. I see the following happening

- You construct app by calling `createApp` (queues rendering)
- You create and use the client kicks off `getAuth` and resolves in the following microtick
- Calls `useQuery` and bumps into an existing `authPromise` resulting in [a bail](https://github.com/FormidableLabs/urql/blob/main/exchanges/auth/src/authExchange.ts#L155)
- Microtick resolves and the authState is hydrated
- Request from step 3 is dispatched

`willAuthError` is a pre-flight check, the behavior here makes sense as there is no `authState` yet like for instance the user hasn't logged in/... it doesn't really make sense for us to then delay calls or re-invoke a `willError` it makes more sense for `didError` to handle this case.

**Comment by darthmeme** [comment]
@JoviDeCroock Interesting. I guess I could move the query to `onMounted` using a one-off query since `useQuery` will immediately send that request.

**Comment by JoviDeCroock** [comment]
I'll be closing this issue as even if `willAuthError` does not run it will still be caught by a `didAuthError` and is just your `getAuth` getting ready,

**Comment by darthmeme** [comment]
@JoviDeCroock  - do you mean that `didAuthError` is *already* suppose to catch the error or it will in a future release? Because currently it doesn't seem that it does.
