### ISSUE TITLE
Previously canceled queries are not refetched, but fetching is true

### ISSUE THREAD

**Issue by tappiz** [FormidableLabs/urql#280]
You can try it here https://codesandbox.io/s/tender-hodgkin-5xiqh by changing the input before the query finishes (for example 1 -> 2 -> 3 -> 2)

Version 1.1.0

**Comment by kitten** [comment]
Hiya :wave:

Thank you for the CodeSandbox! Made it really easy to pin down what was going on :heart: For future reference, you can add the `debugExchange` to get some idea of what operations are being sent and what results make it back.

I've got a fix open and it's pretty high priority so I'm hoping we can get it in soon!

**Comment by kitten** [comment]
We just published [v1.1.1](https://github.com/FormidableLabs/urql/releases/tag/v1.1.1) and I verified that the above fix in #281 indeed fixes this :rocket: https://codesandbox.io/s/interesting-wu-tpmjn
