### ISSUE TITLE
Example to use with Redux

### ISSUE THREAD

**Issue by williamtran29** [FormidableLabs/urql#285]
Does anyone have an example to use with Redux?

**Comment by kitten** [comment]
I think this is more of a usage question. It's kind of vague so I'm not sure what you're actually asking for, sorry 😅

**Comment by williamtran29** [comment]
@kitten I'm really confused with the remote data from urql, and need to update local ( local store from redux). Example, How to update the Redux store after urql GraphQL query returns?

**Comment by kitten** [comment]
So this would be a great question for something like Spectrum but ultimately we can't answer broad questions like how does urql work with X or Y. Sorry 😅
