### ISSUE TITLE
Component does not update if the query is "fast".

### ISSUE THREAD

**Issue by kptlronyttcna** [FormidableLabs/urql#287]
I'm trying graphql with a local server, so results come pretty fast. But apparently the component wont re-render when result of the query returns quickly.

```
const query = `
    query ASDF {
        tracks {
            name
        }
    }
`

export const UrqlUser: React.FC = () => {
    const [res] = useQuery({
        query: query,
    })
    if (res.fetching) return <div>Fetching ...</div>
    if (res.error) return <div>Error ...</div>
    return <div>{JSON.stringify(res.data)}</div>
}
```

I tried to render `UrqlUser` but it gets stuck on `Fetching...`, but if I use chrome network throttling, it works fine. I've tested several different throttling settings, any delay below 50ms is problematic. Sometimes it gets stuck on fetching and sometimes it doesn't, but the lower the delay the more it gets stuck.

**Comment by HusseinMorsy** [comment]
same problem

**Comment by JoviDeCroock** [comment]
I have tried reproducing this in the examples folder as well as in a test and can't seem to get this to work. Could you provide a repo/codesandbox where we can see the problem?

**Comment by kptlronyttcna** [comment]
[Here](https://codesandbox.io/s/nostalgic-sound-psbzf?fontsize=14)

You can configure the delay in `fetch.ts#98`.
