### ISSUE TITLE
Same-page links in docs are all broken

### ISSUE THREAD

**Issue by corysimmons** [FormidableLabs/urql#289]
1. https://formidable.com/open-source/urql/docs/basics/
2. Click "Basics" in sidebar
3. Click "fetchExchange" in sidebar

- Takes you to https://formidable.com/open-source/urql/#fetchexchange
- It should take you to https://formidable.com/open-source/urql/docs/basics/#code-classlanguage-textfetchexchangecode

---

Similarly, clicking any of the permalink icons in the docs will take you to the wrong place.

1. Click on "cacheExchange" permalink icon on the https://formidable.com/open-source/urql/docs/basics/ page

- Takes you to https://formidable.com/open-source/urql/#code-classlanguage-textcacheexchangecode
- Should take you to https://formidable.com/open-source/urql/docs/basics/#code-classlanguage-textcacheexchangecode

**Comment by corysimmons** [comment]
btw happy to fix all these and PR. Just wanted to make sure it wasn't some sort of small config thing on your end and you'd be open to a PR.

**Comment by parkerziegler** [comment]
@corysimmons thanks for the issue report! This was fixed a little bit back internally and should be working as expected now.

**Comment by corysimmons** [comment]
Awesome, thanks for the update.
