### ISSUE TITLE
problem running examples

### ISSUE THREAD

**Issue by akwmak** [FormidableLabs/urql#295]
I am having problem getting started with the example. Could you help?

> $ yarn start:client
> yarn run v1.16.0
> $ webpack-dev-server --hot --inline
> ℹ ｢atl｣: Using typescript@3.5.1 from typescript
> ℹ ｢atl｣: Using tsconfig.json from /media/g/fast_dev1/Tmp/urql/examples/1-getting-started/tsconfig.json
> ℹ ｢atl｣: Checking started in a separate process...
> ✖ ｢atl｣: Checking finished with 4 errors
> ✖ ｢wdm｣: 
> ERROR in ./examples/1-getting-started/src/app/index.tsx
> Module not found: Error: Can't resolve './home' in '/media/g/fast_dev1/Tmp/urql/examples/1-getting-started/src/app'
>  @ ./examples/1-getting-started/src/app/index.tsx 16:13-30
> 
> ERROR in ./examples/1-getting-started/src/app/index.tsx
> Module not found: Error: Can't resolve 'react' in '/media/g/fast_dev1/Tmp/urql/examples/1-getting-started/src/app'
>  @ ./examples/1-getting-started/src/app/index.tsx 13:30-46
> 
> ERROR in ./examples/1-getting-started/src/app/index.tsx
> Module not found: Error: Can't resolve 'react-dom' in '/media/g/fast_dev1/Tmp/urql/examples/1-getting-started/src/app'
>  @ ./examples/1-getting-started/src/app/index.tsx 14:28-48
> 
> ERROR in ./examples/1-getting-started/src/app/index.tsx
> Module not found: Error: Can't resolve 'urql' in '/media/g/fast_dev1/Tmp/urql/examples/1-getting-started/src/app'
>  @ ./examples/1-getting-started/src/app/index.tsx 15:13-28
> 
> ERROR in [at-loader] ./src/app/components/Todo.tsx:2:29 
>     TS2307: Cannot find module 'urql'.
> 
> ERROR in [at-loader] ./src/app/Home.tsx:3:26 
>     TS2307: Cannot find module 'urql'.
> 
> ERROR in [at-loader] ./src/app/index.tsx:3:40 
>     TS2307: Cannot find module 'urql'.
> 
> ERROR in [at-loader] ./src/app/index.tsx:4:22 
>     TS2307: Cannot find module './home'.

**Comment by parkerziegler** [comment]
👋 Hey @akwmak. It looks like your dependencies may not be properly installed. Make sure you take the following steps.

1. Clone the repository.
2. From the root directory run `yarn` from the command line to install dependencies for `urql`.
3. Navigate into the examples directory (`cd examples/1-getting-started`).
4. Run `yarn` in that directory to install the example's dependencies.
5. Run `yarn prestart` in that directory to build the `urql` source for the example.
6. Run `yarn start` to start the app.

Can you give those steps a shot and ping here if the issue persists? I just verified the above works with a fresh clone of `urql` on `master`.

**Comment by akwmak** [comment]
@parkerziegler I did it several times with several version of nodes (v8 and v10), same error.

When I tried using npm instead of yarn, I got

> $npm install
> npm ERR! code EUNSUPPORTEDPROTOCOL
> npm ERR! Unsupported URL Type "link:": link:../../

> $npm -v
> 6.9.0
> $ yarn -v
> 1.16.0

Not sure why?

**Comment by kitten** [comment]
Have you delete both node_modules folders before following the steps above by Parker? NPM will also not work with the repository as we're using Yarn.

**Comment by akwmak** [comment]
@kitten @parkerziegler 
Thanks for the help. I missed the step where I have to run `yarn` at the root of urql.

Also the Home.tsx should be renamed to home.tsx
or
In the index.tsx, 
`import { Home } from './home';`
`./home` should be `./Home`

**Comment by kitten** [comment]
We'll try to make this easier by setting up some CodeSandboxes 👍

**Comment by akwmak** [comment]
@kitten I think

Add "From the root directory run yarn from the command line to install dependencies for urql." to the readme.md of examples
OR
In the package.json, use the latest version of urql instead of relative path
`"urql": "link:../../"`

**Comment by sunpietro** [comment]
I'm trying to run the examples, but it looks like something is wrong: `Module not found: Can't resolve 'urql' in '/Users/<user-name>/Projects/urql/packages/next-urql/dist'`

1. I've run `yarn` in the root directory,
2. I've run `yarn` in the chosen example directory,
3. I'm getting this error while running `yarn start` after all.

**Comment by kitten** [comment]
@sunpietro I think some examples have Webpack aliases set up, which are pointing to the wrong folder; e.g. https://github.com/FormidableLabs/urql/blob/baa76ae785e99dd42765ef689353d00a9ee69c92/packages/react-urql/examples/3-ssr-with-nextjs/next.config.js#L10

**Comment by sunpietro** [comment]
@kitten can you tell me where it should be pointing to?

**Comment by kitten** [comment]
@sunpietro `packages/react-urql` for `urql`; I'm not 100% sure whether that'll be it but we'll have to take another look I suppose and update the examples

**Comment by sunpietro** [comment]
Probably, I'm making something wrong, but I cannot get it working :( Waiting for other suggestions or a fix :)
