### ISSUE TITLE
userQuery with pause=true still issues an initial request

### ISSUE THREAD

**Issue by Cooke** [FormidableLabs/urql#300]
I have a search query that I want to execute as soon as something has been entered into a input field so I use "useQuery" with pause: input != "". Though a query is still being issues on mount even though pause is true.

**Comment by kitten** [comment]
I tried this out and unfortunately can't reproduce it. I'll close this issue due to inactivity but if you have more details we can reopen it 🙌 

Maybe you had a timing issue in your code or sth that flips `pause` to `false` temporarily?

**Comment by narinluangrath** [comment]
Hey @kitten, I think the `pause` argument might be broken in the latest version. It works in `Urql 1.1.1` but breaks in the latest version. To repro checkout https://codesandbox.io/s/silent-pine-562mu and switch between `1.1.1` and `latest`. By the way this pause feature is awesome! Helps us avoid conditional rendering :)

**Comment by JoviDeCroock** [comment]
@narinluangrath thanks for the awesome reproduction, this lead to a quick find.

**Comment by kitten** [comment]
@JoviDeCroock @narinluangrath I'll release another patch in an hour or two 👍

**Comment by kitten** [comment]
@narinluangrath Sorry again about this! `1.1.3` has been published with the above fix in #315 and a test has been added to prevent this regression from reoccurring.

**Comment by ifokeev** [comment]
@kitten I'm confused why query is executing while it's paused. Is it the designed behaviour?

**Comment by narinluangrath** [comment]
@ifokeev Nope that is not the designated behavior. Could you reproduce the issue?
