### ISSUE TITLE
React Native error on graphql require

### ISSUE THREAD

**Issue by danielkov** [FormidableLabs/urql#303]
Currently `apollo-graphql` supports React Native. I enjoy using `urql` more and more and there should be no reason it doesn't support React Native. Right now if I were to try to use it I would get:
```
Uncaught ReferenceError: module is not defined
```
in the `graphql` dependency built into the module. This is because React Native doesn't support Node-style import/export syntax. I didn't spend much time trying to get it to work, so I don't know if there is a workaround available. If there is, I think it should be added to the documentation.

**Comment by kitten** [comment]
I'm not sure how your bundling is set up bit doesn't that sound more like an issue for graphql then? 😉

**Comment by danielkov** [comment]
> I'm not sure how your bundling is set up but doesn't that sound more like an issue for graphql then? 😉

I'm running the out-of-the-box `expo init` setup for React Native.

The way Apollo Client solves this is that they do not depend on the module `graphql` but instead they have a package called [`graphql-anywhere`](https://github.com/apollographql/apollo-client/tree/master/packages/graphql-anywhere) that is bundled correctly to allow ESM-style imports.

**Comment by kitten** [comment]
So React Native does support normal ESM modules and should resolve all packages with a `module` field in `package.json` correctly.

Apollo depends on `graphql` just as other GraphQL clients have to. I'm aware of `graphql-anywhere`, but it's an unrelated package to run a small GraphQL service/API-like resolver without the full package. The client however still depends on `graphql` for parsing/stringifying/transforming GraphQL queries.

I've just tried to create an Expo project, so a simple set of:

```sh
expo init
yarn add graphql urql
expo start
```

The code I've then added was:

```js
import React from 'react';
import { Provider, createClient } from 'urql';

const client = createClient({
  url: 'https://urql-testapi-todos.philpl.now.sh'
});

export default function App() {
  return (
    <Provider value={client}>
      {/* ... */}
    </Provider>
  );
}
```

Which worked and bundled fine, so I'm not sure what might be going on in your setup. Can you provide a reproduction? :+1:

**Comment by happyfloat** [comment]
@kitten I got the same error on a fresh RN setup and urql. The error is raised after trying to use `useQuery`. Add the provider only is fine.

**Comment by happyfloat** [comment]
@danielkov I think I found a solution: Adding `ignore: [/node_modules\/@urq/],` to the `babel.config` solves the issue...
