### ISSUE TITLE
Export `QueryProps`?

### ISSUE THREAD

**Issue by dotansimha** [FormidableLabs/urql#309]
Hi! 

A user opened an issue (https://github.com/dotansimha/graphql-code-generator/issues/1995) for our GraphQL Code Generator, regarding an error while using our plugin for `urql`.

I noticed that `QueryProps` is defined and exported from `Query.ts` (https://github.com/FormidableLabs/urql/blob/master/src/components/Query.ts#L5), but it's not exported from the `index.ts` (https://github.com/FormidableLabs/urql/blob/master/src/components/index.ts#L2).

Is there a reason not to export everything from `Query.ts` (and others?) ? 

Thanks

**Comment by JoviDeCroock** [comment]
Hey,

Thanks for the clear error report, I'll make work of this tonight.

**Comment by kitten** [comment]
Sorry about that! We're about to push a patch release, so I'll quickly add a fix for this on.

**Comment by dotansimha** [comment]
Perfect, thanks @kitten @JoviDeCroock . 
Any chance we can get a release?

**Comment by kitten** [comment]
@dotansimha v1.1.2 has just gone out with a bunch of fixes :+1:
