### ISSUE TITLE
Q: Is there any way to query via URLQL outside the React?

### ISSUE THREAD

**Issue by helloguille** [FormidableLabs/urql#311]
I could find a method I could call outside the React Components to make the query.

Currently I'm using plain node-fetch for querying data I need for the  HTML skeleton generation (this happens exclusively server-side in the express server). This involves having my own caching done hashing both query and variables. 

I think it would be much better if I could use the same library I use inside the React components!

**Comment by kitten** [comment]
There's a section in the docs on this: https://github.com/FormidableLabs/urql/blob/master/docs/extending-and-experimenting.md#writing-new-apis-for-the-client

Also some discussions that might make this easier:

- https://github.com/FormidableLabs/urql/issues/290
- https://github.com/FormidableLabs/urql/issues/216

And questions around non-React frameworks:

- https://github.com/FormidableLabs/urql/issues/253

Hope these are good sources, but in general we touched on this topic in some discussions, and you can use Wonka to directly hook into `urql`'s client. Let me know if you have any questions around that. More docs on that coming soon :+1:

**Comment by helloguille** [comment]
Thank you! After one year of looking for the right library, I found the one!
