### ISSUE TITLE
RFC: First-class Fragment API

### ISSUE THREAD

**Issue by jevakallio** [FormidableLabs/urql#317]
This RFC is a conversation-opener for a first-party support for Fragments in urql. This proposal is "20% complete", so feedback is appreciated at all levels.

## Motivation

Users can already use fragments with urql today, but there is no guidance on how this is best achieved, and urql is not able to get any benefit from the additional information provided by fragments. 

With a first-party API, we can

- guide developers towards good practices
- solve some ergonomics issues related to use of Fragments
- provide better data for e.g. smarter caching

### Fragment composition

The assumption is that we want to encourage developers to compose their queries by allowing child components to define their own data requirements as fragments, and passing those upwards to the query component.

### We can write an efficient fragment cache

Yup, that's a big assumption. Research needs to be done on this.

### Add `fragments` option to `useQuery`/`Query`

Example:

```js
// NOTE: fragment imported from component file
import ProductListItem, { productFragment } from './ProductListItem';

const query = gql`
  query Products {
    products {
      id
      name
      ...ListRowFragment #<-- fragment referenced here
    }
  }
`;

const ProductListing = () => {
  const [res] = useQuery({
    query,
    fragments: {
      ListRowFragment: productFragment
    }
  });

  if (loading || !data) { return null; }

  return (
    <div>
      {res.data.products.map(p => <ProductListItem data={p} />)}
    </div>
  );
};
```

In above example, we allow the user to define a query that references a named fragment ("ListRowFragment"), without defining that fragment. The fragment can then be passed to the `useQuery` hook by name.

`useQuery` will then append the passed fragment to the query, AND rename the fragment to whatever key was provided as a key to the `fragments` option map.

Benefits:
- Having a formal API for fragments will encourage their use
- We don't need to worry about fragment naming (e.g. child component does not need to know what name the query expects, or vice versa). This could solve same problem as [fraql](https://github.com/smooth-code/fraql), but with a significantly simpler implementation and API.

### Introduce a `useFragment(fragment, data)` hook

Example of a child component which defines a fragment:

```js
// just a regular module export
export const productFragment = gql`
  fragment _ on Product { # <- note that fragment name does not matter
    sku
    name
    price
  }
`;

const ProductListItem = ({ data }) => {
  const { name, sku, price } = useFragment(
    productFragment,
    data
  );

  return (
    <div>
      {name} ({sku}): ${price}
    </div>
  );
}

export default ProductListItem;
```

The first argument to `useFragment` is a reference to the fragment. The second argument is the data passed down from the parent component, and is expected to match the type of the entity defined by fragment.

This can be used to implement Relay-like [data masking](https://relay.dev/docs/en/thinking-in-relay#data-masking). Basically, `useFragment` can ensure that only the fields defined in the fragment are returned to the caller. Further, we can ensure this by making the passed prop to be an opaque container type that can only accessed by using the useFragment hook. Similarly, we could ensure the parent component can not access fields defined on the fragment unless it also defines them in the query or a fragment of its own.

Issues: 
- It's not clear whether implementing data masking is worth the hassle.
- If we don't implement data masking, or we make it opt-in, then there is no way to guarantee that developers will actually use the `useFragment` API (since it's not strictly necessary). This means that we won't get the additional metadata benefits discussed below.

## Why do this?

The goal of fragment support, other than making fragments ergonomic to use via fraql-like renaming, is to collect additional metadata for better caching purposes.

- By being aware of the fragments, we can register them instead of trying to parse them out of the queries, making it simpler to create a fragment-aware cache

- Because `useQuery` and `useFragment` hooks can be aware of the component lifecycle of their parent component, we can use this to make better decision about cache invalidation. For instance, we could implement a simple reference counting based garbage collector, where we can keep track of all used queries and fragments and whether the components that use them are mounted, and implement an eviction policy that prunes the cache from unused fragments and queries when the cache reaches a certain max size or generational age.

## Discussion

I feel like there's value to implementing something like this on `urql`, but I'm not sure I've hit on the best possible API yet. 

Suggestions and feedback welcome!

**Comment by maraisr** [comment]
Thank you so much for wanting this. My only two cents are:

If you look at your example, there is an implicit requirement to link the fragments from imports, in both the `Query`, and also in the `useQuery`. With Relay, I know we have the power that the compiler gives us, to link those for us. But wondering if this could be coupled with a babel-plugin perhaps? And enforce globally unique fragment names (much like Relay does).

**Comment by jasonlor** [comment]
Are there any existing examples describing how fragments are used in URQL today? I've searched through the issues and documentation and found no mention on best practices.

**Comment by fnky** [comment]
Agreed with @maraisr — I think it's really nice that you can just use fragments within your query, without having to specify the dependencies to the query. Would love this feature in urql.

**Comment by kitten** [comment]
Closing this for now, because we don't have a good idea of what this may look like. Happy to reopen if someone has a good idea on how this may work regardless of how caching is implemented, while actually adding value (just query stitching is a React proble, not a GraphQL problem imho)

**Comment by FrederickEngelhardt** [comment]
Yep pretty much what I'm doing is:

```
export const myFragment = `fragment MyFragment on Node {
  key1
  key2
}`

const nodeDataQuery = `
${myFragment}
query NodeData {
  ...MyFragment
}
`
```

To share fragments you just turn the Fragment into another exported variable and import it wherever.

Is this what others are doing?
