### ISSUE TITLE
Unable to get data from inside custom exchange

### ISSUE THREAD

**Issue by Chrischuck** [FormidableLabs/urql#318]
I am trying to do exactly what this [issue](https://github.com/FormidableLabs/urql/issues/225) describes but I'm running into the same problem where I cannot get the result from the exchange. 

The following code is what I have for my client.

```javascript
import {
  createClient,
  dedupExchange,
  cacheExchange,
  fetchExchange,
} from 'urql';
import {
  pipe,
  tap,
} from 'wonka';


const errorExchange = ({ forward }) => (ops$) => {
  console.log('exchange'); // this logs
  return pipe(
    forward(ops$),
    tap(result => {
      console.log('GOT HERE', result); // this does not
    }),
  );
};

const client = createClient({
  url: 'http://localhost:4000/graphql',
  fetchOptions: () => {

    if (token) {
      return {
        headers: {
          Authorization: `Bearer ${window.localStorage.getItem('token')}`,
        },
      };
    }
    return {};
  },
  exchanges: [
    dedupExchange,
    cacheExchange,
    errorExchange,
    fetchExchange,
  ],
});

export default client;
```
I am using the client inside of a redux saga (no provider) like so:

```javascript

  const gqlRequest = {
    query: FetchActionsQuery, // gql document parsed from graphql-tag
    variables: {
      first: 4
    },
  }

  const res = yield call(client.executeQuery, gqlRequest);
  console.log(res)
```

**Comment by Chrischuck** [comment]
When using the `executeQuery` api, I needed to subscribe to the stream.

```javascript
  const res = yield call(client.executeQuery, gqlRequest);

  subscribe((data) => {console.log(data)})(res)
```

this allowed me to get data. If someone on the team could better explain this behavior/why this works, that would be awesome!

**Comment by kitten** [comment]
@Chrischuck sorry for the late reply. I was under the impression that you were using this with the normal components / hooks which should work fine and hence could've helped to pin this down quicker. But I suppose we'll have to work on making reproductions easier :)

So regarding the second question. As the types and API docs are trying to convey, everything in urql happens via streams, specifically observables. We're currently working on docs for Wonka that we can link to to better explain this.

Essentially though it's very similar to RxJS, hence you have to subscribe to the stream for it to start it's query.

We also have an open issue where we're working and proposing alternative promise- based APIs. These APIs won't update you on new values but will be useful for quick and easy fire-and-forget queries
