### ISSUE TITLE
<Mutation> docs example fails typecheck

### ISSUE THREAD

**Issue by reverie** [FormidableLabs/urql#335]
Looking at https://formidable.com/open-source/urql/docs/getting-started/#writing-mutations, the provided example does not typecheck.

The `Mutation` element fails with error: "JSX element type 'ReactNode' is not a constructor function for JSX elements. Type 'undefined' is not assignable to type 'Element | null'.ts(2605)"

![Screen Shot 2019-07-08 at 1 51 29 PM](https://user-images.githubusercontent.com/73446/60831471-a9075e00-a187-11e9-81ab-f32de21b556f.png)
![Screen Shot 2019-07-08 at 1 51 38 PM](https://user-images.githubusercontent.com/73446/60831472-a99ff480-a187-11e9-8ca7-c022f59a71b5.png)

**Comment by parkerziegler** [comment]
Released in [v1.2.0](https://github.com/FormidableLabs/urql/releases).
