### ISSUE TITLE
Usage with NextJS' getInitialProps?

### ISSUE THREAD

**Issue by corysimmons** [FormidableLabs/urql#338]
I found https://github.com/FormidableLabs/urql/tree/8405ac2fdbae77b8f82ab3dcdb4fe556c9b68d94/examples/3-ssr-with-nextjs and have copied most of it, but it doesn't actually make use of `getInitialProps` anywhere so I can't find the method to use within `getInitialProps` to access the Urql client.

**Comment by JoviDeCroock** [comment]
To use this specific lifecycle we would need a promisified query, this is not yet merged into master so we can't use it yet.

**Comment by corysimmons** [comment]
Thanks for the info. Going to back to Apollo I guess.

**Comment by JoviDeCroock** [comment]
I think my explanation fails to touch the point correctly: https://formidable.com/open-source/urql/docs/basics/#server-side-rendering

Urql doesn't need this method, the Query can use react-ssr-prepass to fetch this data on the server.

**Comment by corysimmons** [comment]
Okay I'll investigate a little more.

At this point I'm not sure what GraphQL lib brings to the table other than caching? I'm always tempted to just use graphql-request and fetch whatever I need.

If I want it persisted, just plop it in localstorage or something... :\

**Comment by JoviDeCroock** [comment]
The library provides an abstraction, using this abstraction can move the hassle away from you having to rewrite code to incorporate certain changes in React (for example Suspense). Using the library is entirely up to you just gave you my point of view on using libs like urql and apollo.

In next.js I see: https://github.com/zeit/next.js/blob/canary/package.json#L95
