### ISSUE TITLE
cache-and-network seems to not fire the network

### ISSUE THREAD

**Issue by dusty** [FormidableLabs/urql#345]
I am brand new to urql and while testing it out in my app, it appears to me that cache-and-network is not working as I had expected.

I created a different issue than #299 as that issue was primarily concerned about the executeQuery part of useQuery. 

My expectations from reading the docs is that it would return what is in cache, then it would also fire a network request in the background, update the cache, and cause a re-render if the data has changed.

Let me know if those expectations are incorrect.

I created this codesandbox to demonstrate.  https://codesandbox.io/s/youthful-fast-7g373

I created two components that each utilize the same query and have the requestPolicy set to cache-and-network.  We are grabbing the first new story from hackernews using graphqlhub api. 

When I load a component for the first time, it shows me the network request.  However, when moving between the components, it is only pulling from cache and not firing the network request.

I added debugExchange after cacheExchange.  It only logs on the first network request, which I believe is demonstrating that the cacheExchange is not forwarding on.

Below is a video:

![Fgi0NS0wxe](https://user-images.githubusercontent.com/792/61467886-43f2fb80-a931-11e9-8b2b-030909985e06.gif)

**Comment by parkerziegler** [comment]
Thanks for the report @dusty. Agreed that I would expect `cache-and-network` to do what you expect – pull from the cache and then _always_ trigger a new network request. I believe this line in the `cache` exchange is the one we're looking to hit: https://github.com/FormidableLabs/urql/blob/d0bfd4928763029d155427554fe3022d0cee62e8/src/exchanges/cache.ts#L62.

Happy to look into this more and see what may be going awry. I'm also curious to investigate what using the same query for two components does for how we manage the cache.

One last thing – I popped open the CodeSandbox you provided (❤️thank you so much for that) and I ran into this error. Looks like the access on `data` may just be a bit off. I can work with this tho!

![image](https://user-images.githubusercontent.com/19421190/61475070-de0d7080-a93e-11e9-96ee-a5620fd27584.png)

**Comment by dusty** [comment]
Thanks for the response and the pointer to the location.  

I've got it running locally and with some old fashioned console.log debugging, I traced it through and it is passing those checks and calling ```reexecuteOperation```.  

It makes its way over to and calling ```this.dispatchOperation(operation)``` in client.ts.  I see that it has the context.requestPolicy set to 'network-only' at this point as well.  However, its still not initiating the network request.

I've never used typescript or wonka so its starting to get a little fuzzy for me at this point in the code.  But, here is my example that runs locally instead of on codesandbox if that is helpful.

https://github.com/dusty/urql/tree/master/examples/4-cache-and-network

**Comment by dusty** [comment]
![3uwsVpZtWs](https://user-images.githubusercontent.com/792/61483055-de166c00-a950-11e9-8541-780b327606fe.gif)

**Comment by parkerziegler** [comment]
@dusty I'm seeing the same behavior you are with our example app. It looks like `reexecuteOperation` in the `client` doesn't actually re-execute the Network request. I'll continue to explore, but I think this is definitely a 🐛. cc/ @kitten would you have any insight into why this may be happening? I'm curious if this operation isn't actually making it into our exchange pipeline 🤔
