### ISSUE TITLE
Add OperationContext to useQuery arguments

### ISSUE THREAD

**Issue by isker** [FormidableLabs/urql#346]
Hi!  I am trying to wrap `useQuery` in a custom hook so that I can provide new per-query functionality that interacts with a custom exchange I've written.  This is done by attaching per-query data in my hook via the `OperationContext`'s arbitrary-string properties.  But this data can only be provided by calling the `executeQuery` callback from `useQuery` ourselves; `useQuery` takes no `OperationContext` while `executeQuery` does:
https://github.com/FormidableLabs/urql/blob/fe99b20850ae18b9c9cb4b8d7aa0937e041a5ad1/src/hooks/useQuery.ts#L49-L50

It's not clear why this is the case.  To work around it in my hook, I have to pause the query on the call to `useQuery` then immediately invoke `executeQuery`, taking care not to create an infinite loop on render.  Are you open to adding this argument to `useQuery` directly?

**Comment by kitten** [comment]
That's true. I think we've removed the rest spread some time before we were done but it should definitely be readded so that this can be provided cleanly
