### ISSUE TITLE
Fetching data on the server, or SSR in other words

### ISSUE THREAD

**Issue by einarlove** [FormidableLabs/urql#36]
I get why SRR is low on the prioritization list seing you guys have other features to bake first, but I'm wondering where it is in your pipeline and what your initial thoughts are for implementing it. 

And how can we help?

**Comment by kenwheeler** [comment]
Its #1 on the todo https://github.com/FormidableLabs/urql#todo

Right now I'm trying to stabilize the API and shake out some introductory bugs. Past that, I would assume there will be a two pass render, where we walk the tree, identify queries, execute and cache them, and then serialize the cache. Then add a hydration helper on the client side. Does that sound about right?

**Comment by einarlove** [comment]
Sounds about right! Would be cool if we could also control how and which queries should be executed on the server vs client, and option to resolve the queries using your schema directly if the SSR is served from the same server has your GraphQL endpoint. Would be rad 🥇.

**Comment by chrischen** [comment]
Did this ever get implemented? I don't see any references to SSR anymore.

**Comment by kitten** [comment]
@chrischen Not yet unfortunately! We haven't found a way yet to traverse a React element tree and extract pending requests with hooks.

**Comment by chrischen** [comment]
Here's an implementation from graphql-react.

https://github.com/jaydenseric/graphql-react/blob/master/src/server/ssr.mjs <https://github.com/jaydenseric/graphql-react/blob/master/src/server/ssr.mjs>

**Comment by kitten** [comment]
@chrischen yea, I've dabbled with getDataFromTree implementations before, but I'm put off by the newer approaches of repeatedly rendering to static markup and waiting for a promises / operations array to come back empty
