### ISSUE TITLE
Export useImmediate{Effect,State}?

### ISSUE THREAD

**Issue by isker** [FormidableLabs/urql#381]
In writing custom hooks that wrap urql's (for example, following the recommendation of https://github.com/FormidableLabs/urql/issues/201#issuecomment-466693504) we've found some cases where useImmediateEffect/useImmediateState would be useful to have.  

For now we copy-pasted but it makes me wonder whether these can't just be exported by urql itself, for the benefit of anyone extending urql.

**Comment by parkerziegler** [comment]
@isker Interesting idea. My only hesitancy around exporting these as part of `urql` is that they're not really a part of `urql`'s core API – they're just implementation details we use to achieve specific functionality. I could see us doing this, but I'm also concerned that people will then see these hooks as "`urql`-specific". Moreover, I feel like the copy-paste method is sort of the recommended approach in the community for sharing hooks? cc/ @kitten @JoviDeCroock @andyrichardson thoughts?

**Comment by isker** [comment]
The main reason why copy-pasting has made me feel a bit uncomfortable is
that these hooks have seen updates with non-negligible frequency (some
addressing subtle bugs as far as I understand).

Tracking those changes manually is where my unease comes from 🙂.

That being said I understand if your point about these being implementation
details entirely.  But if you think your need for these hooks is unlikely
to go away...

**Comment by kitten** [comment]
I feel like we could easily consider splitting them into a new package? That would however make it more confusing to the urql codebase, since it'll be less discoverable when someone is reading through our hooks

**Comment by JoviDeCroock** [comment]
I'm a bit opposed to the idea of moving the `immediate` hooks to a separate package. One of the reasons being the discoverability and the fact that this is the only repository we're using them in. However if we could think of a valid use case for them and we know they'd be reusable I think it would be a good solution. However I can't really come up with a general use case.

**Comment by kitten** [comment]
They're not related to Wonka but the synchronous streaming operators do make this concept possible in the first place.

Mainly they're for the initial state and suspense. We want the initial state to immediately reflect what the cache has in terms of data, and we want a promise to be thrown on mount, outside of an effect, for suspense 

I'd actually be happy if anyone else chooses to extract these hooks and publishes a packages, but you're right, we don't have any other use cases for them right now for urql.

**Comment by kitten** [comment]
After thinking about this a little more and consulting about it internally we likely won't expose these hooks from urql or a separate package.

Things may change if someone is willing to create a package based on them, but currently we don't have any demand to reuse them.

Hope that makes sense! Closing for now
