### ISSUE TITLE
Export useDevtoolsContext?

### ISSUE THREAD

**Issue by NoahWilson4** [FormidableLabs/urql#382]
I'm writing a custom useMutation and would like to include the dev tools. Can you export useDevtoolsContext so that I can use it directly?

**Comment by Jay-A-McBee** [comment]
👋 hey everybody - seemed like low hanging fruit that would give me a chance to get my feet wet

**Comment by kitten** [comment]
Quick update on this regarding #388 and #387. We're looking to actually remove this hook and other metadata utilities and code from the codebase.

We can achieve the same functionality by baking it into the devtools and hence remove all metadata concerns from urql.

This ensures that our codebase remains manageable and keeps the devtools as the only owner of this kind of data. So we're looking to bake all metadata into the devtools exchange :)
