### ISSUE TITLE
Hash usage?

### ISSUE THREAD

**Issue by jmeas** [FormidableLabs/urql#39]
I am curious to learn more about the decision to use a hashing function [here](https://github.com/FormidableLabs/urql/blob/2b7f30155a5c0160c8313d75f07cb497a7c66965/src/modules/client.ts#L122). What value do you think it is adding?

Were it to be removed, these are the benefits that I would see:

1. urql's bundle size is smaller
2. urql is faster (though this would not impact users probably. Network requests aren't exactly sent off at 60fps or anything)

The key remains as unique as it needs to be either way, so the _function_ of they key is equal between the two options.

One possible reason I can think of for it is that maybe graphql queries could get very large, so hashing them to a fixed string could be valuable. Apollo [doesn't seem to worry about that](https://github.com/apollographql/apollo-link/blob/d5b0d4c491563ed36c50170e0b4c6c5f8c988d59/packages/apollo-link/src/linkUtils.ts#L121-L127), though, and it appears to be working fine for them (but maybe not?).

Anyway, I'm not necessarily recommending that you make this change. I'm just trying to learn more. Thanks for taking the time to read / respond!

**Comment by kenwheeler** [comment]
I just thought that using a serialized query for a string was silly. I didn't want to expose the query itself, with variables, to the different cache implementations as a readable key. I didn't think the perf/size was enough of a hit to matter.

**Comment by jmeas** [comment]
Cool, makes sense. Thanks for the response!
