### ISSUE TITLE
Terrible grammar

### ISSUE THREAD

**Issue by deadcoder0904** [FormidableLabs/urql#392]
I can't make any sense of this line at https://formidable.com/open-source/urql/docs/basics/

`When an operation is sent it is identifier via its key which is a hash of the query and variables. `

I know what it actually means but grammar is terrible 😂

**Comment by deadcoder0904** [comment]
Also, typo on the same page

`The can be used to ensure that data skips the cache, if it's clear to you that the result will need to be up-to-date.`

should be

`They can be used to ensure that data skips the cache, if it's clear to you that the result will need to be up-to-date.`

Only changed `The` to `They` :)

I have to say the documentation is pretty good except a few typos & grammar mistakes 👌

**Comment by deadcoder0904** [comment]
Also this one

```js
import { Client, defaultExchanges, subscriptionExchange } from "urql";

const client = new Client({
  url: "/graphql",
  exchanges: [
    ...defaultExchanges,
    subscriptionExchange({
      forwardSubscription
    })
  ]
});
```

where does the `forwardSubscription` comes from?

Sorry to put everything in one issue but makes it easier for me  🤷‍♂️🤣

**Comment by kitten** [comment]
These are both just minor things thst can be fixed by a PR 😅 So I won't keep this issue open. Sorry, but it's just as fast to send a PR for this and we can't keep issues open for one or two typos a time 😉
