### ISSUE TITLE
operationName is never set by fetchExchange

### ISSUE THREAD

**Issue by davidhouweling** [FormidableLabs/urql#400]
**Describe the bug**
When executing a query via urql, our graphql server (apollo) is not receiving an `operationName`. When using the apollo playground, even individual queries have an `operationName` computed.

I understand that `operationName` is only required for multiple operations in a query (as per https://graphql.org/learn/serving-over-http/#post-request) but from my experience, even multiple queries inside a transaction isn't setting it.

**Steps to reproduce**
1. Create an apollo graphql server
2. As part of it, create an extension (such as this one) and consume it in the `extensions` of apollo config
``` js
import { GraphQLExtension } from 'graphql-extensions';

export default class CustomExtension extends GraphQLExtension {
  requestDidStart({ operationName }) {
    console.log(`operation name is "${operationName}"`);
  }
}
```
3. fire a call to the apollo server and you observe the server console

**Expected behavior**
The `operationName` should be picked intelligently such as the name of the query being executed (as apollo client does)

**Actual behavior**
The `operationName` parameter is `undefined`

**Additional context**
n/a

**Comment by kitten** [comment]
Yes, early on in development we've removed this, because it's optional and not needed. Specifying multiple queries and passing them to `urql` is not going to yield any desirable result, so setting this wasn't ever really relevant 🤔 

Is there any use-case that we're missing here where this is absolutely needed, ignoring a case where a document contains multiple queries, which is by convention not expect in `urql` nor Apollo?

**Comment by davidhouweling** [comment]
So our use case is that we are doing transaction tracing to be able to timeline how long a call takes, and this is based on the `operationName`. With the value being `undefined` it means it's not very clear as to what the call was, so we have to drill in to see.

**Comment by Tuffail** [comment]
I have been doing some research on other clients (namely Apollo GraphQL, GraphQL playground, and GraphiQL) to see what behaviour they have around this. They all add the `operationName` to the request if available even if there is only a single named query. I have attached a screenshot of a GraphiQL IDE with only a single query and the network request to the server including the `operationName` in the request payload. ![image](https://user-images.githubusercontent.com/10976379/63431577-0cd3a680-c417-11e9-873a-f7be6881c75d.png)

**Comment by davidhouweling** [comment]
@kitten / @JoviDeCroock you guys are awesome, thanks for the speedy response!

**Comment by josteph** [comment]
@kitten / @JoviDeCroock I keep getting on:

```
operationName: "query"
```

which should be expected to have the query name for the value instead, as it's more useful when debugging.
