### ISSUE TITLE
JSON.stringify vs immutable data structure

### ISSUE THREAD

**Issue by Gregoirevda** [FormidableLabs/urql#41]
I see the library is using `JSON.stringify` which is probably a bit slow : https://github.com/FormidableLabs/urql/blob/3f859ed42d7a2ef2bff74c03e5245444425bd429/src/modules/client.ts#L116

Can't you do something like that:
```
const memoize = (fn) => {
 let prevArgs;
 let prevResult;
 return function(args) {
    if(args === prevArgs)
       return prevResult;
    prevArgs = arg;
    return prevResult = fn.call(this, arg);
 }
};
```

Instead of

```
const memoize = (fn) => {
 let cache = {};
 return function(args) {
 let hash = JSON.stringify(args); /* slow */
 if(hash in cache)
   return cache[hash];
 return cache[hash] = fn.call(this, arg);
 };
};
```

**Comment by kenwheeler** [comment]
So you mean memoize the stringification?

**Comment by Gregoirevda** [comment]
I mean replacing the JSON.stringify and hash is in cache by a reference comparison using immutable data structures. https://youtu.be/rtcn9I9sB5M

**Comment by kenwheeler** [comment]
What does this mean for external cache storage?

**Comment by kitten** [comment]
So the previous points remain unaddressed, the most important one being: the query is a string and variables are rarely huge, so the result is that the number of fields and paths are low. `JSON.stringify` is also by no means slow but an efficient `O(n)` which is even preferred in this case.

This can potentially be enhanced by caching a hash for the query and only doing `JSON.stringify` on the variables or doing a custom recursive & partial combined murmurhash.

Either way, I'll tag this to be addressed in the future

**Comment by sbrichardson** [comment]
I'm a fan of stringify(), just .02. I find it helps keep functions and undefined properties out, and has the replacer function that comes in handy sometimes. I had to use it recently to clean some __typename stuff out of a mutation when using apollo client. I've been working with cache/localStorage also as mentioned above, so I've been using JSON more.

**Comment by kitten** [comment]
We likely won't use `stringify` in the future, but we've now released v1 with the same caching strategy, which is just the default one. The keys are also still the same.

That being said, there won't be a data structure to preserve queries, but I'm thinking more of hashing queries directly, still stringifying variables, and just setting IDs on queries when they're parsed `DocumentNode`s.

But for now, I'll close this since it's not quite up-to-date with v1.
