### ISSUE TITLE
💬  Making it work better for ⚛  Electron apps

### ISSUE THREAD

**Issue by morajabi** [FormidableLabs/urql#42]
Hey! I'm gonna do this myself today and I'll dig the source code too, but in the meantime, I'd like to know what do you think is the best way to do this. 

## What's the problem?
In Electron, each window is on its own separate BrowserWindow (exactly like a browser tab). This makes using Apollo or Redux across windows impossible, at least without implementing a utility on top.

## KK, What's the question?
I thought maybe implementing a custom cache, and storing/retrieving it on `electron-store` (which is a universal store across the app) would allow me to have multiple instances of `urql` in multiple windows, all sharing a single source of truth.

Would that be OK from the `urql` side? What are the problems might occur with `urql`? Any thoughts welcome! 

ty,
/cc @kenwheeler

**Comment by kenwheeler** [comment]
Should work. Give it a shot. If it doesn't work, let me know and I'd be happy to add whatever it takes to make it work.

**Comment by morajabi** [comment]
@kenwheeler Ah, super cool! I'll get on this today, I'll let you know. 

>I'd be happy to add whatever it takes to make it work.
That's very nice of you Ken!

**Comment by morajabi** [comment]
It seems it works! Woot!
I'll publish it as a package later.
