### ISSUE TITLE
RFC: Client specific packaging

### ISSUE THREAD

**Issue by JoviDeCroock** [FormidableLabs/urql#423]
In light of https://github.com/FormidableLabs/urql/issues/253 I would actually opt to take a similar approach as we’ve taken in [Preact](https://runpkg.com/?preact@10.0.0-rc.1/dist/preact.js) and that is to publish one urql package, but we just make a separate entry-point with non-react-specifics. In our case this would be the client and exchanges. In the normal urql package we can just use relative imports to the src of urql/client. This would imply no breaking changes at all

for example `import  Client from 'urql/client'`. This effectively solves our issues with non-React consumers needing a dependency on React or the package crashes, I don’t think a lot of vue users would like to add react to their dependencies just to make the client import work. This breaks because the entry-point imports the hooks and those require React. This will be tree-shaken out in the production build but yes...

The only concern I'm having is where to put the /utils, obviously `toSuspenseSource` is part of React but it's used in `client`. `createRequest` is a neutral one but used in `useRequest` and `useMutation` as well as in the `client` package. `withPromise` is only used in the `client` so that can easily be moved. The utils used in exchanges seem to be limited to only there.

Specific steps to produce this would be:

- make a sub-folder /client/src and move our client and exchanges there.
- update imports in /src to /client/src ones
- introduce build for /client

This encourages others to make thirth party packages like `urql-vue`. I think this is the best effort to having a non-react entry point while not resorting to a monorepo.

- #311
- #263

**Comment by kitten** [comment]
I think this is definitely what we should do :+1: I think we don't have to actually change a lot if we leverage rollup's code-splitting i.e. separate aliased entrypoints :+1:
