### ISSUE TITLE
What if a mutation affects more than one object?

### ISSUE THREAD

**Issue by sompylasar** [FormidableLabs/urql#43]
It's mentioned in the README that "If you change a todo, return it. If you delete a todo, return it. If you add a todo, return it."
<img width="913" alt="screen shot 2018-02-13 at 2 41 22 pm" src="https://user-images.githubusercontent.com/498274/36177900-06fa234c-10cc-11e8-82aa-e9663ad6ade5.png">

I'm not a GraphQL guy, so correct me if what follows is discouraged in GraphQL universe, but I'm a CQRS guy, so when designing APIs, I make mutations (commands) that reflect the logic of the app, not align them 1-to-1 with the data entities.

The "add todo" (or "add anything else") is a simple mutation that by coincidence aligns 1-to-1 with the data entity it mutates.

In the real world, there may be more interesting mutations, for example, "signup" may want to create a new user profile record, a picture record, a greeting notification record, etc.

Thanks.

**Comment by kenwheeler** [comment]
In that event, I'd return the entire record. The user with the linked picture type and greeting.

**Comment by sompylasar** [comment]
> In that event, I'd return the entire record. The user with the linked picture type and greeting.

But this won't technically be one record, it'll be three, or I'm missing something GraphQL-ish?

Do you call any composed object a record, or just the underlying data entities?

**Comment by cjhowe7** [comment]
GraphQL can return multiple records that are linked. They would be separate records in the database sense, but in GraphQL they are explicitly linked by child fields. For example, the `User` type can contain a record of the `Avatar` type through a `User` field called `avatar`. Perhaps your mutation would still have to only affect records that are linked to the thing you return from that mutation - if that's not the case, I think that you should try manually invalidating the cache.

**Comment by sompylasar** [comment]
One more example of a mutation of unrelated objects is bulk update.

Returning the whole array of things that were actually mutated may be 1) unknown because of internal implementation e.g. `UPDATE WHERE some condition`; 2) too large set to respond with.

**Comment by cjhowe7** [comment]
All that matters is the type since urql invalidates caches aggressively based on the returned types of the mutation. If you're bulk updating things of the same type, then it should pull all the queries that use that type. I think you could even just return one item of the given type and it'd still work. Not too sure this is a good idea though, but I believe it would work.
