### ISSUE TITLE
urlq hooks return momentarily stale results

### ISSUE THREAD

**Issue by rafeca** [FormidableLabs/urql#432]
**Describe the bug**

When rendering a React component that call a `urql` hook with different variables/query between renders, the return value of the hook returns stale results (without the `fetching=true` flag) momentarily.

E.g with the following component:

```js
const MyComponent = (props) => {
  const [{ fetching, data }] = useQuery({
    query: `{ todos { id } }`,
    variables: props.id
  });

  console.log(fetching, data);

  return fetching ? <Loading /> : <List data={data.todos} />;
};
```

rendering `<MyComponent id={1} />`, waiting for the results and then rendering `<MyComponent id={2} />` results in the following lines printed on the console:

```
// first render with id=1
true undefined
// we get response from backend
false { todos: <todosForId=1> }
// second render with id=2 (WRONG)
false { todos: <todosForId=1> }
// on next tick, we get the fetching=true
true undefined
// we get response from backend
false { todos: <todosForId=2> }
```

**Steps to reproduce**

I've created the following test for `src/hooks/useQuery.test.tsx` that currently fails :

```js
it('sets fetching to true after changing query', () => {
  // Only mock the response once.
  client.executeQuery.mockReturnValueOnce(empty);
  const wrapper = renderer.create(<QueryUser {...props} />);
  expect(state).toMatchObject({ fetching: false });

  wrapper.update(<QueryUser {...props} variables={{ myVar: 4321 }} />);

  // This fails!
  expect(state).toMatchObject({ fetching: true });

  // Once `setImmediateState()` gets executed, `fetching` is true.
  setTimeout(() => {
    expect(state).toMatchObject({ fetching: true });
  }, 400);
});
```

**Expected behavior**

I expect that when passing a different query or variables, the return value immediately get invalidated by having `fetching: true`, to avoid showing stale results on the UI.

**Actual behavior**

The query returns the previous value.

**Additional context**

N/A

**Comment by rafeca** [comment]
This behaviour may be intended, but wanted to flag it anyways just in case it isn't 🙂

**Comment by kitten** [comment]
This may be normal, but it’s hard to tell. In a lot of cases React updates aren’t synchronous anymore. They may not even run in the same tick, hence the `act` helper was introduced for testing.

urql does guarantee that the first result is never stale on mount and reflects all the data it has, but any further update is subject to React’s scheduling.

So if you update your test code with `act` according to their new guides you may find it to just work 🙂

**Comment by rafeca** [comment]
Gonna close this one, thanks again folks for the quick response!
