### ISSUE TITLE
💬 URQL future

### ISSUE THREAD

**Issue by morajabi** [FormidableLabs/urql#45]
I'm curious to know, do Formidable Labs have a long-term plan for maintaining `urql` as it gains more traction? Or it's considered a small side project and it will be?

My developer friends concern was this too since Apollo Client is actively maintained. I know @kenwheeler is taking care of it, but what about 1 year later or when new features are introduced to GraphQL. 

So I think answering this might help a lot with the adoption.

**Comment by ryan-roemer** [comment]
Yep, Formidable is actively maintaining this project. Thanks for your interest and concern.
