### ISSUE TITLE
RFC: next-urql

### ISSUE THREAD

**Issue by parkerziegler** [FormidableLabs/urql#452]
`next-urql` would be a small package exposing our `init-urql-client` and `with-urql-client` modules to make it easier for users of NextJS to integrate with `urql`.

### Motivation

Currently to use NextJS with `urql`, I think a lot of folks are probably copy pasting the setup from our NextJS example directly into their projects. It could be nice for us to create our own package that users can just install. The package would include the two modules mentioned above, but it would be most common for them to just wrap their application with `withUrqlClient` (via `_app.js`). This idea is inspired mostly by the ease of using [`next-apollo`](https://github.com/adamsoffer/next-apollo) for this task on the Apollo side.

### Advantages

- Users get a single small package to help them get server-side rendered apps with `urql`. They don't need to learn much about `react-ssr-prepass` to get going.
- Easy to version and to modify as new versions of Next come out and as support for `Suspense` on the server gets codified.
- Continues to grow the `urql` ecosystem ❤️ 

@kitten @JoviDeCroock I'll start spinning up a repo today and try integrating it with example we have in source here. If it shows promise we'll get it up and published. @kitten I know you mentioned a Gatsby plugin as well. I'm not totally sure where that should live – in a separate repo, or perhaps we want to extend this repo to be something like `urql-addons`? I get a little worried that that may give way to one of the core things we're trying to avoid with `urql` – having way too many packages in the ecosystem without clarity around how they fit together. The benefit to a separate package here is that it keeps `urql`'s bundlesize smol and is totally opt-in (users could take another route with Next if they want something more custom).

**Comment by JoviDeCroock** [comment]
I support this idea, and in my opinion, it does not play into having too many packages since it are specific helpers for gatsby/next. I'm totally 👍 on this

**Comment by c0b41** [comment]
I think best option, wait for the new nextjs plugin system https://github.com/zeit/next.js/issues/9133

**Comment by parkerziegler** [comment]
@c0b41 I agree that integrating with the Next plugin system will be the best option for users in the long run. For now, however, and to support legacy Next users, we've got this supported here: https://github.com/FormidableLabs/next-urql. Once the plugin system is formalized, we'll migrate this repo over to the plugin system.

**Comment by parkerziegler** [comment]
@JoviDeCroock @kitten I'd love if either of you could check out https://github.com/FormidableLabs/next-urql and see if it needs any additional polish. I released v0.1.0, mostly pulling the `rollup` config from `urql` with some modifications, including removing properties that were set explicitly to their defaults. Everything seems to be working fine on my end, but always appreciate an extra set of 👀

**Comment by parkerziegler** [comment]
Closing this as `next-urql` is out! All future issues when using that lib should be opened in that repo 😄
