### ISSUE TITLE
(Question) Does UseQuery Return an Array or Json?

### ISSUE THREAD

**Issue by athul** [FormidableLabs/urql#454]
The Title may be vague but I'm really new to the whole Ecosystem. 

I followed the docs and used the `useQuery` hook.

Here is my code
```js
const dataQuery=`
  query {
    user(id: 1) {
      Name
      Bio
      College
      dob
      Phone
      Email
      Designations
      Skill1
      Skill2
      Skill3
      Skill4
      GitHub
      Twitter
      LinkedIn
      Instagram
      Project1
      Project1desc
      Projecturl1
      Project2
      Project2desc
      Projecturl2
      Project3
      Project3desc
      Projecturl3
      Project4
      Project4desc
      Projecturl4
    }
  }

`
const UserData = () => {
  const [result] = useQuery({
    query: dataQuery}) ;
      if (result.fetching) {
        return 'Loading...';
      } else if (result.error) {
        return "Wabba Lubba Dubb Dubbb";
      }
      console.log(result.data.user)
        console.log(typeof(result))
        const tres=Array.from(result.data.user)
        console.log(tres)
        //baaki work aakunilla, check console msgs
    return (
    <div>
        {result.data.user.map(({Name,Bio,College,dob,Phone,Email,Designations,Skill1,Skill2,Skill3,Skill4,GitHub,Twitter,LinkedIn,Instagram,Project1,Project1desc,Projecturl1,Project2,Project2desc,Projecturl2,Project3,Project3desc,Projecturl3,Project4,Project4desc,Projecturl4}) => (
        <div className="card" >
          <Helmet>
            <link rel="shortcut icon" type="image/png" href={"https://avatars1.githubusercontent.com/"+GitHub+"?size=16"}/>
            <title>{Name}</title>
          </Helmet>
            <div className="card-body" style={{
              color:`crimson`
            }}>
                <center><img src={"https://avatars1.githubusercontent.com/"+GitHub+"?size=200"} alt=""/><br/>
                <p className="title has-text-danger">{Name}</p>
              </center>
```

But the console returns that `Userdata.js:47 Uncaught TypeError: result.data.user.map is not a function`

Any Idea on how to resolve this. Even the 
```js
const tres=Array.from(result.data.user)
```
returns a null array with length=0 . 

I made the backend with **Django** and do you think this issue is due to the Backend?

Thanks in Advance 😃

**Comment by athul** [comment]
I cracked it but a question remains..

Why is it said to `.map()` an object in the docs? It always shows up an Error.

**Comment by kitten** [comment]
Hiya, as you can tell from your query, you’re likely asking for a single user since you’re passing an ID. This very much depends on your schema and our docs don’t make much note of any specifics.

The rule of thumb is, we always serve the data that your schema / GraphQL API serves. So depending on your schema some selections will return a list and some will serve objects.

So in any GraphQL client you’ll have to check your schema for what you get.

If you use types JavaScript dialects (e.g. TypeScript) you could also use GraphQL Code Generator to type this response to avoid any mistakes.

**Comment by athul** [comment]
Thanks. It was my mistake actually. I should've checked again.  I'm sorry for the inconvinience caused 😅

I resolved my error as the query returned an `object` type. While the `allUser` query returned a `json`. 

I was trying to `.map()` an object while `.map()` was only to be used on an `Array`.😂 🤣 . But I learned a lot today. And a Huge thanks for making **urql**
