### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by JoviDeCroock** [FormidableLabs/urql#455]
After a conversation on Twitter it turned out there are some area's of the docs we can improve in

- [x] query.pause, how does this work
- [x] executeQuery, this accepts a context, add an example of it
- [ ] variables, how are they applied, ...
- [x] client.suspense, what happens and what changes, ...

If there are others who have had a hard time with certain parts feel free to comment on this issue.

**Comment by kitten** [comment]
I think we’re just not covering enough content in “Getting Started”. It’s supposed to be comprehensive but has been written a long time ago, so it’s missing:

- executeQuery beyond refetching
- Pause and when to use it
- Request policies
- SSR / suspense intro with link to its guide
- improvements to polling

Maybe also a short overview of the lifecycle (state will always reflect all synchronous exchanges immediately)

And we can probably boot out the component API from it and write about it somewhere else instead

**Comment by boygirl** [comment]
As a general suggestion, the "getting started" section of the docs could benefit from a high level overview of urql's basic concepts before diving into specifics of writing queries. I think this would be a great place to include something like the architecture diagram @kitten originally made to explain the rewrite.
