### ISSUE TITLE
Imperative Calls are throwing error

### ISSUE THREAD

**Issue by BjoernRave** [FormidableLabs/urql#458]
I wanted to implement the imperative way to make queries, but I keep on getting the following error:
```
index.js:1 Uncaught (in promise) Error: The error you provided does not contain a stack trace.
```

So I thought maybe I am doing something wrong, tested the example from the repo and the same happens. I also tested it in various browsers, the same behavior everywhere.

**Comment by kitten** [comment]
Sorry, the reference above from that PR was incorrect. We'll need more information here on what's going on; optimally a reproduction. Is this maybe an issue with suspense-mode?

**Comment by BjoernRave** [comment]
Are you able to reproduce it? I guess from the codesandbox you cannot get much, but just try to use the nextjs example from the urql repo, with the latest version, I also have the example in a repo here if you need it: https://github.com/BjoernRave/official-urql-nextjs-example

**Comment by kitten** [comment]
Sorry for the late reply! I’ll take another look today and will let you know how that goes

**Comment by jasonlor** [comment]
I'm seeing the same error on my end

**Comment by BjoernRave** [comment]
thanks alot to you @kitten I love your work and the approach to it :)

**Comment by BjoernRave** [comment]
@kitten sorry to bother you once again, but do you already know when you will do a new release with this fix or is there a way to use the fix already right now?
