### ISSUE TITLE
executeQuery not using new variables

### ISSUE THREAD

**Issue by andrenanninga** [FormidableLabs/urql#464]
**Describe the bug**
Using the `executeQuery` function returned by the `useQuery` function with new variables doesn't actually send the new variables in the next request. Using the code from the example

```js
  const [_, executeQuery] = useQuery({
    query: 'query ($sort: Sorting!) { todos(sort: $sort) { text } }',
    variables: { sort: 'by-date' },
  })

  executeQuery({ variables: { sort: 'by-text' } })
```

I can see two request happening in my network tab, request 1 with the expected `by-date` variable:

```json
{
	"query": "query ($sort: Sorting!) {\n  todos(sort: $sort) {\n    text\n    __typename\n  }\n}\n",
	"variables": {
		"sort": "by-date"
	}
}
```

And the second request, where I expect to see the variable `by-text` for `sort`, but instead still see `by-date`:

```json
{
	"query": "query ($sort: Sorting!) {\n  todos(sort: $sort) {\n    text\n    __typename\n  }\n}\n",
	"variables": {
		"sort": "by-date"
	}
}
```

**Additional context**

Reproduction using https://graphql-pokemon.now.sh/

https://codesandbox.io/s/urql-issue-template-client-hsdi4?fontsize=14

**Comment by JoviDeCroock** [comment]
This is true, the first argument is an `operationContext` at this point in time there's no way to manually override the variables bound on `useQuery` this would cause a discrepancy in the expected outcome.

Maybe I don't really understand the use case for this correctly, could you elaborate?

**Comment by andrenanninga** [comment]
In my specific case I am building a Chrome extension where I want to use the url of the current tab in a query, the call for getting that url is async. So my thinking was to define the query with a variable and `pause: true` and then use `executeQuery({ variables: { url } })` to actually make the call when I have the url. Something like this:

```js
const Item = () => {
  const [query, executeQuery] = useQuery({
    variables: { url: null },
    query: 'query ($url: String) { info(url: $url) { id } }'
  })

  React.useEffect(() => {
    chrome.tabs.getSelected(tab => executeQuery({ url: tab.url }))
  }, [])
}
``` 

I have solved in a different way currently, but I was under the impression that this was a valid usage because I am reading a similar style of code in the README at [Pausing and Request Policies](https://github.com/FormidableLabs/urql#pausing-and-request-policies). The first examples shows updating the `variables`.

**Comment by JoviDeCroock** [comment]
Yes but in the example you link the variables of `useQuery` are updated and then `executeQuery` is called to execute the query with the new variables in `useQuery` none are passed in `executeQuery`.

**Comment by andrenanninga** [comment]
Yeah, that's basically how I changed it. 
I guess I'm not understanding this example from the readme:

```js
const [result, executeQuery] = useQuery({
  query: 'query ($sort: Sorting!) { todos(sort: $sort) { text } }',
  variables: { sort: 'by-date' },
});

// executeQuery can trigger queries and override options
const update = () => executeQuery({ variables: { sort: 'by-text' } });
```

How is `update` supposed to be used and what does `{ variables: { sort: 'by-text' } }` do.

**Comment by JoviDeCroock** [comment]
Well the thing is that `result` in your case if you don't call it with `url` won't return the correct result since looking for it in the `cache` will just return the `url: null` result. Linearly in the example you are showing above, `result` will be the result from `{ sort: 'by-date' }`. This example is indeed confusing and we'll have to do something about it.

Thanks for bringing that to our attention.

**Comment by andrenanninga** [comment]
Thank you for you explanation!

**Comment by bhalsodkhushal** [comment]
Can you share solution of this, i am still facing this issue ?

**Comment by JacksonChristopherHowell** [comment]
> Yeah, that's basically how I changed it. I guess I'm not understanding this example from the readme:
> 
> ```js
> const [result, executeQuery] = useQuery({
>   query: 'query ($sort: Sorting!) { todos(sort: $sort) { text } }',
>   variables: { sort: 'by-date' },
> });
> 
> // executeQuery can trigger queries and override options
> const update = () => executeQuery({ variables: { sort: 'by-text' } });
> ```
> 
> How is `update` supposed to be used and what does `{ variables: { sort: 'by-text' } }` do.

I agree with @bhalsodkhushal. I am still confused by the explanation here. Is there no way to pass variables when "calling a lazy query"?
