### ISSUE TITLE
RFC: Auto populate mutation body

### ISSUE THREAD

**Issue by imranolas** [FormidableLabs/urql#472]
It would be handy if mutation bodies could be auto populated based on the set of currently watched queries. As inspired by [Relay](https://relay.dev/docs/en/classic-guides-mutations#a-complete-example).

## How do updates currently work?

```gql
type Query {
  todos: [Todo]
}
	
type Mutation {
  toggleTodo(id: ID!): Todo
  addTodo(text: String!): Todo
  deleteTodo(id: ID!): Todo
}

type Todo {
  id: ID
  text: String
  complete: Boolean
}
```
Given the schema above. We could request the `todos` using the following query.

```gql
query {
  todos {
	__typename
    id
    text
    complete
  }
}
```

Whilst a component is mounted with this associated query, it is identified as watched. This means any changes to fields or selections within it will trigger reactive UI updates whenever its data changes.

---

Mutations that affect it will also trigger updates so long as the entity can matched to one in the cache.

```gql
mutation($id: ID!) {
  toggleTodo(id: $id) {
	__typename
    id
    complete
  }
}
```

A mutation body should include any fields that may change as a result of the mutation. Ideally these fields at least match those that have already been requested. We can enforce this by spreading common fragments, however, this can become chaotic as the schema and application grow.

The following works quite well but can result in overfetching since not all requested fragments may be mounted but they are now deeply coupled to component fragments.

```gql
fragment Todo on Todo {
	__typename
    id
	text
    complete
}

query {
  todos {
    ...Todo
  }
}

mutation($id: ID!) {
  toggleTodo(id: $id) {
	...Todo
  }
}
```

# Proposal

Instead of declaring the mutation body explicitly, we can infer the body from the currently watched queries. Using schema introspection we can infer that for the following watched query a `Todo` fragment exists.

```diff
# This query belongs to a currently mounted component
query {
  todos {
-	__typename
-    id
-	text
-   complete
}

fragment Todo on Todo {
+	__typename
+    id
+	text
+   complete
}

```

We can also infer that a mutation may require a Todo fragment, however we cannot infer where in its selection that may be. Using a directive we can be explicit about where we'd like to auto populate.

```diff
mutation($id: ID!) {
-  toggleTodo(id: $id) @populate
}

# Replaces the scalar with a selection set populated by the watched fragment
mutation($id: ID!) {
+  toggleTodo(id: $id) {
+	...Todo
+  }
}
```

As queries are mounted and unmounted the mutation body dynamically updates to accommodate the immediate requirements of the UI.

# What do we need to do this?

Since this behaviour is additive to urql it would be best served as an opt-in exchange. We'll need access to the following in order to achieve the above.

- Knowledge of currently watched queries via mount/teardown events.
- Handling for the custom `@populate` directive. These need to be replace by selections at runtime.
- Type info for the annotated selection set or field ideally via introspection since we'll reliably need the typename in all cases

**Comment by kitten** [comment]
As of today this has been merged into Graphcache ✨ https://github.com/FormidableLabs/urql-exchange-graphcache/pull/120
