### ISSUE TITLE
Retry exchange

### ISSUE THREAD

**Issue by mxstbr** [FormidableLabs/urql#475]
I want to create an exchange that automatically retries queries that failed due to a network error. It should employ exponentially backoff and a maximum amount of retries to avoid the thundering herd problem.

This is what I have so far, which unfortunately does not work:

```JS
const retryExchange: Exchange = ({ forward, client }) => {
  const reexecute = (result: OperationResult) => {
    return client.reexecuteOperation({
      ...result.operation,
      context: {
        ...result.operation.context,
        requestPolicy: "network-only"
      }
    });
  };

  const filterIncomingResult = (result: OperationResult) => {
    return result.error && result.error.networkError ? true : false;
  };

  return operation$ =>
    pipe(forward(operation$), filter(filterIncomingResult), map(reexecute));
};
```

I assume the problem is in the `reexecute` part, however I am unsure how to turn a `Source<OperationResult>` "around" and send it back in the other direction as a `Source<Operation>`. 

Any pointers? :pray:

**Comment by JoviDeCroock** [comment]
I think you'll have to capture the request like this:

```
return op$ => {
  let result;
  return pipe(
    map(op => (result = op))
    forward(op$)
    filter
    map(() => reexecute(result)
  )
}
```

Not entirely sure though, if it's a missmatch in what kind of operation you are reexecuting this would be my best guess

**Comment by mxstbr** [comment]
Hm, isn't the initial operation the same as `result.operation`? 🤔 Otherwise all the caching etc wouldn't work, so that shouldn't matter?

**Comment by JoviDeCroock** [comment]
> however I am unsure how to turn a Source<OperationResult> "around" and send it back in the other direction as a Source<Operation>.

Made me think you were encountering a difference so I wanted to clear that up, well mainly the only difference in the two is that the returning one will have a payload with data etc attached to it.
That being said, your UI will always be notified of the NetworkError since the returning signal can't just be aborted as far as I know. It might be easier to implement this in the `fetchExchange` itself is also one of my thoughts

**Comment by kitten** [comment]
One possible working solution is here: https://gist.github.com/kitten/843fd82ccb0183e0070851b5faf2dde4

We may still want to ship this in the future though

**Comment by spikebrehm** [comment]
@kitten we've been using the solution in your Gist, and it works well. However while trying to upgrade from 1.6 -> 1.11, I'm getting some type errors. I'm unfamiliar with Wonka and this type of stream programming, so I was wondering if you could easily point me in the right direction to get this working with 1.11. Thanks!

<img width="735" alt="Screen Shot 2021-01-18 at 5 44 49 PM" src="https://user-images.githubusercontent.com/133937/104968808-de178200-59b4-11eb-801f-0033c8881461.png">

**Comment by spikebrehm** [comment]
I see now that this has upgraded us to Wonka 4.0. I'll check the [migration guide](https://wonka.kitten.sh/migration) for tips 🤞🏼

```diff
-        "wonka": "^3.2.1"
+        "wonka": "^4.0.14"```

**Comment by spikebrehm** [comment]
For anybody coming here from Google search, here's how to update to work for wonka@4

```diff
@@ -23,7 +23,7 @@ const DELAY_MS = 100;
 // Retry logic from this thread: https://github.com/FormidableLabs/urql/issues/475
 const errorExchange: Exchange = ({ forward }) => ops$ => {
   const sharedOps$ = pipe(ops$, share);
-  const [retry$, nextRetryOperation] = makeSubject<Operation>();
+  const { source: retry$, next: nextRetryOperation } = makeSubject<Operation>();
 
   const retryWithBackoff$ = pipe(
     retry$,
@@ -41,8 +41,7 @@ const errorExchange: Exchange = ({ forward }) => ops$ => {
         sharedOps$,
         filter(op => {
           return (
-            (op.operationName === 'query' || op.operationName === 'teardown') &&
-            op.key === key
+            (op.kind === 'query' || op.kind === 'teardown') && op.key === key
           );
         })
       );

```

**Comment by kitten** [comment]
I would maybe recommend our retry exchange package as an alternative these days though 😇 https://formidable.com/open-source/urql/docs/api/retry-exchange/
