### ISSUE TITLE
Q: beautiful chart, created by tool or ps?

### ISSUE THREAD

**Issue by kiinoo** [FormidableLabs/urql#476]
I noticed the charts in the readme are very intuitive and beautiful, wonder how were they created ;-)

**Comment by kitten** [comment]
Thanks! Glad you like them!

We had a short answer for that on Spectrum ✨ I made them in Sketch https://spectrum.chat/urql/general/random-question~9babf416-a648-40a3-a2e2-5b9587012101

Maybe I’ll post the sketch file here later if I remember 👍
