### ISSUE TITLE
Add support for skipping queries for SSR so they only run in the client side

### ISSUE THREAD

**Issue by Tuffail** [FormidableLabs/urql#477]
Hi,

Is it possible to selectively disable SSR on some queries so they are only made on the client side? For example, there might be a very time consuming query and we do not want to delay the user request so skip it on SSR and run it on the client side.

Apollo has a similar feature - https://www.apollographql.com/docs/react/performance/server-side-rendering/#skipping-queries-for-ssr

Is there an equivalent for URQL? If not, what would be the best approach and is there any plans to support this?

**Comment by JoviDeCroock** [comment]
I would assume this can be done atm by doing `useQuery({ skip: !process.isBrowser })`

**Comment by Tuffail** [comment]
I'm using the `Query` component and passing `skip={!process.isBrowser}` as a prop does not work

**Comment by kitten** [comment]
Sorry 😅 it’s not supposed to be `skip` but the prop is named `pause`

**Comment by Tuffail** [comment]
That works thanks @kitten and @JoviDeCroock! ❤️
