### ISSUE TITLE
Error in stringifyVariables during mutation

### ISSUE THREAD

**Issue by gridbox** [FormidableLabs/urql#478]
We recently updated our version of urql from 1.3.1 to 1.6.3 and our mutations started breaking.

The error logged in the console is
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at stringify (stringifyVariables.ts:36)
    at stringify (stringifyVariables.ts:35)
    at stringify (stringifyVariables.ts:35)
    at stringify (stringifyVariables.ts:35)
    at stringify (stringifyVariables.ts:35)
    at stringifyVariables (stringifyVariables.ts:49)
    at createRequest (request.ts:36)
    at useMutation.ts:47
```
We have Momentjs fields in the object that is being passed into the mutation variables and it appears this is where the embedded stringify is breaking.  Version 1.3.1 was able to stringify these just fine with the default string version of a Moment being an ISO date.

Any guidance would be appreciated.

**Comment by JoviDeCroock** [comment]
Hey thanks for the issue report,

That might be related to us not calling `toJSON` on the `moment` date. I'd try to add a check here: https://github.com/FormidableLabs/urql/blob/master/src/utils/stringifyVariables.ts#L4

```
if (x && x.toJson) x = x.toJSON()
```
