### ISSUE TITLE
refetch not triggered when variable changed

### ISSUE THREAD

**Issue by BjoernRave** [FormidableLabs/urql#479]
I have the following code to fetch data:
```
  const [{ data, fetching, error }, fetchMovements] = useQuery<
    Get_MovementsQuery
  >({
    query: GET_MOVEMENTS,
    variables: { skip: startRow, first: rowNumber, orderBy, where: filter },
    requestPolicy: 'cache-and-network'
  })
```

Where filter is an object with all the different filter options. 

I have a datetime-range filter. The structure of the filter object for that case looks like this:
```
{
    date: {
      gte: DateTime,
      lte: DateTime
    }
  }
```

When changing one of the values for the first time, it correctly detects a change in the variables and triggers a refetch, but when changing the same datetime another time, it doesn't cause a refetch.

If necessary I can provide a reproduction.

Maybe it's also just my own stupidity, but I am pretty sure it's related to urql.

I am using the latest version with the urql-graphexchange.

**Comment by JoviDeCroock** [comment]
Is it just a string datetime or a moment object or ... It's quite important to know if it stays referrentially equal or not, a repro could help a lot

**Comment by BjoernRave** [comment]
@JoviDeCroock it's a javascript dateTime object and it stays like that the whole time

**Comment by JoviDeCroock** [comment]
Do you mutate it or is your gte/... immutable?

**Comment by BjoernRave** [comment]
@JoviDeCroock this is my datetimepickercomponent, where I alter the filter object, which is stored with `useState`:
```
                <KeyboardDatePicker
                  variant='inline'
                  label={t('table:endTime')}
                  value={filter?.date?.lte || null}
                  onChange={date => {
                    setFilter({
                      ...filter,
                      date: { ...filter.date, lte: date }
                    })
                  }}
                  format='dd/MM/yyyy'
                  style={{ width: '48%' }}
                />
```

**Comment by JoviDeCroock** [comment]
Yes this could be solved by adjusting `stringifyVariables` to respect the `toJSON` of dates and other complex structures.
I can look into this later or if you want the solution is described in #478.
