### ISSUE TITLE
Improve support for non-react usage 

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql#480]
As of right now, our ES bundle requires React (unless a build step with tree shaking is being used).

While Urql is primarily used with React, we should ensure that it is fully usable in isolation.

Proposed changes:
 - Split client+util bundle output from react specific output (adds ability to do `import { createClient } from urql/client`)
 - Change React peer dependency to be an optional dependency

**Comment by kitten** [comment]
Duplicate of #423 :)
