### ISSUE TITLE
cache and network policy does not seem to work

### ISSUE THREAD

**Issue by mixvar** [FormidableLabs/urql#486]
**Describe the bug**
When fetching a query using "cache-and-network" policy the effect is the same as when using "network-only" policy, i.e. the data is only available after the request is complete event though cached result should be available instantly.

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Set up server that responds to query with 1s delay
2. Set up client that uses the query to display some data and uses ` requestPolicy: "cache-and-network"`
3. Use the client in a way that makes the query execute multiple times e.g. navigating between pages
4. verify whether query data is available instantly from the cache or not

**Expected behaviour**
After executing query for the first time its cached, so for any consecutive executions query result is retrieved from cache first (also request is sent to update cache if needed). The `data` returned from the query result is not `undefined`.

**Actual behavior**
Each execution of the query behaves like "network-only", no data from cache is extracted. The `data` returned from the query result is `undefined` until request completes.

**Additional context**
 - using urql v1.6.3
 - using default `cacheExchange`
 - using react v16.11.0
 - using hooks API (generated via https://www.npmjs.com/package/@graphql-codegen/typescript-urql)
 - not running any mutations that would invalidate the cache
 - urql devtools show that data is cached, but report "This result wasn't served from cache" anyway
 - query has no variables
 - when using the default "cache-first" policy the data is cached and retrieved from cache properly

related piece of code when I encountered this:
```
  const [{ data, error }] = usePostsListQuery({
    requestPolicy: "cache-and-network",
  });
  const posts = data && data.posts;

  if (error) return <h3>Error!</h3>;
  if (!posts) return <h3>Loading...</h3>;

  return (...);
  ...
```
I get `Loading...` each time until backend responds with data.

**Comment by JoviDeCroock** [comment]
Hey, mind giving the contents of `usePostsListQuery`? I think there could be something funky going on, I've tried reproducing it with a simple example [here](https://codesandbox.io/s/loving-sammet-xfl3x) but can't seem to get your issue.

**Comment by mixvar** [comment]
I also get the issue when using `useQuery` directly, like so:
```
import gql from "graphql-tag";
import { useQuery } from "urql";

export const PostsListQuery = gql`
  query PostsList {
    posts {
      id
      title
      authorName
      tags
    }
  }
`;

export const PostsList: React.FC = () => {
  const [{ data, error }] = useQuery({
    query: PostsListQuery,
    requestPolicy: "cache-and-network",
  });

  (...)
```

If you can't be reproduce it I'll try to setup separate repo for this on github when I'll have some time.

**Comment by JoviDeCroock** [comment]
If you want you can fork my codesandbox.

**Comment by mixvar** [comment]
I can't seem to be able to replicate it on codesandbox, I'll try to extract the code I have to public github repo. 
One thing I find weird in the example you send is that I see fetch requests flying over the network only when I click `refetch`. Shouldn't there be also requests flying after each `switch`?

**Comment by mixvar** [comment]
Looks like this is some weird side effect of the particular dev setup I had.
I extracted it to [this github repo](https://github.com/mixvar/urql-cache-and-network-issue) and simplified the code. The issue occurs when i run the app in dev mode but is gone when i build and run it in prod mode. Perhaps it's something related to HMR or razzle.

You can investigate further if you want, but I am closing the issue.
