### ISSUE TITLE
Is it possible to change the schema programmatically and call it immediately?

### ISSUE THREAD

**Issue by TriStarGod** [FormidableLabs/urql#489]
I have a situation that requires changing the schema of the query / mutation based on user input. Is it possible to change the schema after its been set and call it immediately?

Thanks for the great library!!!

**Comment by kitten** [comment]
Hiya 👋

I’m not quite sure what you mean by changing the schema since that’s not an option? Do you mean the GraphQL API url?

You can either programmatically set it in your state and recreate the client when it changes, and pass it to the Providern

Or you can pass in `context.url` in the hooks to change this once off: https://github.com/FormidableLabs/urql/blob/fb070cba2170c89f39baac757a694da92447ddce/src/hooks/useQuery.ts#L24

**Comment by TriStarGod** [comment]
Once I examined the code, I noticed it couldn't be changed. So I created a custom query.

```
const CustomQueryAsync = (value) => {
  console.log({ value });
  return pipe(
    fromValue(value),
    debounce(() => 5000),
    mergeMap((name) => client.executeQuery(createRequest(GetIndustries, name ? { input: { name } } : undefined))),
    map(({ data: { GetIndustries } }) => GetIndustries),
    take(1),
    toPromise,
  );
};
```

Except for the debounce, everything else is working great.

**Comment by JoviDeCroock** [comment]
The only thing I see your custom query do is alter the `variables` object which should be possible by doing this:

`const result = useQuery({ query, variables: name ? { input: { name} } : undefined })` or am I misunderstanding this?

**Comment by TriStarGod** [comment]
In my use case, I would run a function that would choose the appropriate query based on certain conditions. I could have either made multiple `useQueries` or setup a `useEffect` to run whenever the `useQuery's` execute function changes but it seemed very inefficient.

**Comment by kitten** [comment]
Oh so you still want both results to be available?
You can maybe still use `useQuery`. We have a `pause: true | false` option so you can conditionally only let one of them run at a time maybe?

**Comment by JoviDeCroock** [comment]
Yes what @kitten sais is a good way I t hink

Let me introduce a small example:

```jsx
const MyApp = () => {
  const [type, setType] = useState('dogs');
  const [dogsRes] = useQuery({ query: dogsQuery, pause: type === 'dogs' });
  const [catsRes] = useQuery({ query: catsQuery, pause: type === 'cats' });

  ...jsx stuff
}
```

**Comment by TriStarGod** [comment]
I did consider that but I had 5 queries and initialization of all 5 every time seemed inefficient when only 1 of the queries was required depending on some parameters. Either way, I got everything working. Really like urql.
