### ISSUE TITLE
Export useOperator

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#497]
When the new concurrent mode supported version is released could you also publicly export useOperator?

Right now in one of my projects i am using the useSubjectValue to merge subscription data with custom state and update it using a reducer style approach (via the update method)

From the concurrent mode pull request i noticed that you have replaced useSubjectValue with useOperator and once it is realease i would not be able to update my code unless i fork the hook

Thanks

**Comment by kitten** [comment]
Hiya 👋

Yes, it’s our intention to move this back to either `react-wonka` or create a more generic hook package. We’ve merged this to `master` only so we can test Wonka 4 and this new hook together properly

**Comment by zenios** [comment]
Hi @kitten 

Great news.  Thanks you very much

As for the Edit part no i was not expecting synchronous updates. As already explained i was merging subscription data with custom state and update at the same time using a reducer approach style.

It worked perfect
