### ISSUE TITLE
Tagging the query/mutations to enable syntax highlighting possibility 

### ISSUE THREAD

**Issue by morajabi** [FormidableLabs/urql#50]
Syntax highlighting libraries have no idea if a template string is GraphQL or not. In styled-components, they can detect it by `css` tag, or `styled.X`. 

For GraphQL, highlighting extensions they can detect `gql` tagged strings. So I tend to define this: 
```js
const gql = String.raw

const UserQuery = gql`query { user }`
```
And I get syntax highlighting! (I use [this](https://github.com/kumarharsh/graphql-for-vscode) in VSCode)

So as an idea we can refer to this method at the end of `readme`, as a "Syntax Highlighting" section, or we can export this from the library which might not be the best thing. I can do a PR as well.
 
Your thoughts? Thanks!

**Comment by einarlove** [comment]
Use
```
const query = `#graphql
  type User {}
`
```
https://github.com/kumarharsh/graphql-for-vscode/pull/57

**Comment by jaydenseric** [comment]
The future is comment tags, supported by many tools ([and soon prettier](https://github.com/prettier/prettier/pull/4395)):

```js
/* GraphQL */`
  {
    foo
  }
`
```

In the meantime, you can use [`fake-tag`](https://github.com/jaydenseric/fake-tag) to avoid gotchas with `String.raw` and other hacks:

```js
import gql from 'fake-tag'

const typeDefs = gql`
  "A foo."
  type Foo {
    "The \`Foo\` ID."
    id: ID!
  }
`
```
