### ISSUE TITLE
`fetching` breaks when variables change

### ISSUE THREAD

**Issue by narinluangrath** [FormidableLabs/urql#501]
**Describe the bug**
Changing `variables` in `useQuery` causes `fetching` to get stuck on `true`, even when data has finished requerying.

**Steps to reproduce**
https://codesandbox.io/s/urql-fetching-bug-8xond

1. Change the input
2. Change it back what it originally was

**Expected behavior**
`fetching` goes back to `false` after data requeries (or gets it from cache).

**Actual behavior**
`fetching` stays at `true`

**Comment by narinluangrath** [comment]
The `data` field seems broken too. Probably just missing dependency in `useMemo` or something.

**Comment by kitten** [comment]
Interesting! I can confirm that this is happening and I’ll look into it

**Comment by kitten** [comment]
A fix for this is ready and it does cause the correct behaviour again in the CodeSandbox 🙌

**Comment by kitten** [comment]
The fix in #503 is now published with [`v1.8.1`](https://github.com/FormidableLabs/urql/releases/tag/v1.8.1) :tada:
