### ISSUE TITLE
using `context` inside of `useQuery` falls into an infinite loop

### ISSUE THREAD

**Issue by rmacy** [FormidableLabs/urql#507]
**Describe the bug**
`useQuery` will fall into an indefinite render loop if you pass `context` aka `Partial<OperationContext>` as a parameter.

**Steps to reproduce**
Create a `useQuery` hook and pass `context`, e.g.

```js
useQuery({ query: MyQuery, variables: { someId }, context: {} });
```

**Expected behavior**
useQuery is only called once.

**Actual behavior**
useQuery falls into an infinite loop.

**Additional context**
I think using `context` is valuable because it's a great way to pass in an auth token as a header if you don't have access to an auth token outside of a component render context.

**Comment by JoviDeCroock** [comment]
Hey @macy

Thanks for the error report, this is intended. We advice using `useMemo` this way you can control when the query should refetch. There can be conditions where you don't want to refetch for some minor change (i.e. token being refetched). We can't anticipate these scenario's that's why  we move this responsibility to your side.

```js
useQuery({ query: MyQuery, variables: { someId }, context: React.useMemo(() => ({}), []) });
```

Should do the trick.

**Comment by rmacy** [comment]
Thanks @JoviDeCroock -- I don't know if that was clear in the docs after a quick glance, I'd be happy to make a PR, thoughts?

**Comment by JoviDeCroock** [comment]
That would be awesome, we're trying to be as clear as we can in our documentation but an outside view is most often the best to show us these oversights. That contribution would be more than welcome!

**Comment by rmacy** [comment]
🔥 Will do! Thank you for the awesome work in this library!

**Comment by sunpietro** [comment]
I've created a PR that updates the missing info in the docs: https://github.com/FormidableLabs/urql/pull/1800
