### ISSUE TITLE
useLazyQuery hook

### ISSUE THREAD

**Issue by jgoux** [FormidableLabs/urql#513]
Hello,

Apollo has the very useful [useLazyQuery](https://www.apollographql.com/docs/react/v3.0-beta/data/queries/#executing-queries-manually) which allows to trigger the query independently of the component rendering.

I didn't see an equivalent with urql.

Right now I'm wiring things manually :
```tsx
const SelectBoxForm: FC<{ onChange: any }> = ({ onChange }) => {
  const graphqlClient = useClient();
  const onSubmit = async ({ boxBarcode }: SelectBoxFormData) => {
    const { data } = await graphqlClient
      .query<GetBoxQuery, GetBoxQueryVariables>(GET_BOX, {
        barcode: boxBarcode
      })
      .toPromise();
    onChange(data?.boxByBarcode);
  };

  return (/* JSX */)
}
```

I think it would be a great addition to the lib as these lazy queries are quite common (at least in my apps? 😄)

Also we could then leverage this hook to generate more typesafe utilities with graphql-codegen!

**Comment by JoviDeCroock** [comment]
Hey @jgoux 

Thanks for bringing this up!
Isn't that the same as using `pause: true` in our hooks?

**Comment by jgoux** [comment]
Hi @JoviDeCroock and thanks for the very fast answer! ⚡️ 

I'm not sure they're the same.

In this example : 
```js
const [res, executeQuery] = useQuery({
    query: getTodos,
    pause: true
  });
```
Is it possible to omit the "variables" from the hook and pass it to executeQuery later?
Also `executeQuery` returns void, not the state's object, so I don't see how I could use it in the snippet I shared.

**Comment by kitten** [comment]
No, it's not possible to override the variables in `executeQuery` since in that case we'd really recommend a custom hook based on `client.query()` which returns a promise :)

Alternatively you can in most cases achieve complex changes with `pause` dependent on some state and variables being in a `useState` hooks, but it really depends on your use-case.

**Comment by jgoux** [comment]
@kitten Ok, good to know!

As you said, I can roll my own custom hook but I really think there is a strong use-case for this hook.

The [graphql-hooks](https://github.com/nearform/graphql-hooks#usemanualquery) also has this hook.

I'm running out of arguments so I let you decide if it's worth it or not. 👍

**Comment by kitten** [comment]
I think this is mainly the same as calling `client.query` and saving the result to a hook so I'd rather not make a distinction here :)

I'm convinced that in most cases `pause: true` is sufficient where queries are _eventually_ made reactive to the UI. I've seen an app that used `urql` where a query was made to validate some form data, but only after the form was deemed "valid" in some offline validation. That was done by deriving the variables and feeding them to `useQuery` from some state and setting `pause` to `true` when the form was valid.

In other cases I can completely see the need for queries that are non-UI-driven and transactional, but since in such cases the logic will be very transaction-based and possibly imperative, I think we should stick to recommending `client.query()` in those cases :)

**Comment by kitten** [comment]
Closed due to inactivity. The above programmatic API is still the recommended way to use "lazy queries"

**Comment by javiertury** [comment]
I think that useLazyQuery could be used to improve performance by reducing the number of re-renders. This would be especially useful when combined with `react-hook-form`.

```ts
import { useForm } from 'react-hook-form';
import { useLazyQuery } from 'urql';

export default function App () {
  const { formState, getValues, watch } = useForm()
  // It automatically picks the last query result
  const [runQuery, { loading, error, data }] = useLazyQuery({ query: FooDocument });

  useEffect(() => {
    // Watch all changes in the form without triggering a re-render, just change the query variables
    const subscription = watch(() => {
      if (formState.isValid) {
        runQuery({ variables: getValues() });
      }
    });
    return () => subscription.unsubscribe();
  }, [watch]);
  
  // Renders only if there is a change in the query result
  return <div>{data.foo}</div>
}
```

**Comment by kitten** [comment]
@javiertury So, if I'm not mistaken, what you're after is simply to be able to overwrite `variables` when calling `executeQuery`?

**Comment by javiertury** [comment]
> to be able to overwrite `variables` when calling `executeQuery`?

Yes, implementation-wise I think it's equivalent.

```ts
import { useForm } from 'react-hook-form';
import { useLazyQuery } from 'urql';

export default function App () {
  const { formState, getValues, watch } = useForm()
  // It automatically picks the last query result
  const [{ fetching, error, data }, executeQuery] = useQuery({ query: FooDocument, pause: true });

  useEffect(() => {
    // Watch all changes in the form without triggering a re-render, just change the query variables
    const subscription = watch(() => {
      if (formState.isValid) {
        executeQuery({ variables: getValues() });
      }
    });
    return () => subscription.unsubscribe();
  }, [watch]);
  
  // Renders only if there is a change in the query result
  return <div>{data.foo}</div>
}
```

**Comment by prankymat** [comment]
personally I find the useLazyQuery very useful since we can basically define the "query execution plan" and pass in variables  when we need to use it. I've created a useLazyQuery hook in my project, might be clumsy but it works.

```
const useLazyQuery: (args: Omit<UseQueryArgs, 'variables' | 'pause'>) => UseQueryResponse = (args) => {
  const firstUpdate = useRef(true);
  const [variables, setVariables] = useState<any>();

  const [result, refetch] = useQuery({
    ...args,
    variables,
    pause: true,
  });

  useEffect(() => {
    if (firstUpdate.current) {
      firstUpdate.current = false;
      return;
    }
    refetch();
  }, [variables]);

  const makeRequest = useCallback((reqVariables) => {
    setVariables(reqVariables);
  }, []);

  return [result, makeRequest];
};
```

example usage:

```
const [{
  data,
  error,
  loading
}, refetchCurrent] = useLazyQuery({
  query: GraphQLAPI.queries.GetActivityStatsUser,
  requestPolicy: 'network-only',
});

refetchCurrent({ startDate: 'xxx', endDate: 'yyy' });
...
refetchCurrent({ startDate: 'zzz', endDate: 'ttt' });
```

**Comment by lewnelson** [comment]
> personally I find the useLazyQuery very useful since we can basically define the "query execution plan" and pass in variables when we need to use it. I've created a useLazyQuery hook in my project, might be clumsy but it works.
> 
> ```ts
> const useLazyQuery: (args: Omit<UseQueryArgs, 'variables' | 'pause'>) => UseQueryResponse = (args) => {
>   const firstUpdate = useRef(true);
>   const [variables, setVariables] = useState<any>();
> 
>   const [result, refetch] = useQuery({
>     ...args,
>     variables,
>     pause: true,
>   });
> 
>   useEffect(() => {
>     if (firstUpdate.current) {
>       firstUpdate.current = false;
>       return;
>     }
>     refetch();
>   }, [variables]);
> 
>   const makeRequest = useCallback((reqVariables) => {
>     setVariables(reqVariables);
>   }, []);
> 
>   return [result, makeRequest];
> };
> ```
> 
> example usage:
> 
> ```ts
> const [{
>   data,
>   error,
>   loading
> }, refetchCurrent] = useLazyQuery({
>   query: GraphQLAPI.queries.GetActivityStatsUser,
>   requestPolicy: 'network-only',
> });
> 
> refetchCurrent({ startDate: 'xxx', endDate: 'yyy' });
> ...
> refetchCurrent({ startDate: 'zzz', endDate: 'ttt' });
> ```
> 
> Happy to open a feature request or pull request if it's also something others will use.

thanks for this ❤️. I've modified it slightly to have stricter types when following the [TypeScript integration docs](https://formidable.com/open-source/urql/docs/basics/typescript-integration/). Follows the same interface, but strict types for the data and variables.

```TypeScript
type Variables<TQuery extends TypedDocumentNode> = TQuery extends TypedDocumentNode<any, infer TVariables> ? TVariables : never;
type Data<TQuery extends TypedDocumentNode> = TQuery extends TypedDocumentNode<infer TData, any> ? TData : never;

export const useLazyQuery = <TQuery extends TypedDocumentNode<any, any>>(
  args: Omit<UseQueryArgs<Variables<TQuery>, Data<TQuery>>, 'variables' | 'pause' | 'query'> & { query: TQuery }
): [UseQueryResponse<Data<TQuery>, Variables<TQuery>>[0], (variables: Variables<TQuery>) => void] => {
  const firstUpdate = useRef(true);
  const [variables, setVariables] = useState<Variables<TQuery>>();

  const [result, refetch] = useQuery<Data<TQuery>, Variables<TQuery>>({
    ...args,
    variables: variables!,
    pause: true,
  });

  useEffect(() => {
    if (firstUpdate.current) {
      firstUpdate.current = false;
      return;
    }

    refetch();
  }, [variables]);

  const makeRequest = useCallback((reqVariables: Variables<TQuery>) => {
    setVariables(reqVariables);
  }, []);

  return [result, makeRequest];
};
```

**Comment by okparaa** [comment]
> > personally I find the useLazyQuery very useful since we can basically define the "query execution plan" and pass in variables when we need to use it. I've created a useLazyQuery hook in my project, might be clumsy but it works.
> > ```ts
> > const useLazyQuery: (args: Omit<UseQueryArgs, 'variables' | 'pause'>) => UseQueryResponse = (args) => {
> >   const firstUpdate = useRef(true);
> >   const [variables, setVariables] = useState<any>();
> > 
> >   const [result, refetch] = useQuery({
> >     ...args,
> >     variables,
> >     pause: true,
> >   });
> > 
> >   useEffect(() => {
> >     if (firstUpdate.current) {
> >       firstUpdate.current = false;
> >       return;
> >     }
> >     refetch();
> >   }, [variables]);
> > 
> >   const makeRequest = useCallback((reqVariables) => {
> >     setVariables(reqVariables);
> >   }, []);
> > 
> >   return [result, makeRequest];
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > example usage:
> > ```ts
> > const [{
> >   data,
> >   error,
> >   loading
> > }, refetchCurrent] = useLazyQuery({
> >   query: GraphQLAPI.queries.GetActivityStatsUser,
> >   requestPolicy: 'network-only',
> > });
> > 
> > refetchCurrent({ startDate: 'xxx', endDate: 'yyy' });
> > ...
> > refetchCurrent({ startDate: 'zzz', endDate: 'ttt' });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Happy to open a feature request or pull request if it's also something others will use.
> 
> thanks for this ❤️. I've modified it slightly to have stricter types when following the [TypeScript integration docs](https://formidable.com/open-source/urql/docs/basics/typescript-integration/). Follows the same interface, but strict types for the data and variables.
> 
> ```ts
> type Variables<TQuery extends TypedDocumentNode> = TQuery extends TypedDocumentNode<any, infer TVariables> ? TVariables : never;
> type Data<TQuery extends TypedDocumentNode> = TQuery extends TypedDocumentNode<infer TData, any> ? TData : never;
> 
> export const useLazyQuery = <TQuery extends TypedDocumentNode<any, any>>(
>   args: Omit<UseQueryArgs<Variables<TQuery>, Data<TQuery>>, 'variables' | 'pause' | 'query'> & { query: TQuery }
> ): [UseQueryResponse<Data<TQuery>, Variables<TQuery>>[0], (variables: Variables<TQuery>) => void] => {
>   const firstUpdate = useRef(true);
>   const [variables, setVariables] = useState<Variables<TQuery>>();
> 
>   const [result, refetch] = useQuery<Data<TQuery>, Variables<TQuery>>({
>     ...args,
>     variables: variables!,
>     pause: true,
>   });
> 
>   useEffect(() => {
>     if (firstUpdate.current) {
>       firstUpdate.current = false;
>       return;
>     }
> 
>     refetch();
>   }, [variables]);
> 
>   const makeRequest = useCallback((reqVariables: Variables<TQuery>) => {
>     setVariables(reqVariables);
>   }, []);
> 
>   return [result, makeRequest];
> };
> ```

This is awesome. You have done very well.  I was looking for a way to still pass initial variables but could not. How do I do this looking at the line below. Thank you
args: Omit<UseQueryArgs<Variables<TQuery>, Data<TQuery>>, 'variables' | 'pause' | 'query'> & { query: TQuery }

**Comment by lucasforchino** [comment]
Another version based on your solutions, to avoid use effect and get the the result as a promise 

```
import { useCallback } from "react";
import {
  OperationResult,
  TypedDocumentNode,
  UseQueryArgs,
  useClient,
} from "urql";

type Variables<TQuery extends TypedDocumentNode> =
  TQuery extends TypedDocumentNode<any, infer TVariables> ? TVariables : never;
type Data<TQuery extends TypedDocumentNode> = TQuery extends TypedDocumentNode<
  infer TData,
  any
>
  ? TData
  : never;

export const useLazyQuery = <TQuery extends TypedDocumentNode<any, any>>(
  args: Omit<
    UseQueryArgs<Variables<TQuery>, Data<TQuery>>,
    "variables" | "pause" | "query"
  > & { query: TQuery }
): ((
  variables: Variables<TQuery>
) => Promise<OperationResult<any, Variables<TQuery>>>) => {
  const client = useClient();

  const handler = useCallback(
    (variables: Variables<TQuery>) => {
      return client.query(args.query, variables).toPromise();
    },
    [args.query, client]
  );
  return handler;
};
```
then you can use

```
const handler = useLazyQuery({query: GraphqlQuery})

handler({id=1}).then( resp  => {
...
})
```

**Comment by lucasforchino** [comment]
Another version based on your solutions, to avoid use effect and get the the result as a promise 

```ts
import { useCallback } from "react";
import {
  OperationResult,
  TypedDocumentNode,
  UseQueryArgs,
  useClient,
} from "urql";

type Variables<TQuery extends TypedDocumentNode> =
  TQuery extends TypedDocumentNode<any, infer TVariables> ? TVariables : never;
type Data<TQuery extends TypedDocumentNode> = TQuery extends TypedDocumentNode<
  infer TData,
  any
>
  ? TData
  : never;

export const useLazyQuery = <TQuery extends TypedDocumentNode<any, any>>(
  args: Omit<
    UseQueryArgs<Variables<TQuery>, Data<TQuery>>,
    "variables" | "pause" | "query"
  > & { query: TQuery }
): ((
  variables: Variables<TQuery>
) => Promise<OperationResult<any, Variables<TQuery>>>) => {

  const client = useClient();

  const handler = useCallback(
    (variables: Variables<TQuery>) => {
      return client.query(args.query, variables).toPromise();
    },
    [args.query, client]
  );

  return handler;
};
```

then you can use

```ts
const handler = useLazyQuery({query: GraphqlQuery})

handler({id=1}).then( resp  => {
...
})
```

**Comment by lucasforchino** [comment]
Another version based on your solutions, to avoid use effect and get the the result as a promise 
```ts
import { useCallback } from "react";
import {
  OperationResult,
  TypedDocumentNode,
  UseQueryArgs,
  useClient,
} from "urql";

type Variables<TQuery extends TypedDocumentNode> =
  TQuery extends TypedDocumentNode<any, infer TVariables> ? TVariables : never;
type Data<TQuery extends TypedDocumentNode> = TQuery extends TypedDocumentNode<
  infer TData,
  any
>
  ? TData
  : never;

export const useLazyQuery = <TQuery extends TypedDocumentNode<any, any>>(
  args: Omit<
    UseQueryArgs<Variables<TQuery>, Data<TQuery>>,
    "variables" | "pause" | "query"
  > & { query: TQuery }
): ((
  variables: Variables<TQuery>
) => Promise<OperationResult<any, Variables<TQuery>>>) => {

  const client = useClient();

  const handler = useCallback(
    (variables: Variables<TQuery>) => {
      return client.query(args.query, variables).toPromise();
    },
    [args.query, client]
  );

  return handler;
};
```

then you can use

```ts
const handler = useLazyQuery({query: GraphqlQuery})

handler({id=1}).then( resp  => {
...
})
```

**Comment by kitten** [comment]
@lucasforchino: I'd highly recommend for you not to do this and to instead rely on `pause: true`. The easiest effectless way to actually do this is to set `pause: false` with local state.

Promisifying queries means that they can _never_ update and become inactive after a result, which means that cache (and other reactive) updates become impossible.
While this is fine for mutations, in queries and subscriptions this means that you have no invalidation or changes coming in on your query when you use a promise under the hood.

**Comment by lucasforchino** [comment]
@kitten , good point thanks for clarifying

**Comment by Eigilak** [comment]
I would like to implement useLazyQuery as a generated hook for executing queries, similar to Apollo's implementation (https://www.apollographql.com/docs/react/data/queries#manual-execution-with-uselazyquery). As demonstrated in Apollo's documentation, this approach provides significant flexibility by allowing queries to be prepared for execution once valid variables are available. Currently, we must rely on conditional rendering logic to handle scenarios where variables are not yet present.

Copy
Retry

**Comment by onx2** [comment]
FWIW this is what I use in `solid-js` for querying, both immediately and lazily. variables are set initially and stored for use later when the consumer calls refetch -- optionally overwriting them. Seems to work so far for my use-cases, if it looks good to you I'm sure it isn't difficult to convert to react.


```ts
import type { AnyVariables, CombinedError, GraphQLRequest } from "@urql/core";
import { print } from "graphql";
import { batch, createSignal, onCleanup, onMount, type Accessor } from "solid-js";
import type { Subscription } from "wonka";

import { client } from "./client";
import { getDocumentNodeKey } from "./getDocumentNodeKey";

type Performance = {
  // The time it took to execute the query in milliseconds
  executionTime: number | null;
  // The unique key of the query, urql-cache uses this to identify the query in its cache
  key: number;
  // The DocumentNode printed as a string
  query: string;
};

/**
 * Custom hook to execute a GraphQL query using URQL and manage its state reactively in SolidJS.
 *
 * @template Data - The shape of the GraphQL response data.
 * @template Variables - The shape of the GraphQL query variables.
 *
 * @param {Omit<GraphQLRequest<Data, Variables>, "key">} request - The GraphQL query and its variables.
 * @param {DocumentNode} request.query - The GraphQL query document node.
 * @param {Variables} request.variables - The variables for the GraphQL query.
 *
 * @returns {[
 *   data: Accessor<Data | null>,
 *   { fetching: Accessor<boolean>; error: Accessor<CombinedError | null>; refetch(newVariables?: Variables): void }
 * ]} - A tuple containing the reactive data state and an object with fetching state, error state, and a refetch function.
 *
 * @example
 * import { createGraphQLRequest } from "~/graphql";
 * import GetUser from "./GetUser.graphql";
 *
 * function MyComponent() {
 *   const [data, { fetching, error, refetch }] = createGraphQLRequest({ query: GetUser, variables: { id: "1" } });
 *
 *   return (
 *     <div>
 *       {fetching() && <p>Loading...</p>}
 *       {error() && <p>Error: {error().message}</p>}
 *       {data() && <p>Data: {data().myData.name}</p>}
 *       <button onClick={() => refetch({ id: "2" })}>Refetch with new ID</button>
 *     </div>
 *   );
 * }
 */

export function createGraphQLRequest<Data = unknown, Variables extends AnyVariables = AnyVariables>(
  request: Omit<GraphQLRequest<Data, Variables>, "key"> & { lazy?: boolean }
): [
  data: Accessor<Data | null>,
  {
    fetching: Accessor<boolean>;
    error: Accessor<CombinedError | null>;
    refetch(variables?: Variables): void;
    performance: Accessor<Performance>;
    lazy?: boolean;
  },
] {
  const key = getDocumentNodeKey(request.query);
  const [data, setData] = createSignal<Data | null>(null);
  const [fetching, setFetching] = createSignal<boolean>(true);
  const [error, setError] = createSignal<CombinedError | null>(null);
  const [variables, setVariables] = createSignal<Variables>(request.variables);
  const [performance, setPerformance] = createSignal<Performance>({
    executionTime: null,
    key,
    query: print(request.query),
  });

  let abortController: AbortController | undefined;
  let subscription: Subscription | undefined;

  function executeQuery() {
    const start = window.performance.now();

    batch(() => {
      setPerformance((p) => ({ ...p, executionTime: null }));
      setFetching(true);
      setData(null);
      setError(null);
    });

    if (subscription) subscription.unsubscribe();
    if (abortController) abortController.abort();

    abortController = new AbortController();
    subscription = client
      .executeQuery(
        {
          query: request.query,
          variables: variables(),
          key,
        },
        {
          fetchOptions: {
            signal: abortController.signal,
          },
        }
      )
      .subscribe(({ data, error }) => {
        batch(() => {
          if (data) setData(() => data);
          if (error) setError(error);
          setPerformance((p) => ({
            ...p,
            executionTime: window.performance.now() - start,
          }));
          setFetching(false);
        });
      });
  }

  function refetch(variables?: Variables) {
    if (variables) {
      setVariables(() => variables);
    }
    executeQuery();
  }

  onMount(function executeInitialQuery() {
    if (request.lazy !== true) {
      executeQuery();
    }
  });

  onCleanup(() => {
    if (subscription) subscription.unsubscribe();
    if (abortController) abortController.abort();
  });

  return [
    data,
    {
      fetching,
      error,
      refetch,
      performance,
    },
  ];
}
```
