### ISSUE TITLE
Make dedupExchange an embedded part of urql.

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#524]
After the conversation due to these issue https://github.com/FormidableLabs/urql-exchange-graphcache/issues/162

I think that dedupExchange should possibly be embedded into urql, since if someone removes it you have multiple queries being executed at the same time when in StrictMode

Also i don't see a reason why someone should not use dedupExchange

**Comment by kitten** [comment]
This is not "embedded" intentionally. There's different places where you may want to put the `dedupExchange` (maybe you'd event want to add it multiple times)

`urql`'s philosophy is always:

- A thin client managing the lifecycle of operations and providing the base "event hub"
- Bindings for said client for React (and `svelte`, `preact`, or whaterver really in separate packages)

That only leaves one thing **the actual implementation of fulfilling GraphQL operations**. And that's always in exchanges, so any logic apart from the two above points will always be in exchanges.

We don't want to anticipate every single use-case ourselves. When oush comes to shove and you implement your own exchange to change or add your own specific business logic or cater for your use-case, then we don't want to stand in your way with behaviour that is built-in, like in Apollo.
