### ISSUE TITLE
pollInterval doesn't wait for a response before dispatching next call

### ISSUE THREAD

**Issue by mjadczak** [FormidableLabs/urql#531]
I am using `pollInterval` with a short interval (~1s) to get a reasonably current "live view" of some data on the server (pending a better implementation with subscriptions). The other day the server experienced a slowdown in its DB access, causing it to take multiple seconds to respond to requests usually served in <50ms. I then found out that the `pollInterval` option dispatches a new request every interval, instead of waiting between successful requests, which ended up sending lots of requests to the already-under-load server. It may be that the previous request is "cancelled" when the new is dispatched, but the server is already doing the work for it.

Do you think that this is the correct behaviour, or should the interval be from the completion of one request to the start of the next request instead? I didn't look into it in-depth, but I think this behaviour could be achieved by changing `switchMap` into `concatMap` [here](https://github.com/FormidableLabs/urql/blob/master/packages/core/src/client.ts#L274). If this shouldn't be the default behaviour, would it make sense to at least make it an option?

**Comment by kitten** [comment]
Well we would have to change the semantics of `pollInterval` to then also limit all queries to a single response which may be a breaking change and which may have odd cache interactions.

In the case of `cache-and-network` for instance we can’t predict whether a query may yield one or two results.

**Comment by mjadczak** [comment]
Does the stream (callbag) of responses not get closed when all possible responses have been returned? If not, then `concatMap` as suggested would not work anyway.

**Comment by kitten** [comment]
@mjadczak There is no “list of expected responses” we could get anywhere from zero to unlimited results for a query. That’s because the stream returns updates reacting to changes in the cache as well.

I’m thinking however whether we can make the polling a background side-effect 🤔

**Comment by mjadczak** [comment]
Ah, I get you now. By "background side effect", do you mean that it would be as if something is calling the `executeQuery` function in the background on a timer? (And if that's the case, the promise returned could be used to throttle the dispatch of the next query?)

**Comment by kitten** [comment]
There's no exact timer, no, but it would probably work something like this:

```js
    if (pollInterval) {
      return pipe(
        response$,
        onPush(res => this.reexecuteOperation({
          ...res.operation,
          context: {
            ...res.operation.context,
            requestPolicy: 'network-only',
          }
        }))
      );
    }
```

**Comment by peterdemartini** [comment]
Are there any updates on the progress of this?
