### ISSUE TITLE
[exchange-graphcache] TypeScript errors in updateQuery

### ISSUE THREAD

**Issue by iamkevinwolf** [FormidableLabs/urql#537]
I am getting some TypeScript errors when trying to use `cache.updateQuery` within the`updates` object of `@urql/exchange-graphcache`.

Given the following query:

```graphql
query teams {
  __typename
  teams {
    __typename
    id
    name
    slug
  }
}
```

And the following mutation:

```graphql
mutation createTeam($team: CreateTeamInput!) {
  __typename
  createTeam(team: $team) {
    __typename
    id
    name
    slug
  }
}
```

I am not being able to compile the following cache

```typescript
const cache = cacheExchange({
  updates: {
    Mutation: {
      createTeam: (result, _args, cache) => {
        cache.updateQuery({ query: graphql.TeamsDocument }, (data) => {
          return {
            ...data,
            teams: [...data.teams, result.createTeam],
          }
        })
      },
    },
  },
})
```

Getting the following errors:

```
Argument of type '(data: Data | null) => { teams: any[]; } | { teams: any[]; __typename: string; _id?: string | number | null | undefined; id?: string | number | null | undefined; }' is not assignable to parameter of type '(data: Data | null) => Data | null'.
  Type '{ teams: any[]; } | { teams: any[]; __typename: string; _id?: string | number | null | undefined; id?: string | number | null | undefined; }' is not assignable to type 'Data | null'.
    Type '{ teams: any[]; }' is not assignable to type 'Data'.
      Property '__typename' is missing in type '{ teams: any[]; }' but required in type 'SystemFields'.
```

**Comment by kitten** [comment]
The important part here is:

> Property '__typename' is missing in type '{ teams: any[]; }'

I'm assuming TypeScript gets a little confused here. It may help to handle the case where `data` is `null`. This may happen when `TeamsDocument` has never been queried before.

I also just spotted that we may have a small mistake in our typings here. We ask for a return value of `Data | null` which must contain `__typename` but internally we are and can assume that `__typename` at that location will be `"Query"`, so it's actually not necessary. I'll see whether I can fix that.

Once you handle `null` this means that you may still have to add a default of `__typename: 'Query'` for now.

**Comment by JoviDeCroock** [comment]
Hey, this is part of the latest graphcache release! Thanks for reporting this issue

**Comment by bkiac** [comment]
I still get this error with `urql@1.10.0` and `@urql/exchange-graphcache@3.0.2`.
This is my `Cache.updateQuery` type definition:
```ts
/** updateQuery() can be used to update the data of a given query using an updater function */
updateQuery(input: QueryInput, updater: (data: Data | null) => Data | null): void;
```
