### ISSUE TITLE
operationName is not showing the query name

### ISSUE THREAD

**Issue by josteph** [FormidableLabs/urql#545]
**Describe the bug**
Following #400 , the value for `operationName` is wrongly given. It should be the query name instead of the name of operation type.

**Steps to reproduce**

```
const dummyExchange = ({ forward }) => operations => {
    return pipe(
      forward(operations),
      tap(({ operation, error = {} }) => {
        console.log(operation);
      }),
    );
};
```

**Expected behavior**
The operationName should be picked intelligently such as the name of the query being executed (as apollo client does)

**Actual behavior**
I keep getting on:

```
operationName: "query"
```

which should be expected to have the query name for the value instead, as it's more useful when debugging.

<img width="838" alt="Screen Shot 2020-02-15 at 15 09 47" src="https://user-images.githubusercontent.com/13672022/74584474-43286200-5005-11ea-979a-affba576ba31.png">

**Additional context**
Currently using:
```
"urql": "1.8.2"
```

**Comment by kitten** [comment]
This is expected behaviour and not likely to be changed. Internally for urql the `DocumentNode`’s name is irrelevant. This field is used more as an action type for us.

If you need to read the `DocumentNode`’s name you can probably extend our `debugExchange`.

Our dev tools will soon also include this information in the events tab

**Comment by josteph** [comment]
Thanks! That clarifies a lot the difference.

**Comment by kitten** [comment]
In retrospect, maybe we should’ve named it `operationType` but we want to maintain the structure of our operations stable across major versions for now 😅
