### ISSUE TITLE
How to write tests with Provider

### ISSUE THREAD

**Issue by bstro** [FormidableLabs/urql#550]
Is there any documentation for how to write tests for components that make calls to `useQuery` and `useMutation`? 

What should I use in tests since the entire app is wrapped in urql's `Provider`? In tests, I need access to that context, but I need the ability to provide it mocked data. `apollo-client` offers a `MockedProvider` which takes a `mocks` prop that I can provide mocked data, but I'm not quite sure what to do in the case of urql.

**Comment by JoviDeCroock** [comment]
Hey @bstro 

I’ve heard about [this exchange](https://github.com/mxstbr/urql-exchange-schema) being used to test. This creates your own miniature resolver. I’m thinking if we can abstract it further but personally I think it’s a good start.

Hope this helps you out, feel free to express any concerns you have with that approach.

**Comment by andyrichardson** [comment]
Funny (or suspicious) that you should ask this, keep your eyes peeled for new docs on testing some time today.
