### ISSUE TITLE
./types.d.ts missing from exchnage-graphcache

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#573]
I am trying the latest graphcache 2.2.0 and types.d.ts is missing from the build

**Comment by zenios** [comment]
I am referring to this line 

export * from './types';

inside exchange-graphcache/dist/types/index.d.ts

**Comment by JoviDeCroock** [comment]
I just noticed, seems like `TypeScript` does something funky with type-only files when specifying multiple `rootDirs`.

**Comment by zenios** [comment]
Not sure if its multiple root dirs.Populate has also multiple rootdirs and its exports are just fine

**Comment by JoviDeCroock** [comment]
Because it has no types-only file

**Comment by kitten** [comment]
This should be fixed in `@urql/exchange-graphcache@2.2.1` https://github.com/FormidableLabs/urql/releases/tag/%40urql%2Fexchange-graphcache%402.2.1
