### ISSUE TITLE
subscriptionExchange actively tears down queries which leads to no updates

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#576]
I am not sure if this is relevant to #574 but i found out that if using subscription exchange to execute all operations (Query / Mutation / Subscription) then updateQuery / writeFragment  inside update function of graphcache does not rerender the final result.

The difference with #574 is that not even updateQuery updates the component with the final result.

**Comment by zenios** [comment]
The problem is here

https://github.com/FormidableLabs/urql/blob/b8d4423e103ab94df93b675be84885a1b4930dce/packages/core/src/exchanges/subscription.ts#L88

When the operation is an actual subscription and its completed (Closed from the server) we execute a manual teardown 

In the other hand if an operation is a query || mutation then a teardown should not be executed.

**Comment by kitten** [comment]
@zenios i see! Thanks for investigating this 🙌 that’s very actionable and a patch shouldn’t be hard then

**Comment by kitten** [comment]
This should be fixed in `@urql/core@1.9.2` https://github.com/FormidableLabs/urql/releases/tag/%40urql%2Fcore%401.9.2
