### ISSUE TITLE
ShouldInvalidate on non mounted components

### ISSUE THREAD

**Issue by flexzuu** [FormidableLabs/urql#58]
Hey first of i love the simplicity of urql.

It might be that i just discovered a bug or problem in design but it might as well be that i am just dump as f*ck.
If i have 2 Connect Components one using query to get data and one using mutation to update stuff that the other component read. It seems that as long as both Components are Rendered the mutation invalidates the cache and urql refetches the needed data so everything is is sync. But as soon as the read component is mounted then unmounted while the mutation is happening the cache does not get invalidated. I don't really could test is this was the case for the internal cache invalidation but it is definitely happening with shouldInvalidate because while we are not mounted the function can't be run. I have some ideas on how to fix this maybe but i want to make sure that i did not miss understand/use urql.

**Comment by kenwheeler** [comment]
What are you thinking? Send the should invalidate down the pipes as an argument rather than rely on the component?

**Comment by flexzuu** [comment]
Yeah my idea was to pass it in the `query` or `mutation` function that applies the variables and that we can register it somewere down the pipes but i was not to sure how urql works internally.
An apollo equivalent would be something like this: 

- https://github.com/haytko/apollo-link-watched-mutation
- https://www.youtube.com/watch?v=8ZKpIB1pDw8

**Comment by kitten** [comment]
Will be fixed with v0.3 since the `cacheExchange` now invalidates independently from mounted components https://github.com/FormidableLabs/urql/commit/0c2c57cc56286f999b42ddf6a6804498543e7b71
