### ISSUE TITLE
initUrqlClient called twice browser side

### ISSUE THREAD

**Issue by addstar34** [FormidableLabs/urql#582]
I noticed that `initUrqlClient` is getting called twice browser side. It first gets called in `withUrql.getInitialProps` and then again within `withUrql`.

Maybe `urqlClient` needs to get passed down here:

```
// withUrqlClient.tsx

const isBrowser = typeof window !== 'undefined'
if (isBrowser) {
  return { ...pageProps, urqlClient }
}
```

which would then be set in the `useMemo`

**Comment by kitten** [comment]
Fixed by #589
