### ISSUE TITLE
Allow user to configure `suspense` client config.

### ISSUE THREAD

**Issue by hugo** [FormidableLabs/urql#583]
While suspense is currently experimental, Next does offer experimental support for using it (albeit without streaming SSR). However, it’s not possible to enable it with this library. At present, adding the `suspenseExchange` results in a [warning](https://github.com/FormidableLabs/urql/blob/b8d4423e103ab94df93b675be84885a1b4930dce/exchanges/suspense/src/suspenseExchange.ts#L14):
> [@urql/exchange-suspense]: suspenseExchange is currently disabled.

It should be possible to override the [default configuration](https://github.com/FormidableLabs/next-urql/blob/321328ce26fd20edb34ddd47b0576d731be96be7/src/init-urql-client.ts#L37) which is to only enable suspense on the server.

**Comment by ryan-gilb** [comment]
On it!
