### ISSUE TITLE
adding an onError prop ?

### ISSUE THREAD

**Issue by shrynx** [FormidableLabs/urql#61]
Hi, thanks for making urql, it makes using graphql a breeze.
I have a Feature Request for adding an error handler

**Feature Request**
How about adding an onError  prop to connect/ or a configuration option directly at Client maybe.
eg:
```js
<Connect
    query={query(TodoQuery)}
    mutation={{
      addTodo: mutation(AddTodo),
    }}
    onError={ error => doSomethingOnError(error) }
    children={({ loaded, fetching, refetch, data, error, addTodo }) => {
      //...Your Component
    }}
  />
```
or 

```js
const client = new Client({
  url: 'http://localhost:3001/graphql',
  onError: (error => doSomethingOnError(error))
});
```

**Usecase**
if i have access to onError, i can change route (404/500) / fire a redux action / log error message / send error to sentry.

**Possible Implementation**
possible by passing the error handler function to query and mutation
https://github.com/FormidableLabs/urql/blob/master/src/modules/client.ts#L159
https://github.com/FormidableLabs/urql/blob/master/src/modules/client.ts#L202

If this feature is to be considered, i can try making a PR

**Comment by morajabi** [comment]
That one which is directly on the client makes more sense to me.

**Comment by shrynx** [comment]
@morajabi I am not sure what do you mean by using connect HOC (are you pointing at redux, this isn't related to it). anyway i want to handle error in component but also want to have associated side effects for the corresponding error. For eg, if the page listing todo's has error, then push pack to home page or maybe 500 page.
And yes, errors like these should be handled on server-side (in an ideal world), but there are times, when server side has uncaught bugs and i want to gracefully handle them on ui.

Currently i am using `getDerivedStateFromProps ` (`componentWillRecieveProps`  has been / is getting depreciated) to check in the child component of Query if there was error or not, but for this i have to always use a class component as a child of query.
The other approach is to **throw an error** and catching it in `componentDidCatch`, enabling me to use stateless components to render result of `Query`.

**Comment by morajabi** [comment]
I'm not pointing at Redux, as I didn't mention and don't use Redux. Urql exports a `ConnectHOC` which is a HoC. 

You can gracefully handle them in UI, I think you're not quite used to the render props pattern yet, maybe. 

```
<Connect> 
({ error }) => {
  if (error) {
    return <ErrorScreen error={error} />
  }
  // ...
}
</Connect>
```

**Comment by shrynx** [comment]
@morajabi ahh i didn't know about `ConnectHOC` 😅  , will look into it. But my problem is I don't want to display error, i want to change route (for eg)

**Comment by shrynx** [comment]
i am sticking to trowing errors and catching the , thus closing the issue
