### ISSUE TITLE
next-urql@0.3.3 + @urql/exchange-suspense. How to use it properly?

### ISSUE THREAD

**Issue by nghiepit** [FormidableLabs/urql#612]
Hi guys,
 I tried the `next-urql/examples/5-with-suspense-exchange` example.
If I direct link from another page to `/` then there will be errors:
```
Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.
    in PokémonList (at pages/index.tsx:24)
```
The errors are very clear. So, How to use it properly?
Another question for`@urql/exchange-suspense`. How to use `suspense: true` for each `useQuery` in the component suspense.
Because of the `@urql/exchange-suspense` require `suspense: true` in the `urql` client config.

**Comment by kitten** [comment]
I personally haven't tried the example, so I can't tell you whether it's 100% working yet, but that being said, you'll have to add a `<Suspense>` boundary, like the error says.

> Another question for `@urql/exchange-suspense`. How to use `suspense: true` for each useQuery in the component suspense.

I don't think I get the question :sweat_smile: once you set `suspense: true` via `next-urql` then `suspense: true` will also be set on the client. Mainly the `next-urql` options are 1:1 the same as the usual `Client` options, with the exception of exchanges. To quote the docs page: https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#nextjs

> The `withUrqlClient` higher-order component function accepts the usual `Client` options as an argument.
> 
> One added caveat is that these options may not include the exchanges option because next-urql injects the ssrExchange automatically at the right location.

So as long as you follow the example's steps and add a `<Suspense>` boundary that's only active on the client-side you should be fine. Specifically you need to avoid adding `<Suspense>` on the server-side, which you can do by conditionally wrapping your page elements in it if `typeof window !== 'undefined'`

Hope that helps! :raised_hands:

**Comment by nghiepit** [comment]
Tks @kitten,
That means I will have to code:
```jsx
//pages/index.tsx
import React, { Suspense } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { withUrqlClient, SSRExchange } from 'next-urql';
import { dedupExchange, cacheExchange, fetchExchange } from 'urql';
import fetch from 'isomorphic-unfetch';
import { suspenseExchange } from '@urql/exchange-suspense';

import PokémonList from '../components/pokemon_list';

const Home: React.FC = () => (
  <div>
    <Head>
      <title>Home</title>
      <link rel="icon" href="/favicon.ico" />
    </Head>

    {process.browser ? (
      <Suspense fallback={<span>Loading...</span>}>
        <PokémonList />
      </Suspense>
    ) : (
      <PokémonList />
    )}
  </div>
);

export default withUrqlClient(
  { url: 'https://graphql-pokemon.now.sh', fetch, suspense: true },
  ssrExchange => [
    dedupExchange,
    suspenseExchange,
    cacheExchange,
    ssrExchange,
    fetchExchange,
  ]
)(Home);
```
or
```jsx
// pages/_app.tsx
const App = ({ Component, pageProps }: AppProps) => {
  return process.browser ? (
    <Suspense  fallback={<span>Loading...</span>}>
      <Component {...pageProps} />
    </Suspense>
  ) : (
    <Component {...pageProps} />
  );
};
export default App;
```
Might resolved the problem, but It get an warning error
```
index.js:1 Warning: Did not expect server HTML to contain a <div> in <div>.
    in div (at pages/index.tsx:12)
```
I'm waiting for a better solution.
