### ISSUE TITLE
Question: Passing headers in context as opts to fetcher

### ISSUE THREAD

**Issue by josteph** [FormidableLabs/urql#615]
Hi guys!

Is it currently possible to customise each query's header on the fly?

For example:
```
const [{ data, fetching: loading }] = useQuery({
    query: HomeQuery,
    context: {
       headers: {
           'custom': 1
       },
    },
});
```

Looking at apollo, looks like they are passinng the context as the second arguments to the `fetch` function (opts).

Thanks!

**Comment by JoviDeCroock** [comment]
Hey,

Yes you can pass in `fetchOptions` which can be an object or function containing `headers`, ... https://formidable.com/open-source/urql/docs/api/core/#operationcontext I saw an error in our docs I'll correct it asap.

**Comment by josteph** [comment]
Passing in `fetchOptions` means it's during initialization of the Urql client right?

Some of use cases, you might need to pass specific header in specific query call.

**Comment by JoviDeCroock** [comment]
My explanation relates to the query call where you can do

useQuery({ context: { fetchOptions } })

**Comment by kitten** [comment]
We should likely expand on this in additional sections in “Queries” and “Mutations” along the lines of `requestPolicy` being a shortcut for the context object, but the entire object being modifiable

**Comment by josteph** [comment]
I recently tried to append `fetchOptions` to `context` to each individual query, it's resulting into something weird:

<img width="626" alt="Screen Shot 2020-03-21 at 12 06 08" src="https://user-images.githubusercontent.com/13672022/77219870-73b36c80-6b6c-11ea-80ab-076d9cd7a64b.png">

It always says the cache outcome is `miss`, even though the fetchPolicy is `cache-first`.

Both using v1.8.2 or v1.9.4 are the same.

Do you guys have any idea or maybe I'm missing something basic?

**Comment by JoviDeCroock** [comment]
Could you paste in your code or reproduce it in codesandbox please?

**Comment by josteph** [comment]
@JoviDeCroock here's some minimal reproduction of it, call the `useInfiniteLoop` as a function instead.

https://codesandbox.io/s/hopeful-euler-e2gmq

**Comment by JoviDeCroock** [comment]
Yes so that's what I'm saying in that comment @josteph 

```
const useInfiniteLoop = () => {
  const [result] = useQuery({
    query: gql`
      {
        books {
          id
          name
          genre
          author {
            name
          }
        }
      }
    `,
    context: useMemo(() => ({
      fetchOptions: {
        headers: {
          "some-headers": "hello world"
        }
      }
    }, []),
  });

  return result;
};
```

**Comment by josteph** [comment]
Alright now I understood about it more now. 
Honestly wasn't quite expecting it to be like that 😅

Thanks for the explanation!
