### ISSUE TITLE
File Upload regression with @urql/exchange-graphcache 2.2.6

### ISSUE THREAD

**Issue by BjoernRave** [FormidableLabs/urql#635]
When installing the latest version of @urql/exchange-graphcache my file uploads to the apollo-server changed from looking like:

```
interface File {
  filename: string
  mimetype: string
  encoding: string
  createReadStream: () => any
}

file: Promise<File>
```

to:

```
interface File {
path: string
}

file: File
```

Now I cannot access `createReadStream` anymore and thus not pass the file to s3 to upload

**Comment by kitten** [comment]
Hiya👋

Do you have a CodeSandbox (without any API / server will do)
Also are you using `@urql/exchange-multipart-fetch` or something else for uploads?

**Comment by BjoernRave** [comment]
@kitten  I am using `@urql/exchange-multipart-fetch`. Will work on a codesandbox now

**Comment by JoviDeCroock** [comment]
That codesandbox doesn't seem to show any issues in terms of what's being sent. 
<img width="494" alt="Screenshot 2020-03-18 at 16 06 49" src="https://user-images.githubusercontent.com/17125876/76975181-7c206300-6932-11ea-843e-6d5f67b9e496.png">

Is there something I'm missing @BjoernRave

**Comment by BjoernRave** [comment]
@JoviDeCroock the problem lays in what I receive on my server.

**Comment by JoviDeCroock** [comment]
So are you saying that if you leave graphcache out with the latest urql it works or is it specific to graphcache? It's very hard for us to analyze what goes wrong since we can only see that it sends a binary in the sandbox

**Comment by BjoernRave** [comment]
@JoviDeCroock ah, seems link you found the problem. 

Thanks alot for that :)

And yes it works fine with `@urql/exchange-graphcache@2.2.5`
