### ISSUE TITLE
mjs changes broke builds using create-react-app

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#640]
After upgading to the latest urql + graphcache i get the following errors

./node_modules/@urql/exchange-graphcache/dist/urql-exchange-graphcache.esm.mjs
Can't import the named export 'buffer' from non EcmaScript module (only default export is available)

**Comment by kitten** [comment]
Well, this is great. We almost have a fix ready, but we didn't expect to have to work around this Webpack quirk 😅

**Comment by kitten** [comment]
Okay, `urql@1.9.4` and `next-urql@0.3.6` have been fixed up to account for `react` having no ESM bundle. The fixes for #636 have created a ripple effect of us trying to utilise `.mjs` and `package.json:exports` correctly and consistently and on the way we also ran into a Webpack issue. Sorry about that! 🙏
