### ISSUE TITLE
[next-urq] ReactDOMServer does not yet support Suspense

### ISSUE THREAD

**Issue by nghiepit** [FormidableLabs/urql#647]
Hi guys,

I have an example:
```jsx
const time = +new Date();

console.log(time); // 1584677644139 , 1584679644140

const [result] = useQuery({
  query: MY_QUERY,
  variables: {
    time
  }
})
```
In the server, the `console.log(time)` called twice and response two values are the difference.
So, It throws an error `ReactDOMServer does not yet support Suspense`

**Comment by kitten** [comment]
You have to keep your renders and hence variables completely consistent on the server-side.
next-urql uses react-ssr-prepass which means that we add an additional render pass on the server. This pass prefetches data using suspense before letting Next.js render the actual app.
That in turn means that if your variables change when Next.js renders, React won’t fetch your data.

This will hopefully not be a limitation in the future but for now you’ll have to be mindful of it.
