### ISSUE TITLE
[react] Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#655]
Reproduction

https://codesandbox.io/s/wizardly-wright-f42o1

This has been discussed again and fixed

https://github.com/FormidableLabs/urql/issues/493

but i think it broke again when use-sbuscription was removed

**Comment by JoviDeCroock** [comment]
I'm not seeing any errors, I just clicked the button a few times.

![image](https://user-images.githubusercontent.com/17125876/77237087-2dd6c280-6bc5-11ea-9395-3e96395ae175.png)

**Comment by zenios** [comment]
![Screenshot from 2020-03-21 23-43-15](https://user-images.githubusercontent.com/89569/77237110-e99bf000-6bcd-11ea-87a6-e76849832d65.png)

**Comment by JoviDeCroock** [comment]
Got it, your sandbox was missing the `{!data.todo.complete && <Button />}` part, was probably lagging behind for me. Thanks!

**Comment by zenios** [comment]
You are on fire :) 

Two issues both fixed in less than an hour. Congrats
