### ISSUE TITLE
Fix active teardowns stopping queries from working

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#661]
Hi All

I have a very weired issue which i cannot explain why it is happening.

It involves
1.A useQuery
2.A useSubscription (That completes from server once connected)
3.@reach/tabs :)

The query does not reach the server and data is always undefined unless i comment out the tabs component or replace it with any other component! 

See for your self

Client: https://codesandbox.io/s/focused-night-ztnmm
Server: https://codesandbox.io/s/determined-hill-5wuic

**Comment by JoviDeCroock** [comment]
The UI should not be constraining urql so I guess this could be an issue on their side

**Comment by zenios** [comment]
I understand but why does a component that has nothing to do with urql, block the execution of the query?

i.e the query goes from fetching true to fetching false without data so its not  something is blocking it.

**Comment by zenios** [comment]
Forgot to mention that query also execute successfully if useSubscription is commented. 

For these issue to appear it has to have the following things
1.A subscription that completes directly
2.A useQuery that is unmounted and mounts when subscription completes
3.A tabs component

This is the reason i said its weird

**Comment by JoviDeCroock** [comment]
Adding that does make for a valid issue yes

**Comment by JoviDeCroock** [comment]
I think you can't conditionally render those tabs, there's something weird going on if you do so.

**Comment by zenios** [comment]
So you think its a tabs issue? I found out that only adding <Tabs/> without its children will still have issues.

**Comment by JoviDeCroock** [comment]
I'm not sure, this is feels very weird. The fact that conditionally rendering this makes it hesitate kinda worries me :/

**Comment by zenios** [comment]
I also added a debugexchange and what happens is 2 query executions and 2 teardown while as if i comment tabs i get 3 executions and 2 teardown

**Comment by JoviDeCroock** [comment]
So it never establishes a connection since `execution into teardown` is a query-peek.

**Comment by zenios** [comment]
Exactly its like the useQuery hook does not execute at all after the second teardown

**Comment by JoviDeCroock** [comment]
Feels like it's the case in all urql versions as well

**Comment by zenios** [comment]
And multiple react versions

**Comment by JoviDeCroock** [comment]
Progress on diagnosing the issue, the use case is kinda weird in the sense that this happens, you start a query, due to this query starting you unmount that query and send a teardown signal.

**Comment by JoviDeCroock** [comment]
We have a fix, this was a very confusing issue but it came down to queueing and React getting into trouble with each other. A more elaborate explanation is available on #662

**Comment by zenios** [comment]
Thats great.Thanks a lot

**Comment by zenios** [comment]
One question though.why was this happening only when tabs was visible?

I.e if i had a span instead of tabs then everything was fine.

Does it have to do with provider ordering?

**Comment by kitten** [comment]
The issue only occurs with two conditions: The operation we're currently operating on must come from `reexecuteOperation` asynchronously (in this case the active teardown of the subscription), this must then lead to another hook mounting which "peeks" so in this case `useQuery` was mounted. Then the last condition is that the full update happens synchronously, and that very much depends on React's `scheduler` deciding to schedule all of this at the same time... as far as we understand.
