### ISSUE TITLE
Query does not refetch when variables change

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#668]
After upgrading to the latest @urql/core, queries stopped refetching when variables change

**Comment by JoviDeCroock** [comment]
I have tried this locally and everything works so not really much to go off atm

**Comment by zenios** [comment]
Let me try and make a sandbox

**Comment by zenios** [comment]
Ok i have some more data.

It does not work when populateExchange is added for a field. I am using it with an infinite scroller.

What happens is that when variables change ($after),  query is entered into engine but it returns directly with stale data.

![Screenshot from 2020-03-24 23-44-26](https://user-images.githubusercontent.com/89569/77479933-6ecf1100-6e29-11ea-9257-82c2d76056dc.png)

On the screenshot you can see 

- Query with key 1189792430 which has $after empty and returns valid data
- Query with key 4027465652 which is the same as 1189792430 wtih different cursor that returns data of 1189792430 as stale

Working on a sandbox as we speak

p.s:The same code used to work fine with @urql/core:1.10.5

**Comment by zenios** [comment]
That was trickier than i thought

https://codesandbox.io/s/wizardly-wright-f42o1

It requires:

1.Graphcache
2.Relay pagination
3.Pass schema to graphcache

**Comment by JoviDeCroock** [comment]
I've taken a quick look what could be going wrong here, I think I found the cause as in when a result is partial (we haven't got your new stuff yet) we `reexecute` an operation but the `key` we are observing doesn't seem to have an active operation at this time.

Without a `schema` this reexcute wouldn't happen, this could potentially mean that `cache-and-network` has an issue at this point as well.

**Comment by zenios** [comment]
Yes but why this happens only on the latest version?

**Comment by kitten** [comment]
@zenios This is basically a regression for which this operation queue was added in the first place. I've added a test to the fix above, but basically we've forgotten to "activate" the queue for the dispatched operation and instead the queue would be started for the first reexecuted operation.

- We expect `operation => result (stale) => operation (network-only) => result`.
- But instead we had `operation => operation (network-only) FILTER => result (stale)`
