### ISSUE TITLE
relayPagination and network-only

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#672]
Hi All

I have the following query
```
query FriendsQuery($after: String!) {
  me {
    id
    friends(after: $after) {
      edges {
        node {
          ...FriendshipFragment
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
```

And the following hook

```

export const useFriends = () => {
  const client = useClient();
  const [{ fetching, error, data }] = useQuery<
    FriendsQueryQuery,
    FriendsQueryQueryVariables
  >({
    query: FRIENDS_QUERY,
    requestPolicy: "network-only",
    variables: {
      after: "",
    },
  });

  const friends =
    data === undefined ? undefined : data?.me?.friends ?? undefined;

  const fetchMore = React.useCallback(
    (cursor: string) => {
      return client
        .query<FriendsQueryQuery, FriendsQueryQueryVariables>(
          FRIENDS_QUERY,
          { after: cursor },
          { requestPolicy: "network-only" }
        )
        .toPromise();
    },
    [client]
  );

  return React.useMemo(
    () => ({
      fetching,
      error,
      friends,
      fetchMore,
    }),
    [fetching, error, friends, fetchMore]
  );
```

Results are merged using relayPagination 
```
resolvers: {
  User: {
    friends: relayPagination()
  }
}
```

I have a component that does an infinite scrolling and shows all my friends. 

When the component is unmounted and afterwards remounted **i would like to fetch again the lists of friends (hence the network-only)**

The problem is that due to the relay pagination the friends variable contains all the friends fetched from the previous mount with pageInfo.hasNextPage === false.

The only request that is requested again is the initial with after === "" 

Thanks

**Comment by zenios** [comment]
I think the problem relies in the pageInfo of relayPagination. It always sets it to the last even though after the remount i have refetched the first page.

I am not sure if its wise to reset pageInfo to the currently fetched page results

**Comment by JoviDeCroock** [comment]
Hey Zenios,

Good question but this isn't really the use case of a resolver, for us it would be impossible (and a waterfall) to refetch it all.

Let me explain, if we would refetch your first page we can't eagerly refetch your second page, we would have to check the pageInfo of your first response to go for your second one and so son.

The better solution for this situation would be to make a custom hook:

```
const useRevalidatingPagination = () => {
  const [list, setList] = useState([])

  const [data] = useQuery(query);

  useEffect(() => {
    if we go from fethcing to not fetching 
      addToList
  }, [data]);

  return list;
}
```

So now we have a list that resets every time you navigate back, when you query you will receive the result with a stale flag so you can wait until it gets revalidated.

**Comment by zenios** [comment]
I dont expect urql to refetch all.

What i expect though is once the results are merged via relayPagination pageInfo should show the latest updated pageInfo not the last fetched from the previous results.

**Comment by zenios** [comment]
TO be more clear

Fetch page 1 results should be edges:[...page1] pageInfo:page1PageInfo

Fetch page 2 results should be edges:[...page1,...page2] pageInfo:page2PageInfo

Unmount / remoount and network only

Fetch page 1 results should be edges[...page1,...page2] pageInfo:**page1PageInfo**

while know its page2PageInfo

Hope its clear

**Comment by kitten** [comment]
The `pageInfo` is merged like all the pages are, so it'll appropriately merge the beginning and end bits.

Because you can fetch pages in "both directions" (after / before) we account for that and create a new `pageInfo` based on that. https://github.com/FormidableLabs/urql/blob/51ae6806a6adf5a9fc7f17c43ca2dbe066f9c9c3/exchanges/graphcache/src/extras/relayPagination.ts#L200-L214

So it will follow the logic you're describing, but unmount/remount is not what you're expecting here. Instead the result is identical no matter what page you ask for currently. We're thinking of maybe filtering it down, but that'd be an additional option on the resolver.

That being said even if you ask for the "first page" you'll get a result based on _all the pages_ that Graphcache knows about.

**Comment by zenios** [comment]
That is understood but the way relayPagination is structtured right now there is no way once the whole list is fetched to refetch it (Throught the whole applications lifecycle)

Lets take facebook for example. If i view friends list once then go to another page and go back to friends list the full cycle is executed from the beginning while us with relayPagination i cannot do that.

**Comment by kitten** [comment]
You could try to write a resolver that's _similar_ to `relayPagination`, I suppose, that is more strict. So you could _walk_ the pages in the cache using `pageInfo` explicitly (by using `endCursor` as the input for `after` for instance) which means that if you refetch (using `network-only` or `cache-and-network`) the chain of pages can be broken by an earlier page changing.

**Comment by zenios** [comment]
The problem is that i didnt find a way to know which page was the last refreshed / fetched

**Comment by kitten** [comment]
I don't think you'll ever have to check which page was last fetched. The resolver just needs to get the requested page for your use-case and then "walk backwards" (so use the input arguments e.g. use the `after` cursor and find the page that has `endCursor` set to that).

When you're missing a page you can set `info.partial = true` to fetch the other pages. And when you don't have your current page you can either return the previous ones and set partial or just return undefined for a cache miss.

**Comment by zenios** [comment]
Thanks a lot

**Comment by kitten** [comment]
@zenios I’ll think about how much sense it makes to integrate this into the `relayPagination` helper btw 😇 it may just be very specific 😅

**Comment by zenios** [comment]
Think about it.my only concern is what i said before.once you use relay
pagination forget about refreshing. You have to *hack* your way around it

**Comment by zenios** [comment]
As for the very specific, I dont think i am the only person who want to use relayPagination with cache-and-network || network-only

**Comment by lemes** [comment]
I'm having what I think is the same problem described here. @zenios did you end up finding a solution/workaround?

**Comment by zenios** [comment]
Nope i did the merging manually without using relayPagination

**Comment by wenerme** [comment]
Feel sad, I think I have to manually merge the result too.

**Comment by taneba** [comment]
> if you refetch (using network-only or cache-and-network) the chain of pages can be broken by an earlier page changing.

I have an issue probably related to this behavior, I mean lack of data after refetch. 
Imagine the case of fetch page1, page2 , and add an item, and then fetch again. 

1. fetch page1: `[{id: 10}, {id: 9}, {id: 8}]`
2. fetch page2: `[{id: 10}, {id: 9}, {id: 8}, {id: 7}, {id: 6}, {id: 5}]`
3. add item `{id: 11}`
4. fetch page1, page2:  `[{id: 11}, {id: 10}, {id: 9}, {id: 7}, {id: 6}, {id: 5}]`
so item of `{id: 8}` is gone in the paginated list.

Ideally I want step 4 to be `[{id: 11}, {id: 10}, {id: 9}, {id: 7}, {id: 6}, {id: 5}]` but at least I don't loose `{id: 8}`. 
So I want to ask is there any way to clear or invalidate entire cache of the paginated query?

@kitten

**Comment by taneba** [comment]
After investigation, I found that I could invalidate all paginated query like in the example of invalidating-individual-fields in the doc. That way I won't loose the data in between pages.

https://formidable.com/open-source/urql/docs/graphcache/cache-updates/#invalidating-individual-fields
