### ISSUE TITLE
SchemaLink equivalent for SSR?

### ISSUE THREAD

**Issue by leebenson** [FormidableLabs/urql#679]
Apollo has something called [schema-link](https://www.apollographql.com/docs/link/links/schema/), which allows queries running on the server to execute against schema locally, instead of passing the request through HTTP back to itself.

Just curious if urql has an exchange to support that pattern yet, or if there are any plans for it?

Thanks for a great lib!

**Comment by kitten** [comment]
We're indeed looking to get that published :tada: It'll be called `@urql/exchange-execute` (although we may change the name before publishing? it's not final yet) https://github.com/FormidableLabs/urql/pull/474

**Comment by kitten** [comment]
This has now finally been released! :tada: https://github.com/FormidableLabs/urql/tree/master/exchanges/execute
