### ISSUE TITLE
useQuery unexpectedly refetching data

### ISSUE THREAD

**Issue by bolandrm** [FormidableLabs/urql#686]
urql version & exchanges:   1.9.5   / default exchanges

**Steps to reproduce**

I have defined a query and mutation like so:

```
    useEffect(() => {
      console.log('mounting')
    }, [])

    const [{ fetching, data: offeringData }] = useQuery({
      query: `{
        me {
          bakery {
            offerings(offeringType: bakedGood) {
              id
              name
              selected
            }
          }
        }
      }`,
    })

    const [{}, updateOffering] = useMutation(UPDATE_OFFERING)
```

The `useQuery` query is fetched when the component mounts (i see the `'mounting'` text from the `useEffect`).  When I call the `updateOffering` function of the mutation, the `useQuery` query is re-fetched.  

From reading the documentation, i expect this query to never be refetched since the query never changes.  I have put the `useEffect` call in there to ensure that the component isn't remounting or anything weird like that.  I only see the `remounting` text once.

**Expected behavior**

I expect that the query would never be refetched, as the query never changes and there are no variables.

**Actual behavior**

The `useQuery` reruns (and hits the server) when the `updateOffering` function is called.

My client looks like this:

```
export const client = createClient({
  url: Configuration.apiUrl,
  fetchOptions: () => {
    return {
      headers: { authorization: jwt ? `Bearer ${jwt}` : '' },
    }
  },
  // requestPolicy: 'network-only',
  // exchanges: [dedupExchange, cacheExchange, errorExchange, fetchExchange],
})

```

note, i would like to use `network-only`, but it doesn't matter if that's commented out or not.

**Comment by bolandrm** [comment]
Here's a reproduction:

https://codesandbox.io/s/lively-leftpad-bz38d?file=/src/components/Todos.js

If you look at the network log, you'll see that both the mutation AND the query are executed when the button is clicked.

**Comment by JoviDeCroock** [comment]
This is intended behavior of the default cache as documented, your mutation mutates an entity of type offering so the cache will trigger refetches for observed offerings.

If you don’t want this you can look at graphCache, this will not referch but update the offering if the id matches up with the received response.

**Comment by bolandrm** [comment]
Thanks - is there any way to disabled this automatic refetch behavior?  Ideally, i'd like the following:

- Never auto refetch
- `requestPolicy: 'network-only',`

**Comment by JoviDeCroock** [comment]
You can remove the `cacheExchange` by not specifying it in your `client.exchanges`.

**Comment by kitten** [comment]
@bolandrm If you don't need any caching, just leave out the `cacheExchange` like so: https://codesandbox.io/s/clever-river-lpgl7?file=/src/index.js

**Comment by bolandrm** [comment]
Ah, perfect, thanks!
