### ISSUE TITLE
Testing a mutation

### ISSUE THREAD

**Issue by Matth10** [FormidableLabs/urql#691]
I have a mutation like so.
```javascript
const [addItemResult, addItem] = useMutation(addItemMutation)

//....

const addItemToCart = async () => {
 const {error} = await addItem(variables)
} 
```
So I trigger this mutation when the user submit the form. So pretty basic here.

Next I tried  to test the mutation by mocking the the `executeMutation` function. In the documentation it suggest to do something like this `executeMutation: jest.fn()`.  
However this was causing an error: `TypeError: Cannot read property 'length' of undefined` triggered by the function `Object.toPromise` from `wonka`

Dependencies
```json
{
"urql": "^1.9.6"
"wonka":  "^4.0.9",
"jest": "^25.3.0",
"@testing-library/react": "^10.0.2",
}
```
**Steps to reproduce**
Reproduce the example of the documentation. I used `react-testing-library` instead of `enzyme`
```javascript
const mockClient = {
 executeMutation: jest.fn()
}

it('triggers a mutation', () => {
  const { getByText,  getByTestId } = render(
    <Provider value={mockClient}>
      <MyComponent />
    </Provider>
  );
  const variables = {
    name: 'Carla',
  };
  fireEvent.change(getByTestId('input'), { target: { value: variables.name } })
  fireEvent.click(getByTestId(button'))
  expect(mockClient.executeMutation).toBeCalledTimes(1);
  expect(client.executeMutation.mock.calls[0][0]['variables']).toMatchObject(variables)
});
```

**Solution**
I came over this problem by doing this: ```executeMutation: jest.fn(() => empty)``` So my mock function returns an empty stream which is completed immediately. So I don't know if the best solution and if the documentation needs to be updated or not.

**Comment by kitten** [comment]
Hiya 👋

Thanks for raising this!
It does mention this further down on the documentation page, but I agree that it’s very unclear: https://formidable.com/open-source/urql/docs/advanced/testing/#response-success

Optimally all the code samples on this page should be explained better, and `fromValue` should be explicitly highlighted, and a section on subscriptions and mutations should be added, despite the testing strategy there not being different.

This is a new page in our docs, so I did expect it to be a little rough around the edges 😅

**Comment by Matth10** [comment]
Thanks @kitten. I'll propose a PR for the changes. I'm not fluent in English so you'll might need to change a thing or two 😄 .
