### ISSUE TITLE
Unable to invalidate null Connection type

### ISSUE THREAD

**Issue by olistic** [FormidableLabs/urql#693]
```
urql@1.9.6
@urql/exchange-graphcache@2.3.1
```

**Steps to reproduce**

1. Have a Connection type following the [spec](https://relay.dev/graphql/connections.htm) and a mutation that creates a Node type.

```graphql
type Query {
  exercisesConnection(page: PageInput!): ExercisesConnection
}

type Mutation {
  createExercise(input: CreateExerciseInput!): CreateExerciseResult
}
```

2. Configure the Graphcache's `cacheExchange` so that when creating a Node type, all queries for the corresponding Connection type (i.e. the different pages) are invalidated:

```js
cacheExchange({
  updates: {
    Mutation: {
      createExercise: (_result, _args, cache) => {
        cache
          .inspectFields({ __typename: 'Query' })
          .filter(({ fieldName }) => fieldName === 'exercisesConnection')
          .forEach(({ fieldName, arguments: args }) => {
            cache.invalidate('Query', fieldName, args);
          });
      },
    },
  },
})
```

3. Query the first page for which there are no results:

```graphql
query {
  exercisesConnection({ page: { after: null, first: 10 } }) {
    ...
  }
}
```

This returns `null` for the `exercisesConnection` field as there are no exercises:

<img width="720" alt="Screen Shot 2020-04-11 at 21 45 20" src="https://user-images.githubusercontent.com/5600126/79057973-bfbe7200-7c3d-11ea-97d8-9157b50d2691.png">

4. Execute the mutation and return to the list view.

**Expected behavior**

The query for the first page (3) results in a cache miss and a new request is made to the server, populating the list with the newly created exercise.

**Actual behavior**

The query for the first page results in a cache hit, and the list remains empty.

If the page is refreshed, the new exercise appears:

<img width="724" alt="Screen Shot 2020-04-11 at 21 51 04" src="https://user-images.githubusercontent.com/5600126/79058016-8d614480-7c3e-11ea-9ba5-c9d7d6979379.png">

The curious thing is that, at this point, if a second exercise is created, the cache is properly invalidated and the query is re-executed upon visiting the list view.

I'm gonna work on a reproduction ASAP, but figured I'd open this in the meantime just in case it's obvious what I'm doing wrong.

Thanks!

**Comment by olistic** [comment]
If I add the following logging lines:

```diff
@@ -19,7 +19,10 @@ const cacheOptions = {
      .inspectFields({ __typename: 'Query' })
      .filter(({ fieldName }) => fieldName === 'exercisesConnection')
      .forEach(({ fieldName, arguments: args }) => {
+       console.log(`Invalidating Query.${fieldName} with following args:`, args);
+       console.log('Pre:', cache.resolve('Query', fieldName, args));
        cache.invalidate('Query', fieldName, args);
+       console.log('Post:', cache.resolve('Query', fieldName, args));
      });
  },
},
```

**Console after creating the first exercise**

<img width="719" alt="Screen Shot 2020-04-11 at 22 00 21" src="https://user-images.githubusercontent.com/5600126/79058112-d82f8c00-7c3f-11ea-8bb4-155e8ffa1107.png">

**Console after creating the second exercise**

<img width="722" alt="Screen Shot 2020-04-11 at 22 02 49" src="https://user-images.githubusercontent.com/5600126/79058130-32c8e800-7c40-11ea-826e-4baf283e08b0.png">

**Comment by JoviDeCroock** [comment]
hey @olistic 

Thank you for the awesome explanation, I found the cause and there's a PR up.
