### ISSUE TITLE
graphql js stuff in final bundle

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#698]
**Steps to reproduce**

I'm trying "@urql/svelte": "0.1.3" and it works great!

**Expected behavior**

I'm also using `babel-plugin-graphql-tag` and it work if I remove `urql` (using let's say Apollo with the same queries).

**Actual behavior**

If I just add `initClient()` in my `App.svelte` the final bundle contains `graphql` js too in it (42 KB!).

![image](https://user-images.githubusercontent.com/41120635/79362772-4bd6df00-7f47-11ea-9c18-8a50798d600f.png)

How to fix it?

**Comment by kitten** [comment]
I’ve created an experiment branch that attempts to crunch down the size of what we’re importing: https://github.com/FormidableLabs/urql/pull/700

This will only have an effect if tree-shaking isn’t fully removing some parts of the GraphQL package.

Overall we may see a slight decrease in the minzipped size. You can test the above change by installing the test packages that CodeSandbox CI has created for the PR 📬

**Comment by kitten** [comment]
Closing this for now since #700 does as much as we currently can :heart:

If you have any more questions regarding this though feel free to leave some questions in more comments 🙌

**Comment by frederikhors** [comment]
I created two identical projects:

- one with `@urql/svelte`: https://github.com/frederikhors/svelte-urql-app

- one with `svelte-apollo`: https://github.com/frederikhors/svelte-apollo-app

**URQL size is amazing!**

### Final bundle sizes:

- **@urql/svelte**: 66 KB!

- **apollo**: 147 KB!!! (116 with a "trick" I'm going to tell you...)

`urql` can still be better than 66 KB!

### HOW:

In this commit: https://github.com/frederikhors/svelte-apollo-app/commit/a0924f14bd7619964e5a508a6f53012bf6818a15 I added the magic: https://github.com/gajus/babel-plugin-graphql-tag.

With it (and Babel, of course) **apollo** drops from 147 KB to 116 KB!

Unfortunately **@urql/svelte** doesn't seem to care!

So my question: WHY?

**Additional context**

I also published the two `source-map-explorer` reports:

- `@urql/svelte`: https://github.com/frederikhors/svelte-urql-app/blob/master/README.md

- `svelte-apollo`: https://github.com/frederikhors/svelte-apollo-app/blob/master/README.md

As you can see the difference is `graphql` package:

- `@urql/svelte`: 41.2 KB (with parser.mjs, lexer.mjs, printer.mjs, visitor.mjs, kinds.mjs, printLocation.mjs, etc.)

- `svelte-apollo`: 10.5 KB (only with printer.mjs, visitor.mjs)

Is this how it should be?

Can we remove from `@urql/svelte` all that 30,7 KB ?!

_I hope you will appreciate the love I have for Urql and Svelte._

**Comment by JoviDeCroock** [comment]
The main part why these are still included is because we don't enforce the usage of `graphql-tag` as you can see here https://github.com/FormidableLabs/urql/blob/master/packages/core/src/utils/request.ts#L21

This won't bee tree-shaken out since it's a runtime process

**Comment by kitten** [comment]
Yes, the difference is mostly that Apollo now enforced the usage of `graphql-tag`. They even export the `gql` tag themselves.

But `urql` also supports just passing in the query trying directly (which is actually used really frequently) without `graphql-tag`

So that means we always include `parse` from `graphql`
