### ISSUE TITLE
svelte: previous data undefined on variable update

### ISSUE THREAD

**Issue by cdock1029** [FormidableLabs/urql#706]
Unlike with the react version of library, when updating variable components of query, the current data (before request returns) is no longer present but is `undefined`. So only relying on `fetching` is possible and thus we get a flash of content, having to branch off of fetching / not fetching alone.

I would like to do this pattern to only show top-level loading when there is no (previous) data.

```svelte
{#if $result.fetching && !$result.data}
    <Loading />
{:else}
<!-- show data UI -->
   <!-- some data table, etc -->    
  
  <!-- subsequent queries with new data can show loading state within the UI, not top level -->
  <Pagination>
    <button>Prev</button>
    <button>Next</button>
    {#if $result.fetching}
      <Loading/>
    {/if}
  </Pagination>
{/if}
```

urql version: `@urql/svelte@0.1.3`

**Expected behavior**
svelte version works like React

**Actual behavior**
data is reset to undefined each time variables change
 
React: (expected)
https://codesandbox.io/s/nervous-herschel-wqpz0?file=/src/Page.js

Svelte: (data undefined)
https://codesandbox.io/s/affectionate-euclid-25gxp?file=/page.svelte

I'm new to this library, but just tested this out with React and it works as I'm expecting. It is likely that hooks caching intermediate values doesn't map 1:1 with the svelte observable code.. or something.

**Comment by kitten** [comment]
We tried to implement this before but it doesn’t seem possible in Svelte unless we’d somehow break out of the store patterns.

When stores change they’re reinitialised without any prior state. So we’d need a primitive that allows us to maintain component-wide state to make this work

**Comment by cdock1029** [comment]
Yea I figured as much... run into this sort of thing a lot with svelte. It can be kinda "solved" by using a component and handling the subscription/updates within it, but it doesn't compose as well as a top level "hook".

**Comment by frederikhors** [comment]
@cdock1029 the people who work at Svelte are always very kind and quick to respond in the issues of the project on Github.

What do you think if we ask for their opinion?

But we would need a minimal REPL of the problem using https://svelte.dev/repl.

**Comment by kitten** [comment]
I'm currently looking into this and our options are to read the prior state; we explored a hooks like option, but the compiler is very clever and stores are only called for an update, when their inputs have actually changed using a dirty-flag in the component's internal state at `component.$$.dirty`.

So we could read the prior state by looking in-order at `$$.dirty` and `$$.ctx` but that seems like something that'd break easily.

The alternative would be to propose a new store primitive that is IO (input-output based) which receives signals for when the store function has updated, or which receives it's previous state on an update. (i.e. the store function becomes a reducer over its input with its own prior output)

**Comment by cdock1029** [comment]
As described in that issue above, derived store does get us much closer. Seems to cover the internal updates part of it.

For me the key insight was you can write a function that won't get called every time, to setup your stores

I made a slight tweak to example to think about how to handle external changes to props.

https://codesandbox.io/s/lucid-paper-t8l4j?file=/page.svelte

Either you keep the store in tact and update prop variables imperatively, or recreate the entire store based on prop changes. Still the division between stored declarative values that get thrown away or imperative partial updates..

**Comment by kitten** [comment]
Given the amount of things that can be input though it’d comical to make all of them just assignable 😅

I’ve also played around with separating the store creation from the subscribable, but all of these options seem to me like rather leaky  abstractions

**Comment by cdock1029** [comment]
If you guys have something that serializes queries, maybe

```svelte
$: myQuery = query({query: SOME_QUERY, variables: {a, b, c}})
```
can be a layer around a context lookup, keyed by serialized query that looks for created store or creates it, then returns. So won't be re-created every time if already exists, just retrieved.

Maybe ctx isnt necessary just that a place to store 'store' reference

or if `query(..)` didn't return a store but some just some object. Reactivity handled by declaration. Can just run function:

```svelte
$: myQuery = query({query: SOME_QUERY, variables: {a, b, c}})

// the stores are inside
{myQuery.$fetching}
{myQuery.$data}
```

eh. I'm starting to understand hooks design actually. keying by query not necessary. keying by "this" component is all we really want, and if possible counting the calls to `query(..)` just to return the right store if we had multiple queries.

**Comment by frederikhors** [comment]
I was looking at `svelte-apollo` code.

Can the `readable` store here: https://github.com/timhall/svelte-apollo/blob/master/src/query.ts#L61 have anything to do with it?

**Comment by kitten** [comment]
@frederikhors the problem boils down to how store functions work. A new input leads to a new call, which leads to a new store, which means the previous state is gone.

Basically I’d love to preserve the functional nature (like with React hooks) _and_ have it retain some state, but that doesn’t seem easily doable without hacking into the Svelte internals right now
