### ISSUE TITLE
next-urql: ctx in clientConfig undefined during ssrPrepass

### ISSUE THREAD

**Issue by nickrttn** [FormidableLabs/urql#707]
When `ssrPrepass` is ran in the `getInitialProps` function of the `withUrql` HOC, the clientOptions are initialized without app or page context.

This is an issue because I am passing an API token through to a GraphQL endpoint by including it in the request headers. During the SSR prepass phase, the endpoint will not receive a token and will not return the data I'm expecting for the current user.

urql version & exchanges:

- `next-urql@^0.3.6`
- `urql@^1.9.6`
- default exchanges

**Steps to reproduce**

1. Clone and run the reduced test case at https://github.com/nickrttn/next-urql-test-case
2. Take a look at the server logs

**Expected behavior**

I would expect `AppOrPageContext` to be available during all stages of server-side rendering so the environment can be configured correctly.

**Actual behavior**

During the prepass phase, the AppTree component does not receive a preconfigured client or the correct options for the `clientConfig` function, causing it to create a new client in the `useMemo` hook of the `withUrql` render function. That client is not configured correctly when `ctx` is used in the `clientConfig` function.

**Comment by kitten** [comment]
@parkerziegler I believe we've seen something like this before, right? Could it be that we simply forgot a case for how `clientConfig` is called?

**Comment by parkerziegler** [comment]
Ah! I think I know what may be happening. `console.trace` is a good friend for this case; I'll put up a PR shortly that I think ought to fix this. Thanks @nickrttn for the reproducible test case 🚀 It makes our lives a lot easier.

**Comment by nickrttn** [comment]
> Thanks @nickrttn for the reproducible test case 🚀 It makes our lives a lot easier.

Glad I could help, and thanks for fixing this so quickly!
