### ISSUE TITLE
Unable to parse some scalar values for fieldKey

### ISSUE THREAD

**Issue by olistic** [FormidableLabs/urql#717]
```
urql@1.9.6
@urql/exchange-graphcache@2.3.1
```

**Steps to reproduce**

1. Define a field that uses the [`DateTime`](https://github.com/excitement-engineer/graphql-iso-date#datetime) type for an argument:

```graphql
type Query {
  timetable(from: DateTime!, to: DateTime!): [Session!]!
}
```

2. Query that field with the DateTime args:

```graphql
query {
  timetable(from: 2020-04-13T03:00:00.000Z, to: 2020-04-20T02:59:59.999Z}) {
    ...
  }
}
```

3. In a Graphcache Custom Update, try to inspect the `Query` fields:

```js
cache.inspectFields({ __typename: 'Query' })
```

**Expected behavior**

You get the `timetable` field with the used args:

```js
[
  { fieldName: 'timetable', arguments: { from: '2020-04-13T03:00:00.000Z', to: '2020-04-20T02:59:59.999Z' }, fieldKey: 'timetable({"from":"2020-04-13T03:00:00.000Z","to":"2020-04-20T02:59:59.999Z"})' },
]
```

**Actual behavior**

`fieldInfoOfKey` throws:

```
SyntaxError: Unexpected number in JSON at position 12
```

at this line:

https://github.com/FormidableLabs/urql/blob/522736606028fafcb8a313b2b2c3160a6400a852/exchanges/graphcache/src/store/keys.ts#L13

when trying to parse:

```
{"from":2020-04-13T03:00:00.000Z,"to":2020-04-20T02:59:59.999Z}
```

This is because `2020-04-13T03:00:00.000Z` is not a valid JSON value.

**Further comments**

I fixed this by calling `.toString()` on the dates before passing them to `urql` which also works with the DateTime type.

**Comment by kitten** [comment]
Sorry, I think we need more information here. Having non-scalar values in a query is not GraphQL-compliant, i.e. that's not a valid GraphQL query.

So a subsequent parse reveals that this doesn't parse:

```js
import gql from 'graphql-tag';

gql`
	query {
	  timetable(from: 2020-04-13T03:00:00.000Z, to: 2020-04-20T02:59:59.999Z}) {
	    ...
	  }
	}
`; // Syntax Error: Invalid number, unexpected digit after 0: "4".
```

This I would expect; but I'm wondering how this has been parsed then in the first place?

**Comment by olistic** [comment]
I think you already figured it out, but yeah, [`DateTime`](https://github.com/excitement-engineer/graphql-iso-date#datetime) is a scalar type defined on the server.

**Comment by kitten** [comment]
What threw me off mostly is that the query you had there is invalid 😅  But I did realise afterwards that this affects only the internal data in Graphcache
