### ISSUE TITLE
svelte: client.reexecuteOperation queuing is not effective

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#721]
`@urql/svelte: 0.1.3`
`@urql/exchange-graphcache: 2.3.3`

**Steps to reproduce**

1. go on [fullscreen REPL](https://m6wj9.csb.app)

1. click on "Posts"; let it load...

1. now open browser Dev Tools

1. reload page (the /#/posts one)

1. in Dev Tools Network tab there is no call to https://graphqlzero.almansi.me/api

1. (it's the same on my localhost, not a codesandbox fault)

**Expected behavior**

I expect to immediately see the cached data (it works!) and then a call to API for the `network` part of `cache-and-network`.

**Actual behavior**

There is no call to API when I refresh the page with that component.
If I instead navigate to that page everything works.

_[Codesandbox project](https://codesandbox.io/s/urql-svelte-cache-and-network-on-reload-m6wj9)._

**Comment by kitten** [comment]
I just tested your Sandbox and it seems to work correctly.

I did notice that your "Steps to reproduce" call for a reload, but step `5.` seems incorrect. You only have your query on the `/posts` page, but when I reload I'm on `/home` which doesn't load this query. So is this simply the problem of the app not starting out with the query when the app is reloaded?

**Comment by frederikhors** [comment]
A gif(T) for you! 😄 

![123456](https://user-images.githubusercontent.com/41120635/79771616-56222000-832f-11ea-9c5e-af5d717429d4.gif)

**Comment by kitten** [comment]
This seems to be a weird interaction between how the subscriptions are called in Svelte and how our operation queuing is working. This will need some time to be fixed, since I don’t know what the root cause is.

In the meantime, you should be able to work around this by removing the `dedupExchange`

**Comment by kitten** [comment]
This took us a really, really, _reaaallly_ long time to debug, since it was so elusive to debug and think about the timing here 😓
