### ISSUE TITLE
exchange-graphcache: 2.3.4: Uncaught TypeError: y is not a function

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#723]
`@urql/exchange-graphcache: 2.3.4`

Just updated from `2.3.3` and BOOM! 💥

![image](https://user-images.githubusercontent.com/41120635/79782266-17946180-833f-11ea-8544-c33c22119507.png)

![image](https://user-images.githubusercontent.com/41120635/79782370-3eeb2e80-833f-11ea-9770-b0998333d241.png)

Updates follow.

**Comment by frederikhors** [comment]
Simple REPL here: https://codesandbox.io/s/urql-svelte-broken-exchange-graphcache-234-hjt10

**Comment by JoviDeCroock** [comment]
You'll have to update `@urql/core` and it won't be an issue

**Comment by frederikhors** [comment]
OK. So I think also here we need a change: https://github.com/FormidableLabs/urql/blob/master/packages/svelte-urql/package.json, right?

**Comment by JoviDeCroock** [comment]
Yes, thought it would've done this automatically but it just turns  out it didn't

**Comment by frederikhors** [comment]
Yes, me too. Because of `"@urql/core": "^1.10.8",`. I'm reinstalling all in my project now to try.

**Comment by frederikhors** [comment]
After re-install it works anche in package-lock I can see new core. I hate npm. Thanks anyway. 😄

**Comment by JoviDeCroock** [comment]
Thanks for making us aware of this and have a nice day :)

**Comment by frederikhors** [comment]
Maybe we should reopen this to update @urql/svelte package.json?

**Comment by kitten** [comment]
Sorry about this! I finally found what caused our broken builds and #734 fixed it. That's released as `@urql/core@1.11.4` and `@urql/exchange-graphcache@2.3.8`. The broken releases have been marked as deprecated (or deleted where possible) on npm.
