### ISSUE TITLE
svelte: mutate in a try catch

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#756]
Using `@urql/svelte` I cannot use this simple code:

```js
mutate({
  query: DELETE_TODO,
  variables: { id: todoID }
})
```

The mutation doesn't start at all.

It just works like this:

```js
mutate({
  query: DELETE_TODO,
  variables: { id: todoID }
}).then()
```

or like this:

```js
async function callMutation() {
  await mutate({
    query: DELETE_TODO,
    variables: { id: todoID }
  })
}
```

but I wanna use the first one in a `try {} catch {}`.

Is it possible?

**Comment by kitten** [comment]
> The mutation doesn't start at all.

I’ll take a look at that, that seems unusual;

> but I wanna use the first one in a try {} catch {}.

I assume you mean an async-try&catch with a wait? That shouldn’t be necessary as that promise never rejects

**Comment by frederikhors** [comment]
I honestly don't want to use "try catch" at all.

Since I'm handling errors globally (in a custom exchange) it would be great to have such a thing in my components:

```js
mutate({
  query: DELETE_TODO,
  variables: { id: todoID },
  errorMessage: `Something bad happened while you were trying to clear todo: ${todoID}.`
})
```

and then globally I can show this message and not only the `[Graphql]` Combined Error Message "generic" one.

What do you think about?

Now I'm using it like this:

```js
mutate({
  query: DELETE_TODO,
  variables: { id: todoID }
}).then(result => result.error && alert(`Something bad happened while you were trying to clear todo: ${todoID}.`))
```

But now I have two alert (this one and the one in custom exchange which prints combined error message) and more code to write.

Am I brutally wrong?

**Comment by kitten** [comment]
> I'm handling errors globally (in a custom exchange)

If you already have a global error exchange, what is it you’re trying to achieve?

Locally you call `mutate`, so all you want to do then surely is ignore errors? That would only require you to check for `res.error`.

You could also swallow the error in the global error exchange, by transforming the mutation results to `data: null, error: undefined`. Then locally errors aren’t possible.

Either way, locally it seems that you can also just ignore the result, if there’s nothing you’re doing with it.

**Comment by frederikhors** [comment]
### FIRST

The problem I have now (which is the reason for this isuee) is that I cannot use this simple code:

```js
mutate({
  query: DELETE_TODO,
  variables: { id: todoID }
})
```

### SECOND

For errors, the problem is I get error codes form server (like `0x015248A5`).

So in my custom "Errors" exchange - globally - I'm using a temporary `alert(err.message)` (there are other friends who are in charge of implementing notifications).

And in my single components - locally - I need to "handle" that error code translating it in human error.

From this need the [previous question](https://github.com/FormidableLabs/urql/issues/756#issuecomment-619604487).

**Comment by kitten** [comment]
The lazy promise was a mistake based on some assumptions so that shouldn’t be hard for us to fix (meanwhile you can just use async-await or call `then` as you discovered.

Are you putting your error codes in extensions? If so you can identify your errors using `res.error.graphQLErrors.some(x => x.extensions.code === A_CODE)` where you define `extensions.code` or some other property

**Comment by kitten** [comment]
The issue of lazy promises has been fixed; as per the global error exchange, I suppose if you already have one there isn't much special to consider here? I'll close for now but I think you had another thread going on Spectrum about this, right? :) https://github.com/FormidableLabs/urql/pull/758
