### ISSUE TITLE
Resolving a cache item using non-id key

### ISSUE THREAD

**Issue by andrewmclagan** [FormidableLabs/urql#762]
> using `latest` versions.

Attempting to resolve items from the cache without knowing the id field. We use `uuid` for various reasons on the frontend and within `urql` although when actually fetching or mutating we send the `id` of the entity. 

```javascript
cacheExchange({
  keys: {
    User: data => data.uuid,
    Activity: data => data.uuid,
    Role: data => data.uuid
  },
  // ...
});
```

When doing an optimistic update on an `Activity` entity I cannot workout how to resolve the activity by its original `id` attribute? e.g.

```javascript
cacheExchange({
  keys: {
    User: (data) => data.uuid,
    Activity: (data) => data.uuid,
    Role: (data) => data.uuid,
  },
  optimistic: {
    updateActivity: (variables, cache, info) => {
      // always null
      const cachedActivity = cache.resolve({
        __typename: "Activity",
        id: variables.id,
      });
      // error occurs...
      return {
        __typename: "Activity",
        id: variables.id,
        ...cachedActivity,
        ...variables.input,
      };
    },
  },
});
```

Always returning null?

Is it possible to `cache.resolve()` an entity via another identifying field thats not one of the `id`, `_id` or `data => data.custom` fields / methods? This could be helpful i many circumstances

**Comment by kitten** [comment]
It’s not possible to resolve items when the key can’t be generated. All items are normalised and indexed by the customisable key;

In theory we may make it possible in the future to list all entities of a certain type, but even then; that’d be an expensive operation for what’s essentially a GET.

The question I guess is, why do your `uuid` fields exist? Are they generated on the client-side and if they’re essentially only created on the front-end and are not concrete keys, why are they used for keying? It’d seem to me like they’d essentially break normalisation, since they’re random.

**Comment by andrewmclagan** [comment]
I figured as much. Thank you for clarifying.

To answer your question, we are simply using `uuid` to a unique identifier we can generate and guarantee on the front-end. They are globally unique in the database. We can still use them on the backend as they are indexed. 

I think we will expose the GraphQL api to use them as the single and only identifier and use the natural database `id` on the backend internally, behind the GraphQL layer.

**Comment by kitten** [comment]
That makes a lot of sense to me and seems like it’d solve the problem. Unfortunately most use-cases revolve around having a single primary key that indexes each type of item.

That’s just true for so many APIs that we don’t support multiple indexes (although it would be possible)

As a note, I do want to say for future readers that it’s an inherent data problem in legacy systems. If multiple keys are used then the correct one must be available when looking up data against a backend. You can likely build up a secondary index manually on the front end, but that also isn’t as easy as it sounds.
Another alternative is to combine keys into a serialised format, but that also requires every query to take this into account.

I’ll close this issue for now, but feel free to ask more questions on Spectrum if you require more discussions or ideas for temporary solutions 🙌
