### ISSUE TITLE
RFC: Persisted Fetch - support GET for hashed queries 

### ISSUE THREAD

**Issue by jakubriedl** [FormidableLabs/urql#799]
## Summary
New Persisted fetch exchange is awesome, but it is missing support for GET for hashed queries that prevents us from using it.

In our use-case we want to use standard POST queries when query is not persisted (to avoid super long urls which cause issues on some devices) but GET for persisted (hashed) queries so it can be cached on CDN. Apollo Client supports this behaviour with [useGETForHashedQueries option](https://www.apollographql.com/docs/apollo-server/performance/apq/#using-get-requests-with-apq-on-a-cdn)

## Proposed Solution
Implement `useGETForHashedQueries` option similar to Apollo.

**Comment by JoviDeCroock** [comment]
Hey,

Since we are using our [builder](https://github.com/FormidableLabs/urql/blob/master/exchanges/persisted-fetch/src/persistedFetchExchange.ts#L117) which already supports using [`GET`](https://github.com/FormidableLabs/urql/blob/ec9b8cf77bfb113c54fac11167e6e70316685a84/packages/core/src/internal/fetchOptions.ts#L38).

You can enable this with the [`client.preferGETMethod`](https://formidable.com/open-source/urql/docs/api/core/#client) option

**Comment by jakubriedl** [comment]
I tried that but unfortunately it changes also the normal non-persisted queries to GET. That leads to huge URLs that are causing troubles on some devices. The `useGETForHashedQueries` behaviour works the way that only persisted queries are GET.

**Comment by JoviDeCroock** [comment]
To exclusively use `GET` for hashed queries we'd need to transform that `exchange` to be a Higher Order Function I'd guess. That would set [`operation.context.preferGETMethod`](https://github.com/FormidableLabs/urql/blob/ec9b8cf77bfb113c54fac11167e6e70316685a84/packages/core/src/internal/fetchOptions.ts#L24) or something similar.

**Comment by jakubriedl** [comment]
That is exactly what I did in my local fork and it is working fine (not configurable though).
https://github.com/FormidableLabs/urql/blob/master/exchanges/persisted-fetch/src/persistedFetchExchange.ts#L75

```
            return makePersistedFetchSource(
              {
                ...operation,
                context: { ...operation.context, preferGetMethod: true },
              },
              body,
              dispatchDebug,
            )
```

**Comment by JoviDeCroock** [comment]
Something that I'm wondering is people opting for `persisted-queries` will probably exclusively use `GET` for those queries so it might even be a good default for `persisted-queries` to use `GET`.

Both transforming to a higher order function and that default would be breaking though so I'm thinking if there's an in between solution we could utilize, not dismissing going for a breaking change though, we've got a few things lined up for a new major (offline, ...).

**Comment by kitten** [comment]
I think it’s more about convenience to some.
When a CDN is used people can skip sending different `Cache-Control` headers for the persisted GET queries and POST queries, as only the persisted shorthand queries would be `GET` and hence cached.

That’s a weak guarantee though, as any user can send a self-crafted GET query though and hence clog the CDN anyway, in which case this should still be handled. In fact, Apollo Server may or may not handle this automatically and send the appropriate headers? Investigation needed.

Where it may count is when queries are close to the GET URL size limit. To circumvent this, it’d be useful to let only the persisted exchange send GET requests.

**Comment by kitten** [comment]
@JoviDeCroock i think we can go for a breaking change of the `persisted-fetch` exchange and bump it to 1.0.0, since it’s still a prerelease

**Comment by lorenries** [comment]
I think a feature like this would be very useful for a situation like:

- When your CDN doesn't support caching POSTs, regardless of cache control headers
- **and** when you have big queries that are sometimes bigger than GET size limits

I also have a naive implementation [here](https://github.com/FormidableLabs/urql/compare/master...lorenries:persisted-queries-get), but a HOC with the exchange would probably be better!

**Comment by JoviDeCroock** [comment]
This will be implemented in the next release of `@urql/persisted-fetch`

**Comment by jakubriedl** [comment]
Thank you

**Comment by kitten** [comment]
This has just been released: https://github.com/FormidableLabs/urql/releases/tag/%40urql%2Fexchange-persisted-fetch%401.0.0
Do take care as it's a small breaking change in how the exchange is instantiated 😉
