### ISSUE TITLE
issue with codesandbox example

### ISSUE THREAD

**Issue by tgrecojs** [FormidableLabs/urql#80]
The GraphQL API is returning a `400` error in the sample code. I also recieved the same 400 when I tried it out inside GraphiQL as well as [this apollo launchpad](https://launchpad.graphql.com/jvnqnnxpp) link. 

below is just a quick gif showing it in action

![urql codesandbox issue](http://g.recordit.co/oz1gA4xFSt.gif)

**Comment by dennisja** [comment]
I think, its a backend issue. I forked the launch pad demo added an API token from TMDB and the frontend works fine as seen here https://codesandbox.io/s/r520rrlp04. Though the backend still has an issue with poster resolution which

**Comment by HawiCaesar** [comment]
yeah it looks like theres an issue with backend. If you use a different graphQL endpoint you can make the code sandbox work just as @dennisja has done.

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️
