### ISSUE TITLE
urql-next _app bundle size

### ISSUE THREAD

**Issue by jakubriedl** [FormidableLabs/urql#801]
While analyzing _app bundle size I noticed that some packages are shipped to the client even though they are never used there.

### react-ssr-prepass (5KB gzip)
React SSR prepass is used [only on server](https://github.com/FormidableLabs/urql/blob/master/packages/next-urql/src/with-urql-client.tsx#L87) (after `if (typeof window !== 'undefined') return ..`) so it doesn't need to be shipped to client and can safe 5KB of bundle on every page. One option how to fix it could be use of `const ssrPrepass = await import('react-ssr-prepass')` which is supported by since Node 9.7 but conflicts with current TS configuration (requires module flag to `es2020 | esnext | commonjs | amd | system | umd`) while current is `es2015`.

### js-sha256 (4KB gzip) (from persisted-fetch exchange)
Because of [import on top of sha256.ts](https://github.com/FormidableLabs/urql/blob/master/exchanges/persisted-fetch/src/sha256.ts#L1) client bundle with persisted fetch contains `js-sha256` which is used only on server side and doesn't need to be shipped to client. Possible fix would be similar as above using dynamic import and native node module.
[sha256.ts#L49](https://github.com/FormidableLabs/urql/blob/master/exchanges/persisted-fetch/src/sha256.ts#L49)
```js
    const { createHash } = await import('crypto')
    return createHash('sha256').update(query).digest('base64')
```

urql version & exchanges:
```
"urql": "^1.9.7",
"@urql/exchange-persisted-fetch": "^0.1.3",
"next-urql": "^0.3.7",
```

**Steps to reproduce**
Create production bundle using next and [analyze the bundles](https://flaviocopes.com/nextjs-analyze-app-bundle/). 

**Expected behavior**
Client bundles contain only code executed on client

**Actual behavior**
At least 2 significant packages are included in client bundle, possibly some others I haven't notice.
- react-ssr-prepass
- js-sha256

**Monkey patch**
As temporary fix it is possible to remove those packages from client bundle by using webpack [null-loader](https://webpack.js.org/loaders/null-loader/). To do so add following code to `next.config.js` webpack configuration.
```js 
    if (!isServer) {
      config.module.rules.push({
        test: /.*react-ssr-prepass.*|.*js-sha256.*/,
        use: 'null-loader',
      })
    }
```

**Comment by JoviDeCroock** [comment]
Hey,

The library `js-sha256` is indeed needed for the Node but also for the IE11 side of things, IE11 does not support `TextEncoder` which is needed  to safely form the string we're passing to the sha function.

About `next.js` async importing in libraries is still a very flakey thing but I think we can utilise `process.browser` to notify next to shake this out in the client-side build.

**Comment by jakubriedl** [comment]
Thanks for quick response. `process.browser` looks good, didn't know about that.

I'm maybe missing some side-effect of `js-sha256` but the only place where I can see it being used is inside window check condition https://github.com/FormidableLabs/urql/blob/master/exchanges/persisted-fetch/src/sha256.ts#L48-L50.
```
  if (typeof window === 'undefined') {
    return Promise.resolve(sha256Standard.sha256(query));
  }
```

**Comment by JoviDeCroock** [comment]
Oh right, there was a way around that `TextEncoder` issue. The point remains that async imports aren't really well-supported in libraries. That being said this could probably be resolved by allowing for the user to pass `hasher` in node-environments where we defer this optimization to the user-space.

At a library level we can't do much more than moving this to user-space as long as async imports in libs aren't well supported by bundlers.

**Comment by jakubriedl** [comment]
That makes sense, fair point.

**Comment by JoviDeCroock** [comment]
The issue with `prepass` can be solved by bumping to the latest version (was missing `sideEffects: false`) and the newest version of `persisted-fetch` will be without the `js-sha256` and will use the native node implementation instead.

**Comment by jakubriedl** [comment]
Thank you
