### ISSUE TITLE
Use GET for persisted queries

### ISSUE THREAD

**Issue by lorenries** [FormidableLabs/urql#803]
## Summary

Often, CDNs don't support caching `POST` requests by default, so support for sending queries over `GET` can have big performance gains. In some cases, however, the size of a `GET` request in a big query can exceed browser/server limits.

**Proposal**: an option to use `GET` for a persisted query request, with a fallback to `POST` on a persisted query miss or if the server doesn't support persisted queries.

**Prior art**: [Apollo's `useGETForHashedQueries` config](https://github.com/apollographql/apollo-link-persisted-queries#options).

## Proposed Solution

I have a naive, working implementation [here](https://github.com/FormidableLabs/urql/compare/master...lorenries:persisted-queries-get) that coopts the existing `preferGetMethod` setting.

It might be better to separate this as a different option, either in the urql client config or in the creation of the exchange, a lá:

```ts
exchanges: [dedupExchange, cacheExchange, persistedFetchExchange({ useGetForPersistedQueries: true }), fetchExchange]
```

**Comment by lorenries** [comment]
Oops, i totally did not see https://github.com/FormidableLabs/urql/issues/799 before i posted this 😬 . Going to close this.

**Comment by kitten** [comment]
This has just been released: https://github.com/FormidableLabs/urql/releases/tag/%40urql%2Fexchange-persisted-fetch%401.0.0
Do take care as it's a small breaking change in how the exchange is instantiated 😉
