### ISSUE TITLE
svelte: getClient() returns undefined

### ISSUE THREAD

**Issue by gawlk** [FormidableLabs/urql#806]
Hi guys,

there is a little bug that I wanted to report.

Here's my component:

```
<script>
    import {
        getClient,
        mutate,
    } from '@urql/svelte';
    import { push } from 'svelte-spa-router';

    import Input from 'src/components/Input';

    let username = '';
    let password = '';

    const login = async () => {
        const client = getClient();
        console.log(client);
    }
</script>

<form
    on:submit|preventDefault={() => { login() }}
    method="POST"
    class="
    space-y-4
">
    <Input
        on:change={(event) => { username = event.detail }}
        label="Username"
        value={username}
    />
    <Input
        on:change={(event) => { password = event.detail }}
        label="Password"
        value={password}
        type="password"
    />
    <Button
        type="submit"
        class="
        mt-10
    ">
        Submit
    </Button>
</form>
```

If the first thing I do after the page loads is to click on the submit button, getClient() will return undefined even though it has been before BUT if I just write a single letter in one of the inputs before clicking on the button it will return the actual client. Of course I can add an if but I don't think this a normal behavior haha.

Not sure what the problem is.

Anyway,

thanks for this great library 👍

**Comment by kitten** [comment]
I’m fairly sure (I haven’t written a lot of Svelte yet)
That’s because the timing of the event handlers may differ in a way where the current component instance isn’t available.

If you bind the client outside of the handler, it should work as expected. So this is likely something specific to Svelte itself

**Comment by gawlk** [comment]
The init was in the parent component, I just wrapped it in a onMount and it works great.

Thanks !

**Comment by gawlk** [comment]
Actually it still doesn't work in Chrome, I moved the init in this component and it works now
