### ISSUE TITLE
Query doesn't wait for Mutation to finish

### ISSUE THREAD

**Issue by mellogarrett** [FormidableLabs/urql#81]
I have a component like so: 
```
<Connect
  query={query(getItemsQuery)}
  mutation={{
    updateItem: mutation(updateItemMutation)
  }}
  children={({ data, updateItem }) => {
  ...
```

When I fire the `updateItem` mutation, the `getItems` query is immediately reran, giving me items back before the mutation finishes. This results in a weird ux where a user edits a field, hits "save" (updateItem), and the field flashes back to it's old value, then to the new value again.

Is the query supposed to fire again before the mutation completes?

**Comment by kitten** [comment]
Can you try whether this is still an issue with 0.3.0-next1 please? You can install it using the “next” tag.

**Comment by mellogarrett** [comment]
Yea, still doing it on 0.3.0-next1. 

When I add `if (data) console.log("test");` inside the render prop, then fire the mutation once (via onClick), I see this in the console:

<img width="85" alt="screen shot 2018-05-19 at 2 25 27 pm" src="https://user-images.githubusercontent.com/9908831/40271790-8ddeb3ca-5b70-11e8-9a4d-bd9ae35dec6b.png">

Seems a little excessive.

**Comment by mellogarrett** [comment]
Hey @kitten I'm sorry, I ended up just using Axios to make graphql requests from `componentDidMount` rather than on every render via urql's render prop.

**Comment by kitten** [comment]
@mellogarrett Alright, since this is not reproducible right now and stale I'll close the issue. Sorry about that, let's see if someone else hits a similar case in the future
