### ISSUE TITLE
RFC: next-urql mergeExchangeOption should receive ctx

### ISSUE THREAD

**Issue by lionelB** [FormidableLabs/urql#813]
## Summary

In a context of a jwt auth based application, best practices enforce using a short live token (jwt-token) and a longer live token (refresh_token). 
A common practice si to store the refreshToken as a serverSide cookie. It's generally do in a `refreshToken()` method that could be happen clientSide or serverSide(on initial access) 
To having a authExchange that take care of refreshing the token, we need to access ctx so authExchange can pass `ctx` to refreshToken when it happen on serverside so cookie header can be set.
Since it's not the case,  we need to use fetchOption to bind context to the refreshToken method
```js
 return withUrqlClient(
    (ctx) => ({
      url: "/graphql",
      fetchOptions: {
        refreshToken: () => refreshToken(ctx),
      },
    }),
```

## Proposed Solution

It would be simpler to also have ctx from the mergeExchange
```
(ssrExchange, ctx) => [
      dedupExchange,
      cacheExchange,
      ssrExchange,
      () => authExchange(ctx),
      fetchExchange,
    ]
```
@kitten wrote an authExchange example https://gist.github.com/kitten/6050e4f447cb29724546dd2e0e68b470#file-authexchangewithteardown-js
and an auth example is here https://gist.github.com/lionelB/65c0472304b18f9417665b5bce85991e

**Comment by kitten** [comment]
I’m starting to think that it may be interesting to attempt to change the API entirely, if possible.

The second `mergeExchanges` argument has lead to confusion and we could steer people in the right direction by simply making the entire HOC accept a single option, e.g.

```ja
withUrqlClient((ctx, ssrExchange) => ({
  /* ... options */
  url: ‘/api/GraphQL’,
  exchanges: [
    dedupExchange,
    cacheExchange,
    ssrExchange,
    fetchExchange
  ],
}))(Page);
```
