### ISSUE TITLE
[@urql/exchange-graphcache] Heuristic Fragment Matching

### ISSUE THREAD

**Issue by nghiepit** [FormidableLabs/urql#819]
Hi guys,

I have an example of using `exchange-graphcache`.
My warning:

> Heuristic Fragment Matching: A fragment is trying to match against the `SimpleProduct` type, but the type condition is `Product`. Since GraphQL allows for interfaces `Product` may be aninterface.
A schema needs to be defined for this match to be deterministic, otherwise the fragment will be matched heuristically!
(Caused At: "GetProducts" query, Inline Fragment on "SimpleProduct", "productFields" Fragment)

I don't know, the problem is where?

```gql
interface Product {
  id: ID!
  name: String!
  sku: String!
  price: UnsignedInt!
}

type SimpleProduct implements Product {
  id: ID!
  name: String!
  sku: String!
  price: UnsignedInt!
}

type ComplexProduct implements Product {
  id: ID!
  name: String!
  sku: String!
  price: UnsignedInt!
  tax: UnsignedInt!
  fee: UnsignedInt!
}
```

```js
import gql from 'graphql-tag';

export const PRODUCT_FRAGMENT = gql`
  fragment productFields on Product {
    id
    name
    sku
    price
  }
`;

export const PRODUCTS_QUERY = gql`
  query GetProducts() {
    products() {
      ... on SimpleProduct {
        ...productFields
      }
    }
  }
  ${PRODUCT_FRAGMENT}
`;

export const COMPLEX_PRODUCTS_QUERY = gql`
  query GetComplexProducts() {
    products() {
      ... on ComplexProduct {
        ...productFields
        tax
        fee
      }
    }
  }
  ${PRODUCT_FRAGMENT}
`;
```

Some where:
```js
const [{data}] = useQuery({
  query: PRODUCTS_QUERY
});
```

I just want to reuse the `PRODUCT_FRAGMENT ` fragment.

Thank you in advance.

**Comment by JoviDeCroock** [comment]
Is your `schema` passed to the `cache`? If not it can never know that both `Complex` and `Simple` product are inheriting from the same interface.

**Comment by nghiepit** [comment]
Thanks @JoviDeCroock , I've missed the document.

**Comment by nghiepit** [comment]
@JoviDeCroock But I've used `Inline Fragment`. Does that help `Simple` and `Complex ` same interface?

**Comment by JoviDeCroock** [comment]
No so the problem is that we can’t know this is right for your backend, that means we never know if the SimpleProduct is a Product. You could be making a mistake and we point that out, unless we know your schema we can’t know for sure.
