### ISSUE TITLE
Svelte: mutation and subsequent cache update

### ISSUE THREAD

**Issue by artecoop** [FormidableLabs/urql#834]
Imagine having this query in a svelte project

```graphql
$: result = query({
    query: `query($limit: Int!, $cursor: Int, $orderBy: BindingOrderByInput) {
        bindings(limit: $limit, cursor: $cursor, orderBy: $orderBy) {
            edges {
                id
                name
            }
            pageInfo {
                hasNextPage
                endCursor
            }
       }
   }`,
   variables: {
       limit,
       cursor,
       orderBy
   },
   requestPolicy: 'cache-and-network'
});
```
This show a list of bindings on my page. 

If I need to delete one of the listed bindings, I'll call this mutation

```graphql
const { error } = await mutate({
    query: `mutation($bindingId: ID!) {
        deleteBinding(id: $bindingId)
     }`,
     variables: { bindingId }
});
```
Now, how to refetch the data? In react, I can use reexecutequery
```js
const [{ data, fetching, error }, reexecuteQuery] = useQuery({ query: ..., variables: ..., requestPolicy: 'cache-and-network' });
```

Thanks in advance!

**Comment by kitten** [comment]
In that case it’s actually not recommended to manually refetch. Instead you would let the document cache refetch your related queries: https://formidable.com/open-source/urql/docs/basics/document-caching/

If your `deleteBinding` resolves to the binding that’ll be deleted, then it’s enough to add a selection set to it, e.g. `deleteBinding(id: $bindingId) { id }`

Then the document cache will add the `__typename` field to your selection set and automatically invalidate and refetch all queries that contain a “binding”

**Comment by artecoop** [comment]
@kitten as always, thanks for your quick response. And thanks for your clarification. In a separate project, used as test field for migrating from apollo to urql, I can confirm that your solution works as expected.

But in my main project it doesn't. Then it struck to me: the query you see on the question up here returns a `BindingPagedResult` __typename. But the delete mutation returns a __typename of `Binding`, resulting in not invalidating the cache.

RTFM again, in the very link you gave me on your answer, I found the solution: adding `additionalTypenames`.

So modifying the mutation as follow
```graphql
const { error } = await mutate({
    query: `mutation($bindingId: ID!) {
        deleteBinding(id: $bindingId) {
            id
        }
    }`,
     variables: {
         bindingId
     },
     additionalTypenames: ['BindingPagedResult']
});
```

solved the problem.

Before closing this issue, I'll wait for your OK to be the best solution for this problem.

**Comment by kitten** [comment]
Sounds good! :+1:
