### ISSUE TITLE
Order of array with null keys

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#835]
Hi All

I have a query that returns an object witch contains an array. The items of the array have a predefined keys function that return null

For some of the objects the order of the array is not retained. (Actually it is reversed)

I have checked that the server returns the data in the correct order but the object returned from useQuery have them in the reverse order.

Find below the actual query. In the below query combinations in 2 of the 5 object returned are given in the reversed order. Also urql dev tools shows them in the correct order (When viewed inside explorer)

Any idea?

```
#import "./PurchasedScratchCardFragment.graphql"
#import "../../../graphql/AmountFragment.graphql"

query ScratchCards {
  scratchCards {
    id
    name
    background {
      width
      height
    }
    grid {
      rows
      columns
      x
      y
      width
      height
    }
    coverSmall {
      width
      height
    }
    coverLarge {
      width
      height
    }
    price {
      ...AmountFragment
    }
    mask {
      x
      y
    }
    maximumCombination {
      win {
        ...AmountFragment
      }
    }
    minimumCombination {
      win {
        ...AmountFragment
      }
    }
    combinations {
      count
      symbol
      profitability
      win {
        ...AmountFragment
      }
    }
    symbolIndexes
    purchases {
      ...PurchasedScratchCardFragment
    }
  }
}

```

And this is the relevant keys section
```
        keys: {
          ScratchCardMask: () => null,
          ScratchCardCombination: () => null,
          ScratchCardDimensions: () => null,
          ScratchCardGrid: () => null,
          Amount: () => null,
        }
```

**Comment by kitten** [comment]
Are you mutating the result somewhere before it reaches Graphcache or while it’s inside Graphcache, e.g. with `arr.reverse()`?

**Comment by zenios** [comment]
No

**Comment by zenios** [comment]
They entered graphcache in a normal order since keys functions is called
with the original order defined.

**Comment by kitten** [comment]
The problem here is that if you check our `write` / `read` operations, what you’ll find is that they always use for-loops in natural order to read or write links. It isn’t even different whether those are embedded or not.
So the only immediate difference could be in custom resolvers.

**Comment by zenios** [comment]
@kitten you were right i was doing a sort somewhere having the impression that sort does not modify the original array. 

Really sorry!

**Comment by kitten** [comment]
No worries! Glad we figured it out
