### ISSUE TITLE
graphql-upload compatibility

### ISSUE THREAD

**Issue by artecoop** [FormidableLabs/urql#836]
Hello again guys,
your nightmare here, with another question:

On client side:
```
"@urql/svelte": "0.2.3",
"@urql/exchange-multipart-fetch": "0.1.7",
```
On server side:
```
"graphql": "15.0.0",
"graphql-upload": "11.0.0",
```

When trying to upload a file, e.g.: 

```js 
async function addImage(event) {
    const file = event.target.files[0];

    const foo = await mutate({
        query: `mutation($id: ID!, $file: Upload!) {
            addAuthorImage(authorId: $id, file: $file)
        }`,
        variables: {
            id,
            file
        }
    });

    console.log(foo);
}
```
I got this error:
`[GraphQL] Variable "$file" got invalid value { resolve: [function], reject: [function], promise: {}, file: { filename: "file.jpg", mimetype: "image/jpeg", encoding: "7bi\", createReadStream: [function createReadStream] } }; Expected type Upload. Upload value invalid.`

The $file passed seems to be a promise instead of "standard" (let's say this way...) Upload spec.

What I'm doing wrong?

**Comment by JoviDeCroock** [comment]
Hey,

`multipart-fetch` is using the exact spec you are referring to with `graphql-upload`, our example [here](https://codesandbox.io/s/urql-upload-client-d0ozh) with the [server](https://codesandbox.io/s/urql-upload-server-p49r8) should adhere to that spec since apollo uses `graphql-upload` under the hood.

A first thing you could do for debugging is check what is being dispatched in your network tab, it should look something like [this](https://github.com/jaydenseric/graphql-multipart-request-spec#request-payload)

**Comment by artecoop** [comment]
Hey Jovi,
I'm waiting for the subscripition email from spectrum to come. Today is not working well I think.

```
-----------------------------217101069242100432811752163731
Content-Disposition: form-data; name="operations"

{"query":"mutation ($id: ID!, $file: Upload!) {\n  addImage(id: $id, file: $file)\n}\n","variables":{"id":"123456789","file":null}}
-----------------------------217101069242100432811752163731
Content-Disposition: form-data; name="map"

{"1":["variables.file"]}
-----------------------------217101069242100432811752163731
Content-Disposition: form-data; name="1"; filename="b41dd722-53f7-4f0a-afcd-5a2d51268ae4.jpg"
Content-Type: image/jpeg

[JPEG file gibberish]
-----------------------------217101069242100432811752163731--
```
This is the request body I send, consistent with the example provided from grapqhl-upload.

What I don't understand is what multipart-fetch pass to my server. 
![Screenshot from 2020-05-26 16-58-29](https://user-images.githubusercontent.com/52246878/82916787-c8ab9e80-9f72-11ea-8a68-7f1278b66b9a.png)

As you can see in this screenshot, this is what's passed to the graphql-upload method `processRequest` that raises the error specified on the first post in this thread. Seems that what is generated is not a compliant Upload type.

**Comment by JoviDeCroock** [comment]
`multipart-fetch` is doing everything correctly if that body is what you're seeing in the console, I think your `File` type has already been processed by some scalar you are using. Feels like a backend thing to me since everything up to the hand-off looks good to me.

**Comment by artecoop** [comment]
Sorry to keep this open.

based on what I see on this file, as the definition of the `Upload` class
https://github.com/jaydenseric/graphql-upload/blob/master/public/Upload.js

compared to the Upload you pass will fail on 
https://github.com/jaydenseric/graphql-upload/blob/a3b7b31406aa47567ced0b60eea1cd764db8932c/public/GraphQLUpload.js#L81

because the upload received (as structured as on the image on my previous comment) and the Upload are incompatible, causing the mentioned error.

**Comment by JoviDeCroock** [comment]
We aren't passing you any functions, your server translates what we sent from `multipart-fetch` to what you are seeing this is nothing that we can change.

**Comment by artecoop** [comment]
Ok I'll go deeper on the server in order to find what changes the request.
Thanks for your help!
