### ISSUE TITLE
Calling `client.query` with subscription is not correctly recognized

### ISSUE THREAD

**Issue by FredyC** [FormidableLabs/urql#837]
I am using `@urql/core` together with XState and I don't need any other abstraction lib. I would have to call `client.executeSubscription` directly in the client code to mitigate the issue which is a bit more verbose.

I would like to propose the addition of `client.subscription`. Alternatively, the subscription exchange could try to identify the actual subscription document(s) instead of relying on operation type.

urql version & exchanges: 1.11.0

**Steps to reproduce**

`client.query(SubscriptionDocument)`

**Expected behavior**

The subscription exchange should be used.

**Actual behavior**

The subscription goes over to fetch instead.

**Comment by kitten** [comment]
This is what `client.executeSubscription` is for :)
The `client.query` and `client.mutation` methods are shorthands, basically, and come with `.toPromise()` helper. This doesn't make much sense for subscriptions, so there's only the base one: https://formidable.com/open-source/urql/docs/api/core/#clientexecutesubscription

I'm open to adding `client.subscription` for completeness' sake though

**Comment by FredyC** [comment]
I think it does make sense simply to mitigate verbosity. I know that everyone can write their own wrapper around `createRequest` & `executeSubscription`, but yea, it feels unnecessary.

I could probably work on the PR if you don't expect too elaborate test cases for it as I am already swamped by other stuff.

**Comment by kitten** [comment]
If you’d like to pick it up, that’d be awesome! I suppose it’ll just be a couple of lines and apart from updating snapshots there shouldn’t be anymore tests to add 👍

**Comment by FredyC** [comment]
@kitten I noticed the change is already propagated to docs, but not actually published? Such a process might confuse someone for sure.
