### ISSUE TITLE
Typescript error when using cache.invalidate

### ISSUE THREAD

**Issue by johnjiang** [FormidableLabs/urql#851]
URQL: 1.9.7
@urql/exchange-graphcache: 2.4.2
TS: 3.9.5

**Steps to reproduce**
Using the example on https://formidable.com/open-source/urql/docs/graphcache/custom-updates/
```
const cache = cacheExchange({
  updates: {
    Mutation: {
      deleteTodo: (result, args, cache, info) => {
        cache.invalidate({ __typename: 'Todo', id: args.id });
      },
    },
  },
});
```

I get the following TS error.

```
TS2322: Type 'string | number | boolean | Variables | ScalarObject | Scalar[] | NullArray<Variables> | null' is not assignable to type 'string | number | null | undefined'.   Type 'false' is not assignable to type 'string | number | null | undefined'.
```

**Expected behavior**
No TS errors

**Actual behavior**
TS error :(

**Comment by JoviDeCroock** [comment]
You can use `cache.invalidate({ __typename: 'Todo', id: args.id as string });`, we can't really predict the shape of your args so it are the normal values. That code snippet is also in JS so the type case isn't included.

**Comment by johnjiang** [comment]
Thanks for the prompt response! That makes sense!

I also noticed that by defining my own custom `cacheExchange`, I've lost all the other benefits of the default `cacheExchange`. e.g. when other mutations are made, urql no longer eagerly refetches all the affected queries. Is there anyway to maintain the default set of `cacheExchange` behaviours and add any custom rules ontop?

**Comment by JoviDeCroock** [comment]
The thing is because this is a normalised cache there's no need for refetching as explained [here](https://formidable.com/open-source/urql/docs/graphcache/normalized-caching/).

When an update mutation has the `id` and `__typename` for a given query entity, this will get updated automatically. However when adding or deleting entities you'll need these updaters.

**Comment by johnjiang** [comment]
Ah got it, I didn't read about how by default it's using Document Caching. I thought everything was normalised to begin with. Thanks so much. That explains a lot!
