### ISSUE TITLE
Expose toPromise to @urql/svelte

### ISSUE THREAD

**Issue by artecoop** [FormidableLabs/urql#854]
When using the Svelte package, to access a Promise version of a query, I need to ditch the usual "query" way:

```js
import { query } from '@urql/svelte';

const result = query({ query: ... });

result.subscribe(...)
```
to a more internal, prone-to-breaking-change way

```js
import { getClient } from '@urql/svelte';

const result = await getClient().query(...).toPromise();
```

Is it possible to expose `toPromise` to the svelte implementation of `query(query: ...)`?

Thanks!

**Comment by artecoop** [comment]
@kitten I'm really glad there are developers like you that grows their product.

But I'm a bit confused on how the new 0.3.0 modificatons works:
Imagine having:

```js
async doSomething(bar) {
    const query = query({ query: TESTQUERY, variables: {foo: bar} });
    const result = await query;

  return result.data
}
```
With this, I'll keep having data = undefined, and fetching = true.

What I'm doing wrong?

**Comment by frederikhors** [comment]
Same here, @kitten. Can you please explain?
