### ISSUE TITLE
Unexpected data: null in useQuery result, possibly due to __typename: 'Subscription'

### ISSUE THREAD

**Issue by stevehollaar** [FormidableLabs/urql#858]
It looks like _something_ in graphcache fails when my nested field with type: 'Subscription' is queried. See sample app in gist, linked below.

urql version & exchanges:
```
"urql": "1.9.8",
"@urql/exchange-graphcache": "3.0.0",
```

**Steps to reproduce**
See [sample app in gist](https://gist.github.com/stevehollaar/d1bb8be85e1b40bcb809a43292be35ca)

**Expected behavior**
`data` returned by `useQuery` should be populated by query result

**Actual behavior**
`data` is `null`

Prior conversation about this issue: https://spectrum.chat/urql/help/infinite-loop-of-query-re-fetching~53171239-62b5-4fc0-9a6e-6f0c6d5a7464

**Comment by kitten** [comment]
Hiya :wave: Luckily, I can explain this rather easily! `Subscription` is by default a special type in your GraphQL Schema for subscriptions. Graphcache hence treats these differently than normal types. The types `Mutation` and `Subscription` are by default "root types" that aren't cached, so they're not written to the cache.

Typically if you really wanted to use these names, you'd set up your schema to use a different name for them. But that will only work in Graphcache with Schema Awareness.

Instead, it's probably better if you renamed the `Susbcription` type to something else.

**Comment by stevehollaar** [comment]
🎉 Thanks for the quick response! Might I suggest, if it _is_ trivially detectable, adding a warning in dev if these "forbidden" typenames are ever seen outside of the expected schema root?

> Typically if you really wanted to use these names, you'd set up your schema to use a different name for them. But that will only work in Graphcache with Schema Awareness.

Could you provide more details on how this might work? I am already passing the `schema` to `cacheExchange({ schema })` for schema-awareness, and I'd prefer to avoid any changes to the schema server-side. Is it possible to tell graphcache to recognize all `__typename: 'Subscription'` as, say, `__typename: 'MySubscription'` (given that I'm not using graphql subscriptions anyway)

**Comment by kitten** [comment]
Well, it's tricky. Technically any part of `Query` can lead back to `Query` and also to `Subscription` and `Mutation`. `Mutation` can even be used in `Query` if the schema is set up that way to mutate, which is by convention discouraged. Similarly using these names like this is also discouraged.

So we were hesitant to add any warnings for these cases, but I'll look into how we may be able to do this.

In theory with a schema to change the name you'd pass a different name on your subscription type on the server-side: https://graphql.org/graphql-js/type/#graphqlschema

**Comment by kitten** [comment]
@stevehollaar I've just worked on a quick warning that should be able to catch this edge case in #859. If you've got time and don't mind, you can test it out using the preview package that CodeSandbox CI publishes 🙌  https://ci.codesandbox.io/status/FormidableLabs/urql/pr/859/builds/31993

**Comment by stevehollaar** [comment]
Thanks @kitten! Confirmed this warning would have caught the issue I was having:
![image](https://user-images.githubusercontent.com/918252/84528737-11fb2e00-ac95-11ea-97ba-944ffebe82f9.png)

As for how I'm solving this, I think versioning the schema server-side to rename the `Subscription` type makes sense. The `RenameTypes` tool in `graphql-tools` is a nice helper for that: https://www.graphql-tools.com/docs/schema-wrapping#modifying-types
