### ISSUE TITLE
jest mock client execute mutation fails assertion

### ISSUE THREAD

**Issue by chiragprodsmiths** [FormidableLabs/urql#868]
@JoviDeCroock @kitten 
expect(mockClient.executeMutation).toBeCalledTimes(1); /// gives 0

may be I am doing something wrong. but can you guys guide me

sample code
```javascript
const apiClient: any = {
        executeMutation: jest.fn(() =>
          fromValue({
            fetching: true,
            data: {
              login: {
                token: '',
              },
            },
          }),
        ),
      };
      const { getByTestId } = render(
        <Provider value={apiClient}>
          <Login />
        </Provider>,
      );
      const submitEl = getByTestId('submit');
      await act(async () => {
        const userNameEl = getByTestId('email');
        const passwordEl = getByTestId('password');
        fireEvent.change(userNameEl, {
          target: {
            value: 'username',
          },
        });
        fireEvent.change(passwordEl, {
          target: {
            value: 'password',
          },
        });
        await fireEvent.click(submitEl);
      });
      expect(mockClient.executeMutation).toBeCalledTimes(1);
```

**Comment by JoviDeCroock** [comment]
Hey,

How does the component look? I assume it works when you're using this in the browser/your relevant environment?

Is it possible there's other stuff running and you just have to use `await wait(0)`?

**Comment by chiragprodsmiths** [comment]
> Hey,
> 
> How does the component look? I assume it works when you're using this in the browser/your relevant environment?
> 
> Is it possible there's other stuff running and you just have to use `await wait(0)`?

below is my actual async submit handler.
as you see i immediately call await login mutation

```javascript
const onLoginSubmit = async (credentials: FormData): Promise<void> => {
    const { data, error } = await login(credentials);
    if (error || !data || data === null) {
      setLoginErrors(true);
      return;
    }
    if (setAuthenticated && setToken) {
      setAuthenticated(true);
      setToken(data.login.token);
    }
  };
```

**Comment by JoviDeCroock** [comment]
What happens when you put logs around it? I guess the log under `login` won't be called before this fails. This would indicate that there's a tick delay due to the `Promise.resolve`, we'll need some way to test this out since it's quite hard to debug this way

**Comment by chiragprodsmiths** [comment]
> What happens when you put logs around it? I guess the log under `login` won't be called before this fails. This would indicate that there's a tick delay due to the `Promise.resolve`, we'll need some way to test this out since it's quite hard to debug this way

sample repo
https://github.com/chiragprodsmiths/ts-jest-urql.git

**Comment by JoviDeCroock** [comment]
This does not seem to relate to `urql`, I've put a log-statement in your code and the `submit` button click does not bubble up to your form.

**Comment by chiragprodsmiths** [comment]
> This does not seem to relate to `urql`, I've put a log-statement in your code and the `submit` button click does not bubble up to your form.

@JoviDeCroock  
I m so stupid it was mistake from my end. 

thanks for this wonderful library by the way.

**Comment by chiragprodsmiths** [comment]
> > This does not seem to relate to `urql`, I've put a log-statement in your code and the `submit` button click does not bubble up to your form.
> 
> @JoviDeCroock
> I m so stupid it was mistake from my end.
> 
> thanks for this wonderful library by the way.

sorry to bother you guys again but based on testing docs i am now trying to do 
```javascript
expect(mockClient.executeMutation).toBeCalledWith(expect.objectContaining({ variables }));
```

![image](https://user-images.githubusercontent.com/49074609/84792674-c7214380-b011-11ea-9816-23c400291ee7.png)

**Comment by kitten** [comment]
@chiragprodsmiths looks like you're just missing the second argument for `executeMutation` here: https://github.com/FormidableLabs/urql/blob/062c1359a7ccd41044d2eb963ab0da5629143cc5/packages/core/src/client.ts#L343-L344
(Note the red `, {}` at the end of Jest's Received output.

**Comment by chiragprodsmiths** [comment]
> @chiragprodsmiths looks like you're just missing the second argument for `executeMutation` here:
> 
> https://github.com/FormidableLabs/urql/blob/062c1359a7ccd41044d2eb963ab0da5629143cc5/packages/core/src/client.ts#L343-L344
> 
> 
> (Note the red `, {}` at the end of Jest's Received output.

thank you

**Comment by baldurpan** [comment]
There is nothing about that second argument in the testing docs, so I can see why that would cause confusion.
It currently demonstrates:
```javascript
expect(mockClient.executeMutation).toBeCalledWith(expect.objectContaining({ variables }));
```

Perhaps the docs should be updated?
