### ISSUE TITLE
ssrExchange deletes synchrnous errored results too eagerly on rehydration

### ISSUE THREAD

**Issue by sinwailam193** [FormidableLabs/urql#874]
urql version & exchanges:
"@urql/exchange-graphcache": "^3.0.1"
"urql": "^1.9.8"

Hello I have a question, I'm currently using server side rendering with URQL. I'm fetching the data on server side using `react-ssr-prepass`. Then I send the data to client side with `ssr.extractData()`. So in this case I'm hydrating the data into the `ssrExchange` cache on client. So on the client side if I want to reference the cache that I already populated from the server side by using `cache-only` instead of `cache-first` so that I don't have to use another API call on the client side.
```
export const useQueryUserMe = (): UseQueryResponse<UserMe> => useQuery({
    query: GET_ME,
    requestPolicy: typeof window !== "undefined" ? "cache-only" : "cache-first"
});
```
So on the client side I'm using `cache-only` and on the server side I'm using `cache-first`. The reason why I'm doing this is because if I get a 401 unauthorized error on server side, I don't want to call this again on the client side. But I do want to use the query to check if user exist in the cache or not. However the issue I'm getting on client-side is that the data is always null if I use `cache-only` even though the cache should already been populated from server side hydration. Is there a way that I can call the query only on server side only and on the client side I will only fetch it from the cache regardless if it is already hydrated or not from ssr?

**Comment by kitten** [comment]
The `cache-only` request policy relates to caches, and technically the `ssrExchange` is not a “cache exchange” but a fetch-like exchange that replays past responses once.

So when you pass `cache-only` then the actual `cacheExchange` won’t have your result yet and will abort.

The crucial thing here is that the `ssrExchange` already does what you expect with `cache-first` actually. https://github.com/FormidableLabs/urql/blob/master/packages/core/src/exchanges/ssr.ts

You can see in the code base that it actually handles errors and outputs/hydrates them to avoid this second call exactly as what you’re looking to do, since that’s the correct behaviour for SSR caching.

**Comment by sinwailam193** [comment]
Hi @kitten, thank you for taking your time to answer my questions. So I did try the `cache-first` approach, however, for some reason on the client side, it is still making the call even though the server side already returns errors for it.

![image](https://user-images.githubusercontent.com/8454621/85239358-eed73800-b465-11ea-8bea-b7f7c85a3152.png)

To give you context in the console, the first `undefined` is the `data` and the boolean in the middle is the `fetching` flag and the the last console output is the `error`. As you can see from the screenshot, the server side already hydrated the error that was received on the server side. But, on the client side, it is making the call again and `fetching` is set to true. Is there anything that I may have missed, because according to your answer above, `cache-first` should already provide that functionality if I'm not wrong?

This is my current setup for `createClient`
```
const options: ClientOptions = {
        url: "/api/graphql",
        exchanges: [
            dedupExchange,
            cacheExchange({}),
            ssr, // Add `ssr` in front of the `fetchExchange`,
            fetchExchange
        ]
    };
```

**Comment by sinwailam193** [comment]
The main concern for me is that if I were to use the same query in like, for example, 24 other different places of my app. Will the query be making 24 calls to server on the client side with all 24 returning the same 401 error? In the case, should I just store the call in one place and just pass it down via props/context to other components?

**Comment by kitten** [comment]
It’s certainly always a good idea to reduce the amount of queries with GraphQL to get as much out of individual queries as possible, especially with the document cache to avoid excessive queries / network requests.

I think the problem you’re describing is actually an issue as at least the first synchronous queries from the SSR cache are supposed to be resolved as they were on the server-side. I’ll look into that!

I think we may be removing results from the `ssrExchange` too eagerly.

Apart from that though, after rehydration any additional query will hit the `cacheExchange`, which doesn’t cache errors, so you’ll have to react to the 401 error appropriately to avoid it if you’re making further asynchronous queries.

**Comment by sinwailam193** [comment]
Thank you for taking a look into this, much appreciated. As for the errors that are captured on client side via `cacheExchange` I would certainly react to it appropriately, thank you for the tip.
