### ISSUE TITLE
Avoid eval in persisted-fetch exchange

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#875]
```
"@urql/exchange-graphcache": "3.0.1",
"@urql/exchange-persisted-fetch": "1.0.1",
"@urql/svelte": "0.3.0",
```

I'm trying for the first time https://github.com/FormidableLabs/urql/tree/master/exchanges/persisted-fetch exchange.

In my https://github.com/sveltejs/template project Rollup warns with:

![image](https://user-images.githubusercontent.com/41120635/85223261-fe9d4080-b3c1-11ea-87d3-d071730a001f.png)

Is there a way to avoid using `eval` here: https://github.com/FormidableLabs/urql/blob/master/exchanges/persisted-fetch/src/sha256.ts#L34?

This is stopping all of our customers' CI pipelines.

Thanks for your amazing work!

**Comment by JoviDeCroock** [comment]
We need this to see if `crypto` is available when we're in a node context, without eval this would crash browser code.

You can customize rollup warnings like [this](https://rollupjs.org/guide/en/#onwarn)

**Comment by frederikhors** [comment]
I know how to remove warning. I just can't do it (for many reasons independent of me).

What about the solution here: https://stackoverflow.com/a/30140906/10088259?

```js
var e = eval;
e("require('./x.js')");
```

Rollup does not warn with this code.

**Comment by JoviDeCroock** [comment]
That feels like using a bug to bypass the warning, which could get fixed 😅 if you're not using SSR you can also just remove this code-path by using the `replacePlugin` and replacing `typeof window` with `defined`.

**Comment by kitten** [comment]
Closing, since this technically isn't on our end, since it's working correctly.
You could also use a replace plugin and try `new Function('return require("crypto")')()` instead, which is functionally equivalent but may not be caught by whatever has that warning there
