### ISSUE TITLE
SSR pages re-executing queries

### ISSUE THREAD

**Issue by aaron7** [FormidableLabs/urql#879]
Hi :wave:

I've been debugging an issue where SSR pages are re-executing queries on the client (some of the time).

I believe this is caused by `cacheExchange` mutating `operation.query` when it [calls `formatDocument(operation.query)`](https://github.com/FormidableLabs/urql/blob/e6e2fa9/packages/core/src/exchanges/cache.ts#L28). 

There is a [comment](https://github.com/FormidableLabs/urql/blob/ec8c318/packages/core/src/utils/typenames.ts#L43) in `formatDocument()` which explains that mutating the `node` is ok because `visit()` clones the AST upwards. Although `visit()` does clone the AST upwards, it looks like mutating the `node` still mutates the original `operation.query` which is used when computing the query `__key`.

This issue only appears intermittently and likely with a specific version of node. I've managed to reproduce this issue locally using node `v10.20.1` and a production webpack build of our app. I have confirmed we see different `__key`'s for the same query on the client and server due to additional `__typename` entries on the server side only. Deep copying `operation.query` before passing it to `formatDocument()` resolves the issue for us, which suggests mutating the node is the cause.

Looking at other active issues, https://github.com/FormidableLabs/urql/issues/874 may be related.

urql version & exchanges: `1.9.5` `cacheExchange`

Thanks :)

**Comment by kitten** [comment]
Do you have a quick reproduction that causes this issue using `formatDocument`? I understand that it may mutate, and we should fix that, but the differing key on the server- and client-side shouldn't happen.

Even if we mutate these documents a little, the `__key` should be stored on the global `DocumentNode`. Or are you saying that two queries are sharing some parts and hence receive different keys when the second one is hashed?

**Comment by aaron7** [comment]
Thanks for the quick reply.

I don't have a quick reproduction on hand, sorry. I may have some time to create one tomorrow.

When adding logging [here](https://github.com/FormidableLabs/urql/blob/e6e2fa9/packages/core/src/utils/request.ts#L28) to print out the stringified query `createRequest` is hashing to create the `__key`, I see the client and the server hashing the same query, but sometimes one or the other contains the additional `__typename`s. This generates different keys on the client and server, causing the client to re-execute the query.

The issue is intermittent. For some queries, both the client and server see the additional `__typename`s when hashing. For other queries, both the client and server do not see them. In the cases where only one or the other contains the additional `__typename`s, the issue occurs. Interestingly, the queries which are affected are consistent within a single build, but change with rebuilds.

**Comment by kitten** [comment]
You should be able to use the CodeSandbox CI build in the #880 fix to see whether this solves your problem, by adding a resolution for `@urql/core` to the test package here: https://ci.codesandbox.io/status/FormidableLabs/urql/pr/880/builds/34670
