### ISSUE TITLE
How to remove subscription? 

### ISSUE THREAD

**Issue by vicsnow** [FormidableLabs/urql#881]
Hi, probably a dumb question, but I didn't find the answer for it yet.
How do I force unsubscribtion using react hooks? 

i.e. I have this functional component
```
function ({ query, queryType }) {

        const [result] = useSubscription({
            query: query,
        })

        const data = result.data && result.data[queryType];

        useEffect(() => {
            console.log("unsubscribe from previous sub")
        }, [queryType])

        return data ? <Component data={data} /> : <>No data</>
}
```

I want to unsubscribe from previous subscription, when `queryType` changes and `useEffect` is triggered.
Is there a way to do it?

**Comment by JoviDeCroock** [comment]
Hey @vicsnow 

There are no dumb questions, so on `useQuery` and `useSubscription` we have a property called `pause` that can be passed as an option, similar to how you're passing `query` at this time.

Let's say you want to pause when `queryType` is not "sub" then we can do:

```jsx
function ({ query, queryType }) {

        const [result] = useSubscription({
            query: query,
            pause: queryType !== 'sub',
        })

        const data = result.data && result.data[queryType];

        return data ? <Component data={data} /> : <>No data</>
}
```

Now the `subscription` will be torn down until you unpause it.

**Comment by svkior** [comment]
Hello, @JoviDeCroock.

I and @vicsnow  trying this solution today, but unsubscribe did not work every time.
And if query was changed by another (top level) subscription, we have doubling of subscription instead of unsubscription and new subscription.

**Comment by JoviDeCroock** [comment]
Hey @svkior could you provide us with a reproduction?

**Comment by svkior** [comment]
@JoviDeCroock tomorrow we will extract the peace of our current project into separate repo and I will provide the link in this issue

**Comment by kitten** [comment]
@svkior maybe in the meantime you can let us know which unsubscription you mean? Is it this one that isn't happening for you? https://github.com/FormidableLabs/urql/blob/master/packages/core/src/exchanges/subscription.ts#L35

**Comment by vicsnow** [comment]
here's an issue repo 
https://github.com/vicsnow/urqlsubscriptionissue

**Comment by Cordo-van-Saviour** [comment]
@vicsnow I know that it's been more than 3 years but I have this problem now and if you have any ideas on how to solve it, it would be greatly appreciated 💜
