### ISSUE TITLE
window.crypto.subtle API is not available error if not on https nor localhost

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#882]
"@urql/exchange-graphcache": "3.0.1",
"@urql/exchange-persisted-fetch": "1.0.1",
"@urql/svelte": "0.3.0",

**Steps to reproduce**

Using Chrome serving pages not in https on let's say http://192.168.1.2:3000.

**Actual behavior**

Error and nothing works:

```
urql-exchange-persisted-fetch.mjs:44 [@urql/exchange-persisted-fetch]: The window.crypto.subtle API is not available.
This is an unexpected error. Please report it by filing a GitHub Issue.
```

**Comment by JoviDeCroock** [comment]
This is intended from a browser standpoint, `localhost` is a trusted origin while non secure urls aren't.

- [chromium issue](https://groups.google.com/a/chromium.org/g/security-dev/c/DtOFo51WFMo?pli=1)
- [stackoverflow link](https://stackoverflow.com/questions/46670556/how-to-enable-crypto-subtle-for-unsecure-origins-in-chrome)

**Comment by kitten** [comment]
We should probably update the warning. We were aware of this limitation but I agree that not including it in the message may mislead some people.

**Comment by frederikhors** [comment]
I know this "limitation". What I'm asking here is if we really need to use the `window.crypto` API for that exchange.

**Comment by JoviDeCroock** [comment]
It's a web-api that we get for free even in IE11, the alternative is chugging in an extra 3-5kb that's my main motivation behind it. You could always use the `hash` function to provide your own hasher
