### ISSUE TITLE
Avoid refetching data client-side when using SSR with request policy set to cache-and-network

### ISSUE THREAD

**Issue by TimonVS** [FormidableLabs/urql#898]
I'm using Next.js with urql and next-urql. When setting `requestPolicy` to `cache-and-network` and the `ssr` option to `true`, I noticed that all queries are executed again on the client. I understand why this is the case, next-urql merely prefills the cache in SSR, the client will use this cache to show results immediately and fetch the queries in the background. I was wondering if there's a way to skip the initial queries on the client, since SSR already provides all the data necessary. [Apollo has an option called `ssrForceFetchDelay`](https://www.apollographql.com/docs/react/performance/server-side-rendering/#store-rehydration) which allows initial queries to use the cache only.

![image](https://user-images.githubusercontent.com/876666/87045174-ddc54f80-c1f7-11ea-9364-1e2e39477b9c.png)

Notice 41 requests on the right and 39 on the left. The extra two requests are for an OPTIONS and POST call to the Pokemon GraphQL API. In our case it's like 10 extra requests because we have multiple queries. 

CodeSandbox with request policy set to `cache-first`: https://codesandbox.io/s/next-urql-pokedex-f4hic
CodeSandbox with request policy set to `cache-and-network`: https://codesandbox.io/s/next-urql-pokedex-7s3if

urql version & exchanges:

- urql: 1.9.8
- next-urql: 1.0.2

**Comment by kitten** [comment]
We were actually thinking of making a `policyExchange` or providing a recipe for one as it'd also be useful for Graphcache's Offline Support.

The basic idea is:

- stick to `cache-first`
- upgrade queries to `cache-and-network` on-the-fly if a TTL has passed
- upgrade to `cache-and-network` if the initial queries have come from a persisted cache (neither network nor SSR cache)
- potentially integrate inactive/active tab events for upgrades like Vercel's SWR

Does that sound potentially interesting? It's a lot more flexible and efficient than defaulting to `cache-and-network`

**Comment by TimonVS** [comment]
That sounds fantastic!

**Comment by kitten** [comment]
Sorry for not coming back on this earlier! We do now have an exchange that does just this; dynamically "upgrading" operations to `cache-and-network` dynamically instead of defaulting to it: https://github.com/FormidableLabs/urql/tree/main/exchanges/request-policy

It's still experimental, but I'd love to hear your feedback on this!

**Comment by zenios** [comment]
Hi

I stumbled upon this issue my self. Request policy exchange is not really optimal for this kind of situation. Ended up writting the following exchange

```
import { makeOperation, Operation, Exchange } from "@urql/core";
import { pipe, map } from "wonka";

export interface Options {
  delay: number;
}

export const sslForceFetchDelayExchange = (options: Options): Exchange => ({
  forward,
}) => {
  const initialized = new Date().getTime();
  const { delay } = options;

  const processIncomingOperation = (operation: Operation): Operation => {
    if (
      operation.kind !== "query" ||
      operation.context.requestPolicy !== "cache-and-network"
    ) {
      return operation;
    }

    if (new Date().getTime() - initialized <= delay) {
      return makeOperation(operation.kind, operation, {
        ...operation.context,
        requestPolicy: "cache-first",
      });
    }

    return operation;
  };

  return (ops$) => {
    return forward(pipe(ops$, map(processIncomingOperation)));
  };
};

```
