### ISSUE TITLE
Is there a way to disable typeName being sent in every query?

### ISSUE THREAD

**Issue by coco98** [FormidableLabs/urql#90]
Does urql support a `addTypename: false` type configuration like Apollo? Or maybe this can be achieved by setting cache to false?

**Comment by kitten** [comment]
No, there's no way to disable this. Like with Apollo the cache won't function correctly when this is disabled.

We might alter this in the future, or you'll even be able to customise it once "exchanges" (our version of Apollo's links but with more central power to affect the query pipeline) become available. I forgot whether the caching exchange performs this query transpilation for us right now, but this might be customisable in the future (if not in v0.3, then in v0.4)
