### ISSUE TITLE
404 for docs: "Extending and Experimenting"

### ISSUE THREAD

**Issue by ericksonc** [FormidableLabs/urql#900]
On the topic of using URQL outside of React, a lot of closed issues here point to https://github.com/FormidableLabs/urql/blob/master/docs/extending-and-experimenting.md#writing-new-apis-for-the-client

However, this is a 404, and I wasn't able to find the current version of the link.

Does this page still exist? If not, what's the best existing documentation for using URQL outside of React?

**Comment by kitten** [comment]
The docs have changed a little, so this document has been split up. You can mostly find the same topics in this section: https://formidable.com/open-source/urql/docs/concepts/

Specifically this page is very similar and the API docs will also help in conjunction with it: https://formidable.com/open-source/urql/docs/concepts/core-package/#usage-with-nodejs
