### ISSUE TITLE
RFC: GCG Typegen for Graphcache's config

### ISSUE THREAD

**Issue by Andrew-Talley** [FormidableLabs/urql#901]
## Summary
Right now, the cache exchange's types seem to do a good job at preventing any type errors without manual casting. That being said, it doesn't have the same support for type-hinting that other parts of the package (e.g., `useQuery`) do. This also seems to have confused some people (e.g., #851). I think the cacheExchange could provide better type support by being transformed into a generic function that lets users provide the types that should appear in their cache, so that, e.g., when writing an optimistic response, the types of arguments available will be listed.

## Proposed Solution
I can think of two ways to achieve this. First, provide manual overrides of the `CacheExchangeOpts` types. This would enable graphql code generating tools to build these types. However, this makes it highly unlikely that someone would build all these types by hand, since that'd be just as slow as using the existing types. And, until the code generators tools exist, this feature would be mostly useless.

The second way would be to let something representing the schema be passed to it, and determine the types that way. I think the best candidate would be something like graphql-codegen's [typescript resolvers](https://graphql-code-generator.com/docs/plugins/typescript-resolvers). Then, the cache exchange could derive the types it needs from that. I built out types that at least show it's possible to do this for all of the fields on the cache exchange options – I'm happy to post all of those if that's helpful, but to give an example of just one:

```typescript
type ResolverMap = Record<string, Record<string, (...args) => any>>; // Simplified representation of graphql codegen's resolver type
type MapParent<T extends Record<string, AnyFunction>> = {
  [P in keyof T]: ReturnType<T[P]>
}
type NewResolverConfig<T extends ResolverMap> = {
  [P in keyof T]: {
    [R in keyof T[P]]: (parent: MapParent<T[P]>, args: Parameters<T[P][R]>[1], cache: Cache, info: ResolverInfo) => DataField | undefined; // The return type could likely be improved – maybe Partial<ReturnType<T[P][R]>> | undefined
  }
}


export interface CacheExchangeOpts<T extends ResolverMap | undefined = undefined> {
    resolvers?: T extends undefined ? ResolverConfig : NewResolverConfig<T>;
    // ... updates, optimistic, etc.
}
```
Then, a user would be able to define a type representing their schema and pass it to cache exchange to get type suggestions:
```typescript
type SchemaResolver = {
  UserDefinedType: {
    field: (parent: UserDefinedType, args: { id: string }) => DataField
  }
}
const myCacheExchange = cacheExchange<SchemaResolver>({ ... });
// Or, of course
const cacheOptions: CacheExchangeOpts<SchemaResolver> = { 
  ...
}
const myCacheExchange = cacheExchange(cacheOptions);
```

_(Side note – this is my first time contributing to this repo, using a broad definition of the word "contribute", so if there's something about this issue I should change to make it more useful, let me know and I'm happy to do so)_

**Comment by kitten** [comment]
We've been really confident that a solution to this can be found, which can likely be added exactly as you're suggesting.
The main problem is that we haven't found a way yet to generate TypeScript typings for an entire schema using GraphQL Code Generator. (then again, I personally haven't looked too closely yet)

It's possible that a GraphQL Code Generator plugin can be written to generate a complete type set that would make it possible to type each possible field here, and I'd love to find out more about this! Since we have a lot of access in GraphQL Code Generator to read the schema, as far as I know, it's possible to write a custom plugin for this, but I'm interested in whether there's some prior art on the project.

It's also possible that we'd first have to internalise these plugins, which would be a lot of maintenance work for us, as we haven't yet built up an efficient line of communication with the GCG maintainers, see e.g. https://github.com/dotansimha/graphql-code-generator/pull/3648

**Comment by Andrew-Talley** [comment]
@kitten Thank you for the quick response. I'm working on a couple of GCG plugins now, and based on that, I will say a) it's a very well designed system, so it would definitely be possible to make something to do this, but b) it may not be super easy. Since you'll have different types of output for each field (resolvers, updates, etc.), you may need to write a few plugin's worth of code to achieve it. And internalizing it may be tough, but the [core library is on npm](https://www.npmjs.com/package/@graphql-codegen/core), so I'd think that would be achievable.

But the issues with developing, effectively, "multiple plugins" made me think morphing the shape of the data in typescript would be simpler than a code generator. More generally, though, this would be really useful for me to have, and if there's any way to help, I'm more than happy to, no matter what approach you take to the problem.

**Comment by dotansimha** [comment]
@kitten hope we can improve our communication :) Sorry for neglecting https://github.com/dotansimha/graphql-code-generator/pull/3648, hope to get it in soon ;)

**Comment by kitten** [comment]
@dotansimha no worries! I believe @bkonkle is slowly working on type generation for the Graphcache config object. That'll come along rather slowly so don't expect updates too soon 😅 but once that's done I'll ping you so we can have a think about where it should live ✌️

**Comment by JoviDeCroock** [comment]
Covered in:

- https://github.com/FormidableLabs/urql/pull/1562
- https://github.com/dotansimha/graphql-code-generator/pull/5950

Once merged we'll be able to do:

```sh
yarn add @graphql-codegen/typescript-urql-graphcache
```

make a `codegen.yaml`:

```yaml
overwrite: true
schema: endpoint | schema
generates:
  __generated__/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-urql-graphcache"
```

Finally you'll be able to import the generic from `__generated__/graphql.ts` and use it

```ts
import { cacheExchange } from "@urql/exchange-graphcache";
import { GraphCacheConfig } from '__generated__/graphql';

const cache = cacheExchange<GraphCacheConfig>({
  ....
})
```

Enjoy a typed schema!

**Comment by shapeng1998** [comment]
> Covered in:
> 
> * #1562
> * [dotansimha/graphql-code-generator#5950](https://github.com/dotansimha/graphql-code-generator/pull/5950)
> 
> Once merged we'll be able to do:
> 
> ```shell
> yarn add @graphql-codegen/typescript-urql-graphcache
> ```
> 
> make a `codegen.yaml` and run `yarn graphql-codegen --config codegen.yml`
> 
> ```yaml
> overwrite: true
> schema: endpoint | schema
> generates:
>   __generated__/graphql.ts:
>     plugins:
>       - "typescript"
>       - "typescript-urql-graphcache"
> ```
> 
> Finally you'll be able to import the generic from `__generated__/graphql.ts` and use it
> 
> ```ts
> import { cacheExchange } from "@urql/exchange-graphcache";
> import { GraphCacheConfig } from '__generated__/graphql';
> 
> const cache = cacheExchange<GraphCacheConfig>({
>   ....
> })
> ```
> 
> Enjoy a typed schema!
> 
> Edit: published 16th of May

**The latest release seems to have a type mismatch problem.**

The `codegen.yaml` file.

```yaml
overwrite: true
schema: 'http://localhost:4000/graphql'
documents: 'src/graphql/**/*.graphql'
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-urql'
      - 'typescript-urql-graphcache'

```

The `package.json` file.

```json
"devDependencies": {
    "@graphql-codegen/cli": "1.21.5",
    "@graphql-codegen/introspection": "1.18.2",
    "@graphql-codegen/typescript": "1.22.1",
    "@graphql-codegen/typescript-operations": "1.18.0",
    "@graphql-codegen/typescript-urql": "^2.0.7",
    "@graphql-codegen/typescript-urql-graphcache": "^1.0.2",
    "@types/node": "^14.6.0",
    "@types/react": "^17.0.3",
    "@types/react-dom": "^17.0.3",
    "graphql-tag": "^2.12.4",
    "typescript": "4.2.3"
  },
```

The `_app.tsx` file and the error.

```tsx
const client = createClient({
  url: 'http://localhost:4000/graphql',
  fetchOptions: {
    credentials: 'include', // send the cookie with the request
  },
  exchanges: [
    dedupExchange,
    cacheExchange<GraphCacheConfig>({}),
    fetchExchange,
  ],
});
```

```
Type 'GraphCacheConfig' does not satisfy the constraint 'Partial<GenericCacheExchangeOpts>'.
  Types of property 'updates' are incompatible.
    Type 'GraphCacheUpdaters | undefined' is not assignable to type 'Partial<GenericUpdatesConfig> | undefined'.
      Type 'GraphCacheUpdaters' is not assignable to type 'Partial<GenericUpdatesConfig>'.
        Types of property 'Mutation' are incompatible.
          Type '{ createPost?: UpdateResolver<{ createPost: WithTypename<Post>; }, MutationCreatePostArgs> | undefined; updatePost?: UpdateResolver<...> | undefined; deletePost?: UpdateResolver<...> | undefined; register?: UpdateResolver<...> | undefined; login?: UpdateResolver<...> | undefined; } | undefined' is not assignable to type '{ [fieldName: string]: GenericUpdateResolver<DataFields, Variables>; } | undefined'.
            Type '{ createPost?: UpdateResolver<{ createPost: WithTypename<Post>; }, MutationCreatePostArgs> | undefined; updatePost?: UpdateResolver<...> | undefined; deletePost?: UpdateResolver<...> | undefined; register?: UpdateResolver<...> | undefined; login?: UpdateResolver<...> | undefined; }' is not assignable to type '{ [fieldName: string]: GenericUpdateResolver<DataFields, Variables>; }'.
              Property 'createPost' is incompatible with index signature.
                Type 'UpdateResolver<{ createPost: WithTypename<Post>; }, MutationCreatePostArgs>' is not assignable to type 'GenericUpdateResolver<DataFields, Variables>'.
                  Types of parameters 'parent' and 'parent' are incompatible.
                    Property 'createPost' is missing in type 'DataFields' but required in type '{ createPost: WithTypename<Post>; }'.ts(2344)
```

Really hope the code-generator team can fix this soon.

**Comment by prichodko** [comment]
This is amazing, thank you everyone for making this happen.

**Comment by prichodko** [comment]
@JoviDeCroock this needs to be in the docs 😄  . I am happy to send a PR, if that's okay with you.

**Comment by JoviDeCroock** [comment]
@prichodko that would be great yea, I've honestly not really gotten to it but from using it myself I think it's a great addition for the docs and people to just start out with.

**Comment by JeroenReumkens** [comment]
Just tried it on my side as well — works great! 🎉

**Comment by gyermich** [comment]
@graphql-codegen/typescript-urql-graphcache doesn't preserve typesPrefix case in the generated schema (e.g. 'GQL' -> becomes 'Gql'):

The `codegen.yaml` file:
```yaml
overwrite: true
schema: 'http://localhost:3000/graphql'
documents: 'src/graphql/**/*.graphql'
generates:
  src/generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-urql'
      - 'typescript-urql-graphcache'
    config:
      typesPrefix: GQL
```

generated type:

```
export type GQLRating = {
  __typename?: 'Rating';
  id: Scalars['ID'];
  ...
};
```
Generated schema:

```
 Rating?: {
    id?: GraphCacheResolver<WithTypename<GqlRating>,
...
}
```

**Comment by dotansimha** [comment]
Feel free to report an issue in https://github.com/dotansimha/graphql-code-generator :)

**Comment by gyermich** [comment]
> @gyermich
> Feel free to report an issue in https://github.com/dotansimha/graphql-code-generator :)

Ahh, thanks! Opened an issue https://github.com/dotansimha/graphql-code-generator/issues/7382

**Comment by AmruthPillai** [comment]
When trying to use this library, the keys config that get generated don't seem to be using the right casing for types as used in `typescript` plugin. So they fail to find them.

<img width="808" alt="Screenshot 2022-08-19 at 11 31 44 AM" src="https://user-images.githubusercontent.com/1134738/185589924-0683ccbc-06e6-45e5-9c22-bbcaab9cb1f7.png">

These types exist in the same file, but they have the first letter after `I` capitalized

**Comment by JoviDeCroock** [comment]
@AmruthPillai mind opening that issue in https://github.com/dotansimha/graphql-code-generator?

**Comment by adamsoderstrom** [comment]
>  this needs to be in the docs 😄 . I am happy to send a PR, if that's okay with you.

Excuse me on beforehand if i'm missing out on something here, but have there been any documentation taken place of this somewhere? I can't seem to find any.

This seems great btw! 😊
