### ISSUE TITLE
RFC: urql test-utils

### ISSUE THREAD

**Issue by JoviDeCroock** [FormidableLabs/urql#930]
## Summary

We often showcase urql as an extensible graphql-client which is great but when people made these testing them can prove hard, internally in the urql repository we have a lot of boilerplate to make testing easier. We should offer a package abstracting these to make testing custom-exchanges more ergonomic for our urql-users.

## Proposed Solution

A package `@urql/test-utils` (or `@urql/exchange-test-utils`), I personally think we could simplify testing.

## Requirements

- A `setupClient` method
- A `createRequest` method

This requirements list will need to be expanded, if people are having issues with testing custom-exchanges please post your difficulties here.

**Comment by kitten** [comment]
I think we haven't really heard a lot of complaints on this ever since this doc was added: https://formidable.com/open-source/urql/docs/advanced/testing/

It may be interesting to think about exchange testing, but let's close this for now ❤️
