### ISSUE TITLE
svelte: await query() should really await

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#932]
urql version & exchanges: `svelte 0.4.0`

**Steps to reproduce**

The same as https://github.com/FormidableLabs/urql/issues/854#issuecomment-648752066 by @artecoop.

```js
async doSomething(bar) {
  const query = query({ query: TESTQUERY, variables: {foo: bar} });
  const result = await query;
  return result.data
}
```

**Expected behavior**

`await query` should await until `fetching == false` and `stale == false` (especially if I'm using `requestPolicy: 'network-only'`)

**Actual behavior**

```js
result == {
  data: undefined,
  error: undefined,
  extensions: undefined,
  fetching: true,
  operation: undefined,
  stale: false
}
```

Am I wrong? If yes, sorry.

**Comment by cfbraun** [comment]
Currently query().then() uses take(1) to return the first result. The modification below looks right to me, but would maybe never return if the query fails?

```
diff --git a/packages/svelte-urql/src/operations/query.ts b/packages/svelte-urql/src/operations/query.ts
index 47a01dd..079b5dc 100644
--- a/packages/svelte-urql/src/operations/query.ts
+++ b/packages/svelte-urql/src/operations/query.ts
@@ -8,6 +8,7 @@ import {
   scan,
   map,
   take,
+  skipWhile,
   share,
   subscribe,
   publish,
@@ -119,7 +120,12 @@ export const query = <T = any, V = object>(
     };
 
     query$.then = (onValue: (result: QueryResult<T>) => any): Promise<any> => {
-      return pipe(result$, take(1), toPromise).then(onValue);
+      return pipe(
+        result$,
+        skipWhile(val => val.fetching),
+        take(1),
+        toPromise
+      ).then(onValue);
     };
 
     return query$ as any;
```

**Comment by Manborough** [comment]
Yeah I've ran into this problem too. Have either of you @frederikhors @cfbraun  found a work around when trying to trigger a query with a function call?

You can do this so updating variables will recall the query, but it always results in an initial query on load which is a pain.

```js
const locationsQuery = query({query:LOCATIONSBYROOMQUERY})

$: ({error = '', data: = []} = $locationsQuery)
```

**Comment by Manborough** [comment]
```js
const roomQuery = `query getRoom ($roomId: String!) {
		room(id: $roomId) {
			roomName
			id
		}
	}`

var result = ''
const executeQuery = mutate({ query: roomQuery });
const onClick = async (value) => result = await executeQuery({ variables: {roomId: value} });
$: ({data = [], error: {message} = ''} = result)
```js

For a temp work around it seems you can use the mutate API instead of query.

**Comment by kitten** [comment]
@Manborough Needless to say, please don't do this 😅 mutations aren't handled the same as queries in urql and behave differently

**Comment by cfbraun** [comment]
@Manborough I think you could solve this problem by using the 'pause' parameter to query:

```
let variables = null

$: pause = variables !== null
$: ({error = '', data: = []} = query({query:LOCATIONSBYROOMQUERY, variables, pause}))

const onClick = async (value) => variables = {roomId: value}
```

**Comment by kitten** [comment]
Our current bindings for Svelte have a lot of problems, as we never intended for them to be extensively used already. Hence I'm grouping several issues into an umbrella issue to express an intent to reimplement the bindings for a v1.0 with all that we've learned, which supersedes this issue.
The umbrella issue where we'll plan out a new version, API, and implementation can be found here: #1007
