### ISSUE TITLE
Add svelte to basic docs pages

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#935]
What do you think about starting to publish something for the "svelte" package in the [official documentation](https://formidable.com/open-source/urql/docs/)?

If you agree I can start with some PR in a couple of days.

I'd start with this very useful information: https://github.com/FormidableLabs/urql/pull/862.

Thanks guys.

**Comment by kitten** [comment]
The API isn't stable yet and we ourselves don't have any demos to test whether a full app can be built using this, so we've held off of writing docs for now until it's stabilised. :)

**Comment by kitten** [comment]
Our current bindings for Svelte have a lot of problems, as we never intended for them to be extensively used already. Hence I'm grouping several issues into an umbrella issue to express an intent to reimplement the bindings for a v1.0 with all that we've learned, which supersedes this issue.
The umbrella issue where we'll plan out a new version, API, and implementation can be found here: #1007
