### ISSUE TITLE
RFC: Clarify terminology and edge cases in Graphcache docs

### ISSUE THREAD

**Issue by kitten** [FormidableLabs/urql#938]
- Add explanation for "entities," "links," and "records" to "Normalized Caching" introduction document, with diagrams if necessary (See: https://spectrum.chat/urql/help/solved-trying-to-update-a-relay-connection-edges-fields-with-invalidate-inspectfields~b86a1c05-2e73-44d5-bf4c-c9b605cd658b)
- Clarify that optimistic updates reflect the current cache state and can't query more data dynamically as they reflect offline optimistic changes and not real updates (See: https://spectrum.chat/urql/help/solved-cant-read-the-cache-inside-of-an-optimistic-response~860f1064-246e-46a8-9dc7-9b5aab19e4a2)
- Clarify what happens to entities without IDs in regards to how that can be worked around and how these entities can be updated (See: https://spectrum.chat/urql/help/optimistic-responses-without-an-id~1d76fe6b-3971-43f1-be69-80f0f1393ec5)

**Comment by earksiinni** [comment]
Another idea based on https://spectrum.chat/urql/help/how-do-you-access-entities-directly-from-graphcache~76d4f5f5-1fdc-4ae7-8056-fc18fe2eb014:

Clarify cache manipulations:

- Default cache update after mutations
  - Attempts to automatically merge retrieved results based on `__typename` and key (but how? under what specific conditions? edge cases? etc.)
  - Clarify that the schema can be carefully designed to take advantage of this default behavior, give an example.
- Reading/writing query results
  - `readQuery`
  - `updateQuery`, which incidentally updates entities (explain under what conditions an entity update happens, how the merge works, etc.)
  - Clarify the difference and relationship between query results vs. cache entities (for example, when does updating one update the other?)
- Reading/writing whole entities
  - `readFragment`
  - `writeFragment`
- Reading/writing entity properties
  - `resolve`
  - `writeFragment`
