### ISSUE TITLE
RFC: Make "consumer" components reactive to cache changes

### ISSUE THREAD

**Issue by kitten** [FormidableLabs/urql#94]
In the `next` branch we already moved a lot of the caching logic to an exchange. It's basically almost equivalent. If we now introduce a more complete "watching" mechanism, then components can react to changes in the cache, which allows us to move **all** caching logic to an exchange and completely remove it from components.

This also has the nice side-effect of users being able to introduce 100% new caching logic via a custom cache exchange. This could pave way for a normalized cache a la Apollo, which is opt-in as an exchange.

cc @kenwheeler: Let's discuss the potentials of this and its feasibility pre-0.3?

**Comment by kenwheeler** [comment]
Let's chat today about the implications

**Comment by blorenz** [comment]
How'd this go?
