### ISSUE TITLE
Using additional component props when updating a cache after mutation

### ISSUE THREAD

**Issue by aiven715** [FormidableLabs/urql#941]
How I can pass additional variables (apart from mutation arguments) to the update function?

In my use-case I have drag and drop page builder. Each page is having layout with modules, every module may have layout with child modules and so on in a recursive manner. In theory such nesting could be infinite.

In order to implement such scenario in a graphql world, I'm getting all modules on a page with their child layout as flat array. And then in my component, I'm creating hierarchy tree. The query looks the following:

```graphql
query($pageId: Int!) {
  page(pageId: $pageId) {
    id
    title
    # Getting top level page layout with it's positions
    layout {
      id
      positions {
        id
        x
        y
        w
        h
      }
    }
    # Getting flat list of all modules on the page regarding their nesting level
    modules {
      id
      type
      # Module position id on a parent layout. With it's help, we can create page tree structure
      position {
        id
      }
      # Child module layout
      layout {
        id
        positions {
          id
          x
          y
          w
          h
        }
      }
    }
  }
}
```

The problem is that when I create new module, I need to append it to the page. But page id is not passed as arguments to a mutation.
```graphql
input PositionInput {
  id: Int
  layoutId: Int!
  x: Int!
  y: Int!
  w: Int!
  h: Int!
}

mutation(
  $type: ModuleType!
  $position: PositionInput!
) {
  createModule(type: $type, position: $position) @populate
}
```

So in the update function there is no access to page id and therefore I can not append newly created module to a page
```javascript
export default (result, args, cache) => {
  // I need to have page id somehow here
}
```

Is it something wrong on the architecture level of my schema?

**Comment by kitten** [comment]
There's two ways to get this working:

- Either you can use `cache.inspectFields` on various entities to find the lists you're looking for https://formidable.com/open-source/urql/docs/graphcache/custom-updates/#cacheinspectfields
- Alternatively, it's possible to pass in additional variables that'll be filtered out for the server if they're not in the mutation and access them using `info.variables` (the 4th argument) https://github.com/FormidableLabs/urql/blob/ffe28467aaa2a9f5a758db7020efc5c10d2b84fc/exchanges/graphcache/src/types.ts#L59

The first approach is recommended when it's possible because it'll be UI-agnostic and encourages you to imitate server behaviour. The second is an escape hatch trick

**Comment by aiven715** [comment]
@kitten thanks for the quick response.

I'm having troubles understanding how I can achieve that with `cache.inspectFields` since it returns fields and I need page id. I'm inspecting `Module` type like this:
```javascript
cache.inspectFields({ __typename: "Module", id: result.createModule.id })
``` 
gives me the following array:

```javascript
[{fieldKey: "layouts", fieldName: "layouts", arguments: null},
{fieldKey: "__typename", fieldName: "__typename", arguments: null},
{fieldKey: "id", fieldName: "id", arguments: null},
{fieldKey: "type", fieldName: "type", arguments: null},
{fieldKey: "positionId", fieldName: "positionId", arguments: null}]
```

From my understanding with such approach we can go from parent to children, but as I see I need to do the opposite - find `pageId` by the module id. I've tried also to use:

```javascript
cache.inspectFields("Query")
````

but in this case I get all requested pages and don't know how to find the one my module belongs to...

---

Also regarding the second option, I'm trying to pass `pageId` to `variables` but it does not appears for me in `info.variables` object. I was not declaring `pageId` in the mutation since I get an exception(variable is unused) if I do so.

**Comment by kitten** [comment]
I'll double check but on the latest Graphcache you should see the unfiltered variables on your `info.variables` if you pass them. I'll double check that.

Once you have the field you're interested in, you can use `cache.resolve` to drill down. That's a method that reads the graphed data in the cache back by entity and field.

So for instance, given the `cache.inspectFields("Query")` output, you can first filter by field:

```
cache.inspectFields("Query")
  .filter(x => x.fieldName === "page")
```

And then resolve any field from there respectively:

```
cache.resolve(
  cache.resolve("Query", "page", argsFromInspect),
  "title"
)
```

**Comment by aiven715** [comment]
@kitten I see, so you mean I'll need to traverse all requested pages and then for every page drill down until I find what I need?

**Comment by JoviDeCroock** [comment]
How does your backend know where to add this module, shouldn't that be 1-1 reflected to how it's possible in the updater function? As in if you could read out the `layoutId` it should be sufficient, no?

**Comment by aiven715** [comment]
@JoviDeCroock in my back-end, module is attached to layout through a position and layout is related to a page. Therefore when I create to a module by providing layoutId, back-end know's which page it will be assigned to.
