### ISSUE TITLE
documentation clarification: next-urql - isomorphic-unfetch - is it needed?

### ISSUE THREAD

**Issue by TriStarGod** [FormidableLabs/urql#945]
First off, great library! I need clarification on the documentation. The read me and codesandbox examples, isomorphic-fetch isn't used.
In the example folder, it is being used. Is it needed or not?

urql version & exchanges:
"urql": "^1.10.0",
"next-urql": "^1.1.0",
"isomorphic-unfetch": "^3.0.0",

exchanges: dedupExchange, cacheExchange, fetchExchange

**Comment by lukasluecke** [comment]
It's not needed anymore if you use the current NextJS version, as they bundle a polyfill now.

**Comment by TriStarGod** [comment]
Thanks
