### ISSUE TITLE
[Graphqlcache] The parent sometimes undefined field value in resolver

### ISSUE THREAD

**Issue by nghiepit** [FormidableLabs/urql#949]
Hi,

urql version & exchanges: 1.10.0 & 3.0.2

```js
const cache = cacheExchange({
  schema,
  resolvers: {
    Property: {
      slug(parent) {
        const {type} = parent;

        console.log({type, parent});

        return `${type.slug}-${parent.slug}`;
      },
    },
});
```

Check in the console.log:
`type` is `undefined` but the `parent` object contains `type` field value. 🤦 
The log run many times, and the last time it's show correct data.
Final the resolver does not work well in any cases.

Additional. I'm using `next` and `next-urql`.

**Comment by JoviDeCroock** [comment]
Hey,

Could you provide a reproduction? This is very limited in terms of information, it would speed up a potential fix a lot if we had the information.

**Comment by nghiepit** [comment]
I having created a reproduction https://codesandbox.io/s/holy-snowflake-xi2d9?file=/utils/urql.js.

Steps to reproduce:
- Click About
- Click Index
- Click About
- ....
<img src="https://user-images.githubusercontent.com/4768095/91751066-5a6c1d00-ebee-11ea-9636-82b682f0bacc.png" height="300" />

**Comment by JoviDeCroock** [comment]
> Btw: could it be that you're asking for the parent.type to be resolved after the other, this could be a reason. In GraphQL server the same occurs.

This should solve it

**Comment by nghiepit** [comment]
@JoviDeCroock Thanks for your answer, I'm clear my problem.
