### ISSUE TITLE
Avoid sending extra query request after invalidating the cache. 

### ISSUE THREAD

**Issue by aiven715** [FormidableLabs/urql#953]
After I use `cache.invalidate`, there is an extra query request sent that I would like to avoid.

I have the following query in my app:

```graphql
query($pageId: Int!) {
  page(pageId: $pageId) {
    id
    title
    modules {
      id
      type
      config
    }
  }
}
```

After I delete the module, I would like  to update the cache optimistically:

```javascript
cacheExchange({
  schema: introspection,
  optimistic: {
    removeModule: ({ moduleId }, cache) => {
      cache.invalidate({ __typename: "Module", id: moduleId })
    }
  },
}),
```

But the problem is, when I delete a module, a new request is sent to fetch the page again. [I've seen in docs](https://formidable.com/open-source/urql/docs/graphcache/custom-updates/#cacheinvalidate), that using `cache.invalidate` may lead to additional request unless I use schema awareness. But in my case, I use schema awareness and the request is still sent.

Here it is my schema definition for the additional context:

```graphql
type Page {
  id: Int!
  title: String!
  modules: [Module!]!
}

type Module {
  id: Int!
  type: ModuleType
  config: JSONObject!
}


extend type Mutation {
  removeModule(moduleId: Int!): Boolean
}
```

I assume, that it may happen because module list element type is marked as required in the `modules` field definition - `[Module!]!`, but if I make it optional(`[Module]!`), I get `null` value in the array after invalidation which is undesired behavior as well.

Any way I can make the required item to disappear from the array without making an additional request since I exactly know what's the schema should look like without making a new query?

Best wishes

**Comment by JoviDeCroock** [comment]
If you are using schema-awareness and you are seeing an additional request that means your graphql schema is saying that a module is not nullable. Which is the case `modules: [Module!]!` the `!` after `Module` means that it isn't nullable.

**Comment by frederikhors** [comment]
@aiven715 It would be very nice and useful to have a reproduction of the problem on codesandbox.

**Comment by kitten** [comment]
@frederikhors I don't believe that's necessary as it's documented behaviour :+1:
So yes again, you're completely right in that invalidating an item in a list while using schema awareness will set the item to `null` without an additional request if it _is_ indeed nullable. But if it can't be set to `null` then the "missing data" cascades upward. The list can't be `null` (which would be undesirable anyway) and the `Page` can't be `null`, and so on...

Either way, you'd be missing data, so an additional request would be made. That almost always happens with `cache.invalidate`. It deletes data, which means that whatever the outcome is, Graphcache is likely going to acknowledge that data is missing and will issue a request. The difference is what it does in the meantime, and with schema awareness it can still serve _partial data_ to bridge the gap.

But you're still advised to update lists manually in most cases if you want the correct result to be displayed without an additional request.

**Comment by JoviDeCroock** [comment]
@aiven715 Yes, an optimistic update is tentative until the mutation completes. Under the hood this is a layer on top of the entity so it can have temporary attributes. When a response comes in we delete this layer, this way when there's an error we have no issues later on with inconsistent data, ....

Because optimistic and updates have the same semantics you should be able to reuse the function body but have a different signature:

```
const optimistic = ({ moduleId }, cache) => action(moduleId, cache)
const updater = (result, args, cache, info) => action(args.moduleId, cache)

const action = the body of your current func
```

**Comment by aiven715** [comment]
Works perfectly, the issue is resolved, thanks!

**Comment by kitten** [comment]
Just a quick note; the updater will also run for optimistic updates (as long as there's an optimistic function to provide this update), so you can also just return `true` there and do the removal from the list only in `updates` :)

**Comment by aiven715** [comment]
That's outstanding, so I don't even need to duplicate the code. Perfect!
