### ISSUE TITLE
component does not update on qeury string change

### ISSUE THREAD

**Issue by nabsofken** [FormidableLabs/urql#955]
I am using the `useQuery` hook to retrieve some data from a public graphql endpoint: `https://countries-274616.ew.r.appspot.com`
My query is as follows:
`query countries {
    Country(first: 1) {
        name
        _id
    }
}`
This is my component:
`

```
const Countries = () => {
  const [result, execQuery] = useQuery({
    query: countryQuery,
  });

  if (result.fetching) return <p>Loading...</p>;
  if (result.error) return <p>Error</p>;
  console.log(result);
  return (
    <>
      <p>Countries</p>
      <ul>
        {result.data.Country.map((c) => (
          <li key={c._id}>{c.name}</li>
        ))}
      </ul>
    </>
  );
};

export default Countries;
```

`
If I run this the first time or refresh the page, the response returned is accurate, however, if I change the query e.g. get the  first 10, the component still displays the old. Checked the network tab and the correct response is returned, however, the result from useQuery returns the original response. I tried using "network-only" caching as well with no luck. Any ideas on what I am doing wrong?
urql version:1.10.0
graphql version: 15.3.0
next version: 9.5.2

**Comment by JoviDeCroock** [comment]
Is it possible this issue is related to a fast refresh? The signature is calculated on the arguments passed, urql calculates a hash on that. If you refresh the page then the query with first: 10 works all right I assume?

**Comment by nabsofken** [comment]
yup a page refresh gives me the correct result. Will I need to disable fast refresh?

**Comment by nabsofken** [comment]
I added the // @refresh reset that forces a reset of the component and that solved the issue

**Comment by kitten** [comment]
Closing since I don't think we can do anything here / not our bug 😅

**Comment by JoviDeCroock** [comment]
@nabsofken we've found something that kept urql from fast-refreshing, this should now be resolved and should allow you to remove the force-reset comment.
