### ISSUE TITLE
[next-urql] Graphqlcache doesn't share cache from the server.

### ISSUE THREAD

**Issue by nghiepit** [FormidableLabs/urql#959]
Hi,
In my `_app.js` I have to initialize data on the server:

```js
// _app.js
App.getInitialProps = async ({ Component, ctx }) => {
  let pageProps = {};

  if (ctx.req) {
    // Initialize
    const { data } = await ctx.urqlClient.query(CITY_LIST_QUERY).toPromise();

    console.log("getInitialProps:", data);
  }

  if (typeof Component.getInitialProps === "function") {
    pageProps = await Component.getInitialProps(ctx);
  }

  return {
    pageProps
  };
};
```
But on the client-side doesn't cache from the server and the API execute again.
```js
// index.js
export default function IndexPage() {
  const [{ data, fetching, error }] = useQuery({
    query: CITY_LIST_QUERY
  });

  console.log(process.browser ? "Client" : "Server", data);  // undefined and execute

  return (
    <div>
      Hello World
    </div>
  );
}
```
Sorry, If this is the default behavior Graphqlcache.
Reproduce: https://codesandbox.io/s/angry-panini-cprfq?file=/pages/index.js

**Comment by JoviDeCroock** [comment]
Can you provide a reproduction? The ssrExchange should restore your cache with Next.

**Comment by nghiepit** [comment]
Thank you for your quick reply.
The reproduction at the end of the issue.

**Comment by JoviDeCroock** [comment]
I did not notice that sorry, so the problem here is that your client is constructed in the wrong order:

```
export default withUrqlClient((ssrExchange, ctx) => {
  return {
    url: process.env.NEXT_PUBLIC_API,
    exchanges: [dedupExchange, cache, ssrExchange, fetchExchange]
  };
})(App);
```

Is the right order, in your case the ssrExchange is before `cache`.  You might wonder, why is this the case?
So what happens is your ssrExchange contains the SSR-responses and will respond as if the `fetchExchange` responds but if your `cacheExchange` is after the `ssr` one it won't get that response and won't be able to hydrate its cache.

**Comment by nghiepit** [comment]
:( , The my original is the same as you: `exchanges: [dedupExchange, cache, ssrExchange, fetchExchange]`
But, I had some problems with resolvers. The `name` field resolve duplicate. So I had tried change to `cache` after `ssrExchange `.

```js
export const cache = cacheExchange({
  schema,
  resolvers: {
    City: {
      name(parent, args, cache) {
        const name = cache.resolve(parent, "name");
        return "prefix-" + name;

        // return "prefix-" + parent.name;
      }
    }
  }
});

// index.js
<div>
{data.cities.map(({ id, name }) => (
  <div key={id}>{name}</div>
))}
</div>
```
Result:
```js
prefix-prefix-An Giang
prefix-prefix-Bình Dương
```

Reproduction  https://codesandbox.io/s/distracted-wozniak-tlfvf?file=/pages/index.js

**Comment by JoviDeCroock** [comment]
You have to do `exchanges: [dedupExchange, ssrExchange, cache, fetchExchange]` this second is a new issue

**Comment by JoviDeCroock** [comment]
I don't see a client-side request in the networks tab with that exchanges configuration. Could you open a new issue for this since it's not really related to the original and the original seems resolved when I check your sandboxes.

**Comment by nghiepit** [comment]
Yeah, the original issue resolved, But It had related to exchanges order.
New issue https://github.com/FormidableLabs/urql/issues/961
