### ISSUE TITLE
RFC: Drop Spectrum in favor of Github Discussions.

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#987]
I think it's time to drop Spectrum in favor of Github Discussions.

See TailwindCSS discussions here: https://github.com/tailwindlabs/tailwindcss/discussions. Amazing!

And you can also move an issue in discussion and the other way around.

Also Spectrum almost always in the last few days is like this:

![Spectrum](https://user-images.githubusercontent.com/41120635/93626008-172dee80-f9e3-11ea-8e0b-b423bb3c4d31.png)

**Comment by kitten** [comment]
Funnily enough we were talking about this just today! We don't have access to the discussions Beta yet but I'll see what I can do.

Totally agreed that Spectrum isn't cutting it anymore.

**Comment by kitten** [comment]
Done! 🎉
